### ISSUE TITLE
Bug/Question about Calculation of Dynamic Modules' Dropout Rate

### ISSUE THREAD

**Issue by teowenshen** [k2-fsa/icefall#1001]
When calculating the dropout rate for MHSA, FFN, and pooling, I noticed that the latter portion always zeroes out. 

https://github.com/k2-fsa/icefall/blob/5f066d3d538e093d72c94e48ad6be4c23da71f84/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/zipformer2.py#L883-L885

Perhaps it should be below? 

```python
   return initial_dropout_rate - ( 
       initial_dropout_rate - final_dropout_rate 
   ) * (self.batch_count / warmup_period)
```

Though, this doesn't seem to be a fatal bug.

**Comment by danpovey** [comment]
yes, you are right, that looks like a bug; but I wonder whether this file might have been added to the repo accidentally?  Are we using zipformer2.py?

**Comment by csukuangfj** [comment]
> Are we using zipformer2.py?

The only use of `zipformer2.py` is in `train2.py`, which is only used by `export-for-ncnn.py`.
