### ISSUE TITLE
Preparing features takes too long 

### ISSUE THREAD

**Issue by EmreOzkose** [k2-fsa/icefall#101]
Hi, 

Preparing filter banks for large datasets (~6000h) takes too long. Even time of preparing manifest is approximately 10 hours. Do you have any suggestion to make this process fast? 

I am trying to modify Dataset part as on-the-fly computing (if feature is not computed then compute&write else read). So I can observe early batches earlier.

**Comment by csukuangfj** [comment]
Please have a look at https://github.com/lhotse-speech/lhotse/pull/422

Feature extraction for 100 hours of audio takes about 3 minutes.

**Comment by EmreOzkose** [comment]
I missed this merge, thank you :)

**Comment by csukuangfj** [comment]
@EmreOzkose 
Could you share with us some statistics, e.g, the time taken for feature extraction about 6000 hours of audio using CUDA?

**Comment by pzelasko** [comment]
As for preparing manifests, you can usually get a good speed-up with multiprocessing, see e.g. the librispeech recipe in Lhotse. Unfortunately every corpus requires different code structure for manifest preparation so I can’t give a more specific advice. 

One thing that also might be useful with large data is incremental writing of the manifest — it allows you to stop and resume from it left, see here for examples: https://lhotse.readthedocs.io/en/latest/api.html#lhotse.audio.RecordingSet.open_writer

**Comment by EmreOzkose** [comment]
@csukuangfj I started compute_fbank() with `num_jobs=15`. After ~30hours, there wasn't any progress (using cpu). However I will try  [lhotse-speech/lhotse#422](https://github.com/lhotse-speech/lhotse/pull/422) today and report here. 

@pzelasko I am also checking https://lhotse.readthedocs.io/en/latest/api.html#lhotse.audio.RecordingSet.open_writer, thank you.

**Comment by danpovey** [comment]
What does `top` look like: is it using up lots of CPU, or waiting on
something, e.g. disk?
If your disk access is very slow for some reason, any method is going to be
slow.

**Comment by EmreOzkose** [comment]
Sorry for late reply, there was a glitch on my machine. 

@danpovey I checked this issue, but disk access seems good.

With the help of @csukuangfj and @pzelasko, I made 2 changes [in this script](https://github.com/k2-fsa/icefall/blob/810b193dcc3ad3f7a65bc3def63493711c9a084e/egs/librispeech/ASR/local/compute_fbank_librispeech.py#L82):

`compute_and_store_features` to `compute_and_store_features_batch`
`Fbank(FbankConfig(num_mel_bins=num_mel_bins))` to `KaldifeatFbank(KaldifeatFbankConfig(device='cuda:0'))`

Now, estimated progress time is ~4.5 hours with utilization of GPU. Thank you.

**Comment by csukuangfj** [comment]
@EmreOzkose Thanks for sharing.

> Preparing filter banks for large datasets (~6000h) takes too long.

> Now, estimated progress time is ~4.5 hours with utilization of GPU.

Did you mean it takes about 4.5 hours to extract features for 6000 hours of audio on a single GPU?

**Comment by EmreOzkose** [comment]
Yes, for single GPU.
