### ISSUE TITLE
sherpa-onnx not support LM fusion

### ISSUE THREAD

**Issue by minmin0** [k2-fsa/icefall#1012]
Sherpa-onnx is a good ASR runtime，but It's a bit regretful that it is not supported LM.

**Comment by minmin0** [comment]
Can we use LM fusion in sherpa-onnx now? I found kaldi and wenet already support LM in C++ runtime.

**Comment by minmin0** [comment]
Have you tried large text resource to train a LM to boost the recognition rate?

**Comment by marcoyang1998** [comment]
This is on our schedule. We are implementing #1017 and #1002 in sherpa-onnx. Please stay tuned.
