### ISSUE TITLE
Using `simple_am_proj` for CTC loss

### ISSUE THREAD

**Issue by desh2608** [k2-fsa/icefall#1022]
In the pruned transducer recipes which use auxiliary CTC loss, such as the following:

https://github.com/k2-fsa/icefall/blob/45c13e90e42d0f6ff190d69acb18f4e868bfa954/egs/librispeech/ASR/pruned_transducer_stateless7_ctc/model.py#L73

two separate heads are used for the simple AM projection and the CTC output (CTC one additionally has a dropout before the projection). Has anyone tried using the simple AM projection itself to compute CTC loss? I wonder if the CTC may help the simple joiner or vice-versa.

**Comment by marcoyang1998** [comment]
I don't think we tried that before.
