### ISSUE TITLE
Mismatch between word_id in L.pt and that in G_3_gram.fst.txt/G_4_gram.fst.txt

### ISSUE THREAD

**Issue by yfyeung** [k2-fsa/icefall#1032]
`prepare_lang.py` will generate `words.txt` from `lexicon.txt`, which contains the word-to-id mapping for L.pt.
https://github.com/k2-fsa/icefall/blob/master/egs/gigaspeech/ASR/prepare.sh#L188

However, another `words.txt` will be generated by `transcript_words.txt`:
https://github.com/k2-fsa/icefall/blob/master/egs/gigaspeech/ASR/prepare.sh#L214-L237

Later, the `3gram_pruned_1e7.arpa` and `4gram.arpa` will use the new `words.txt` to generate `G_3_gram.fst.txt` and `G_4_gram.fst.txt`.
https://github.com/k2-fsa/icefall/blob/master/egs/gigaspeech/ASR/prepare.sh#L301-L316

All in all, `prepare.sh` of gigaspeech will generate two different `words.txt`, leading to a mismatch between word_id in L.pt and that in G_3_gram.fst.txt/G_4_gram.fst.txt.
As a result, we can't intersect L and G to get LG.pt.

**Comment by csukuangfj** [comment]
Could you delete the second words.txt generated from transcript_words.txt?
We need to keep the one from lexicon.txt.
