### ISSUE TITLE
zipformer

### ISSUE THREAD

**Issue by Yymax-max** [k2-fsa/icefall#1037]
how to train a zipformer in bilingual like zh&en. can get some advice.

**Comment by csukuangfj** [comment]
1. please follow https://github.com/k2-fsa/icefall/tree/master/egs/tal_csasr/ASR to prepare your data.
tal_csasr is a bilingual recipe (English + Chinese recipe) but it is not using zipformer

2. Please follow our zipformer recipe for training using the prepared data from step 1.
