### ISSUE TITLE
Diarization implementation using Icefall

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#1040]
Hello guys,

On your opinion is it possible to implement diarization using Icefall approach?

Thanks a lot,
AlexG.

**Comment by csukuangfj** [comment]
Is there a link to your current approach?

**Comment by AlexandderGorodetski** [comment]
No, for my research I use my inhouse LAB code. Currently there are many articles talking about that Transformer-based diarization can bring very good WER performance. I am curious, if you guys, are planning to implement Transormer-based diarization system in the coming future.
