### ISSUE TITLE
Feature computation for long audio

### ISSUE THREAD

**Issue by treya-lin** [k2-fsa/icefall#1042]
Hi I have some questions about computing fbank features for long audio data (the correct way to do it, some warnings I met, and how to speed up)

I have a conversational corpus where each audio correspond to multiple segments. I am not sure if I should:
(1) directly compute fbank on the trimmed cut manifest where each cut has been trimmed to supervisions (one cut one segment)
(2) or compute fbank on the original cut manifest where each cut has multiple segments, and trim it after feature extraction? In this case should I be careful about the argument `batch_duration` and make sure it is longer than the longest recording?

I think method (2) would be faster as it saves much time on loading audio right?

So, to test it I tried both methods on a small test set that contains 140 recordings (20k+ segments in total, about 20 hours). The feature extraction code looks like this. I borrowed it from the script for gigaspeech. And I noticed that for gigaspeech the trimming happens after the feature extraction (like method 2)
```Python
device = torch.device("cuda", 0)
extractor = KaldifeatFbank(KaldifeatFbankConfig(device=device))
nj = 10
batch_duration = 600

# test 1:
cut_set_feat = cut_set.compute_and_store_features_batch(
      extractor=extractor,
      storage_path= outdir / "conv_feats_dev_test1",
      num_workers=nj,
      batch_duration=batch_duration,
      overwrite=True,
  )
```

1. **Duration-wise warning**: One problem was that when I went with method (2), it always threw a warning at the beginning:
```Shell
lhotse/lhotse/dataset/sampling/simple.py:213: UserWarning: The first cut drawn in batch collection violates the max_frames, max_cuts, or max_duration constraints - we'll return it anyway. Consider increasing max_frames/max_cuts/max_duration.
```
Does it mean some recordings didn't have the feature  extracted succesfully? Is it because the recording itself (or the total duration of its supervisions) is longer than the batch_duration? How do we avoid it?

2. **Time consumption**: 
Method 2 was indeed faster. Can I assume it is the correct way?  
For the time consumption, when I didn't do speed perturbation, method 2 was twice faster than method (1), i.e. method (1) 3 minutes and method (2) 1.5 minutes; 
when I do speed perturbation, method (2) is also twice faster,  i.e. method (1) 9 minutes and method (2) 4.5 minutes.
But for method (2) the afterward trimming part can really took quite a while.

4. **Different output:**
But I also noticed that if I use method 2 and trim the cut set afterwards, it seems the feature storage key was not trimmed, is it a problem here or did I do anything wrong? The comparison of result looks like this, you can see the manifest generated with method 2 has a very long string of storage keys because the feature extraction was done on a cut with multiple segments I suppose

```
# trimmed before feat extraction (method 1)
{"id": "A0263_S015_0_G0387-1277248-1281329", "start": 1277.248, "duration": 4.081, "channel": 0, "supervisions": [{"id": "A0263_S015_0_G0387-1277248-1281329", "recording_id": "A0263_S015_0_G0387", "start": 0.0, "duration": 4.081, "channel": 0, "text": "я тоже так считаю потому что уже уже есть дела уже звонят", "language": "russian", "speaker": "G0387"}], "features": {"type": "kaldifeat-fbank", "num_frames": 408, "num_features": 80, "frame_shift": 0.01, "sampling_rate": 16000, "start": 1277.248, "duration": 4.081, "storage_type": "lilcom_chunky", "storage_path": "/home/user/workspace/asr_workspace/next_gen_kaldi/icefall/egs/my_models/russian/local/test_data_prepare/mdt-conv-dev-feat-test/mdt-conv_feats_dev_test1.lca", "storage_key": "660643380,38221", "recording_id": "A0263_S015_0_G0387", "channels": 0}, "recording": {"id": "A0263_S015_0_G0387", "sources": [{"type": "file", "channels": [0], "source": "/disk2/WAV-16K/A0263_S015_0_G0387.wav"}], "sampling_rate": 16000, "num_samples": 20574883, "duration": 1285.9301875, "channel_ids": [0]}, "type": "MonoCut"}

# trimmed after feat extraction (method 2), but seems the feature key was not trimmed to segments?
{"id": "A0263_S015_0_G0387-1277248-1281329", "start": 0.0, "duration": 4.081, "channel": 0, "supervisions": [{"id": "A0263_S015_0_G0387-1277248-1281329", "recording_id": "A0263_S015_0_G0387", "start": 0.0, "duration": 4.081, "channel": 0, "text": "я тоже так считаю потому что уже уже есть дела уже звонят", "language": "russian", "speaker": "G0387"}], "features": {"type": "kaldifeat-fbank", "num_frames": 128593, "num_features": 80, "frame_shift": 0.01, "sampling_rate": 16000, "start": 0, "duration": 1285.9301875, "storage_type": "lilcom_chunky", "storage_path": "/home/user/workspace/asr_workspace/next_gen_kaldi/icefall/egs/my_models/russian/local/test_data_prepare/mdt-conv-dev-feat-test/mdt-conv_feats_dev_test2.lca", "storage_key": "1664850134,50080,49424,48377,45055,45503,46196,46047,47157,46683,45472,46201,45804,47411,46659,45954,46927,47273,49230,50158,50135,50130,50139,50132,50102,50135,47566,45721,46756,46299,46154,45674,45706,46537,45997,47075,46029,46394,44693,45467,48642,50140,50135,50138,50140,50149,50151,50135,50139,50147,50134,48110,45739,44898,44288,46595,46045,46705,46612,46551,46180,45264,46832,46391,47315,47363,48926,50154,50153,50163,50139,50160,50079,50101,50146,50138,50097,50133,50143,49114,44372,46643,46439,46495,45923,45405,45593,46937,46639,46330,47125,45469,46598,46029,46524,46961,46087,47449,51111,50842,50230,50164,50166,50159,50121,50059,50164,50154,50147,49977,48820,45155,45523,45955,44593,45489,45238,46468,44959,46047,46265,46868,44595,46277,46894,50180,50140,50140,50045,50035,50158,50144,50150,50146,50153,50165,48982,44120,46973,46337,46408,46882,45724,46388,45577,46458,46798,46003,46459,44810,46290,46761,45841,45459,45758,45479,48170,49476,50126,50089,50132,50136,49987,50067,50142,50120,50137,50240,50145,50136,50149,50055,44501,46424,44817,46224,47269,46012,46117,46037,45881,47145,45487,46916,46250,46576,46015,46566,47238,48909,50142,50144,50136,50138,50139,50129,50137,50135,50031,50146,50138,50146,49706,50078,50148,50142,46944,46007,46735,46425,46207,46868,46174,46773,45715,45655,46128,46616,45763,47678,45971,46361,46781,46363,49583,50121,50079,50081,50156,50155,49957,50144,50122,50131,50137,50133,50126,50117,50134,50137,50139,45797,45479,47223,45545,47117,47120,45036,45949,46655,45959,46374,45785,47504,50112,50144,47398,49379,9335", "recording_id": "A0263_S015_0_G0387", "channels": 0}, "recording": {"id": "A0263_S015_0_G0387", "sources": [{"type": "file", "channels": [0], "source": "/disk2/WAV-16K/A0263_S015_0_G0387.wav"}], "sampling_rate": 16000, "num_samples": 20574883, "duration": 1285.9301875, "channel_ids": [0]}, "type": "MonoCut"}
```

So, I am a bit confused now how to implement the feature extraction for conversational data (long audio data) now. I trimmed them earlier because I need to split them into train/dev/test and make sure they don't share segments from the same speakers. So when I extract features is it ok to merge the cut back to the one-cut-many-segments form and split it again after extraction? But how to make sure the trimmed cut has the corresponding feature storage key too? **What is the correct way to prepare the cut manifest, and if possible how to speed it up, and what should we be careful about in terms of duration?** Any insight is much appreciated and thanks for your time! And do let me know if there is any description unclear.

Below is my test script.
```Python
import os,sys
import argparse
import re
import random
import math
from tqdm import tqdm
import torch
from lhotse import RecordingSet, SupervisionSet,Fbank, CutSet,load_manifest,KaldifeatFbank,KaldifeatFbankConfig
from lhotse.recipes.utils import read_manifests_if_cached
from pathlib import Path

torch.multiprocessing.set_sharing_strategy('file_system') # I added this becauase otherwise it throw an error "RuntimeError: received 0 items of ancdata"
device = torch.device("cuda", 0)

# outdir = Path('./local/test_data_prepare/mdt-conv-dev-feat-test/').absolute()
outdir = Path('./local/test_data_prepare/mdt-conv-dev-feat-test-sp/').absolute()

# one cut one segment
cut_set_trimmed = load_manifest('./data/manifests/mdt_conv_combined/mdt-conv_cuts_dev-raw.jsonl.gz')
cut_set_trimmed = (cut_set_trimmed + cut_set_trimmed.perturb_speed(0.9) + cut_set_trimmed.perturb_speed(1.1))

# one cut multi segment
sups_tmp = []
recs_tmp = []
for cut in tqdm(cut_set_trimmed):
  sups_tmp.extend(cut.supervisions)
  if cut.recording not in recs_tmp:
    recs_tmp.append(cut.recording)
sup_set = SupervisionSet.from_segments(sups_tmp)
rec_set = RecordingSet.from_recordings(recs_tmp)

cut_set = CutSet.from_manifests(
    recordings=rec_set,
    supervisions=sup_set
  )

device = torch.device("cpu")
if torch.cuda.is_available():
  device = torch.device("cuda", 0)

extractor = KaldifeatFbank(KaldifeatFbankConfig(device=device))
nj = 10
batch_duration = 600

# test 1:
cut_set_trimmed_feat = cut_set_trimmed.compute_and_store_features_batch(
      extractor=extractor,
      storage_path= outdir / "mdt-conv_feats_dev_test1",
      num_workers=nj,
      batch_duration=batch_duration,
      overwrite=True,
  )
cut_set_trimmed_feat.to_file(outdir / 'mdt-conv_cuts_dev_test1.jsonl.gz')

# test2
cut_set_feat = cut_set.compute_and_store_features_batch(
            extractor=extractor,
            storage_path= outdir / "mdt-conv_feats_dev_test2",
            num_workers=nj,
            batch_duration=batch_duration,
            overwrite=True,
        )
cut_set_feat = cut_set_feat.trim_to_supervisions(
    keep_overlapping=False, min_duration=None
)
cut_set_feat.to_file(outdir / 'mdt-conv_cuts_dev_test2.jsonl.gz')

```

**Comment by csukuangfj** [comment]
> lhotse/lhotse/dataset/sampling/simple.py:213: UserWarning: The first cut drawn in batch collection violates the max_frames, max_cuts, or max_duration constraints - we'll return it anyway. Consider increasing max_frames/max_cuts/max_duration.


This warning is from the dataloader. The reason is that you have utterances whose duration is greater than the 
specified batch_duration. This warning won't affect the result.

You can choose a larger batch_duration if your GPU has much free memory.

**Comment by csukuangfj** [comment]
> But for method (2) the afterward trimming part can really took quite a while.

@pzelasko Could you please have a look?

**Comment by danpovey** [comment]
When you do trim_to_supervisions, it's just an operation on the metadata.  The underlying data is not copied, which is OK because, anyway, it only stores the data in chunks of smallish size which are fairly efficient to read even in small pieces.

We have found recently that speed perturbation is not really necessary (note: I assume you have SpecAugment).  This is especially true for big data.

Regarding whether (1) or (2) would end up dumping more data, I think it depends how much of your data had no transcript at all, vs. how much the segments overlap; this could be very dependent on the dataset.

**Comment by treya-lin** [comment]
@csukuangfj @danpovey 
Hey guys thanks for the reply, so for the two different types of output in `3. Different output`, why are they differ?

```Python
# method 1
{'id': 'A0263_S015_0_G0387-1277248-1281329', 'start': 1277.248, 'duration': 4.081, 'channel': 0, 'supervisions': [{'id': 'A0263_S015_0_G0387-1277248-1281329', 'recording_id': 'A0263_S015_0_G0387', 'start': 0.0, 'duration': 4.081, 'channel': 0, 'text': 'я тоже так считаю потому что уже уже есть дела уже звонят', 'language': 'russian', 'speaker': 'G0387'}], 'features': {'type': 'kaldifeat-fbank', 'num_frames': 408, 'num_features': 80, 'frame_shift': 0.01, 'sampling_rate': 16000, 'start': 1277.248, 'duration': 4.081, 'storage_type': 'lilcom_chunky', 'storage_path': '/home/user/workspace/asr_workspace/next_gen_kaldi/icefall/egs/my_models/russian/local/test_data_prepare/mdt-conv-dev-feat-test/mdt-conv_feats_dev_test1.lca', 'storage_key': '660643380,38221', 'recording_id': 'A0263_S015_0_G0387', 'channels': 0}, 'recording': {'id': 'A0263_S015_0_G0387', 'sources': [{'type': 'file', 'channels': [0], 'source': '/disk2/yuanjingwen/russian/MDT2021S043/WAV-16K/A0263_S015_0_G0387.wav'}], 'sampling_rate': 16000, 'num_samples': 20574883, 'duration': 1285.9301875, 'channel_ids': [0]}, 'type': 'MonoCut'}

# method 2
{'id': 'A0263_S015_0_G0387-1277248-1281329', 'start': 0.0, 'duration': 4.081, 'channel': 0, 'supervisions': [{'id': 'A0263_S015_0_G0387-1277248-1281329', 'recording_id': 'A0263_S015_0_G0387', 'start': 0.0, 'duration': 4.081, 'channel': 0, 'text': 'я тоже так считаю потому что уже уже есть дела уже звонят', 'language': 'russian', 'speaker': 'G0387'}], 'features': {'type': 'kaldifeat-fbank', 'num_frames': 128593, 'num_features': 80, 'frame_shift': 0.01, 'sampling_rate': 16000, 'start': 0, 'duration': 1285.9301875, 'storage_type': 'lilcom_chunky', 'storage_path': '/home/user/workspace/asr_workspace/next_gen_kaldi/icefall/egs/my_models/russian/local/test_data_prepare/mdt-conv-dev-feat-test/mdt-conv_feats_dev_test2.lca', 'storage_key': '1664850134,50080,49424,48377,45055,45503,46196,46047,47157,46683,45472,46201,45804,47411,46659,45954,46927,47273,49230,50158,50135,50130,50139,50132,50102,50135,47566,45721,46756,46299,46154,45674,45706,46537,45997,47075,46029,46394,44693,45467,48642,50140,50135,50138,50140,50149,50151,50135,50139,50147,50134,48110,45739,44898,44288,46595,46045,46705,46612,46551,46180,45264,46832,46391,47315,47363,48926,50154,50153,50163,50139,50160,50079,50101,50146,50138,50097,50133,50143,49114,44372,46643,46439,46495,45923,45405,45593,46937,46639,46330,47125,45469,46598,46029,46524,46961,46087,47449,51111,50842,50230,50164,50166,50159,50121,50059,50164,50154,50147,49977,48820,45155,45523,45955,44593,45489,45238,46468,44959,46047,46265,46868,44595,46277,46894,50180,50140,50140,50045,50035,50158,50144,50150,50146,50153,50165,48982,44120,46973,46337,46408,46882,45724,46388,45577,46458,46798,46003,46459,44810,46290,46761,45841,45459,45758,45479,48170,49476,50126,50089,50132,50136,49987,50067,50142,50120,50137,50240,50145,50136,50149,50055,44501,46424,44817,46224,47269,46012,46117,46037,45881,47145,45487,46916,46250,46576,46015,46566,47238,48909,50142,50144,50136,50138,50139,50129,50137,50135,50031,50146,50138,50146,49706,50078,50148,50142,46944,46007,46735,46425,46207,46868,46174,46773,45715,45655,46128,46616,45763,47678,45971,46361,46781,46363,49583,50121,50079,50081,50156,50155,49957,50144,50122,50131,50137,50133,50126,50117,50134,50137,50139,45797,45479,47223,45545,47117,47120,45036,45949,46655,45959,46374,45785,47504,50112,50144,47398,49379,9335', 'recording_id': 'A0263_S015_0_G0387', 'channels': 0}, 'recording': {'id': 'A0263_S015_0_G0387', 'sources': [{'type': 'file', 'channels': [0], 'source': '/disk2/yuanjingwen/russian/MDT2021S043/WAV-16K/A0263_S015_0_G0387.wav'}], 'sampling_rate': 16000, 'num_samples': 20574883, 'duration': 1285.9301875, 'channel_ids': [0]}, 'type': 'MonoCut'}
```

![image](https://user-images.githubusercontent.com/86940562/236788530-cf3d8333-e6cd-4a48-aba1-ce4c9fd7cf95.png)


So they both refer to a segment  "A0263_S015_0_G0387-1277248-1281329". It is from a recording of 1285.9s, starts at 1277.248 and lasts 4.081s. But the `cut.start` and `cut.features.storage_key` are different.  Is the output of the second method in this picture correct? With this manifest how does the script know where to locate the feature values for this particular segment?

**Comment by treya-lin** [comment]
> > lhotse/lhotse/dataset/sampling/simple.py:213: UserWarning: The first cut drawn in batch collection violates the max_frames, max_cuts, or max_duration constraints - we'll return it anyway. Consider increasing max_frames/max_cuts/max_duration.
> 
> This warning is from the dataloader. The reason is that you have utterances whose duration is greater than the specified batch_duration. This warning won't affect the result.
> 
> You can choose a larger batch_duration if your GPU has much free memory.

So even if the length of the recording, say 1200s, is longer than the batch_duration(600s), it still succesfully extracted the feature for me? Why is this ok though?

**Comment by csukuangfj** [comment]
> So even if the length of the recording, say 1200s, is longer than the batch_duration(600s), it still succesfully extracted the feature for me? Why is this ok though?

Please read the warning log
> lhotse/lhotse/dataset/sampling/simple.py:213: UserWarning: The first cut drawn in batch collection violates the max_frames, max_cuts, or max_duration constraints - we'll return it anyway. Consider increasing max_frames/max_cuts/max_duration.


It says
> we'll return it anyway

The result is that your batch size would be 1 and the duration of the batch size would be greater than the value you specified.  Since the batch size is not empty, it can still compute the features.  The only effect is that you have a batch with one utterance.

---

> Is the output of the second method in this picture correct?

Maybe @pzelasko has something to say about that?

**Comment by treya-lin** [comment]
@csukuangfj by the way, I always meet this warning as my number of worker is larger than 1. Does it happen to you guys and is there anyway to fix it?

```
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
```

**Comment by csukuangfj** [comment]
> ? I assume we don't need to worry about it?

I suggest that you add
https://github.com/k2-fsa/icefall/blob/62c9dd9703857c1d51ee2f0fc863e14671a69857/egs/gigaspeech/ASR/local/compute_fbank_gigaspeech_splits.py#L27-L32

**Comment by pzelasko** [comment]
> @csukuangfj @danpovey Hey guys thanks for the reply, so for the two different types of output in `3. Different output`, why are they differ?

In the picture you highlight two differences: 1) the `storage_key` field and 2) the `start` value for cut.

Re 1), this is the expected behavior. The default storage format encodes the start + chunk offsets in `storage_key`. For example, let's assume a 4s utterance in 1200s recording. If you first trim to supervisions and then compute features, you compute features for only 4s, so the storage key encodes start offset (a large number of bytes) + first chunk size (a smaller number of bytes). OTOH if you compute the features for the whole recording, there will be a lot of chunks, so the list of chunk sizes will be large itself. When you load the features, Lhotse will figure out which chunks contain the segment of features you want and only load and decode those. For more details check out the docs https://lhotse.readthedocs.io/en/latest/_modules/lhotse/features/io.html#LilcomChunkyWriter

Re 2), I believe you made a mistake in constructing the long-recording cutset from the short-recording cutset. In code below:
```python
# one cut multi segment
sups_tmp = []
recs_tmp = []
for cut in tqdm(cut_set_trimmed):
  sups_tmp.extend(cut.supervisions)
  if cut.recording not in recs_tmp:
    recs_tmp.append(cut.recording)
sup_set = SupervisionSet.from_segments(sups_tmp)
rec_set = RecordingSet.from_recordings(recs_tmp)

cut_set = CutSet.from_manifests(
    recordings=rec_set,
    supervisions=sup_set
  )
```

you need to adjust the supervision segment start offset with cut start offset, because supervisions in cuts have starts relative to the start of cut. If you do sth like `sups_tmp.extend(s.with_offset(c.start) for s in cut.supervisions)` you'll be fine.

**Comment by pzelasko** [comment]
Regarding the speed, it is fairly simple to speed up segment-level feature computation (just throw more CPU cores at it), but with long-recordings it's tricky because you need to balance the amount of I/O, available CPU memory, and if you're using GPU then also the batch size. E.g. if you max out the batch size you'll likely be stuck in I/O or blow up CPU memory. I think the most efficient way to extract features for long recordings would require an incremental batched read-compute-write logic (with a dataloader), but we don't currently have that implemented in Lhotse.

**Comment by treya-lin** [comment]
> > ? I assume we don't need to worry about it?
> 
> I suggest that you add
> 
> https://github.com/k2-fsa/icefall/blob/62c9dd9703857c1d51ee2f0fc863e14671a69857/egs/gigaspeech/ASR/local/compute_fbank_gigaspeech_splits.py#L27-L32

Hi I do have that in my code at the beginning of the script, but the warning still exists. So you guys don't have these warnings locally after adding thses two line of code?

**Comment by treya-lin** [comment]
> > @csukuangfj @danpovey Hey guys thanks for the reply, so for the two different types of output in `3. Different output`, why are they differ?
> 
> In the picture you highlight two differences: 1) the `storage_key` field and 2) the `start` value for cut.
> 
> Re 1), this is the expected behavior. The default storage format encodes the start + chunk offsets in `storage_key`. For example, let's assume a 4s utterance in 1200s recording. If you first trim to supervisions and then compute features, you compute features for only 4s, so the storage key encodes start offset (a large number of bytes) + first chunk size (a smaller number of bytes). OTOH if you compute the features for the whole recording, there will be a lot of chunks, so the list of chunk sizes will be large itself. When you load the features, Lhotse will figure out which chunks contain the segment of features you want and only load and decode those. For more details check out the docs https://lhotse.readthedocs.io/en/latest/_modules/lhotse/features/io.html#LilcomChunkyWriter
> 
> Re 2), I believe you made a mistake in constructing the long-recording cutset from the short-recording cutset. In code below:
> 
> ```python
> # one cut multi segment
> sups_tmp = []
> recs_tmp = []
> for cut in tqdm(cut_set_trimmed):
>   sups_tmp.extend(cut.supervisions)
>   if cut.recording not in recs_tmp:
>     recs_tmp.append(cut.recording)
> sup_set = SupervisionSet.from_segments(sups_tmp)
> rec_set = RecordingSet.from_recordings(recs_tmp)
> 
> cut_set = CutSet.from_manifests(
>     recordings=rec_set,
>     supervisions=sup_set
>   )
> ```
> 
> you need to adjust the supervision segment start offset with cut start offset, because supervisions in cuts have starts relative to the start of cut. If you do sth like `sups_tmp.extend(s.with_offset(c.start) for s in cut.supervisions)` you'll be fine.

ohhh I see! Thanks a lot for the explanation and the suggestion!
