### ISSUE TITLE
yes/no recipe log

### ISSUE THREAD

**Issue by tomato18463** [k2-fsa/icefall#1056]
I have justed completed a fresh icefall installation and I am trying the [yesno recipe](https://github.com/k2-fsa/icefall/tree/master/egs/yesno/ASR). In my log I got something like 

`2023-05-12 14:01:01,622 INFO [decode.py:204] batch 0/?, cuts processed until now is 4`

And the example log at the bottom of [this page](https://icefall.readthedocs.io/en/latest/installation/index.html) is like

`2021-08-23 19:35:30,409 INFO [decode.py:190] batch 0/8, cuts processed until now is 4`

Is it normal or something wong with my installation?

Thank!

**Comment by wangtiance** [comment]
If you can get the WER result then there's nothing wrong. For some reason the total batches can't be displayed.

**Comment by csukuangfj** [comment]
> Is it normal or something wong with my installation?

The logs in the doc are from a very old version of lhotse.
If you have time, would you mind updating the logs in the doc with yours?

**Comment by tomato18463** [comment]
@wangtiance I see, thanks.
@csukuangfj Sure, I'm happy to help update the logs in the doc. Should I update all the logs from data preparation to decoding, or just update the decoding part as mentioned in this issue?

**Comment by csukuangfj** [comment]
> Should I update all the logs from data preparation to decoding,

Please update all the logs in the installation doc.

**Comment by tomato18463** [comment]
> > Should I update all the logs from data preparation to decoding,
> 
> Please update all the logs in the installation doc.

Sure. I'll create a pull request later.
