### ISSUE TITLE
How to accelerate computing fbank

### ISSUE THREAD

**Issue by PPGGG** [k2-fsa/icefall#1065]
It seems that computing fbank features cost a lot of time. Can we use another operation to accelerate it ?

**Comment by csukuangfj** [comment]
1. Please refer to
https://github.com/k2-fsa/icefall/blob/bccd20d9786e2ec5f1445e1b20fb806ddfff78b1/egs/librispeech/ASR/prepare_giga_speech.sh#L29

You can split your dataset into multiple splits and start new terminals to process a range of splits at the same time.
You can also use GPU to compute fbank.
