### ISSUE TITLE
How to train a pure Chinese zipformer without bpe model

### ISSUE THREAD

**Issue by PPGGG** [k2-fsa/icefall#1069]
I noticed that the training script in `librispeech/ASR/pruned_transducer_stateless7_streaming/train.py` uses bpe model, which is not the same as `sherpa-ncnn-streaming-zipformer-zh-14M-2023-02-23`. So if i would like to train a zipformer model with Chinese character modeling, which recipe can i refer to ? Thanks.

**Comment by csukuangfj** [comment]
> which recipe can i refer to

You can refer to any recipe in icefall that is for Chinese, for instance, aishell, or wenetspeech.

**Comment by PPGGG** [comment]
Thanks a lot.
