### ISSUE TITLE
Export Non-streaming Zipformer to NCNN

### ISSUE THREAD

**Issue by w11wo** [k2-fsa/icefall#1071]
Hi, thanks for the awesome work.

I would like to know if it's already possible to export non-streaming Zipformer to NCNN. I noticed that the model is exportable to ONNX, and its streaming counterpart already has an `export-for-ncnn.py` script. Would be great if we could do the same for non-streaming Zipformer. Thanks!

**Comment by csukuangfj** [comment]
sherpa-ncnn supports only streaming models. Is there a reason to use the non-streaming zipformer with sherpa-ncnn?

By the way, sherpa-onnx supports non-streaming zipformer.

**Comment by w11wo** [comment]
I see. Is it correct that the model in  `pruned_transducer_stateless7` is a non-streaming Zipformer? The resultant model is what I need to use in sherpa-ncnn, because I find that its results are the best on my own training. Is it possible to use that model in sherpa-ncnn?

**Comment by csukuangfj** [comment]
>  Is it possible to use that model in sherpa-ncnn?

Currently, no. However, you can use it in [sherpa-onnx](https://github.com/k2-fsa/sherpa-onnx)

So do you only need a non-streaming model?

**Comment by w11wo** [comment]
> Currently, no. However, you can use it in [sherpa-onnx](https://github.com/k2-fsa/sherpa-onnx)

Yes, I'm aware that it's exportable to sherpa-onnx. 

> So do you only need a non-streaming model?

Not really. I could also use a streaming model, because I'm deploying for real-time ASR on mobile. I just find that the `pruned_transducer_stateless7` model got the lowest WER during training.

At the moment, I'm using `conv_emformer_transducer_stateless` on mobile, but I'm trying to find a better model, if any.

**Comment by csukuangfj** [comment]
In general, a non-streaming model has better accuracy since it has the full context during recognition but it needs the whole utterance as input. As you are doing real-time ASR, I think non-streaming models are not applicable for you.

**Comment by w11wo** [comment]
Got it, many thanks for the suggestion.

So other than streaming Zipformer, do you have other recommendations?

**Comment by csukuangfj** [comment]
Zipformer (both streaming and non-streaming) is the best-performing model in icefall.

I suggest only Zipformer.

**Comment by w11wo** [comment]
Okay, thank you so much for your help!
