### ISSUE TITLE
Error when setting the parameter "right_context_length" as zero in training step

### ISSUE THREAD

**Issue by Ziyi6** [k2-fsa/icefall#1073]
Hi,

I got an error when I was tring to set the right_context_length as zero in training, with "conv_emformer_transducer_stateless2" with the librispeech dataset.  Could you please have a look? Thanks. The figure below you will find the error report.
![0921d91f79eefad8f0db373b](https://github.com/k2-fsa/icefall/assets/101512377/89555211-cf30-4302-bcbc-544683ed1496)

**Comment by yaozengwei** [comment]
We have fixed this issue in https://github.com/k2-fsa/icefall/pull/1076. You could use the lastest code and have a test.

**Comment by Ziyi6** [comment]
Thanks :-）
