### ISSUE TITLE
segmentation fault  python

### ISSUE THREAD

**Issue by usoylu2** [k2-fsa/icefall#1083]
I am following the installation here: https://icefall.readthedocs.io/en/latest/installation/index.html

When I try to import icefall, i get "zsh: segmentation fault  python" Is it because $PYTHONPATH variable does not work or something else?

**Comment by marcoyang1998** [comment]
Please refer to #674

**Comment by usoylu2** [comment]
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
