### ISSUE TITLE
Error when replicating zipformer (zipformer + pruned stateless transducer)

### ISSUE THREAD

**Issue by usoylu2** [k2-fsa/icefall#1089]
When I try to reproduce the training for zipformer (zipformer + pruned stateless transducer) at https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/RESULTS.md via

```
export CUDA_VISIBLE_DEVICES="0,1,2,3"
./zipformer/train.py \
  --world-size 4 \
  --num-epochs 40 \
  --start-epoch 1 \
  --use-fp16 1 \
  --exp-dir zipformer/exp \
  --causal 0 \
  --full-libri 1 \
  --max-duration 1000
```

I get this error:

-- Process 3 terminated with the following error:            
Traceback (most recent call last):                            │
  File "/local/home/ufsoylu/my_env/lib64/python3.7/site-packag
es/torch/multiprocessing/spawn.py", line 69, in _wrap        
    fn(i, *args)                                             
  File "/local/home/ufsoylu/icefall_tmp/icefall/egs/librispeec
h/ASR/zipformer/train.py", line 1216, in run           
    params=params,                                     
  File "/local/home/ufsoylu/icefall_tmp/icefall/egs/librispeec
h/ASR/zipformer/train.py", line 1326, in scan_pessimistic_batc│
hes_for_oom                                               
    is_training=True,                                       
  File "/local/home/ufsoylu/icefall_tmp/icefall/egs/librispeec
h/ASR/zipformer/train.py", line 778, in compute_loss          
    lm_scale=params.lm_scale,                                 
  File "/local/home/ufsoylu/my_env/lib64/python3.7/site-packag
es/torch/nn/modules/module.py", line 1190, in _call_impl      
    return forward_call(*input, **kwargs)                     
  File "/local/home/ufsoylu/my_env/lib64/python3.7/site-packag
es/torch/nn/parallel/distributed.py", line 1040, in forward   
    output = self._run_ddp_forward(*inputs, **kwargs)         
  File "/local/home/ufsoylu/my_env/lib64/python3.7/site-packag
es/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_f
orward                                                        
    return module_to_run(*inputs[0], **kwargs[0])             
  File "/local/home/ufsoylu/my_env/lib64/python3.7/site-packag
es/torch/nn/modules/module.py", line 1190, in _call_impl      
    return forward_call(*input, **kwargs)                     
  File "/local/home/ufsoylu/icefall_tmp/icefall/egs/librispeec
h/ASR/zipformer/model.py", line 127, in forward               
    x, x_lens = self.encoder_embed(x, x_lens)                 
  File "/local/home/ufsoylu/my_env/lib64/python3.7/site-packag
es/torch/nn/modules/module.py", line 1190, in _call_impl      
    return forward_call(*input, **kwargs)                     
  File "/local/home/ufsoylu/icefall_tmp/icefall/egs/librispeec
h/ASR/zipformer/subsampling.py", line 310, in forward         
    x = self.conv(x)                                          
  File "/local/home/ufsoylu/my_env/lib64/python3.7/site-packag
es/torch/nn/modules/module.py", line 1190, in _call_impl      
    return forward_call(*input, **kwargs)                     
  File "/local/home/ufsoylu/my_env/lib64/python3.7/site-packag
es/torch/nn/modules/container.py", line 204, in forward       
    input = module(input)                                     
  File "/local/home/ufsoylu/my_env/lib64/python3.7/site-packag
es/torch/nn/modules/module.py", line 1190, in _call_impl      
    return forward_call(*input, **kwargs)                     
  File "/local/home/ufsoylu/icefall_tmp/icefall/egs/librispeec
h/ASR/zipformer/scaling.py", line 1388, in forward            
    return k2.swoosh_r(x)                                     
AttributeError: module 'k2' has no attribute 'swoosh_r'

**Comment by desh2608** [comment]
You should update your k2 installation.

**Comment by usoylu2** [comment]
i installed k2 using pip (k2-fsa.org) by selecting the torch version on my environment. How can update k2? Should i also update pytorch and etc?

**Comment by desh2608** [comment]
Swoosh was added in [v1.23.4](https://github.com/k2-fsa/k2/releases/tag/v1.23.4), so you should check that your k2 version should be at least that.
