### ISSUE TITLE
Token/words confidence

### ISSUE THREAD

**Issue by Zeiny96** [k2-fsa/icefall#1092]
Any available way to get each token/word confidence while using the modified beam search decoding method?

**Comment by Zeiny96** [comment]
I successfully added it, but the confidences for out of domain sets are very low even though the result itself is fair, is this normal?

**Comment by csukuangfj** [comment]
Could you describe how you get the scores?

**Comment by Zeiny96** [comment]
Using the log_probs in the modified beam search, then using it as a power of 10 just to get rid of the log scale as follows:
```
for k in range(len(topk_hyp_indexes)):
                ...
                ...
                ...
                new_confidences = hyp.confidences[:]
                if new_token not in (blank_id, unk_id):
                    ...
                    ...
                    ...
                    new_confidences.append(10**topk_log_probs[k].item())

                new_log_prob = topk_log_probs[k]
                new_hyp = Hypothesis(
                    ys=new_ys, log_prob=new_log_prob, timestamp=new_timestamp, confidences=new_confidences
                )
                B[i].add(new_hyp)

    ...
    ...
    ...
    sorted_confidences = [h.confidences for h in best_hyps]
    ...
    ...
    ...
    ans_confidences = []
    unsorted_indices = packed_encoder_out.unsorted_indices.tolist()
    for i in range(N):
        ans.append(sorted_ans[unsorted_indices[i]])
        ans_timestamps.append(sorted_timestamps[unsorted_indices[i]])
        ans_confidences.append(sorted_confidences[i])

    return DecodingResults(
        tokens=ans,
        timestamps=ans_timestamps,
        confidences=ans_confidences,
    )

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/icefall/blob/1aeffa73bce3d4803ec52f0d17287ff65e280430/egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py#L1027

https://github.com/k2-fsa/icefall/blob/1aeffa73bce3d4803ec52f0d17287ff65e280430/egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py#L1058

>                     new_confidences.append(torch.exp(topk_log_probs[k]).item())

`topk_log_probs` is cumulative. You have to subtract it from ys_log_probs to get the log_prob of the current frame.

**Comment by Zeiny96** [comment]
Yeah, that was my bad, it is fixed now:
```
new_confidences.append(torch.exp(topk_log_probs[k]-hyp.log_prob).item())
```

Thanks
