### ISSUE TITLE
Cuda OOM

### ISSUE THREAD

**Issue by usoylu2** [k2-fsa/icefall#1100]
When I try to reproduce results for the pretrained Conformer CTC[](https://icefall.readthedocs.io/en/latest/recipes/Non-streaming-ASR/librispeech/conformer_ctc.html#conformer-ctc)

```
cd egs/librispeech/ASR
cd icefall-asr-librispeech-conformer-ctc-jit-bpe-500-2021-11-09/exp/
ln -s pretrained.pt epoch-999.pt
cd ../..
./conformer_ctc/decode.py \
    --exp-dir ./icefall-asr-librispeech-conformer-ctc-jit-bpe-500-2021-11-09/exp \
    --lang-dir ./icefall-asr-librispeech-conformer-ctc-jit-bpe-500-2021-11-09/data/lang_bpe_500 \
    --lm-dir ./icefall-asr-librispeech-conformer-ctc-jit-bpe-500-2021-11-09/data/lm \
    --epoch 999 \
    --avg 1 \
    --concatenate-cuts 0 \
    --bucketing-sampler 1 \
    --max-duration 30 \
    --num-paths 1000 \
    --method attention-decoder \
    --nbest-scale 0.5
```

I am getting CUDA out of memory. How can I fix that?

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.18 GiB (GPU 0; 15.77 GiB total capacity; 13.42 GiB already allocated; 1023.38 MiB free; 13.97 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by csukuangfj** [comment]
Is the decoding process the only process that is using the GPU?

If yes, then there are several fixes.

1. Please use a GPU with a larger RAM
2. Please switch to a different decoding method, e.g., ctc_decoding
