### ISSUE TITLE
Discrepancies between icefall and sherpa

### ISSUE THREAD

**Issue by ezerhouni** [k2-fsa/icefall#1119]
Hello !
I exported a streaming zipformer (pruned_transducer_stateless7_multi) in onnx. Using sherpa-onnx I have different (quite large) wer than using icefall (I didn't had that issue between when using pruned_transducer_stateless3 and sherpa). Do you have an idea where it might comes from ?

**Comment by csukuangfj** [comment]
Have you used `onnx_pretrained.py` to verify that the exported model is able to decode waves?

**Comment by ezerhouni** [comment]
@csukuangfj Yes, I can decode files (and just double check with `onnx_pretrained.py`), in general it seems like I have 1.5-2% absolute wer than using icefall (approximate estimation). Might be related to https://github.com/k2-fsa/icefall/issues/1006 (second issue)
Thank you !

**Comment by ezerhouni** [comment]
@csukuangfj I test the specific file (which is problematic) using onnx_pretrained.py
```onnx_pretrained.py``` and decode.py give the same results
sherpa-onnx give worst (much worst) wer. Hence, I think it might be a sherpa-onnx issue, let me open an issue there to track it

**Comment by csukuangfj** [comment]
@ezerhouni  Is it possible to share your model?

If the modified_beam_search in sherpa-onnx gives incorrect results, it should not be difficult to debug it.
I suggest you set `num_active_paths` to 1, dump the output of the joiner, and compare it with the greedy search.  If you can share the model, we can debug that.

**Comment by ezerhouni** [comment]
@csukuangfj Thank you for your help, I will try to see if we can share the model. 
From a quick experiment, greedy search and modified beam search with `num_active_paths=1` produces what is expected but modified beam search with `num_active_paths=4` does not. Icefall (`decode.py`) with beam search of 4 does generate the proper output.

**Comment by csukuangfj** [comment]
If num_active_paths=1 generates the correct results, then I suggest that you use `num_active_paths=2` for debugging using gdb.

**Comment by ezerhouni** [comment]
@csukuangfj We are still working on it to try to see where it might comes from. In the mean time, I think I could reproduce the issue:
Model :
1. https://huggingface.co/marcoyang/icefall-libri-giga-pruned-transducer-stateless7-streaming-2023-04-04 using pretrained.pt with pretrained.sh, I get the following transcript :
hyp : THERE ARE SEVERAL NON GOVERNMENTAL ORGANIZATIONS IN SOME SCHEMIST
2. Converting the above model to ONNX and using sherpa-onnx:
hyp : THERE ARE SEVERAL NON GOVERNMENTAL ORGANIZATIONS IN SOME SCHEME MOST
(I modified the padding to 0.64s in sherpa-onnx)
Both are with modified_beam_search with beam of 4

The wav file is common-voice-en-19703943.wav (will try to upload it)

I will add more details later

**Comment by csukuangfj** [comment]
Could you please add more details?

**Comment by w11wo** [comment]
Hi @csukuangfj, I tried to make a reproducible example using the model given by @ezerhouni.

I first prepared a sample audio and cloned the model

```sh
# get audio
wget -q https://datasets-server.huggingface.co/assets/mozilla-foundation/common_voice_13_0/--/en/test/0/audio/audio.mp3
ffmpeg -i audio.mp3 -ar 16000 common_voice_en_27710027.wav

# clone model
cd icefall/egs/librispeech/ASR/
mkdir tmp
cd tmp
git clone https://huggingface.co/marcoyang/icefall-libri-giga-pruned-transducer-stateless7-streaming-2023-04-04
cd ..
```

Then, running inference on Icefall, with modified beam search:

```
2023-06-28 08:56:44,792 INFO [pretrained.py:242] device: cuda:0
2023-06-28 08:56:44,792 INFO [pretrained.py:244] Creating model
2023-06-28 08:56:45,479 INFO [zipformer.py:405] At encoder stack 4, which has downsampling_factor=2, we will combine the outputs of layers 1 and 3, with downsampling_factors=2 and 8.
2023-06-28 08:56:45,491 INFO [pretrained.py:248] Number of model parameters: 70369391
2023-06-28 08:56:48,306 INFO [pretrained.py:256] Constructing Fbank computer
2023-06-28 08:56:48,307 INFO [pretrained.py:266] Reading sound files: ['/root/common_voice_en_27710027.wav']
2023-06-28 08:56:48,308 INFO [pretrained.py:272] Decoding started
2023-06-28 08:56:49,553 INFO [pretrained.py:287] Using modified_beam_search
2023-06-28 08:56:49,879 INFO [pretrained.py:346] 
/root/common_voice_en_27710027.wav:
JOE KITSON DISAPPROVED OF FILMS AND BUSTER ALSO HAD RESERVATIONS ABOUT THE MEDIA


2023-06-28 08:56:49,880 INFO [pretrained.py:348] Decoding Done
```

Then, converting the model to ONNX. Note: I ensured to only use epoch 20, like the Icefall inference.

```sh
./pruned_transducer_stateless7_streaming/export-onnx.py \
  --bpe-model ./tmp/icefall-libri-giga-pruned-transducer-stateless7-streaming-2023-04-04/data/lang_bpe_500/bpe.model \
  --use-averaged-model false \
  --epoch 20 \
  --avg 1 \
  --decode-chunk-len 32 \
  --exp-dir ./tmp/icefall-libri-giga-pruned-transducer-stateless7-streaming-2023-04-04/exp
```

Finally running inference on `sherpa-onnx` with modified beam search:

```sh
# inference in sherpa onnx
python3 /root/sherpa-onnx/python-api-examples/online-decode-files.py \
  --tokens=./tmp/icefall-libri-giga-pruned-transducer-stateless7-streaming-2023-04-04/data/lang_bpe_500/tokens.txt \
  --encoder=./tmp/icefall-libri-giga-pruned-transducer-stateless7-streaming-2023-04-04/exp/encoder-epoch-20-avg-1.onnx \
  --decoder=./tmp/icefall-libri-giga-pruned-transducer-stateless7-streaming-2023-04-04/exp/decoder-epoch-20-avg-1.onnx \
  --joiner=./tmp/icefall-libri-giga-pruned-transducer-stateless7-streaming-2023-04-04/exp/joiner-epoch-20-avg-1.onnx \
  --decoding-method=modified_beam_search \
  /root/common_voice_en_27710027.wav
```

I'm getting the output:

```
Started!
Done!
/root/common_voice_en_27710027.wav
JOE KITON DISAPPROVED OF FILMS AND BUSTER ALSO HAD RESERVATIONS ABOUT THE MEDIA
----------
num_threads: 1
decoding_method: modified_beam_search
Wave duration: 6.300 s
Elapsed time: 1.047 s
Real time factor (RTF): 1.047/6.300 = 0.166
```

So there's just a slight substitution from `KITSON -> KITON`.

I think I've seen worse deterioration in results, but that's using my own models, which I can't share. Also, on most devices (iOS, Windows desktop), we often have to speak loudly for the recognizer to work. I'm not sure how to reproduce this.

Looking forward to having this thoroughly investigated. Cheers!

**Comment by csukuangfj** [comment]
@w11wo @ezerhouni 

Thanks for posting the detailed instructions for reproducing.

I am able to reproduce the results you posted.

However, one thing I want to mention is that `pretrained.py` uses `model.encoder.forward()`, while sherpa-onnx uses
`model.encoder.streaming_forward()`.

I also tested it with `onnx_pretrained.py` from icefall and it produces the same result with `sherpa-onnx `for the 
given wave `common_voice_en_27710027.wav`.

Have you ever encountered a case that `onnx_pretrained.py` decodes a different result from `sherpa-onnx`?

---

cc @yaozengwei

**Comment by ezerhouni** [comment]
@csukuangfj Sorry I forgot to add more details (I wanted to share the audio file). In my small experiment, I am seeing the same results between ```onnx_pretrained.py``` and ```sherpa-onnx```, if I find some time, I will try to do some more experiment this week

**Comment by csukuangfj** [comment]
As for resampling, could you use the wave after resampling to test icefall and sherpa-onnx? In this way, we don't need
to care about the sampling issue.

If we find the root cause is resampling, we can change how resampling is implemented in sherpa-onnx.

**Comment by w11wo** [comment]
@csukuangfj 

Thanks for the response. Yes, I find the same results between `onnx_pretrained.py` and `pretrained.py` like you said.

Regarding the difference between `model.encoder.forward()` and `model.encoder.streaming_forward()`, does that also apply to `sherpa-ncnn` and/or other architectures like `conv-emformer-transducer-stateless2`? Because I also see a drop in performance in `sherpa-ncnn` and when using that architecture.

**Comment by w11wo** [comment]
@csukuangfj

I have found a case where `onnx_pretrained.py` and `pretrained.py` doesn't return the same result (deletion occurs); nor does sherpa-onnx (but it's slightly better). This is using the exact same model and setup as the above. Note that this file has a particularly low volume, which might be related to the normalization issue. 

These are my inference results:

```
pretrained.py:
THE BUNGALOW WAS PLEASANTLY SITUATED NEAR THE SHOR

onnx_pretrained.py:
# completely empty!

sherpa-onnx:
NEAR THE SHOR
```

You can find the audio file here: [timit_test0.wav.zip](https://github.com/k2-fsa/icefall/files/11936067/timit_test0.wav.zip)

Hope this helps!

**Comment by w11wo** [comment]
> You can find the audio file here: [timit_test0.wav.zip](https://github.com/k2-fsa/icefall/files/11936067/timit_test0.wav.zip)

I re-tested the same audio test file with the latest Zipformer model:
- icefall: [Zengwei/icefall-asr-librispeech-streaming-zipformer-2023-05-17](https://huggingface.co/Zengwei/icefall-asr-librispeech-streaming-zipformer-2023-05-17)
- sherpa-onnx: [csukuangfj/sherpa-onnx-streaming-zipformer-en-2023-06-26](https://huggingface.co/csukuangfj/sherpa-onnx-streaming-zipformer-en-2023-06-26)

And it seems to have significantly improved the performance, as suggested in this [thread](https://github.com/k2-fsa/icefall/issues/1006#issuecomment-1617719417)!

```
zipformer/pretrained.py:
THE BUNGALOW WAS PLEASANTLY SITUATED NEAR THE SHORE

zipformer/onnx_pretrained-streaming.py:
THE BUNGALOW WAS PLEASANTLY SITUATED NEAR THE SHOR

sherpa-onnx (with 0.5s tail padding):
THE BUNGALOW WAS PLEASANTLY SITUATED NEAR THE SHOR
```
