### ISSUE TITLE
threads in decoding

### ISSUE THREAD

**Issue by armusc** [k2-fsa/icefall#1134]
Hi

while running a decoding method, in this case one-best decoding in zipformer ctc output, i.e.
https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless7_ctc/ctc_decode.py  

I notice that multiple threads are generated which I don't know where are they coming from
I set
export MKL_NUM_THREADS=1
export OMP_NUM_THREADS=1
to be sure that neural net traversing is not multithreaded
I also set num_workers to 0 in asr_datamodule.py
so additionals processes for data loading should not be created

but I can see 2 threads being generated besides the main process when I do htop
now the main process is always running at 100% CPU, while the threads use very little CPU and seldom, so that using the command
time -v
I can have something like
Percent of CPU this job got: 106%

or anyway a value a bit higher than 100%

I don't know at which point this threads are created; I have being trying to understand why processing time notably increases when I fully charge all the clusters' CPU (I am aware that this is expected in any case, but here it is about 3x slower when I decode an audio file for each of the server's cores), so I was looking at all possible reasons

thanks in advance

**Comment by csukuangfj** [comment]
There is a thread pool of size 2 in k2. 

By the way, the thread pool can be removed by make intersect dense pruned sequential in k2.
