### ISSUE TITLE
handling noise tags in the data preparation

### ISSUE THREAD

**Issue by saurabhbarge** [k2-fsa/icefall#1136]
I need to train the zipformer model on my own data using the Librispeech Recipe. My data includes noise events and have been labelled as follows: [noise], [hesitation] .I would like to know how to prepare my data and how can I handle these tags while preparing the data. I would also like to know if the noise tags will be predicted in the decoding output or not.

Thanks in advance

**Comment by JinZr** [comment]
i think this is totally up to you, some recipes (e.g. swbd) retain the non-verbal symbols and some don't, depending on whether you want to do certain post-processing with the transcript i suppose
