### ISSUE TITLE
cleanup training dataset. 

### ISSUE THREAD

**Issue by kerolos** [k2-fsa/icefall#1145]
Is there any method in Icefall to filter and clean-up the training dataset ?
In traditional Kaldi, there are some scripts to clean up and segments (or cut)  and find also a systematic mismatch between speech and text (which repeated several times).

Kaldi uses /egs/wsj/s5/steps/cleanup/:  
A) GMM (clean_and_segment_data.sh - find_badd_utts.sh ). "not worked perfect for me especially if there are in systematic error in the dataset"
B) NNET (clean_and_segment_data_nnet3.sh - find_badd_utts_nnet3.sh).  "It depends on the pretrained model, which is not good in my case"

Thanks in advance.

**Comment by csukuangfj** [comment]
> Is there any method in Icefall to filter and clean-up the training dataset ?

Yes, there is. The pre-condition is that you have to setup the condition for filtering.

For instance, The following statement removes some cuts that don't satisfy the given constraint.
https://github.com/k2-fsa/icefall/blob/4d5b8369aef8bbe73c0baf5d72200dc2c1e9c0b6/egs/librispeech/ASR/local/filter_cuts.py#L124

Note that `cut_set.filter` accepts a lambda and you can use a lambda implementing any constraint you want.
