### ISSUE TITLE
Docker file build issue. K2 module is giving issue

### ISSUE THREAD

**Issue by sanjuktasr** [k2-fsa/icefall#1171]
During k2 build ------Makefile:159: recipe for target 'all' failed.

**Comment by csukuangfj** [comment]
Please post complete logs.

**Comment by csukuangfj** [comment]
@sanjuktasr 

Please see
https://hub.docker.com/repository/docker/k2fsa/icefall/tags?page=1&ordering=last_updated

We have pre-built docker images for icefall.

<img width="962" alt="Screenshot 2023-07-28 at 10 03 21" src="https://github.com/k2-fsa/icefall/assets/5284924/e775c636-10c8-4c0b-988f-4ffa824b0653">
