### ISSUE TITLE
Librispeech CUDA OOM

### ISSUE THREAD

**Issue by RuslanSel** [k2-fsa/icefall#1174]
When I try to reproduce training Librispeech pruned_transducer_stateless7, I am getting CUDA out of memory.

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 426.00 MiB (GPU 0; 11.75 GiB total capacity; 4.52 GiB already allocated; 83.50 MiB free; 10.46 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

How can I fix that?
Is it possible to train Librispeech with 12 GB CUDA memory?

Thanks in advance.

**Comment by yfyeung** [comment]
Please decrease the --max-duration

**Comment by RuslanSel** [comment]
Thanks.
