### ISSUE TITLE
Which layers should be used to MVQ?

### ISSUE THREAD

**Issue by yuekaizhang** [k2-fsa/icefall#1195]
Hi,

In https://arxiv.org/pdf/2211.00508.pdf, "The embeddings of the 18-th transformer block are extracted for CI generation as we believe this layer contains rich information while being less difficult to learn from."

I was wondering if you have some experience or know some literature about how to choose the teacher model layers for distillation. e.g. How to know if it is difficult or not to learn? Why not use the last layer?

**Comment by marcoyang1998** [comment]
We tried the last layer and it just didn't yield the best results. It might be that the last layer contains more sequence-level information whereas the middle layer focuses more on local information (which is easier to learn).

**Comment by desh2608** [comment]
[This paper](https://arxiv.org/pdf/2107.04734.pdf) did some good analysis of the layer-wise representations from an SSL model. The [Hubert paper](https://arxiv.org/pdf/2106.07447.pdf) also has similar analysis (see Fig. 2).
