### ISSUE TITLE
ValueError when computing fbank

### ISSUE THREAD

**Issue by LoganLiu66** [k2-fsa/icefall#1196]
When I run `python ./local/compute_fbank_online_splits.py`, the following error occurs:
```
ValueError: Caught ValueError in DataLoader worker process 14.
Original Traceback (most recent call last):
  File "/opt/conda/envs/k2/lib/python3.8/site-packages/lhotse/utils.py", line 804, in wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/envs/k2/lib/python3.8/site-packages/lhotse/audio.py", line 641, in load_audio
    audio = assert_and_maybe_fix_num_samples(
  File "/opt/conda/envs/k2/lib/python3.8/site-packages/lhotse/audio.py", line 2212, in assert_and_maybe_fix_num_samples
    raise ValueError(
ValueError: The number of declared samples in the recording diverged from the one obtained when loading audio (offset=0.0, 
duration=8.24). This could be internal Lhotse's error or a faulty transform implementation. Please report this issue in Lhotse and 
show the following: diff=99094, audio.shape=(1, 32746), recording=Recording(id='6483491424227435283', sources=
[AudioSource(type='file', channels=[0], source='6483491424227435283.wav')], sampling_rate=16000, num_samples=131840, 
duration=8.24, channel_ids=[0], transforms=None)
```
When I run  `torchaudio.info(filename)`, it outputs:
```
AudioMetaData(sample_rate=16000, num_frames=131840, num_channels=1, bits_per_sample=16, encoding=PCM_S)
```
When I use `torchaudio.load(filename)` it shows:
```
Sample rate: 16000 Length in seconds: 2.046625 torch.Size([1, 32746])
```
What are the possible reasons for this difference

**Comment by desh2608** [comment]
Where is this script `./local/compute_fbank_online_splits.py` from?

**Comment by danpovey** [comment]
Likely the length of that file in the metadata in the manifest is different from its real length, e.g. duration=8.24 vs. 2.046626 seconds.

**Comment by LoganLiu66** [comment]
> Where is this script `./local/compute_fbank_online_splits.py` from?

This script is similar with `./local/compute_fbank_gigapeech_splits.py`, which is used to process my own data.

**Comment by RuslanSel** [comment]
I have the same error on my own data set, created from kaldi directory with
recordings, supervisions, _ = load_kaldi_data_dir(
    data_dir, sampling_rate=16000
)
recordings, supervisions = fix_manifests(recordings=recordings, supervisions=supervisions)

**Comment by danpovey** [comment]
Try to figure out where the length mismatch came from.  Sometimes a .wav file can have an inaccurate length in its header, which might be corrected once you read the whole file.  Perhaps the script that created the manifest was realying on the header of the .wav file.
There may be a way to put the feature extraction in some kind of try-except block in order to ignore rare errors.

**Comment by RuslanSel** [comment]
In my case, the reason for the error was the difference in sample rate.
