### ISSUE TITLE
Missing optimized_transducer from requirements.txt

### ISSUE THREAD

**Issue by mohsen-goodarzi** [k2-fsa/icefall#1199]
It seems that `optimized_transducer ` is used in some receipts but is not included in requierments.txt!
https://github.com/k2-fsa/icefall/blob/1ee251c8b385f6dcf06da40b1760b76496b0d812/egs/librispeech/ASR/transducer_stateless_multi_datasets/model.py#L145

**Comment by csukuangfj** [comment]
When we first started to use transducer, we used optimized_transducer to compute loss. But now we suggest that you switch to pruned transducer loss from k2.

Please refer to
https://github.com/csukuangfj/optimized_transducer#installation-faq
to install optimized_transducer if you plan to run that old recipe.

**Comment by mohsen-goodarzi** [comment]
Thank you for info.
