### ISSUE TITLE
你好，请问怎么训练双语流式语音识别模型，看demo好像都是仅中文或者仅英文

### ISSUE THREAD

**Issue by cxt520ppgsh** [k2-fsa/icefall#1201]
可以介绍一下https://huggingface.co/csukuangfj/sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13这里的model是怎么训练的吗

**Comment by marcoyang1998** [comment]
我们有一个中英文数据集的recipe，可以参考这里的数据准备和训练的脚本：https://github.com/k2-fsa/icefall/tree/master/egs/tal_csasr/ASR

**Comment by cxt520ppgsh** [comment]
> 我们有一个中英文数据集的recipe，可以参考这里的数据准备和训练的脚本：https://github.com/k2-fsa/icefall/tree/master/egs/tal_csasr/ASR

感谢回复，我看了issue1054的方案大致是
Use https://github.com/k2-fsa/icefall/tree/master/egs/librispeech/ASR/pruned_transducer_stateless7_streaming
to replace [pruned_transducer_stateless5](https://github.com/k2-fsa/icefall/tree/master/egs/tal_csasr/ASR/pruned_transducer_stateless5)

如果仅用tal_csasr 这个recipe是不支持流式的吧。
所以应该参考issue1054用pruned_transducer_stateless7_streaming去训练tal_csasr是吗？

**Comment by marcoyang1998** [comment]
建议参考 https://github.com/k2-fsa/icefall/tree/master/egs/librispeech/ASR/zipformer 训练，这是 icefall 最好的模型，如果需要流式模型，把causal设成True即可

**Comment by JinZr** [comment]
您好，您也可以参考这个 PR https://github.com/k2-fsa/icefall/pull/1265 的内容，使用 byte-level BPE 训练流式 Zipformer 模型。
