### ISSUE TITLE
add new words in any model during recognition (dynamic) ; for example "zipformer"

### ISSUE THREAD

**Issue by kerolos** [k2-fsa/icefall#1203]
Can i add a list of phrases in real time during decoding in a zipformer or any other models to recognize those new words.
I have watched this toturial on Youtube https://youtu.be/gtVWuiCzz2c #62 context braising, but I am not sure if there is an implemention available? 
Thanks in advance

**Comment by pkufool** [comment]
@kerolos  We only implement this feature in one of our old recipe, see https://github.com/k2-fsa/icefall/pull/1038 . It will be good if you can add it to zipformer recipe. You only need to add some code in zipformer/decode.py with [this](https://github.com/k2-fsa/icefall/pull/1038/files#diff-62783b2aaeb193453f97adc4c16123ed5b9c0142ab20f728025839ec7ad25f2b) as a reference.
