### ISSUE TITLE
Zipformer2 with BS

### ISSUE THREAD

**Issue by ezerhouni** [k2-fsa/icefall#1218]
I have code for a zipformer with blank skip (zipformer2). Would you be interested in me pushing the code even though I don't have numbers for librispeech (it works on my dataset) ?
 @csukuangfj

**Comment by yfyeung** [comment]
We are interested in that. Since we only support open-source dataset recipes, maybe you can submit a PR so that we can reference your code.

**Comment by ezerhouni** [comment]
@yfyeung Sounds good, I will work on it tomorrow then

**Comment by yfyeung** [comment]
Thx. And if it is a recipe of a non-public dataset, please add the prefix [Not for merge] to the PR.
