### ISSUE TITLE
Train some model on my own?

### ISSUE THREAD

**Issue by 15899885850** [k2-fsa/icefall#1221]
Hello!
I would like to know if it is possible to train some models on my own, such as models for small languages or dialects, and then use them? Or Lora?
Hope to receive your reply!

**Comment by yfyeung** [comment]
Hi, the first thing you need to do is to prepare your data.

Please have a look at

https://github.com/lhotse-speech/lhotse
https://lhotse.readthedocs.io/en/latest/
You can find a list of corpus at

https://github.com/lhotse-speech/lhotse/tree/master/lhotse/recipes
Specifically, I would recommend reading

https://github.com/lhotse-speech/lhotse/blob/master/lhotse/recipes/yesno.py
You can find the yesno recipe in https://github.com/k2-fsa/icefall/tree/master/egs/yesno/ASR

**Comment by 15899885850** [comment]
> Hi, the first thing you need to do is to prepare your data.嗨，您需要做的第一件事是准备数据。
> 
> Please have a look at请看一下
> 
> https://github.com/lhotse-speech/lhotse https://lhotse.readthedocs.io/en/latest/ You can find a list of corpus at您可以在以下位置找到语料库列表
> 
> https://github.com/lhotse-speech/lhotse/tree/master/lhotse/recipes Specifically, I would recommend reading具体来说，我建议阅读
> 
> https://github.com/lhotse-speech/lhotse/blob/master/lhotse/recipes/yesno.py You can find the yesno recipe in https://github.com/k2-fsa/icefall/tree/master/egs/yesno/ASR您可以在 https://github.com/k2-fsa/icefall/tree/master/egs/yesno/ASR 中找到yesno食谱

Thanks for your reply! I am a novice at TTS or ASR, I would have a try!
