### ISSUE TITLE
diagnostics.py arbitrary types

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/icefall#1233]
Can we change diagnostics.py so that it won't crash regardless of what the return type of forward() is?
e.g. if it's a tuple of ints, or a list of lists, and so on.  We don't have to do anything- just return without
accumulating stats or checking the data, this is to ensure it doesn't crash when applied to arbitrary models.

**Comment by yaozengwei** [comment]
Yes. Currently we just handle a tuple of Tensors or a Tensor. see
https://github.com/k2-fsa/icefall/blob/master/icefall/diagnostics.py#L143-L154
```
    def accumulate(self, x, class_name: Optional[str] = None):
        """
        Accumulate tensors.
        """
        if class_name is not None:
            self.class_name = class_name
        if isinstance(x, Tuple):
            x = x[0]
        if not isinstance(x, Tensor):
            return
        if x.numel() == 0:  # for empty tensor
            return
```
But we can extend it to other cases (a tuple of ints, or a list of lists, and so on.).

**Comment by danpovey** [comment]
My PR #1234 stops it crashing.. it's not quite as general as  your fix but at least it's tested on a newer torch version.  (not on current one though),... also resolves eigenvalue-related issue.
