### ISSUE TITLE
Bypass Temporal Classification: recipe?

### ISSUE THREAD

**Issue by AdolfVonKleist** [k2-fsa/icefall#1246]
The recent Interspeech paper: "Bypass Temporal Classification: Weakly Supervised Automatic Speech Recognition with Imperfect Transcripts"

was really interesting, and I was wondering if you have a timeline to release it in icefall?

**Comment by csukuangfj** [comment]
@DongjiGao Could you take a look?

**Comment by joazoa** [comment]
We'll be happy to test it!

**Comment by AlexandderGorodetski** [comment]
Guys, I would like to test this approach on my data. Could you please point me to the relevant example in icefall.

**Comment by DongjiGao** [comment]
> Guys, I would like to test this approach on my data. Could you please point me to the relevant example in icefall.

@AlexandderGorodetski https://github.com/k2-fsa/icefall/tree/master/egs/librispeech/WSASR

**Comment by AlexandderGorodetski** [comment]
@DongjiGao thank yo so much for your answer. Do you think this recipe will work for another language, e.g. Russian?

**Comment by DongjiGao** [comment]
> @DongjiGao thank yo so much for your answer. Do you think this recipe will work for another language, e.g. Russian?

@AlexandderGorodetski You should definitely give it a try :)
