### ISSUE TITLE
Problem for long wav with multi supervisions

### ISSUE THREAD

**Issue by tz301** [k2-fsa/icefall#126]
When I train with data which has multi supervisions, such as one wav has two supervisions [(0, 5, 'I'm good'), (10, 15, 'ok')], error will occur.

I have debug it and find the reason. For dataloader, lhotse.load_manifest will get one MonoCut with two supervisions, but will only generate one feature. 

I print some variables in compute_loss() in conformer_ctc/train.py. The first dimension of feature is 1, but the length of token_ids = graph_compiler.texts_to_ids(texts) is 2. Then decode_forward() will fail.

**Comment by pzelasko** [comment]
Snowfall had support for multi-supervision cuts, but I think Icefall doesn't work with them (yet/anymore?). You can run `cut_set = cut_set.trim_to_supervisions()` to split multi-supervision cuts to single-supervision cuts (you might need `keep_overlapping=False` flag if there is overlapping speech).
