### ISSUE TITLE
Training model k2

### ISSUE THREAD

**Issue by monid6498** [k2-fsa/icefall#1281]
ImportError: cannot import name 'SingleCutSampler' from 'lhotse.dataset' (/mnt/efs/swetha/icefall_environ/lib/python3.8/site-packages/lhotse/dataset/__init__.py)

**Comment by marcoyang1998** [comment]
This is an error caused by `lhotse`. The latest version of `lhotse` removes `SingleCutSampler`. We will fix this soon, as a temporary fix, you can comment the line importing `SingleCutSampler`.
