### ISSUE TITLE
questions about mandarin Chinese-Cantonese zipformer

### ISSUE THREAD

**Issue by 1215thebqtic** [k2-fsa/icefall#1294]
Hi,

I trained a zipformer model with 80kh mandarin Chinese and 7kh Cantonese. The model performs very poor on Cantonese test set (cer=80%+), and it performs good on madarin Chinese test sets. The loss curve consistently oscillates, and mandarin Chinese is used as dev set. It seems the model learns nothing about Cantonese.
![87k](https://github.com/k2-fsa/icefall/assets/11812181/a6d0ab06-c201-40bb-bf60-d360cb3d2a88)

I didn't shuffle the train cuts between mandarin Chinese and Cantonese. Is it because of this reason resulting in the bad performance on Cantonese? Are there any other issues that I need to pay attention to?

Thanks!

**Comment by marcoyang1998** [comment]
Your dataset is quite unbalanced, I recommend you have both Mandarin and Cantonese data in each batch if possible.

Also, it would be nice to have two dev sets so that you can know how well the model is performing on Cantonese during training.

**Comment by 1215thebqtic** [comment]
Thanks! I'll try.

**Comment by lalimili6** [comment]
@marcoyang1998 
can copy or augment Cantonese?
How can change the goal function for unbalanced data?

**Comment by marcoyang1998** [comment]
@lalimili6 
You can have a look at this: https://lhotse.readthedocs.io/en/latest/api.html#lhotse.supervision.SupervisionSet.mux

**Comment by 1215thebqtic** [comment]
shuffling cuts solved this issue
