### ISSUE TITLE
Tensorboard.dev is shutting down

### ISSUE THREAD

**Issue by desh2608** [k2-fsa/icefall#1298]
It seems that tensorboard.dev is shutting down after Dec 31, 2023. All the training logs uploaded there will become inaccessible after this date. Is there an alternative for sharing logs in the future? I suppose the "training metrics" tab on uploaded HF repos is the only option.

**Comment by desh2608** [comment]
May be worth switching to wandb (https://wandb.ai/site).

**Comment by csukuangfj** [comment]
> https://wandb.ai/site

Is it free?

**Comment by pkufool** [comment]
![image](https://github.com/k2-fsa/icefall/assets/11765074/2ac76677-d405-432a-9fae-3efe6d3b05c6)

100GB storage for personal, similar to tensorboard.dev.

**Comment by csukuangfj** [comment]
> May be worth switching to wandb (https://wandb.ai/site).

100GB is large enough for our use.
