### ISSUE TITLE
librispeech-ASR-prepare.sh 'G_3_gram.fst.txt' not found

### ISSUE THREAD

**Issue by Eric-Chen-007** [k2-fsa/icefall#1306]
egs/librispeech/ASR/prepare.sh

stage 6, line 246
``` shell
>>> if [ ! -f $lang_dir/HL.fst ]; then
>>>  ./local/prepare_lang_fst.py  --lang-dir $lang_dir --ngram-G ./data/lm/G_3_gram.fst.txt
>>> fi
```
'G_3_gram.fst.txt' is generated in stage 8, Is this a problem about the order of stage?
If i sequentially run the prepare.sh shell, in stage 6, i found an error, no such file or directory './data/lm/G_3_gram.fst.txt'.

**Comment by Eric-Chen-007** [comment]
I should run stage 8 first, then run stage 6? For the beginer, it's not friendly.

**Comment by csukuangfj** [comment]
> 'G_3_gram.fst.txt' is generated in stage 8, Is this a problem about the order of stage?

Sorry, it is an error/bug.

**Comment by JinZr** [comment]
this PR should fix the issue https://github.com/k2-fsa/icefall/pull/1307

**Comment by csukuangfj** [comment]
fixed by #1307

**Comment by oshindow** [comment]
> fixed by #1307

The latest verison 
```
if [ $stage -le 8 ] && [ $stop_stage -ge 8 ]; then
  log "Stage 8: Prepare G"

  mkdir -p data/lm

  # Train LM on transcripts
  if [ ! -f data/lm/3-gram.unpruned.arpa ]; then
    python3 ./shared/make_kn_lm.py \
      -ngram-order 3 \
      -text $lang_char_dir/transcript_words.txt \
      -lm data/lm/3-gram.unpruned.arpa
  fi

  # We assume you have installed kaldilm, if not, please install
  # it using: pip install kaldilm
  if [ ! -f data/lm/G_3_gram_char.fst.txt ]; then
    # It is used in building HLG
    python3 -m kaldilm \
      --read-symbol-table="$lang_phone_dir/words.txt" \
      --disambig-symbol='#0' \
      --max-order=3 \
      data/lm/3-gram.unpruned.arpa > data/lm/G_3_gram_phone.fst.txt

    python3 -m kaldilm \
      --read-symbol-table="$lang_char_dir/words.txt" \
      --disambig-symbol='#0' \
      --max-order=3 \
      data/lm/3-gram.unpruned.arpa > data/lm/G_3_gram_char.fst.txt
  fi

  if [ ! -f $lang_char_dir/HLG.fst ]; then
    lang_phone_dir=data/lang_phone
    ./local/prepare_lang_fst.py  \
      --lang-dir $lang_phone_dir \
      --ngram-G ./data/lm/G_3_gram.fst.txt
  fi
fi
```
still report bugs: 

2023-11-07 10:18:22 (prepare.sh:237:main) Stage 8: Prepare G
2023-11-07 10:18:24,930 INFO [prepare_lang_fst.py:174] Building standard CTC topology
2023-11-07 10:18:25,310 INFO [prepare_lang_fst.py:183] Building L
2023-11-07 10:18:30,268 INFO [prepare_lang_fst.py:191] Building HL
2023-11-07 10:19:00,224 INFO [prepare_lang_fst.py:204] Building HLG
Traceback (most recent call last):
  File "./local/prepare_lang_fst.py", line 219, in <module>
    main()
  File "./local/prepare_lang_fst.py", line 205, in main
    with open(args.ngram_G) as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/lm/G_3_gram.fst.txt'

**Comment by csukuangfj** [comment]
> still report bugs:



Could you post the link to the code?

The code you posted does not seem to be the latest one.

**Comment by oshindow** [comment]
> > still report bugs:
> 
> Could you post the link to the code?
> 
> The code you posted does not seem to be the latest one.

https://github.com/k2-fsa/icefall/blob/master/egs/aishell/ASR/prepare.sh

**Comment by csukuangfj** [comment]
I see. You are using aishell, not librispeech.

Could you change `G_3_gram.fst.txt` to `G_3_gram_char.fst.txt`?
