### ISSUE TITLE
training custom dataset

### ISSUE THREAD

**Issue by shreyasinghal-17** [k2-fsa/icefall#1311]
I want to train with a dataset of 8k audios
What changes are required also is there a recipe that is recommended, my use case is both streaming and non streaming asr and I wish to use the Icefall model in sherpa

**Comment by JinZr** [comment]
hi, `8k` refers to the sampling rate or the num of hours?

**Comment by JinZr** [comment]
Dear Shreya Singhal,

i suppose you can make a recipe of your own based on the librispeech
zipformer recipe if an en
based model is what u need, you'll need to modify the
`compute_fbank_librispeech.py` (e.g. set
the sampling rate of feature extractor to 8000 and downsample the musan to
8000 etc.)

setting `--causal` to False will train a non-streaming zipformer model,
`--causal` to True will train a streaming version of zipformer model.

Best

**Comment by shreyasinghal-17** [comment]
Hi Jin,

Would you recommend the latest zipformer recipe or the pruned_transducer_stateless7,  I understand that stateless7 was the first experiment with the zipformer, but my inhibition is that throughout the issues/documentation stateless7 is used more, for example even the documentation about using lm uses stateless7 recipe as example. 

Are my concerns valid or anything that works well with statelessX shouldwork well with zipformer as well?

**Comment by JinZr** [comment]
Hi Shreya Singhal,

Everything that works with stateless7 should work as well with the
Zipformer model. For decoding w. lm, please check the RESULTS.md of the
zipformer recipe for more details. Plus both streaming and non-streaming
versions use the same codebase, which is more convenient.

Best regards
