### ISSUE TITLE
PromptASR training

### ISSUE THREAD

**Issue by pavankumar-ds** [k2-fsa/icefall#1315]
Hi @marcoyang1998,

Thank you for the PromptASR paper and the recipe. I am trying to replicate the training on libriheavy dataset. First, I could not find the base recipe for libriheavy, so I tried using the `libriheavy_recipe` branch of `git@github.com:pkufool/icefall.git`. A few conventions seemed different, for e.g. `texts[0]` versus the conventional `text`. I tried modifying these and started the training, however, the models (both baseline and PromptASR) seem to not converge. Decoding with your uploaded models (both baseline and PromptASR) works perfectly though. Do you have any suggestions for the training part?

Thanks.

**Comment by marcoyang1998** [comment]
Hi @pavankumar-ds ,

On which subset and which recipe are you using to train the baseline model? Are you training with a single style of transcription?

**Comment by pavankumar-ds** [comment]
I tried using the small and medium subsets, using the `zipformer_prompt_asr/train_baseline.py`. I am training with mixed case transcription with punctuation. I used the standard script you committed into the libriheavy directory to generate the sentencepiece model.

**Comment by marcoyang1998** [comment]
The recipe uses the style of upper-cased text without punctuation by default, see https://github.com/k2-fsa/icefall/blob/52c24df61da3d04a6fdcab32d5615c394951279b/egs/libriheavy/ASR/zipformer_prompt_asr/train_baseline.py#L1226
Would you mind decode your models and see if the model outputs only upper-cased text?


If you want to use the MCP style for training, please set the `text_sampling_func` to `get_first`  https://github.com/k2-fsa/icefall/blob/52c24df61da3d04a6fdcab32d5615c394951279b/egs/libriheavy/ASR/zipformer_prompt_asr/train_baseline.py#L103

**Comment by mohsen-goodarzi** [comment]
I am also trying this recipe but I get following error:
`No such file or directory: 'data/tmp/transcript_words_medium.txt'`

How we should prepare this file?

**Comment by marcoyang1998** [comment]
@mohsen-goodarzi Do you have the manifest `data/fbank/libriheavy_cuts_medium.jsonl.gz`?

**Comment by mohsen-goodarzi** [comment]
> @mohsen-goodarzi Do you have the manifest `data/fbank/libriheavy_cuts_medium.jsonl.gz`?

No, how can I obtain it?

**Comment by marcoyang1998** [comment]
@mohsen-goodarzi  There is a base recipe for Libriheavy that has not been merged yet. Please follow this script (https://github.com/k2-fsa/icefall/blob/a2dafee5a348d579b79b92a25105bcc5595cd75d/egs/libriheavy/ASR/prepare.sh) for data preparation.

**Comment by mohsen-goodarzi** [comment]
> @mohsen-goodarzi There is a base recipe for Libriheavy that has not been merged yet. Please follow this script (https://github.com/k2-fsa/icefall/blob/a2dafee5a348d579b79b92a25105bcc5595cd75d/egs/libriheavy/ASR/prepare.sh) for data preparation.

Thank you so much!

**Comment by pavankumar-ds** [comment]
Thank you for your clarification. Changing the base learning rate to 0.01 seems to have worked. The training (with text in all caps as you rightly pointed out) is still in progress; I decoded with an intermediate model and confirmed it is training well. The training log plot looks much better now.

> Would you mind decode your models and see if the model outputs only upper-cased text?
> If you want to use the MCP style for training, please set the `text_sampling_func` to `get_first`

Yes, the decoded output is in upper case, although it just outputs a single letter for every utterance (which means the model did not converge at all). I tried setting `text_sampling_func` to `None` (because my cuts have a single mixed case text) and started another round of training, but it still did not converge.

**Comment by marcoyang1998** [comment]
> Yes, the decoded output is in upper case, although it just outputs a single letter for every utterance (which means the model did not converge at all). I tried setting text_sampling_func to None (because my cuts have a single mixed case text) and started another round of training with the default learning rate, but it still did not converge.

How many GPUs are you training the model with? And what's the `--max-duration` you are using?

**Comment by pavankumar-ds** [comment]
It's 1 GPU and max duration of 100.

**Comment by marcoyang1998** [comment]
> It's 1 GPU and max duration of 100.

The max-duration is too small, which might cause the model convergence issue in your case. We trained with 4 V100 GPUs using max-duration 1000.

**Comment by pavankumar-ds** [comment]
Oh okay, thanks. With this smaller setting, is reducing the learning rate the only option?

**Comment by marcoyang1998** [comment]
> Oh okay, thanks. With this smaller setting, is reducing the learning rate the only option?

Yes, but this will hurt the model's performance.
