### ISSUE TITLE
Reducing of Tedlium data or architecture for study purposes

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#1323]
Guys, 

I would like to study your Tedlium recipe. I've already created manifest files and fbank files. Could you please recommend me what can I do in order to perform relatively fast training for studying purposes. How can I decrease amount of data or architecture of the model?

Thanks a lot,
AlexG.

**Comment by desh2608** [comment]
You could probably train a smaller zipformer by adding the following options to the train.py call:

```
  --num-encoder-layers 2,2,2,2,2,2 \
  --feedforward-dim 512,768,768,768,768,768 \
  --encoder-dim 192,256,256,256,256,256 \
  --encoder-unmasked-dim 192,192,192,192,192,192 \
```

With the above, you should be able to train using a large batch size (e.g., `max-duration 1500`) if you have 32G GPUs.

In any case, all these models train very fast. For me, it took ~13h to train the model for 50 epochs using 4 GPUs.
