### ISSUE TITLE
icefall/rnn_lm/train.py error

### ISSUE THREAD

**Issue by Eric-Chen-007** [k2-fsa/icefall#1335]
UnboundLocalError: local variable 'loss' referenced before assignment

``` python
def compute_validation_loss(
    params: AttributeDict,
    model: nn.Module,
    valid_dl: torch.utils.data.DataLoader,
    world_size: int = 1,
) -> MetricsTracker:
    """Run the validation process. The validation loss
    is saved in `params.valid_loss`.
    """
    model.eval()

    tot_loss = MetricsTracker()

    for batch_idx, batch in enumerate(valid_dl):
        x, y, sentence_lengths = batch
        with torch.cuda.amp.autocast(enabled=params.use_fp16):
            loss, loss_info = compute_loss(
                model=model,
                x=x,
                y=y,
                sentence_lengths=sentence_lengths,
                is_training=False,
            )

        assert loss.requires_grad is False
        tot_loss = tot_loss + loss_info

    if world_size > 1:
        tot_loss.reduce(loss.device)

    loss_value = tot_loss["loss"] / tot_loss["frames"]
    if loss_value < params.best_valid_loss:
        params.best_valid_epoch = params.cur_epoch
        params.best_valid_loss = loss_value

    return tot_loss
```

**Comment by marcoyang1998** [comment]
I don't see a bug here. Could you please check if your `valid_dl` is empty?

**Comment by Eric-Chen-007** [comment]
> I don't see a bug here. Could you please check if your `valid_dl` is empty?

I change 'world_size' to 1, then there's no Error message.
For world_size == 4, it'll crash.

**Comment by marcoyang1998** [comment]
> I change 'world_size' to 1, then there's no Error message.
For world_size == 4, it'll crash.

What are you doing here? Are you using pdb to debug the code? If so, you can only use pdb if you set `--world-size` to 1.

When you are debugging, could you please check if your code ever goes into the for loop: 
```python
for batch_idx, batch in enumerate(valid_dl)
```

**Comment by Eric-Chen-007** [comment]
> > I change 'world_size' to 1, then there's no Error message.
> > For world_size == 4, it'll crash.
> 
> What are you doing here? Are you using pdb to debug the code? If so, you can only use pdb if you set `--world-size` to 1.
> 
> When you are debugging, could you please check if your code ever goes into the for loop:
> 
> ```python
> for batch_idx, batch in enumerate(valid_dl)
> ```

I am tring to generate RNN-LM by "./icefall/rnn-lm/train.py", then to use "Shallow fusion" decoding .
I tried --world-size 4 first, then it crashed, then i changed to 1, it runs correctly.
I'll try to see if my code ever gone to the loop.

**Comment by Eric-Chen-007** [comment]
> > I change 'world_size' to 1, then there's no Error message.
> > For world_size == 4, it'll crash.
> 
> What are you doing here? Are you using pdb to debug the code? If so, you can only use pdb if you set `--world-size` to 1.
> 
> When you are debugging, could you please check if your code ever goes into the for loop:
> 
> ```python
> for batch_idx, batch in enumerate(valid_dl)
> ```

For wolrd-size 2 or 4, it didn't go to the loop.
For world-size 1, it goest to the loop.
A bit strange.

**Comment by Eric-Chen-007** [comment]
> > I change 'world_size' to 1, then there's no Error message.
> > For world_size == 4, it'll crash.
> 
> What are you doing here? Are you using pdb to debug the code? If so, you can only use pdb if you set `--world-size` to 1.
> 
> When you are debugging, could you please check if your code ever goes into the for loop:
> 
> ```python
> for batch_idx, batch in enumerate(valid_dl)
> ```

I find if batch_size == 400, and your valid data set size is 100 (sentences), world_size > 1, then  
```python
valid_dl = get_dataloader(
        filename=params.lm_data_valid,
        is_distributed=is_distributed,
        params=params,
    )
```
len(valid_dl) will be 0

If your validation data set size is 100, and set batch_size = 50, world_size = 2, then len(valid_dl) = 1.

It seems like when your validation size is small, it'll crash there.
