### ISSUE TITLE
broken link in Readme file

### ISSUE THREAD

**Issue by Shreyas0410** [k2-fsa/icefall#1341]
The link of Deployment with C++ is broken in Readme file.
The link - (https://icefall.readthedocs.io/en/latest/recipes/librispeech/conformer_ctc.html#deployment-with-c)

![Screenshot 2023-10-26 112325](https://github.com/k2-fsa/icefall/assets/70795867/cdd43167-8b5a-4925-9663-64da5c50dddf)

To Reproduce - 
Go to Readme file and scroll to Deployment with C++ and click on the documentation link

**Comment by git-create-devben** [comment]
I'll be happy to work on this
