### ISSUE TITLE
pruned_transducer_stateless7_streaming export for ncnn

### ISSUE THREAD

**Issue by epicyclism** [k2-fsa/icefall#1344]
I trained a model with pruned_transducer_stateless7_streaming. I'm experimenting with Portuguese and was able to produce an lstm model a while ago with modest success, exporting it to ncnn format and using it in my code, so used the same data and dataloader. I used train.py and the training completed, decoding made sense, I exported to ncnn. In my code I then get 'layer pnnx.Expression not exists or registered'.

Then I noticed a comment about train2.py and zipformer2,py only existing for exporting to sherpa-ncnn (the comment at the bottom of the readme says 'emformer2.py' rather than zipformer2.py, but...). So I tried those. And I get an assert at line 1884 of zipformer2.py,

```
  File "/working/portuguese_zipformer/zipformer2.py", line 1884, in forward
    assert self.x_size == x.size(0), (self.x_size, x.size(0))
AssertionError: (16, 380)
```

I'm now lost. I'm not a Python expert but there's an implication that if you run zipformer2.py 'standalone' it runs some tests, but that asserts too. Anyone can try this...

Any advice on training and exporting models suitable for sherpa-ncnn?

**Comment by csukuangfj** [comment]
Have you followed our documentation at
https://k2-fsa.github.io/icefall/model-export/export-ncnn.html

It is a detailed step-by-step guide.

**Comment by epicyclism** [comment]
A confusion over my build of pnnx seems to have led me on a wild goose chase yesterday afternoon. Reset according to the instructions and it all works. So sorry for wasting your time and thanks for being so helpful.

FWIW I had to change line 27 of ncnn/tools/pnnx/CMakeFiles.txt because it seems Torch now requires at least C++17.
