### ISSUE TITLE
offline zipformer2, timestamp for first token is always 0

### ISSUE THREAD

**Issue by joazoa** [k2-fsa/icefall#1347]
Hello,

I still experience the issue where the first word timestamp is aways zero with the onnx zipformer2.

I have seen the comments in :
https://github.com/k2-fsa/icefall/pull/942
https://github.com/k2-fsa/icefall/issues/923 
https://github.com/k2-fsa/sherpa/pull/52

Is there any way to avoid this with the zipformer2 ? I tried without onnx and the result is the same. Is the same, there is no padding_idx=blank_id in the decoder as in the decoders patched in the commit above.

Would the zipformer_CTC that was committed earlier today have the same issue ?

I have vague memories of another issue or pull request where [csukuangfj] made a more detailed analysis for another model (I think transducer_stateless ) that did not have the issue, but cannot find those comments anymore.

Thank you!

**Comment by maltium** [comment]
The patch didn't really fix the issue in the original zipformer. Maybe it improved it, but when I did some testing I was still getting 0 timestamps for the first token.

**Comment by joazoa** [comment]
Thank you! I see a few samples with 0,04 but mostly 0. I checked with padded samples with large silence in the beginning and it did not detect it.

**Comment by 0xPNG** [comment]
@joazoa I'm not a core dev, just left a comment with my experience. So probably you should re-open it. 😀

**Comment by maltium** [comment]
@joazoa I'm just a user of icefall sharing my experience. You should probably keep the issue open 🙂.
