### ISSUE TITLE
decoding fails with zipformer2, transducer false, CTC true 

### ISSUE THREAD

**Issue by joazoa** [k2-fsa/icefall#1348]
Hello,

I tried to train a zipformer2 with only CTC, the training seems to work, but on decoding i get:
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "./zipformer/ctc_decode_zoa_ts.py", line 782, in main
    model.load_state_dict(average_checkpoints(filenames, device=device))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for AsrModel:
        Missing key(s) in state_dict: "decoder.embedding.weight", "decoder.conv.weight", "joiner.encoder_proj.weight", "joiner.encoder_proj.bias", "joiner.decoder_proj.weight", "joiner.decoder_proj.bias", "joiner.output_linear.weight", "joiner.output_linear.bias", "simple_am_proj.weight", "simple_am_proj.bias", "simple_lm_proj.weight", "simple_lm_proj.bias".
d

When I enable transducer + ctc for decoding (model is trained with transducer) then it works. (but timestamps for the first token are still always 0).

**Comment by csukuangfj** [comment]
could you show the complete command for training and decoding?

**Comment by joazoa** [comment]
I found a mistake in my decoding bash script, the use-transducer flag was set to false.
My apologies, closing this one.
