### ISSUE TITLE
Adding Contributors section to the readme.md

### ISSUE THREAD

**Issue by mohitd404** [k2-fsa/icefall#1349]
Why Contributors section:- A "Contributors" section in a repo gives credit to and acknowledges 
the people who have helped with the project, fosters a sense of community, and helps others
 know who to contact for questions or issues related to the project.

**Issue type**
- [✅] Docs

expected output:-

![3](https://github.com/k2-fsa/icefall/assets/146939900/5630b104-afca-4607-82ea-0ddf1e3c9b9a)

@csukuangfj  kindly assign this issue to me ! I would love to work on it ! Thank you !

**Comment by desh2608** [comment]
Contributions can already be viewed at: https://github.com/k2-fsa/icefall/graphs/contributors (and also on the side panel on the repo page). I don't see the necessity to add this in the README.
