### ISSUE TITLE
kaldifeat installation error

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#1365]
Hello guys, 

I was not able to install kaldifeat on GPU machine. I got below error. Please note that installation of kaldifeat on CPU machine is OK. Any help is appreciated.

(base) root@gpu-alex-speech-base-0-0:/workspace/inputs/alexg/asr/src/models/k2/icefall/egs/tedlium3/ASR_FA# pip install kaldifeat
Collecting kaldifeat
  Using cached kaldifeat-1.24.tar.gz (467 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: kaldifeat
  Building wheel for kaldifeat (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [119 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.8
      creating build/lib.linux-x86_64-3.8/kaldifeat
      copying kaldifeat/python/kaldifeat/fbank.py -> build/lib.linux-x86_64-3.8/kaldifeat
      copying kaldifeat/python/kaldifeat/online_feature.py -> build/lib.linux-x86_64-3.8/kaldifeat
      copying kaldifeat/python/kaldifeat/plp.py -> build/lib.linux-x86_64-3.8/kaldifeat
      copying kaldifeat/python/kaldifeat/spectrogram.py -> build/lib.linux-x86_64-3.8/kaldifeat
      copying kaldifeat/python/kaldifeat/mfcc.py -> build/lib.linux-x86_64-3.8/kaldifeat
      copying kaldifeat/python/kaldifeat/offline_feature.py -> build/lib.linux-x86_64-3.8/kaldifeat
      copying kaldifeat/python/kaldifeat/__init__.py -> build/lib.linux-x86_64-3.8/kaldifeat
      running build_ext
      Setting PYTHON_EXECUTABLE to /opt/conda/bin/python3
      For fast compilation, run:
      export KALDIFEAT_MAKE_ARGS="-j"; python setup.py install
      Setting make_args to '-j4'
      build command is:
      
                      cd build/temp.linux-x86_64-3.8
      
                      cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=/opt/conda/bin/python3 -Dkaldifeat_BUILD_TESTS=OFF  -DCMAKE_INSTALL_PREFIX=/tmp/pip-install-qagpv2x1/kaldifeat_d5f18258c3ff4469bc7eaf79ef213ed3/build/lib.linux-x86_64-3.8/kaldifeat  /tmp/pip-install-qagpv2x1/kaldifeat_d5f18258c3ff4469bc7eaf79ef213ed3
      
      
                      make  -j4  _kaldifeat install
      
      -- The C compiler identification is GNU 9.3.0
      -- The CXX compiler identification is GNU 9.3.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- C++ Standard version: 14
      -- Downloading pybind11 from https://github.com/pybind/pybind11/archive/5bc0943ed96836f46489f53961f6c438d2935357.zip
      -- pybind11 is downloaded to /tmp/pip-install-qagpv2x1/kaldifeat_d5f18258c3ff4469bc7eaf79ef213ed3/build/temp.linux-x86_64-3.8/_deps/pybind11-src
      -- pybind11 v2.11.0 dev1
      -- Found PythonInterp: /opt/conda/bin/python3 (found suitable version "3.8.10", minimum required is "3.6")
      -- Found PythonLibs: /opt/conda/lib/libpython3.8.so
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      -- Python executable: /opt/conda/bin/python3
      -- TORCH_DIR: /opt/conda/lib/python3.8/site-packages/torch
      -- Looking for pthread.h
      -- Looking for pthread.h - found
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Looking for pthread_create in pthreads
      -- Looking for pthread_create in pthreads - not found
      -- Looking for pthread_create in pthread
      -- Looking for pthread_create in pthread - found
      -- Found Threads: TRUE
      -- Found CUDA: /usr/local/cuda (found version "11.3")
      -- The CUDA compiler identification is unknown
      CMake Error at /opt/conda/lib/python3.8/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:47 (enable_language):
        No CMAKE_CUDA_COMPILER could be found.
      
        Tell CMake where to find the compiler by setting either the environment
        variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
        path to the compiler, or to the compiler name if it is in the PATH.
      Call Stack (most recent call first):
        /opt/conda/lib/python3.8/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:92 (include)
        /opt/conda/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
        cmake/torch.cmake:14 (find_package)
        CMakeLists.txt:59 (include)
      
      
      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-install-qagpv2x1/kaldifeat_d5f18258c3ff4469bc7eaf79ef213ed3/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
      See also "/tmp/pip-install-qagpv2x1/kaldifeat_d5f18258c3ff4469bc7eaf79ef213ed3/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeError.log".
      make: *** No rule to make target '_kaldifeat'.  Stop.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-qagpv2x1/kaldifeat_d5f18258c3ff4469bc7eaf79ef213ed3/setup.py", line 32, in <module>
          setuptools.setup(
        File "/opt/conda/lib/python3.8/site-packages/setuptools/__init__.py", line 163, in setup
          return distutils.core.setup(**attrs)
        File "/opt/conda/lib/python3.8/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/opt/conda/lib/python3.8/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/opt/conda/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/opt/conda/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/opt/conda/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/opt/conda/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/opt/conda/lib/python3.8/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/opt/conda/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/opt/conda/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/opt/conda/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 87, in run
          _build_ext.run(self)
        File "/opt/conda/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
          _build_ext.build_ext.run(self)
        File "/opt/conda/lib/python3.8/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/opt/conda/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
          self.build_extension(ext)
        File "/tmp/pip-install-qagpv2x1/kaldifeat_d5f18258c3ff4469bc7eaf79ef213ed3/cmake/cmake_extension.py", line 124, in build_extension
          raise Exception(
      Exception:
      Build kaldifeat failed. Please check the error message.
      You can ask for help by creating an issue on GitHub.
      
      Click:
          https://github.com/csukuangfj/kaldifeat/issues/new
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for kaldifeat
  Running setup.py clean for kaldifeat
Failed to build kaldifeat
ERROR: Could not build wheels for kaldifeat, which is required to install pyproject.toml-based projects
(base) root@gpu-alex-speech-base-0-0:/workspace/inputs/alexg/asr/src/models/k2/icefall/egs/tedlium3/ASR_FA#

**Comment by csukuangfj** [comment]
please refer to kaldifeat's installation documentation for how to install it.

It has a detailed guide.

**Comment by AlexandderGorodetski** [comment]
Hello guys. I am missing something.

For k2 installation I am using following commands:

pip install torch==1.13.0+cu116 torchaudio==0.13.0+cu116 -f https://download.pytorch.org/whl/torch_stable.html
pip install k2==1.24.3.dev20230725+cuda11.6.torch1.13.0 -f https://k2-fsa.github.io/k2/cuda.html

According to the documentation for kaldifeat installation I have to use following commands:

pip install torch==2.0.1+cu118 -f https://download.pytorch.org/whl/torch_stable.html
pip install kaldifeat==1.25.0.dev20230726+cuda11.8.torch2.0.1  -f https://csukuangfj.github.io/kaldifeat/cuda.html

Could you please send me the command that I can use for kaldifeat installation with torch==1.13

Thanks,
AlexG.

**Comment by csukuangfj** [comment]
the documentation lists example, example, example installation commands.

We expect that you know how to adapt it to your own needs.

**Comment by csukuangfj** [comment]
please visit https://csukuangfj.github.io/kaldifeat/cuda.html
to find out the exact string you need to give to 
pip install.

**Comment by csukuangfj** [comment]
```
pip install kaldifeat==1.25.1.dev20231022+cuda11.6.torch1.13.0 -f https://csukuangfj.github.io/kaldifeat/cuda.html
```

@AlexandderGorodetski
