### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by SSwethaSel0609** [k2-fsa/icefall#1368]
File "./pruned_transducer_stateless7/train.py", line 60, in <module>
    from decoder import Decoder
ModuleNotFoundError: No module named 'decoder'

Then I ran the command "pip install decoder" but it throwed an error 
ImportError: cannot import name 'Decoder' from 'decoder' (/mnt/efs/swetha/icefall_env_new/lib/python3.8/site-packages/decoder/__init__.py)

**Comment by csukuangfj** [comment]
please tell us in which directory and  the exact command you run.

**Comment by SSwethaSel0609** [comment]
./pruned_transducer_stateless7/[train.py](http://train.py/) --world-size 2 --num-epochs 30 --start-epoch 1 --exp-dir pruned_transducer_stateless7/exp --max-duration 100 --on-the-fly-feats True --num-workers 10 --manifest-dir /path/to/manifests --num-buckets 8 --bpe-model /path_to/lang_bpe_500/bpe.model

**Comment by csukuangfj** [comment]
What is the output of
```
ls -lh ./pruned_transducer_stateless7
```

**Comment by SSwethaSel0609** [comment]
total 460K
-rwxrwxrwx 1 anandh anandh    0 Oct 31 10:56 __init__.py
drwxrwxrwx 2 anandh anandh 6.0K Nov  4 12:28 __pycache__
-rwxrwxrwx 1 anandh anandh  15K Oct 31 10:56 asr_datamodule.py
-rwxrwxrwx 1 anandh anandh  79K Oct 31 10:56 beam_search.py
-rwxrwxrwx 1 anandh anandh  33K Oct 31 10:56 decode.py
-rwxrwxrwx 1 anandh anandh  35K Oct 31 10:56 decode_cuts.py
-rwxrwxrwx 1 anandh anandh 1.7K Oct 31 10:56 encoder_interface.py
drwxrwxrwx 9 anandh anandh 6.0K Oct 31 11:03 exp_1
drwxrwxrwx 4 anandh anandh 6.0K Oct 31 10:56 exp_new
drwxrwxrwx 4 anandh anandh 6.0K Oct 31 10:56 exp_streaming
-rwxrwxrwx 1 anandh anandh  17K Oct 31 10:56 export-onnx.py
-rwxrwxrwx 1 anandh anandh  11K Oct 31 10:56 export.py
-rwxrwxrwx 1 anandh anandh 7.4K Oct 31 10:56 jit_pretrained.py
-rwxrwxrwx 1 anandh anandh 2.1K Oct 31 10:56 joiner.py
-rwxrwxrwx 1 anandh anandh 6.6K Oct 31 10:56 model.py
drwxrwxrwx 2 anandh anandh 6.0K Oct 31 10:56 new
-rwxrwxrwx 1 anandh anandh 7.2K Oct 31 10:56 onnx_check.py
-rwxrwxrwx 1 anandh anandh  13K Oct 31 10:56 onnx_pretrained.py
-rwxrwxrwx 1 anandh anandh  42K Oct 31 10:56 optim.py
-rwxrwxrwx 1 anandh anandh  44K Oct 31 10:56 scaling.py
-rwxrwxrwx 1 anandh anandh 2.2K Oct 31 10:56 test_model.py
-rwxrwxrwx 1 anandh anandh 9.4K Oct 31 10:56 test_onnx.py
-rwxrwxrwx 1 anandh anandh  40K Oct 31 10:56 train-orig.py
-rwxrwxrwx 1 anandh anandh  41K Nov  4 11:48 train.py

**Comment by csukuangfj** [comment]
Looks like you created the files by yourself.

Please make sure you have copied all the files you need.

You can check the directory from which you have copied the files.
(You have missed to copy the file decoder.py)

**Comment by SSwethaSel0609** [comment]
yes thank you solved
