### ISSUE TITLE
Wav2Vec2 features for Tedlium recipe

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#1370]
Guys,

Is it possible to run Tedlium recipe with wav2vec2 features instead of fbank features?

Thanks,
AlexG.

**Comment by marcoyang1998** [comment]
Yes. You need to first dump the wav2vec2 features and then re-build your input manifest for training.

**Comment by DongjiGao** [comment]
You can refer to this [script](https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/WSASR/local/compute_ssl_librispeech.py) for making SSL features.

**Comment by AlexandderGorodetski** [comment]
What is size of wav2vec2 feauture vector, is it extracted every 10msec like filter bankd? For filter bank we use 80 bins. In what places in the train file should I replace this value "80" with number of features from wav2vec2.

**Comment by DongjiGao** [comment]
> What is size of wav2vec2 feauture vector, is it extracted every 10msec like filter bankd? For filter bank we use 80 bins. In what places in the train file should I replace this value "80" with number of features from wav2vec2.

The feature dim extract from the default wav2vec2-base model is 768 with a stride of 20 ms. 
You would need to change the corresponding value of feature_dim in [train.py](https://github.com/k2-fsa/icefall/blob/231bbcd2b638826a94cf019fa31ae8683d3552ee/egs/librispeech/WSASR/conformer_ctc2/train.py#L388).

**Comment by AlexandderGorodetski** [comment]
And what about stride? Should be updated somewhere too?

**Comment by DongjiGao** [comment]
> And what about stride? Should be updated somewhere too?

You can set subsampling_factor=2

**Comment by desh2608** [comment]
@DongjiGao I noticed that you use `compute_and_store_features` in that script. I think you can also use `compute_and_store_features_batch` for GPU-based extraction. It might make the feature extraction step much faster. Note that SSL features support `extract_batch()`: https://github.com/lhotse-speech/lhotse/blob/8a4b3b53ed337ecc5def6dcbc0473e0f57f1ecce/lhotse/features/ssl.py#L91
