### ISSUE TITLE
Increasing of zipformer number of parameters

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#1371]
Hello guys,

Currently zipformer in Tedlium recipe used about 65M parameter.

How would you recommend to increase number of parameters in order to work with, let's say 300M, 500M parameters.

Is there some article that describes performance of K2 as function of number of parameters?

Thanks,
AlexG.

**Comment by yaozengwei** [comment]
We have a large version of Zipformer on other recipes with about 150M parameters (e.g., on LibriSpeech, see https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/RESULTS.md#large-scaled-model-number-of-model-parameters-148439574-ie-1484-m). Maybe you could try this first.
