### ISSUE TITLE
Augmentation types in K2

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#1377]
Hello guys, 

I have a question about tedlium recipe. I wanted to discuss please augmentation types. I see that you have speed augmentation. I addition you have additive noise augmentation. Do you have reverberation augmentation?

Thanks,
AlexG.

**Comment by JinZr** [comment]
Dear AlexG

Yes, actually we already have a recipe with rir augmentation in icefall, you can either have a look at https://github.com/k2-fsa/icefall/blob/master/egs/libricss/SURT/prepare.sh to see how to use open-source provided RIR dataset for augmentation, or use the lhotse off-the-shelf  rir augmentation https://github.com/lhotse-speech/lhotse/blob/master/lhotse/augmentation/rir.py.

Best
Jin
