### ISSUE TITLE
Installation on CPU

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#1378]
Hello guys,

I would like to run inference on CPU machine.

Could you please send me guidelines how can I run inference on CPU machine.

In addition, what installations do I need on CPU machine?

**Comment by AlexandderGorodetski** [comment]
Please not that for training I used following installations. So I guess that for CPU I need same versions.

pip install torch==1.13.0+cu116 torchaudio==0.13.0+cu116 -f https://download.pytorch.org/whl/torch_stable.html
pip install k2==1.24.3.dev20230725+cuda11.6.torch1.13.0 -f https://k2-fsa.github.io/k2/cuda.html
pip install lhotse
pip install sentencepiece
pip install tensorboard
pip install six
pip install kaldifst
pip install kaldilm
pip install kaldialign
pip install kaldifeat==1.25.1.dev20231022+cuda11.6.torch1.13.0 -f https://csukuangfj.github.io/kaldifeat/cuda.html

**Comment by csukuangfj** [comment]
Please follow our tutorial at
https://k2-fsa.github.io/icefall/for-dummies/index.html

The `Icefall for dummies tutorial` is for absolute beginners. It guides you step-by-step to setup an environment for CPU.

**Comment by AlexandderGorodetski** [comment]
@csukuangfj Thank you so much for you answer. So based on your tutorial I changed my GPU installation so that it will be suitable for CPU version. I hope that following commands are correct (in your tutorial for dummies you are talking about torc 2.0, but for training I used another version). In any case I used following commands on CPU machine

pip install torch==1.13.0+cpu torchaudio==0.13.0 -f https://download.pytorch.org/whl/torch_stable.html
pip install k2==1.24.3.dev20230725+cpu.torch1.13.0 -f https://k2-fsa.github.io/k2/cpu.html
pip install lhotse
pip install sentencepiece
pip install tensorboard
pip install six
pip install kaldifst
pip install kaldilm
pip install kaldialign
pip install kaldifeat==1.25.1.dev20231022+cpu.torch1.13.0 -f https://csukuangfj.github.io/kaldifeat/cpu.html

But during the inference I got follwoing error

OSError: libtorch_hip.so: cannot open shared object file: No such file or directory

Any help is more than appreciated

**Comment by csukuangfj** [comment]
Could you please post the installation logs related to `torch` and `torchaudio`?

Also, I suggest that you create a new virtual environment for the installation for CPU 

---

You installation commands seem to be correct.

**Comment by AlexandderGorodetski** [comment]
Following is full error report.

Traceback (most recent call last):
  File "k2_scripts/transcribe_utts.py", line 10, in <module>
    from lhotse import Fbank, FbankConfig
  File "/opt/conda/lib/python3.8/site-packages/lhotse/__init__.py", line 29, in <module>
    from .workflows import *
  File "/opt/conda/lib/python3.8/site-packages/lhotse/workflows/__init__.py", line 2, in <module>
    from .forced_alignment import align_with_torchaudio
  File "/opt/conda/lib/python3.8/site-packages/lhotse/workflows/forced_alignment.py", line 12, in <module>
    import torchaudio
  File "/opt/conda/lib/python3.8/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/opt/conda/lib/python3.8/site-packages/torchaudio/_extension.py", line 135, in <module>
    _init_extension()
  File "/opt/conda/lib/python3.8/site-packages/torchaudio/_extension.py", line 105, in _init_extension
    _load_lib("libtorchaudio")
  File "/opt/conda/lib/python3.8/site-packages/torchaudio/_extension.py", line 52, in _load_lib
    torch.ops.load_library(path)
  File "/opt/conda/lib/python3.8/site-packages/torch/_ops.py", line 573, in load_library
    ctypes.CDLL(path)
  File "/opt/conda/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtorch_hip.so: cannot open shared object file: No such file or directory

Is that enough. I started from brand new linux. So I do not think that I need new env.

**Comment by csukuangfj** [comment]
Please change
```
pip install torch==1.13.0+cpu torchaudio==0.13.0 -f https://download.pytorch.org/whl/torch_stable.html
```
to
```
pip install torch==1.13.0+cpu torchaudio==0.13.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
```

You missed `+cpu` for `torchaudio==0.13.0`

It should be
```
torchaudio==0.13.0+cpu
```
not `torchaudio==0.13.0`.

---

We have described that in detail in the documentation. Please follow our doc carefully.

![Screenshot 2023-11-08 at 19 53 11](https://github.com/k2-fsa/icefall/assets/5284924/7ec7caf7-4d43-478c-baad-063fc36660db)

**Comment by AlexandderGorodetski** [comment]
I am really sorry for missing that. Thank you so much for your help.

**Comment by AlexandderGorodetski** [comment]
I will update you if everything is good with installation on CPU
