### ISSUE TITLE
Contextual biasing support for Fast beam search decoding

### ISSUE THREAD

**Issue by uni-manjunath-ke** [k2-fsa/icefall#1384]
Currently, Contextual biasing is supported for modified beam search. Are you planning to implement contextual biasing on Fast beam search decoding ? Any expected timelines for this. Thanks

**Comment by uni-manjunath-ke** [comment]
Hi @pkufool , @ezerhouni , @csukuangfj , @marcoyang1998 ... Any thoughts on this? Thanks

**Comment by pkufool** [comment]
@uni-manjunath-ke It is hard to implement a Aho-corasick on GPU,  I have a idea to implement this feature using RaggedTensor, but it still in a very early stage, I think it will not be finished in months.

**Comment by uni-manjunath-ke** [comment]
Sure, Thanks @pkufool
