### ISSUE TITLE
zipformer recipe: problem with exporting a model in jit format when causal is true

### ISSUE THREAD

**Issue by danielizham** [k2-fsa/icefall#1387]
I have been having a problem when exporting a jit model following the zipformer recipe. The training and decoding finished successfully in the `causal_convolution` mode. However, I couldn't export the model in that mode.

When the `--causal 0` as shown below, the model can be exported successfully.
```bash
python ./zipformer/export.py \
  --exp-dir zipformer/exp \
  --chunk-size 16 \
  --causal 0 \
  --tokens data/lang_bpe_5000/tokens.txt \
  --epoch 20 \
  --avg 5 \
  --use-averaged-model True \
  --jit 1 \
  --decoder-dim 512 \
  --joiner-dim 512 \
  --num-heads "4,4,4,8,4,4" \
  --num-encoder-layers "2,2,4,5,4,2" \
  --feedforward-dim "512,768,1536,2048,1536,768" \
  --encoder-dim "192,256,512,768,512,256" \
  --encoder-unmasked-dim "192,192,256,320,256,192"
```

However, when I changed the causal to True (`--causal 1`), I got `Missing key(s) in state_dict` and `Unexpected key(s) in state_dict` errors. I have included the output in [log.txt](https://github.com/k2-fsa/icefall/files/13425180/log.txt).

I noticed that the layers in the `Missing key(s)` list contain either `.causal_conv.` or `.chunkwise_conv.`, but I'm not sure how to proceed further and solve it.

These are the details of my environment:
```bash
'IP address': '127.0.1.1',
'hostname': 'gpu1',
'icefall-git-branch': 'main',
'icefall-git-date': 'Thu Nov 9 10:50:13 2023',
'icefall-git-sha1': '4a5d7e6-dirty',
'icefall-path': '/home/daniel/source/icefall',
'k2-build-type': 'Debug',
'k2-git-date': 'Wed Aug 23 21:58:26 2023',
'k2-git-sha1': '2b2ac14b326d61d79d04e53fbd69b1ff6d630411',
'k2-path': '/home/daniel/source/k2/k2/python/k2/__init__.py',
'k2-version': '1.24.3',
'k2-with-cuda': True,
'lhotse-path': '/home/daniel/source/lhotse/lhotse/__init__.py',
'lhotse-version': '1.17.0.dev+git.3dde48dc.clean',
'python-version': '3.1',
'torch-cuda-available': True,
'torch-cuda-version': '11.8',
'torch-version': '2.0.1+cu118'
```

**Comment by yaozengwei** [comment]
When you train this model, did you set `causal` to `True` for `train.py`?

**Comment by danielizham** [comment]
I set `causal_convolution` to be true, but I realised it's called `causal` in zipformer. 😓 That could be the only reason, right?

**Comment by yaozengwei** [comment]
I can't find the option of`causal_convolution`? If you want to train a streaming model, you only need to set `--causal` to be True.

**Comment by danielizham** [comment]
Sorry, I used a pruned_transducer_stateless recipe before, and it's called `causal_convolution` there. My bad. Thank you for your fast replies
