### ISSUE TITLE
Reason behind choosing random chunk size during training

### ISSUE THREAD

**Issue by uni-sagar-raikar** [k2-fsa/icefall#1394]
Hi,

I have observed that, choosing a chunk_size / decode_chunk_len while exporting icefall pt model to onnx is affecting the WER drastically in some cases. I see that, while training, the values are chosen randomly for chunk_size. Whats the reason behind this? I am also seeing some difference in the latency & concurrency in sherpa-onnx based on this choice.

Thanks in advance

**Comment by kakashidan** [comment]
https://arxiv.org/pdf/2012.05481.pdf
This paper maybe helpful to understand dynamic chunk size.
