### ISSUE TITLE
Any plan to support SSL training with zipformer encoder ?

### ISSUE THREAD

**Issue by kobenaxie** [k2-fsa/icefall#1397]
like wav2vec2 Hubert w2vbert ...

**Comment by marcoyang1998** [comment]
I believe @yfyeung has tried Zipformer with HuBERT pre-training. Would you mind sharing some progress @yfyeung ?

**Comment by yfyeung** [comment]
> 

Yeah. Training HuBERT Large on LibriLight 60000h takes lots of time. It still takes some time.

**Comment by zw76859420** [comment]
> > I believe @yfyeung has tried Zipformer with HuBERT pre-training. Would you mind sharing some progress @yfyeung ?
> 
> Yeah. I am doing something like:
> 
> * Support transformer-based SSL in icefall.
> * Support zipformer-based SSL in icefall.
> * Release multilingual zipformer-based SSL in icefall.
> 
> Training HuBERT Large on LibriLight 60000h takes lots of time. It still takes some time.

Do you have some results to share?

**Comment by sangeet2020** [comment]
Hi @yfyeung ,
Wanted to know if the paper is out and you could share the link and the code?

**Comment by JinZr** [comment]
Hi,

Thank you for your interest, the PR has been merged and you can find the code under egs/librilight/SSL or egs/librispeech/SSL.

best
jin

**Comment by JinZr** [comment]
You can find the PR here: 
https://github.com/k2-fsa/icefall/pull/1500￼
k2SSL: a Faster and Better Framework for Self-Supervised Speech Representation Learning by yfyeung · Pull Request #1500 · k2-fsa/icefall
github.com
for more details. 

best
jin

**Comment by sangeet2020** [comment]
thank you :)
