### ISSUE TITLE
Which script correspond to the latest streaming zipformer version?

### ISSUE THREAD

**Issue by OswaldoBornemann** [k2-fsa/icefall#1406]
Which script correspond to the latest streaming zipformer version?

https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/zipformer.py or the 
https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/zipformer2.py ?

**Comment by yaozengwei** [comment]
Yes. The `pruned_transducer_stateless7_*` is the old one.

**Comment by OswaldoBornemann** [comment]
I see. Thank you

**Comment by OswaldoBornemann** [comment]
@yaozengwei I have one more question, do i need to upgrade the version of `k2` as well?

**Comment by yaozengwei** [comment]
I'm not sure. You could have a try. The new Zipformer requires the Swoosh functions implemented in k2 in March. We also fixed some memory issues of pruned-rnnt training in May.

**Comment by OswaldoBornemann** [comment]
I see. So i guess that the most safe way is to upgrade both to the lastest version.

**Comment by csukuangfj** [comment]
> @yaozengwei I have one more question, do i need to upgrade the version of `k2` as well?

I suggest that you always use the latest k2.

Install k2 is.super.simple. Please see
https://k2-fsa.github.io/k2/installation/from_wheels.html
