### ISSUE TITLE
RuntimeError exporting stateless2 model using jit

### ISSUE THREAD

**Issue by Tirthankar-iiitb** [k2-fsa/icefall#1409]
Using Pytorch 2.1 on Ubuntu. No problem on training. No problem in decode. However, when want to export using jit True getting runtime error.
Command used to export on pruned_transducer_stateless2 with jit -
./pruned_transducer_stateless2/export.py \
  --exp-dir ./pruned_transducer_stateless2/exp \
  --tokens ./data/lang_bpe_500/tokens.txt \
  --epoch 29 \
  --avg 1 \
  --jit 1

RuntimeError: 
Python builtin <built-in method random of Random object at 0x23363d0> is currently not supported in Torchscript:
  File "/root/icefall/egs/librispeech/tirtho_ASR/pruned_transducer_stateless2/scaling.py", line 652
    def forward(self, x: Tensor) -> Tensor:
        if random.random() >= self.balance_prob: # tirtho
           ~~~~~~~~~~~~~ <--- HERE
            return x
Please advise.

**Comment by csukuangfj** [comment]
@Tirthankar-iiitb 
Could you try #1410 ?
