### ISSUE TITLE
How to get log_prob of decoded result of fast_beam_search_nbest() and fast_beam_search_nbest_oracle() ?

### ISSUE THREAD

**Issue by kobenaxie** [k2-fsa/icefall#1414]
I try to implement [O-1: Self-training with Oracle and 1-best Hypothesis](https://arxiv.org/pdf/2308.07486.pdf) by [fast_beam_search_nbest()](https://github.com/k2-fsa/icefall/blob/d0da509055468f600808a3d7cd8885649d12b96d/egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py#L239) and [fast_beam_search_oracle](https://github.com/k2-fsa/icefall/blob/d0da509055468f600808a3d7cd8885649d12b96d/egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py#L333), but the `DecodingResult` has no score returned, How to get the log_prob score of each hypothsis ?

**Comment by csukuangfj** [comment]
Please have a look at
https://github.com/k2-fsa/icefall/blob/d0da509055468f600808a3d7cd8885649d12b96d/egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py#L323

`nbest.tot_scores()` contains the score for each path in the nbest.
