### ISSUE TITLE
Tedlium recipe with Language Model

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#1434]
Hello guys,

I used Tedlium recipe to train K2 model on my inhouse data.

Currently I would like to improve performance of my model using external Language Model.

Could you please point me to any recipe that use language model with the most promising results (as a result of using of language model).

Thanks,
AlexG.

**Comment by yaozengwei** [comment]
The LibriSpeech zipformer recipe supports using language model for rescoring, including shallow-fusion and LODR. The results are presented in https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/RESULTS.md#non-streaming-1

**Comment by AlexandderGorodetski** [comment]
Hello guys,

I see that you use LSTM model for training LM of word pieces. Don't you plan to use transformer instead of LSTM? I suppose that transformer should work better, especially for long sentences.

Thank you so much,
AlexG.

**Comment by JinZr** [comment]
There are transformer LM support in the icefall toolkit, please check the document for more details.
