### ISSUE TITLE
Small architecture parameters

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#1440]
Hello guys, 

I would like to try Zipformerl-small architecture according to the following article "ZIPFORMER: A FASTER AND BETTER ENCODER FOR AUTOMATIC SPEECH RECOGNITION".

So, I found in the article definition of following params:

  --num-encoder-layers 2,2,2,2,2,2 \
  --feedforward-dim 512,768,768,768,768,768 \
  --encoder-dim 192,256,256,256,256,256 \

But I do not see definition for encoder-unmasked-dim. Could you please let me know which values of encoder-unmasked-dim should I use for zipformer-small.

Thanks,
AlexG.

**Comment by marcoyang1998** [comment]
```bash
export CUDA_VISIBLE_DEVICES="0,1"
./zipformer/train.py \
  --world-size 2 \
  --num-epochs 50 \
  --start-epoch 1 \
  --use-fp16 1 \
  --exp-dir zipformer/exp-small \
  --causal 0 \
  --num-encoder-layers 2,2,2,2,2,2 \
  --feedforward-dim 512,768,768,768,768,768 \
  --encoder-dim 192,256,256,256,256,256 \
  --encoder-unmasked-dim 192,192,192,192,192,192 \
  --base-lr 0.04 \
  --full-libri 1 \
  --max-duration 1500
```

You may find the configurations here: https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/RESULTS.md#small-scaled-model-number-of-model-parameters-23285615-ie-233-m
