### ISSUE TITLE
Minor mistake in LM tutorial

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#1442]
Hello guys,

You have minor error in your tutorial.

In 

https://k2-fsa.github.io/icefall/recipes/RNN-LM/librispeech/lm-training.html#train-nnlm

hidden_dim should be replaced with hidden-dim

Thanks,
AlexG.

**Comment by marcoyang1998** [comment]
Thank you for pointing it out, would you mind making a PR to fix this?
