### ISSUE TITLE
Minor error

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#1446]
In file ~/icefall/icefall/lm_wrapper.py line 162

vocab_size=params.vocab_size

should be replaced with

vocab_size=params.lm_vocab_size

**Comment by marcoyang1998** [comment]
Thanks for pointing it out, would you mind making a PR to fix this?

**Comment by AlexandderGorodetski** [comment]
Could you please guide me how can I create PR ?

I guess that I should to perform following commands

git clone
# changes
git add .
git commit -m "comment"
git pull

Is that correct? After such procedure the Pull Request will be created automatically ?

**Comment by marcoyang1998** [comment]
You could have a look at this tutorial: https://opensource.com/article/19/7/create-pull-request-github

Basically, you need to 
1. create a fork of the project
2. then clone the forked version; 
3. then create a new branch in you local codebase and commit the changes. 
4. Push the changes to github
5. Create the pull request (you will be able to see this option on your github repo once you pushed the changes)

**Comment by JinZr** [comment]
closed as this PR https://github.com/k2-fsa/icefall/pull/1495 should fix the issue
