### ISSUE TITLE
Warning during onnx creation

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#1451]
Hello guys,

I got following warnings during onnx creation. Could you please let me know if I can ignore these warnings. Thanks a lot.

2024-01-07 14:42:24,532 INFO [export_originai.py:537] Exporting to onnx format
/workspace/inputs/alexg/asr/src/models/k2/icefall/egs/tedlium3/asr_k2_train/zipformer/scaling.py:1656: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if num_channels <= x.shape[-1]:
/workspace/inputs/alexg/asr/src/models/k2/icefall/egs/tedlium3/asr_k2_train/zipformer/zipformer.py:1425: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if self.pe.size(0) >= T * 2 - 1:
/workspace/inputs/alexg/asr/src/models/k2/icefall/egs/tedlium3/asr_k2_train/zipformer/zipformer.py:1612: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert p.shape[-1] == num_heads * pos_head_dim
/workspace/inputs/alexg/asr/src/models/k2/icefall/egs/tedlium3/asr_k2_train/zipformer/zipformer.py:1692: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert attn_scores.shape == (num_heads, batch_size, seq_len, seq_len)
/workspace/inputs/alexg/asr/src/models/k2/icefall/egs/tedlium3/asr_k2_train/zipformer/zipformer.py:2120: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert attn_weights.shape == (num_heads, batch_size, seq_len, seq_len)
/workspace/inputs/alexg/asr/src/models/k2/icefall/egs/tedlium3/asr_k2_train/zipformer/zipformer.py:1910: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert attn_weights.shape == (num_heads, batch_size, seq_len, seq_len)
/workspace/inputs/alexg/asr/src/models/k2/icefall/egs/tedlium3/asr_k2_train/zipformer/scaling.py:472: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert x.shape[self.channel_dim] == self.num_channels
/workspace/inputs/alexg/asr/src/models/k2/icefall/egs/tedlium3/asr_k2_train/zipformer/zipformer.py:1338: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert src.shape[0] == d_seq_len * ds
2024-01-07 14:43:00,431 INFO [export_originai.py:282] Saved to zipformer/exp/encoder.onnx
/workspace/inputs/alexg/asr/src/models/k2/icefall/egs/tedlium3/asr_k2_train/zipformer/decoder.py:124: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert embedding_out.size(-1) == self.context_size
/opt/conda/lib/python3.8/site-packages/torch/onnx/_internal/jit_utils.py:258: UserWarning: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (Triggered internally at ../torch/csrc/jit/passes/onnx/shape_type_inference.cpp:1884.)
  _C._jit_pass_onnx_node_shape_type_inference(node, params_dict, opset_version)
/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py:687: UserWarning: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (Triggered internally at ../torch/csrc/jit/passes/onnx/shape_type_inference.cpp:1884.)
  _C._jit_pass_onnx_graph_shape_type_inference(
/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py:1178: UserWarning: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (Triggered internally at ../torch/csrc/jit/passes/onnx/shape_type_inference.cpp:1884.)
  _C._jit_pass_onnx_graph_shape_type_inference(
2024-01-07 14:43:00,470 INFO [export_originai.py:327] Saved to zipformer/exp/decoder.onnx
/workspace/inputs/alexg/asr/src/models/k2/icefall/egs/tedlium3/asr_k2_train/zipformer/joiner.py:60: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if project_input:

**Comment by csukuangfj** [comment]
Does the exported model work fine? If yes, you can safely ignore the warnings.
