### ISSUE TITLE
error on pip install kaldifeat==1.25.0...

### ISSUE THREAD

**Issue by flutter-painter** [k2-fsa/icefall#1459]
Hi,
Amazing project ! Really want to start using it for asr training.
Yet when I follow step by step the dummies' guide : https://k2-fsa.github.io/icefall/for-dummies/model-export.html
I encounter an error when running : 

`pip install kaldifeat==1.25.0.dev20230726+cpu.torch2.0.0 -f https://csukuangfj.github.io/kaldifeat/cpu.html
`
=> ERROR: Could not find a version that satisfies the requirement kaldifeat==1.25.0.dev20230726+cpu.torch2.0.0

I then ran :
`pip install kaldifeat==1.24 -f https://csukuangfj.github.io/kaldifeat/cpu.html
`
=>   ERROR: Failed building wheel for kaldifeat
And found in the log :
=> Protocol "https" not supported or disabled in libcurl

I suppose I need to run :
`sudo apt-get install curl
sudo apt install libssl-dev
`

But still get the error. I am missing something obvious ?

Also  the url below is not found for :
`wget https://huggingface.co/csukuangfj/kaldifeat/resolve/main/ubuntu-cpu/kaldifeat-1.25.0.dev20230726+cpu.torch2.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

**Comment by csukuangfj** [comment]
please visit that cpu.html page and choose the latest one.
