### ISSUE TITLE
Version conflicts for k2 & torchaudio & torch

### ISSUE THREAD

**Issue by EmreOzkose** [k2-fsa/icefall#146]
Hi,

When I want to try rnn-t, I have to upgrade torchaudio to at least 0.10.0 for rnn-t loss. However [k2 requires torch 1.8.1](https://k2-fsa.github.io/k2/installation/index.html). When I upgrade torch to 1.10.0, and torchaudio to 0.10.0, I got this error.

```
>>> import torch
>>> import torchaudio
>>> import k2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/miniconda3/lib/python3.8/site-packages/k2/__init__.py", line 2, in <module>
    from _k2 import DeterminizeWeightPushingType
ImportError: /path/to/miniconda3/lib/python3.8/site-packages/libk2context.so: undefined symbol: _ZNK2at6Tensor7is_cudaEv
```

Can you share versions of packages in the environment?

Note: I also checked `conda search` and couldn't find corresponding k2 vesion for torch1.10.0.
```
...
k2                   1.11.dev20211209 cuda11.1_py3.7_torch1.8.0  k2-fsa              
k2                   1.11.dev20211209 cuda11.1_py3.7_torch1.8.1  k2-fsa              
k2                   1.11.dev20211209 cuda11.1_py3.7_torch1.9.0  k2-fsa              
k2                   1.11.dev20211209 cuda11.1_py3.7_torch1.9.1  k2-fsa              
k2                   1.11.dev20211209 cuda11.1_py3.8_torch1.8.0  k2-fsa              
k2                   1.11.dev20211209 cuda11.1_py3.8_torch1.8.1  k2-fsa              
k2                   1.11.dev20211209 cuda11.1_py3.8_torch1.9.0  k2-fsa              
k2                   1.11.dev20211209 cuda11.1_py3.8_torch1.9.1  k2-fsa              
k2                   1.11.dev20211209 cuda11.1_py3.9_torch1.8.0  k2-fsa              
k2                   1.11.dev20211209 cuda11.1_py3.9_torch1.8.1  k2-fsa              
k2                   1.11.dev20211209 cuda11.1_py3.9_torch1.9.0  k2-fsa              
k2                   1.11.dev20211209 cuda11.1_py3.9_torch1.9.1  k2-fsa
```

**Comment by csukuangfj** [comment]
As an alternative, please install k2 from source.

Will upload a version supporting torch 1.10 to conda later today or tomorrow.

**Comment by danpovey** [comment]
Fangjun, my feeling is that eventually we can use our own RNN-T loss that Kangwei is working with; we could integrate that into k2 as it's faster than the torch one (except for very small inputs).  That will give more flexibility regarding torch versions.  But of course it's good to have the standard one there for now so we can verify they work the same.
@pkufool let's try to have our own RNN-T loss setup ready quite soon, e.g. the next few days.  I think in order to avoid too many things to compile, it might be easiest to just add the code to k2 rather than using the separate repository.

**Comment by pkufool** [comment]
Ok, I will try to integrate our RNN-T loss to k2 in the following days.

**Comment by EmreOzkose** [comment]
When I tried to install k2 from source, It works. Thank you.

**Comment by csukuangfj** [comment]
Please also have a look at https://github.com/k2-fsa/icefall/pull/162

It does not need torchaudio 0.10.0

**Comment by EmreOzkose** [comment]
Thank you.
