### ISSUE TITLE
British English pronunciations dataset: https://www.youtube.com/@EnglishwithLucy

### ISSUE THREAD

**Issue by Pantyhose-X** [k2-fsa/icefall#1479]
British accent is too different from real people.
Maybe train with a standard British accent.. https://www.youtube.com/@EnglishwithLucy

**Comment by JinZr** [comment]
Hi, thank you for your interest!

It would be better if you could give us some suggestions on some
open-sourced datasets that we can possibly use. otherwise, it will be
difficult for us to collect the data required.

Best Regards
Jin


Pantyhose-X ***@***.***>于2024年1月29日 周一22:19写道：
