### ISSUE TITLE
Could you please provide a pretrained.py for whisper?

### ISSUE THREAD

**Issue by 20246688** [k2-fsa/icefall#1480]

**Comment by JinZr** [comment]
for which recipe


20246688 ***@***.***>于2024年1月30日 周二14:25写道：

**Comment by csukuangfj** [comment]
I think he is referring to https://github.com/k2-fsa/icefall/pull/1466
CC @yuekaizhang

**Comment by 20246688** [comment]
icefall/egs/aishell/ASR/whisper
