### ISSUE TITLE
Any pretrained TTS models available ?

### ISSUE THREAD

**Issue by uni-saurabh-vyas** [k2-fsa/icefall#1486]
I would like to test some TTS model which is already available, especially this one (https://arxiv.org/abs/2106.06103)

**Comment by JinZr** [comment]
Hi,

thank you for your interest!

You can find the multi speaker TTS model we pretrained using icefall on
VCTK here

https://huggingface.co/zrjin/icefall-tts-vctk-vits-2023-12-05

Best Regards
Jin

**Comment by uni-saurabh-vyas** [comment]
Thanks!

**Comment by csukuangfj** [comment]
> https://arxiv.org/abs/2106.06103

There are a lot of pre-trained VITS models, though they are in ONNX format.

Please see
https://github.com/k2-fsa/sherpa-onnx/releases/tag/tts-models

You can find the corresponding checkpoints from [piper](https://github.com/rhasspy/piper)

https://huggingface.co/spaces/k2-fsa/text-to-speech
We have a huggingface space that you can test all of the pre-trained models.
