### ISSUE TITLE
Whisper external language model 

### ISSUE THREAD

**Issue by rezame** [k2-fsa/icefall#1489]
Hi dear,
Recently add whisper finetune code https://github.com/k2-fsa/icefall/pull/1466

How can add an external language model to whisper ?

I want to add a finetune (interpolated ) language model (ngram or nn) to improve results, for example on a special domain to improve reconize special in-domain vocabulary.

Best regards

**Comment by marcoyang1998** [comment]
You can use beam search and use an external LM to rescore the n-best candidates.

**Comment by rezame** [comment]
Thanks 
Does whisper decoding suport beam search?

**Comment by JinZr** [comment]
i think @yuekaizhang made some modifications to whisper to support beam search in this recipe, please check

https://github.com/k2-fsa/icefall/tree/master/egs/aishell/ASR/whisper
