### ISSUE TITLE
Change bpe units from transliterated form to utf8 in decoding zipformer model

### ISSUE THREAD

**Issue by uni-bidisha** [k2-fsa/icefall#1492]
Hi, I have an Arabic Zipformer model trained using transliterated text. I want to get utf8 text in decoding. Is there any way to change the bpe.model units to utf8 so that in decoding I retrieve utf8 text.

I converted the units in token.txt to utf8 form, but there is no option pass token.txt in decode.py. Decode.py only uses bpe.model for id to bpe mapping.

**Comment by JinZr** [comment]
hi,

i'm not very familiar with arabic, but i think you can refer to the
sentencepiece document to see if it is possible to modify the  units within
bpe.model.

or another possible solution is that you can modify the code and use
tokens.txt to retrieve your version of tokens from the file directly, you
might want to look into pretrain.py of the librispeech recipe to see how
this is implemented

best
jin
