### ISSUE TITLE
zipformer training for 5000 hours of data

### ISSUE THREAD

**Issue by bsshruthi22** [k2-fsa/icefall#1496]
we are trying to build a k2 zipformer model using around 5000 hours of data.
our system configuration is 
cores- 24
ram- 130gb
gpu - NVIDIA RTX A6000 GPU with 48gb memory.
the feature extraction process is executing in a slow pace,initially we had kept the number of jobs as 15, but we are getting memory issues error as below.we reduced it to 5 but the error is still observed.Finally kept job =1, its working.
**ERROR**:concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
Please suggest what would be the ideal configuration to run a zipformer model with 5000 hours of data?
Any parameter changes to adopt to make it run  in our system?
Thanks in advance

**Comment by csukuangfj** [comment]
What is the format of your data? Is it .wav, .opus, .or wav, or some other format? Also, what is the typical duration of an utterance?

**Comment by JinZr** [comment]
hi,

may i ask how was the feature extraction conducted? i would suggest you to
modify the script for feature extraction for 5000 hours of the training
data based on the gigaspeech feature extraction script, you can find it
here

https://github.com/k2-fsa/icefall/blob/master/egs/gigaspeech/ASR/local/compute_fbank_gigaspeech_splits.py

Best Regards
Jin

**Comment by JinZr** [comment]
i have check the attachment.

the problem is if you are dealing with a much larger amount of data (plus
the speed perturbation), so if you directly handle all of them at the same
time, they might not be able to fit in the memory of your system.

my suggestion is that you can have a look at the gigaspeech script,
compute_fbank_gigaspeech.py, and also the prepare.sh of that recipe as
well. and see how that recipe use lhotse to split the manifest, do the
feature extraction and combine all cut sets obtained.

you can find the link of the script in my earlier reply.

Best Regards
Jin

**Comment by bsshruthi22** [comment]
My data has a mix of sampling rates 8000 and 16000, for which the manifest has been created seperately and merged. when i run https://github.com/k2-fsa/icefall/tree/master/egs/gigaspeech/ASR/local/compute_fbank_gigaspeech_dev_test.py, i get an error,         assert sampling_rate == expected_sr, (
            f"Mismatched sampling rate: extractor expects {expected_sr}, "
            f"got {sampling_rate}"
in lhotse/features/kaldifeat.py file.  how to include sampling rate in   extractor = KaldifeatFbank(KaldifeatFbankConfig(device=device))

**Comment by bsshruthi22** [comment]
I have added cuts.resample(8000) later in the file.there is a class in kaldifeat.py file which is loading 16k as the sample rate by default
.class KaldifeatFrameOptions:
    sampling_rate: int = 16000

**Comment by danpovey** [comment]
I would probably have done cuts.resample(16000) as by default the extractor expects 16k.  you lose info if you downsample to 8, so 16 is better, if mixed.

**Comment by bsshruthi22** [comment]
The model will be tested on telephonic speech data which is in 8k. Hence decided to resample all cuts to 8k.close to 2000 hours of input data is in 8k.manually resampling it to prepare manifest again may take some time.

**Comment by JinZr** [comment]
In this case you can either up sample the testset to 16k or downsample all
training data and testset to 8k, up to you.

for the error you mentioned earlier, you will need to explicitly set the
sample rate parameter of KaldiFeatFbankConfig to 8000 as it uses 16000 as
default.

hope this helps.

Best Regards

Jin

**Comment by bsshruthi22** [comment]
I have created seperate manifests for 16k and 8k and merged them into one. I will resample with cuts to 8k.
I was not sure how to add the sample rate in KaldiFeatFbankConfig, as it internally takes the default setting from frame opts. Can you please give an example as to how to add sampling rate in KaldiFeatFbankConfig.

**Comment by JinZr** [comment]
check the compute_fbank_eval2000_nb.py line 104 in
https://github.com/k2-fsa/icefall/pull/1391/
<https://github.com/k2-fsa/icefall/pull/1391/files>

this is not identical to what you need to do but should be very similar.

Best Regards
Jin

**Comment by bsshruthi22** [comment]
for fbankconfig it works fine.but for KaldiFeatFbankConfig it says no attribute for sampling rate

**Comment by bsshruthi22** [comment]
@JinZr During  this stage --log "Stage 7: Combine features for train (may take 3 hours)" ,when lhotse combines all the split train jsonl.gz files, getting the error -- line 171: /home/armuser/anaconda3/envs/k2/bin/lhotse: Argument list too long.
Please advice

**Comment by JinZr** [comment]
how many splits do you have

Best Regards
Jin

**Comment by JinZr** [comment]
try not to combine all splits at one time if you have too many splits

Best Regards
Jin

**Comment by bsshruthi22** [comment]
249235 splits. Please let me know how to go about this?

**Comment by csukuangfj** [comment]
> 249235 splits. Please let me know how to go about this?

Please see https://github.com/k2-fsa/icefall/blob/master/egs%2Flibrispeech%2FASR%2Fpruned_transducer_stateless3%2Fgigaspeech.py#L62

You can use lhotse.combine()

**Comment by bsshruthi22** [comment]
I have tried to implement the above link sent, in my shell script,  
if [ $stage -le 7 ] && [ $stop_stage -ge 7 ]; then
  log "Stage 7: Combine features for train (may take 3 hours)"
 python3 ./local/combine_train_manifests.py
fi
[combine_train_manifests.zip](https://github.com/k2-fsa/icefall/files/14306155/combine_train_manifests.zip)

i have attached combine_train_manifests.py  file (according to the link).
cuts_train folder is not generated. Please advice.

**Comment by csukuangfj** [comment]
> I have tried to implement the above link sent, in my shell script,  
> if [ $stage -le 7 ] && [ $stop_stage -ge 7 ]; then
>   log "Stage 7: Combine features for train (may take 3 hours)"
>  python3 ./local/combine_train_manifests.py
> fi
> [combine_train_manifests.zip](https://github.com/k2-fsa/icefall/files/14306155/combine_train_manifests.zip)
> 
> i have attached combine_train_manifests.py  file (according to the link).
> cuts_train folder is not generated. Please advice.
> 
> 

The link I posted is to show how to combine the splits on the fly in your asr datamodule.

There is no need to combine them in your prepare.sh.

You don't need a single file containing all the splits.

**Comment by bsshruthi22** [comment]
@csukuangfj  so i have to add  this stage code in train.py script,so during training it happens on the fly?

**Comment by csukuangfj** [comment]
Features are precomputed in prepare.sh.

Splits are combined on the fly.
