### ISSUE TITLE
support for large scale data training(millions or even tens of millions of hours)?

### ISSUE THREAD

**Issue by brainbpe** [k2-fsa/icefall#1505]
The K2 framework does not support large-scale data (millions or even tens of millions of hours) of ASR training, such as the efficiency of multi-machine and multi-card GPU training is not perfect. Are there any plans to improve this in the future?

**Comment by kobenaxie** [comment]
Actually we can use `lhotse` like [Nemo-lhotse-dataset](https://github.com/NVIDIA/NeMo/pull/7880) to load large scale data.
