### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Transducer

### ISSUE THREAD

**Issue by Werjiang** [k2-fsa/icefall#1523]
Hi,
I encountered a RuntimeError while attempting to decode using a trained model with the provided decode command. The training command completed successfully, but the decoding step failed with an error related to an unexpected key in the state_dict.
**Training Command:**

```bash
./pruned_transducer_stateless7_streaming/train.py --use-fp16 1 \
        --exp-dir /root/autodl-tmp/exp/zipformer_pruned_transducer_staless7_straming_aishell1 \
        --max-duration 120
```

**Decode Command**

```bash
./pruned_transducer_stateless7_streaming/decode.py --epoch 30 --exp-dir /root/autodl-tmp/exp/zipformer_pruned_transducer_staless7_straming_aishell1 --max-duration 120 --decoding-method fast_beam_search
```

**Error Message**
```
Traceback (most recent call last):
  File "./pruned_transducer_stateless7_streaming/decode.py", line 735, in <module>
    main()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "./pruned_transducer_stateless7_streaming/decode.py", line 625, in main
    model.load_state_dict(average_checkpoints(filenames, device=device))
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Transducer:
        Unexpected key(s) in state_dict: "decoder.conv.weight".
```

I have checked the difference in decoder :

decode state_dict:
```
(decoder): Decoder(
    (embedding): Embedding(4336, 512)
    (conv): Identity()
  )
 ```
  train state_dict:
  ```
(decoder): Decoder(
      (embedding): Embedding(4336, 512)
      (conv): Conv1d(512, 512, kernel_size=(2,), stride=(1,), groups=128, bias=False)
  )
```
  I don't know why and how to config the decode parameters.
Thanks!

**Comment by Werjiang** [comment]
the train parameter is:
`parser.add_argument(
        "--context-size",
        type=int,
        default=2,
        help="The context size in the decoder. 1 means bigram; 2 means tri-gram",
    )`
the decode parameter is:
'parser.add_argument(
        "--context-size",
        type=int,
        default=1,
        help="The context size in the decoder. 1 means bigram; 2 means tri-gram",
    )'
 If i change decode context-size default to 2, the problem will be solved.

**Comment by csukuangfj** [comment]
> If i change decode context-size default to 2, the problem will be solved.

Yes, your approach can fix the issue.

It is unfortunate that the train.py and decode.py use a different default value for `--context-size`.

Could you open a PR to fix `decode.py`, i.e., change decode.py to use `2` for `context_size`?

**Comment by Werjiang** [comment]
> > If i change decode context-size default to 2, the problem will be solved.
> 
> Yes, your approach can fix the issue.
> 
> It is unfortunate that the train.py and decode.py use a different default value for `--context-size`.
> 
> Could you open a PR to fix `decode.py`, i.e., change decode.py to use `2` for `context_size`?


Thank you for your feedback and suggestion. I will make an effort to submit a Pull Request (PR) to address this issue.

**Comment by Werjiang** [comment]
The discrepancy between the default values for the context-size parameter in decode.py (default 1) and train.py (default 2) has led to this issue. Addressing this inconsistency by aligning the default value of context-size in decode.py to 2 or 1 and will solve this problem.
