### ISSUE TITLE
Errors while preparing Common Voice dataset

### ISSUE THREAD

**Issue by ChrystianKacki** [k2-fsa/icefall#1531]
I'm trying to build zipformer model with Common Voice dataset.
I'm using script `prepare.sh`, located in [https://github.com/k2-fsa/icefall/tree/master/egs/commonvoice/ASR](https://github.com/k2-fsa/icefall/tree/master/egs/commonvoice/ASR).
I downloaded the data manually, because pointing URL is now forbidden and requires to submit e-mail address or to be logged in.
When I execute the script, at `Stage 9: Prepare BPE based lang` get the following error: 

***RuntimeError: Internal: src/trainer_interface.cc(662) [(trainer_spec_.vocab_size()) == (model_proto->pieces_size())] Vocabulary size too high (500). Please set it to a value <= 6.***

Traceback (most recent call last):
- File "/mnt/c/Users/chrys/IdeaProjects/sherpa-onnx-model/model-common_voice/./local/train_bpe_model.py", line 115, in <module>
    main()
- File "/mnt/c/Users/chrys/IdeaProjects/sherpa-onnx-model/model-common_voice/./local/train_bpe_model.py", line 93, in main
    spm.SentencePieceTrainer.train(
- File "/home/chrychoo/.local/lib/python3.10/site-packages/sentencepiece/__init__.py", line 1047, in Train
    SentencePieceTrainer._Train(arg=arg, **kwargs)
- File "/home/chrychoo/.local/lib/python3.10/site-packages/sentencepiece/__init__.py", line 1040, in _Train
    return SentencePieceTrainer._TrainFromMap(new_kwargs)
- File "/home/chrychoo/.local/lib/python3.10/site-packages/sentencepiece/__init__.py", line 985, in _TrainFromMap
    return _sentencepiece.SentencePieceTrainer__TrainFromMap(args)

From the traceback, I think this occurs because `vocab_sizes` variable at the begining of script `prepare.sh` is set to `500`, and then it is passed to `train_bpe_model.py` script. From here, the code in the method `SentencePieceTrainer.train()` of `sentencepiece` library throws this error.
How to deal with this ? Can I simply change the `vocab_sizes` variable value to `6` in `prepare.sh` script ?

**Comment by JinZr** [comment]
Looks like there’s an issue with the text you use to train the bpe model, could you show us whats the text looked like?

**Comment by ChrystianKacki** [comment]
@JinZr Do you mean the text in file `$lang_dir/transcript_words.txt` ?

> Looks like there’s an issue with the text you use to train the bpe model, could you show us whats the text looked like?

**Comment by JinZr** [comment]
Yes

**Comment by ChrystianKacki** [comment]
@JinZr Please see the attached file: [transcript_words.txt](https://github.com/k2-fsa/icefall/files/14510019/transcript_words.txt).
Should the text file contain something or can be empty ? 
Now it contains only one word "pl".
I have to say, that I've changed the Common Voice dataset in script `prepare.sh` from French to Polish.
I modified variables at the beginning of the script to:
```
release=cv-corpus-16.1-2023-12-06
lang=pl
```

**Comment by JinZr** [comment]
then there must be something wrong with the data processing part, this file is supposed to contain all transcripts of the dataset

**Comment by ChrystianKacki** [comment]
Yes you are right. I've found a solution.

It could be helpful for those who want to adapt the Common Voice model receipt to different languages than English and French.

In `prepare.sh` at `Stage 3: Preprocess CommonVoice manifest` there is script `local/preprocess_commonvoice.py` executed.
In method `normalize_text()` of this script the following code should be added, according to used language:
```
if language == "pl":
return re.sub(r"[^a-ząćęłńóśźżA-ZĄĆĘŁŃÓŚŹŻ' ]", "", utt).upper()
```

**Comment by JinZr** [comment]
Thank you so much!

this would be very useful for the recipe, let me look into it tomorrow!

**Comment by ChrystianKacki** [comment]
There are also another 2 errors in stages: `Stage 11: Compile HLG` and `Stage 12: Compile LG`:

1. ***FileNotFoundError: [Errno 2] No such file or directory: 'data/lm/G_3_gram.fst.txt'***
Traceback (most recent call last):
  File "/mnt/c/Users/chrys/IdeaProjects/sherpa-onnx-model/model-common_voice/./local/compile_hlg.py", line 171, in <module>
    main()
  File "/mnt/c/Users/chrys/IdeaProjects/sherpa-onnx-model/model-common_voice/./local/compile_hlg.py", line 161, in main
    HLG = compile_HLG(lang_dir, args.lm)
  File "/mnt/c/Users/chrys/IdeaProjects/sherpa-onnx-model/model-common_voice/./local/compile_hlg.py", line 85, in compile_HLG
    with open(f"data/lm/{lm}.fst.txt") as f:

2. ***FileNotFoundError: [Errno 2] No such file or directory: 'data/lm/G_3_gram.fst.txt***
Traceback (most recent call last):
  File "/mnt/c/Users/chrys/IdeaProjects/sherpa-onnx-model/model-common_voice/./local/compile_lg.py", line 151, in <module>
    main()
  File "/mnt/c/Users/chrys/IdeaProjects/sherpa-onnx-model/model-common_voice/./local/compile_lg.py", line 141, in main
    LG = compile_LG(lang_dir, args.lm)
  File "/mnt/c/Users/chrys/IdeaProjects/sherpa-onnx-model/model-common_voice/./local/compile_lg.py", line 79, in compile_LG
    with open(f"data/lm/{lm}.fst.txt") as f:

To fix these errors you need to modify scripts: `local/compile_hlg.py` and `local/compile_lg.py`. 
In methods `compile_HLG()` and `compile_LG()` you have to replace all strings beginning with `"data/lm/..."` to `{lang_dir}/lm/...`.

**Comment by JinZr** [comment]
hi, do you mind checking this PR https://github.com/k2-fsa/icefall/pull/1532 and see if it fixes the text norm issue?

thanks!

**Comment by ChrystianKacki** [comment]
I've seen the commit [#1532](https://github.com/k2-fsa/icefall/pull/1532), and the code from it works OK in my environment.
So now the script `prepare.sh` goes clearly through stage 9.

There are also another two errors later: in stages 11 and 12 of the script.
Please see the [comment above](https://github.com/k2-fsa/icefall/issues/1531#issuecomment-1981016162), which describes how to fix them.

> hi, do you mind checking this PR #1532 and see if it fixes the text norm issue?
> 
> thanks!

**Comment by JinZr** [comment]
thanks! i’ll merge the #1532 first and fix the other two with a separate
commit.

Best Regards
Jin

**Comment by ChrystianKacki** [comment]
Thanks! Happy to contribute :-)

**Comment by ChrystianKacki** [comment]
I've updated the [comment about the two new errors](https://github.com/k2-fsa/icefall/issues/1531#issuecomment-1981016162) with source code to replace.

**Comment by JinZr** [comment]
thank you!

please check the updated scripts in pr #1534, see if this fixes the
problem.

**Comment by ChrystianKacki** [comment]
I checked both scripts and they work correctly.
So now `prepare.sh` goes through all stages without any errors.

**Comment by JinZr** [comment]
thanks! my colleagues will do the code review tmr and merge the pr.

🎉🎉

Best Regards
Jin
