### ISSUE TITLE
Training recipe for Common Voice throws errors

### ISSUE THREAD

**Issue by ChrystianKacki** [k2-fsa/icefall#1535]
I'm training a streaming model with Common Voice dataset.
The receipt is located in https://github.com/k2-fsa/icefall/tree/master/egs/commonvoice

I'm using script `train.py`, located in `commonvoice/ASR/pruned_transducer_stateless7_streaming`.
I execute it in this way (script arguments are for Polish language Common Voice dataset):
```
./pruned_transducer_stateless7_streaming/train.py \
    --world-size 1 \
    --num-epochs 1 \
    --start-epoch 1 \
    --use-fp16 True \
    --max-duration 550 \
    --enable-musan False \
    --bpe-model data/pl/lang_bpe_500/bpe.model \
    --language pl \
    --cv-manifest-dir data/pl/fbank \
    --exp-dir ./exp
```

The script throws following error:
***ImportError: cannot import name 'SingleCutSampler' from 'lhotse.dataset' (/home/chrychoo/.local/lib/python3.10/site-packages/lhotse/dataset/__init__.py)***
```
Traceback (most recent call last):
  File "/mnt/c/Users/chrys/IdeaProjects/sherpa-onnx-model/model-common_voice/./pruned_transducer_stateless7_streaming/train.py", line 58, in <module>
    from commonvoice_fr import CommonVoiceAsrDataModule
  File "/mnt/c/Users/chrys/IdeaProjects/sherpa-onnx-model/model-common_voice/pruned_transducer_stateless7_streaming/commonvoice_fr.py", line 28, in <module>
    from lhotse.dataset import (  # noqa F401 for PrecomputedFeatures
```

From the traceback I see that error occurs in import section of `train.py`. There is `CommonVoiceAsrDataModule` imported from script `commonvoice_fr.py`.
In the `commonvoice_fr.py` there is import of `SingleCutSampler` from `lhotse.dataset`, which makes the error. There is no such class.
I did some searching and found that `SingleCutSampler` was present in previous versions of `lhotse`. 
Now there is a similar class named `SimpleCutSampler`. Links: [API](https://lhotse.readthedocs.io/en/latest/datasets.html#lhotse.dataset.sampling.SimpleCutSampler), [Source ](https://github.com/lhotse-speech/lhotse/blob/master/lhotse/dataset/sampling/simple.py#L9)
Could the `SimpleCutSampler` class be used instead of `SingleCutSampler`?

Also in script `commonvoice_fr.py`, in `CommonVoiceAsrDataModule`, in method `train_dataloaders()`, at line `train_sampler = SingleCutSampler(...)`, there is another usage of `SingleCutSampler` class which should be corrected.

**Comment by JinZr** [comment]
thanks!

this class has been deprecated by lhotse, the latest commit of #1534 fixes
this issue

best
jin

**Comment by ChrystianKacki** [comment]
great, thanks too!
