### ISSUE TITLE
Official Dockerfile?

### ISSUE THREAD

**Issue by pzelasko** [k2-fsa/icefall#154]
Should we create an official Dockerfile that shows how to prepare the env for Icefall experiments?

**Comment by csukuangfj** [comment]
There is a folder, docker, inside the root directory of icefall repo.

**Comment by pzelasko** [comment]
🤦‍♂️

Sorry, it’s a long day.

**Comment by csukuangfj** [comment]
Please see also
https://hub.docker.com/repository/docker/k2fsa/icefall/tags?page=1&ordering=last_updated

We have pre-built docker images for icefall now.
<img width="962" alt="Screenshot 2023-07-28 at 10 03 21" src="https://github.com/k2-fsa/icefall/assets/5284924/b51a216b-d63d-4b5e-9ca8-c35b5718e29d">
