### ISSUE TITLE
RESULT.md中参数说明

### ISSUE THREAD

**Issue by Hynsn** [k2-fsa/icefall#1542]
![image](https://github.com/k2-fsa/icefall/assets/13035957/f16aa1cb-c996-4b38-98c1-f32c331ae1fd)

--epoch 10 --avg 4, ddp
--epoch 10 --avg 6, deepspeed zero stage1
--epoch 5 --avg 3, deepspeed zero stage1
请问这个参数分别代表什么，有一个比较全的参数说明吗？

**Comment by csukuangfj** [comment]
@yuekaizhang 帮忙看下？

**Comment by JinZr** [comment]
您好，相关参数的含义可以在这个 recipe 的 decode.py 参数 help str，以及 deepspeed 的文档中找到。
