### ISSUE TITLE
Extending existing model with additional words

### ISSUE THREAD

**Issue by ChrystianKacki** [k2-fsa/icefall#1549]
I trained a model using some big datasets.
The quality of recognition is very good, but unfortunately it still not recognizes some words.
I know that these words are not present in transcripts of audio data.
Is there a way to add additonal words manually ?
Can I simply put additional words to `transcript_words.txt` when building model ?
Or better, is it possible to reuse the existing model without rebuilding and use only hotwords ?
Or maybe there are other solutions not mentioned here ?

**Comment by pkufool** [comment]
@ChrystianKacki  You can try hotwords (search context_file or context_score in https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless4/decode.py for the usage).
