### ISSUE TITLE
Extend tokens.txt with new tokens on pretrained model

### ISSUE THREAD

**Issue by gorosei-dev** [k2-fsa/icefall#1552]
Suppose I want to further train the pretrained model on more data, but the new data contains some new tokens that are not covered in the tokens.txt / bpe.model, and I want the new model to be able to recognize these new tokens, how can I achieve this without retraining from scratch?

**Comment by JinZr** [comment]
You can reuse all parameters of your pre-trained model except for the output layer part, also remember to modify the lang_dir you are using for the later fine-tuning
