### ISSUE TITLE
zipformer-adapter streaming_forward without adapters.

### ISSUE THREAD

**Issue by kobenaxie** [k2-fsa/icefall#1553]
All adapters are only used in `forward()`, but not in `streaming_forward`, please fix it.
https://github.com/k2-fsa/icefall/blob/2dfd5dbf8be72fce434445268e415bcdfa4b3028/egs/librispeech/ASR/zipformer_adapter/zipformer.py#L933

**Comment by marcoyang1998** [comment]
Thanks for pointing it out. I will try to add the support for `streaming_forward` this week.

**Comment by kobenaxie** [comment]
Hi @marcoyang1998 , another question, when finetuning `adapter` or `lora`, is there any difference between `optimizer with whole model parameters` and `optimizer with only adapter/lora module paramters` ?

**Comment by marcoyang1998** [comment]
They should be equivalent as only the parameters in `lora` or `adapter` will have gradients, but the latter could be more efficient (not tested though) as it won't traverse all model parameters.

**Comment by marcoyang1998** [comment]
Fixed in #1560
