### ISSUE TITLE
export a non-stream onnx model from a streaming pytorch model

### ISSUE THREAD

**Issue by 1215thebqtic** [k2-fsa/icefall#1576]
Hi,

I'm trying to export a non-stream onnx model from a streaming pytorch zipformer2 model. Training a non-stream zipformer2 model from scratch takes long time, so I decide to use   "--chunk-size -1 --left-context-frames -1" as a non-stream model.

The streaming model was trained using causal=1. 

The script I used to export the non-stream onnx model from a streaming pytorch model:
```
./zipformer/export-onnx.py \
  --tokens $tokenfile \
  --use-averaged-model 0 \
  --epoch 99 \
  --avg 1 \
  --exp-dir zipformer/exp_L_causal_context_2 \
  --num-encoder-layers "2,2,3,4,3,2" \
  --downsampling-factor "1,2,4,8,4,2" \
  --feedforward-dim "512,768,1024,1536,1024,768" \
  --num-heads "4,4,4,8,4,4" \
  --encoder-dim "192,256,384,512,384,256" \
  --query-head-dim 32 \
  --value-head-dim 12 \
  --pos-head-dim 4 \
  --pos-dim 48 \
  --encoder-unmasked-dim "192,192,256,256,256,192" \
  --cnn-module-kernel "31,31,15,15,15,31" \
  --decoder-dim 512 \
  --joiner-dim 512 \
  --causal True \
  --chunk-size -1 \
  --left-context-frames -1
```

When I use the following code to decode the onnx model: 
```
./zipformer/onnx_pretrained.py \
  --encoder-model-filename $repo/encoder-epoch-99-avg-1.onnx \
  --decoder-model-filename $repo/decoder-epoch-99-avg-1.onnx \
  --joiner-model-filename $repo/joiner-epoch-99-avg-1.onnx \
  --tokens $tokenfile \
  icefall-asr-zipformer-streaming-wenetspeech-20230615/test_wavs/DEV_T0000000001.wav
```

An error occured:
![broadcasting_error](https://github.com/k2-fsa/icefall/assets/11812181/35281c26-7db7-4c76-80dc-b2558e11e0d3)

the error node in netron:
![onnx_node](https://github.com/k2-fsa/icefall/assets/11812181/895b6969-4665-4539-8f98-d9b199c33f35)

According to the netron and zipformer code, I think it's because of the broadcasting in https://github.com/k2-fsa/icefall/blob/6cbddaa8e32ec5bc5c2fcc60a6d2409c7f5c7b11/egs/librispeech/ASR/zipformer/scaling.py#L671
x_chunk's shape is (batch_size, num_channels, chunk_size), chunk_scale's shape is (num_channels, chunk_size). 
I noticed that the streaming_forward also has the same code(https://github.com/k2-fsa/icefall/blob/6cbddaa8e32ec5bc5c2fcc60a6d2409c7f5c7b11/egs/librispeech/ASR/zipformer/scaling.py#L730), but there aren't any errors when exporting the streaming onnx model. 

I deleted this line of code, and waves can be decoded successfully, the wers on my test dataset differ a little bit: 5.89 (pytorch) versus 5.61 (onnx) (pytorch decoding script: ./zipformer/pretrained.py; onnx decoding script: ./zipformer/onnx_pretrained.py)

And my questions are:
1. Why does the broadcasting in non-stream mode lead to onnx errors, while no errors in streaming onnx model ?
2. How do I change this line of code that I can avoid this error, and make the wer is same as the pytorch one?

Thanks!

**Comment by JinZr** [comment]
hi,

im not quite familiar with the onnx export scripts, but i believe it’s not designed to just directly export a streaming model to a non-streaming one, perhaps the conversion ruins some of the attention masks, anyway if you need a non-streaming model, you should train a non-streaming model at the first place.

best
jin

**Comment by 1215thebqtic** [comment]
hi jin, thanks for your reply! More than 10k hours are used to train the model, training will take about 20days due to limited gpus. As for the streaming model, the non-stream decoding options (chunk-size=-1, --left-context-frames=-1) shows relative 20%~30% better wer than the streaming decoding options (chunk-size=32, --left-context-frames=128), so I decide to export the non-streaming model.

**Comment by MicKot** [comment]
setting `chunk-size=-1` and `left-context-frames=-1` does not mean 'non-streaming', it just means the model gets full context but the model is still 'streaming', i.e. the convolutions are still causal.  By exporting the model by nonstreaming script you get rid of the ability to use the cache, which is the whole point of training streaming model. From my testing setting `chunk-size=512` and `left-context-frames=512` gives the best WER (which is not suprising given `context is king`) if WER is what you care about while still having the ability to 'stream' (just not in realtime)

**Comment by csukuangfj** [comment]
我在看这个

**Comment by 1215thebqtic** [comment]
> 我在看这个

您好，那个错误我发现是因为这个函数里面有个if else判断语句
https://github.com/k2-fsa/icefall/blob/6cbddaa8e32ec5bc5c2fcc60a6d2409c7f5c7b11/egs/librispeech/ASR/zipformer/scaling.py#L681

导出onnx的时候输入的input是
https://github.com/k2-fsa/icefall/blob/6cbddaa8e32ec5bc5c2fcc60a6d2409c7f5c7b11/egs/librispeech/ASR/zipformer/export-onnx.py#L297
所以走的上面那个if else中if，我在用导出的模型测试的时候语音都是十几秒的语音，所以会报那个维度不匹配的错误。如果把这个dummy input改成x = torch.zeros(1, 1000, 80, dtype=torch.float32)就会走else那个分支，就不会报错可以正常识别了。但是，现在是我不知道怎么把这个if else合并或者拆分让他长短语音都能用

**Comment by csukuangfj** [comment]
Replied in the Next-gen Kaldi WeChat group.

The fix is

```diff
diff --git a/egs/librispeech/ASR/zipformer/scaling_converter.py b/egs/librispeech/ASR/zipformer/scaling_converter.py
index 76622fa1..346db55e 100644
--- a/egs/librispeech/ASR/zipformer/scaling_converter.py
+++ b/egs/librispeech/ASR/zipformer/scaling_converter.py
@@ -36,7 +36,7 @@ from scaling import (
     SwooshROnnx,
     Whiten,
 )
-from zipformer import CompactRelPositionalEncoding
+from zipformer import CompactRelPositionalEncoding, ChunkCausalDepthwiseConv1d


 # Copied from https://pytorch.org/docs/1.9.0/_modules/torch/nn/modules/module.html#Module.get_submodule  # noqa
@@ -93,6 +93,10 @@ def convert_scaled_to_non_scaled(
             # the input changes, so we have to use torch.jit.script()
             # to replace torch.jit.trace()
             d[name] = torch.jit.script(m)
+        elif is_onnx and isinstance(m, ChunkCausalDepthwiseConv1d):
+            # to export a zipformer model that is trained with --causal=1
+            # but to export it with --chunk-size=-1 and --left-chunk-size=-1
+            d[name] = torch.jit.script(m)

     for k, v in d.items():
         if "." in k:
```

**Comment by divyeshrajpura4114** [comment]
I am trying to export streaming zipformer model as non-streaming model and followed the changes suggested 

1. Changing only scaling_converter.py file, I am getting below error

```
  File "/opt/codes/receipe/icefall/models/zipformer/export-onnx.py", line 570, in main
    export_encoder_model_onnx(
  File "/opt/codes/receipe/icefall/models/zipformer/export-onnx.py", line 308, in export_encoder_model_onnx
    encoder_model = torch.jit.trace(encoder_model, (x, x_lens))
  File "/opt/conda/lib/python3.10/site-packages/torch/jit/_trace.py", line 1000, in trace
    traced_func = _trace_impl(
  File "/opt/conda/lib/python3.10/site-packages/torch/jit/_trace.py", line 695, in _trace_impl
    return trace_module(
  File "/opt/conda/lib/python3.10/site-packages/torch/jit/_trace.py", line 1275, in trace_module
    module._c._create_method_from_trace(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1543, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/opt/codes/receipe/icefall/models/zipformer/export-onnx.py", line 223, in forward
    encoder_out, encoder_out_lens = self.encoder(x, x_lens, src_key_padding_mask)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1543, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/opt/codes/receipe/icefall/models/zipformer/zipformer.py", line 338, in forward
    x = module(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1543, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/opt/codes/receipe/icefall/models/zipformer/zipformer.py", line 1262, in forward
    src = self.downsample(src)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1543, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/opt/codes/receipe/icefall/models/zipformer/zipformer.py", line 1351, in forward
    pad == 0
AssertionError: pad should be zero for exporting streaming models. Given 2
```

2. Changing scaling_converter.py file and also dimension to 1000 in export-onnx.py
I am able to export it successfully, but it has skipped some layers and eventually throws an dimension mismatch error in runtime

```
2025-06-23 18:20:00.196222869 [E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running Reshape node. Name:'/encoder/2/downsample/Reshape'
 Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:44 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::Ten
sorShapeVector&, bool) input_shape_size == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{246,1,384}, requested shape:{62,4,1,384}

Traceback (most recent call last):
  File "/opt/codes/receipe/icefall/models/zipformer/onnx_pretrained.py", line 422, in <module>
    main()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/opt/codes/receipe/icefall/models/zipformer/onnx_pretrained.py", line 393, in main
    encoder_out, encoder_out_lens = model.run_encoder(features, feature_lengths)
  File "/opt/codes/receipe/icefall/models/zipformer/onnx_pretrained.py", line 199, in run_encoder
    out = self.encoder.run(
  File "/opt/conda/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'/encoder/2/d
ownsample/Reshape' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:44 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&
, onnxruntime::TensorShapeVector&, bool) input_shape_size == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{246,1,384}, requested shape:{62,4
,1,384}

```

**Comment by csukuangfj** [comment]
Can you post the output of 
```
git diff
```
?

**Comment by divyeshrajpura4114** [comment]
Command to export model
```
python3 zipformer/export-onnx.py --use-averaged-model 1 --epoch 20 --avg 1 --exp-dir /data/models/stt/data/hi_v2.0.0.0/ --tokens /data/models/stt/data/hi_v2.0.0.0/tokens.txt --causal true --chunk-size -1 --left-context-frames -1 --fp16 true --use-transducer true --use-ctc false --use-attention-decoder false --use-cr-ctc false 2>&1 | tee export.log
```

Command to decode audio file
```
python3 zipformer/onnx_pretrained.py --encoder-model /data/models/stt/data/hi_v2.0.0.0/encoder-epoch-20-avg-1.onnx --decoder-model /data/models/stt/data/hi_v2.0.0.0/decoder-epoch-20-avg-1.onnx --joiner-model /data/models/stt/data/hi_v2.0.0.0/joiner-epoch-20-avg-1.onnx --tokens /data/models/stt/data/hi_v2.0.0.0/tokens.txt /data/data/data/audio/kathbath/hi/clean/00000000.wav 2>&1 | tee decode.log
```

[decode.log](https://github.com/user-attachments/files/20866343/decode.log)
[export.log](https://github.com/user-attachments/files/20866342/export.log)

**Comment by divyeshrajpura4114** [comment]
> soxi /data/data/data/audio/kathbath/hi/clean/train_audio/00000000.wav

```

Input File     : '/data/data/data/audio/kathbath/hi/clean/train_audio/00000000.wav'
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Duration       : 00:00:04.99 = 79877 samples ~ 374.423 CDDA sectors
File Size      : 160k
Bit Rate       : 256k
Sample Encoding: 16-bit Signed Integer PCM
```

**Comment by csukuangfj** [comment]
It's strange it does not work for you.

We will try to reproduce your issue using one of our pre-trained non-streaming zipformer cr ctc + transducer model.

**Comment by Alex2025Job** [comment]
Hi any updates on it, I have got the same issue when exporting streaming model with chunk-size = -1 and left-context-size = -1

**Comment by csukuangfj** [comment]
For those who are still experiencing issues, please refer to https://github.com/k2-fsa/icefall/pull/2086.
