### ISSUE TITLE
A question about the data preparation on AMI corpus

### ISSUE THREAD

**Issue by hiranoyu0830** [k2-fsa/icefall#1579]
Hello, thank you for making such a great toolkit.

I am reproducing [pruned_transducer_stateless7](https://github.com/k2-fsa/icefall/tree/c45e9fecfb89bada0233a7b6cd9626fb6633a696/egs/ami/ASR/pruned_transducer_stateless7) on AMI corpus.
When I applied GSS enhancer to training data (prepare.sh: stage 3, local/prepare_ami_gss.sh: stage 4), I encountered an assertion error below.

> Original Traceback (most recent call last):
>   File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 53, in fetch
>     data = self.dataset[possibly_batched_index]
>   File "/opt/conda/lib/python3.10/site-packages/gss/utils/data_utils.py", line 49, in __getitem__
>     self._validate(cuts)
>   File "/opt/conda/lib/python3.10/site-packages/gss/utils/data_utils.py", line 112, in _validate
>     validate(cuts)
>   File "/opt/conda/lib/python3.10/site-packages/lhotse/qa.py", line 39, in validate
>     validator(obj, read_data=read_data)
>   File "/opt/conda/lib/python3.10/site-packages/lhotse/qa.py", line 510, in validate_cut_set
>     validate_cut(c, read_data=read_data)
>   File "/opt/conda/lib/python3.10/site-packages/lhotse/qa.py", line 384, in validate_cut
>     assert is_equal_or_contains(c.recording.channel_ids, c.channel)
> AssertionError

I found that the audio begin with `IS*` `IN*`, and `IB*` have only 4-channel but not 8-channel in Array2 (ex. https://groups.inf.ed.ac.uk/ami//AMICorpusMirror/amicorpus/IS1000a/audio/). 
However, `egs/ami/ASR/local/prepare_ami_gss.sh` stage4 looks to assume that training data has 8-channel audio. I guess the assertion error was caused by this.

I would like to ask you when you implement egs/ami/ASR/pruned_transducer_stateless7, were there 8-channel audio of Array2 in `IS*` `IN*`, and `IB*`?

Thank you.

**Comment by can-cui** [comment]
Hi, may I ask if you solved this problem, I have the same problem.

**Comment by hiranoyu0830** [comment]
Hi, @can-cui 
I fixed this problem by simply excluding all Array2 in `IS*` `IN*,` and `IB*`. But still waiting for answers from contributors.
FYI, the results were almost same as the reported one.

**Comment by hiranoyu0830** [comment]
Hello, @desh2608
It seems you are the one who created [pruned_transducer_stateless7](https://github.com/k2-fsa/icefall/tree/c45e9fecfb89bada0233a7b6cd9626fb6633a696/egs/ami/ASR/pruned_transducer_stateless7) on AMI corpus.
Do you know anything about the issue above?
Thank you.

**Comment by desh2608** [comment]
We don't use Array2 at all, so it shouldn't make a difference. The GSS is only applied using Array1.

**Comment by hiranoyu0830** [comment]
Thank you very much for your reply!

**Comment by can-cui** [comment]
> Hi, @can-cui I fixed this problem by simply excluding all Array2 in `IS*` `IN*,` and `IB*`. But still waiting for answers from contributors. FYI, the results were almost same as the reported one.

Hi, thank you for the solution! Could you please precise how to choose to only use Array1 in the parameters?

**Comment by hiranoyu0830** [comment]
I just deleted Array2.

**Comment by desh2608** [comment]
I believe there's also a "--channels" options in the "gss enhance" command. Please refer to the README on the gss repo.

**Comment by can-cui** [comment]
> I believe there's also a "--channels" options in the "gss enhance" command. Please refer to the README on the gss repo.

I just found the reason for my problem: the IS1003b I downloaded didn't have the full Array due to a problem with the data itself. I manually deleted this folder and re-ran the recipe from stage1 of prepare.sh and stage0 of prepare_ami_gss.sh and it ran without error.

**Comment by sangeet2020** [comment]
Hi @can-cui ,
I am experiencing same issue, and unable to resolve. But I think its due to some incomplete file download, and I can not pinpoint that.
Since it worked for you, can I please request you to send me the output of this 
```
find amicorpus/wav_db/ -type f -exec du -h {} +
```
THis way, i can compare my output with yours, and pinpoint the issue.
thank you
