### ISSUE TITLE
使用sherpa-onnx-streaming-zipformer-ctc-multi-zh-hans-2023-12-13模型进行语音识别，每次重新启动时都有首字不能识别的问题。

### ISSUE THREAD

**Issue by PeiwenWu** [k2-fsa/icefall#1599]
sherpa-onnx/c-api调用sherpa-onnx-streaming-zipformer-ctc-multi-zh-hans-2023-12-13模型进行语音识别，每次重新启动时都会出现第一个字不能识别。

**Comment by JinZr** [comment]
这是 sherpa onnx 项目相关问题，请前往对应 repo 提 issue

Best Regards
Jin
