### ISSUE TITLE
CTC/AED PROBLEMS IN EXPORTING JIT MODULE

### ISSUE THREAD

**Issue by zw76859420** [k2-fsa/icefall#1623]
When we wentto export model(https://github.com/k2-fsa/icefall/issues/1618) which was trained with hybrid CTC/AED methods from https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/zipformer/export.py, the following problem will occured. We don't know how to solve it. Can anyone help me?

2024-05-10 11:34:52,545 INFO [export.py:511] Using torch.jit.script
Traceback (most recent call last):
  File "./zipformer/export.py", line 528, in <module>
    main()
  File "icefall/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "./zipformer/export.py", line 513, in main
    model.save(str(params.exp_dir / filename))
  File "icefall/lib/python3.8/site-packages/torch/jit/_script.py", line 693, in save
    return self._c.save(str(f), **kwargs)
RuntimeError: strides() called on undefined Tensor

Best,
Shylock

**Comment by yaozengwei** [comment]
Could you show your command?

**Comment by zw76859420** [comment]
#!/bin/bash

./zipformer/export.py \
  --exp-dir ./zipformer/exp \
  --tokens data/lang_char/tokens.txt \
  --epoch 10 \
  --avg 1 \
  --causal 0 \
  --jit 1 \
  --use-transducer 1 \
  --use-ctc 1 \
  --use-attention-decoder 1 \
  --num-encoder-layers 2,2,4,5,4,2 \
  --feedforward-dim 512,768,1536,2048,1536,768 \
  --encoder-dim 192,256,512,768,512,256 \
  --encoder-unmasked-dim 192,192,256,320,256,192

**Comment by zw76859420** [comment]
Dear Zengwei, you can try to export your model using the newest codes.
Thanks very much!

**Comment by zw76859420** [comment]
This Problem has been solved, great thanks to Zengwei.
