### ISSUE TITLE
Data cleaning

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#1629]
Hello guys,

Do you please to implement data cleaning process in K2 like it was implemented in Kaldi?

Thanks,
AlexG.

**Comment by JinZr** [comment]
hi,

which data cleaning process and in what way are you referring to?

best regards
jin

**Comment by AlexandderGorodetski** [comment]
Hi,

I meant this code in Kaldi

if [ $stage -le 16 ]; then
  # this does some data-cleaning.  It actually degrades the GMM-level results
  # slightly, but the cleaned data should be useful when we add the neural net and chain
  # systems.  If not we'll remove this stage.
  local/run_cleanup_segmentation.sh
fi

Thanks,
AlexG.

**Comment by AlexandderGorodetski** [comment]
Hi,

I meant this code

if [ $stage -le 16 ]; then
  local/run_cleanup_segmentation.sh
fi

Thanks,
AlexG.

**Comment by JinZr** [comment]
there’s no plan to implement this. 

best regards
jin
