### ISSUE TITLE
How to use my own dataset based on another dataset

### ISSUE THREAD

**Issue by PeaceAndJoyAaron** [k2-fsa/icefall#1637]
I referenced https://icefall.readthedocs.io/en/latest/for-dummies/index.html and successfully constructed my own related dataset file and generated the corresponding epoch logs
I would like to add personal datasets to the one sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20
What should I do next?Is my current process correct?
thanks a lot

**Comment by marcoyang1998** [comment]
Hi,

I'm afraid that I can't understand what you are trying to do. Are you trying to train the model on your own dataset?

**Comment by PeaceAndJoyAaron** [comment]
@marcoyang1998 Thanks Reply！
I want to train my own data based on the previous data set

**Comment by JinZr** [comment]
please refer to the finetune.sh for more details. 

best regards
jin
