### ISSUE TITLE
training very slowly

### ISSUE THREAD

**Issue by tianchaolangzi** [k2-fsa/icefall#1658]
i am training zipformer in egs/audioset/AT, using comand:

`export CUDA_VISIBLE_DEVICES="0,1,2,3"

subset=full
python zipformer/train.py \
    --world-size 4 \
    --num-epochs 50 \
    --num-encoder-layers 2,2,2,2,2,2 \
    --feedforward-dim 512,768,768,768,768,768 \
    --encoder-dim 192,256,256,256,256,256 \
    --encoder-unmasked-dim 192,192,192,192,192,192 \
    --exp-dir zipformer/exp_22M_xiaomi_${subset} \
    --start-epoch 1 \
    --use-fp16 1 \
    --num-events 527 \
    --audioset-subset $subset \
    --max-duration 1200 \
    --enable-musan False \
    --return-cuts False \
    --manifest-dir data_wulan/fbank_xiaomi \
    --master-port 13455 \
    --num-workers 24
`

The first question:
My machine has 128 CPUs and only I am using it myself. So I think this setting is not a problem.
The current situation is that every 50 batches takes 8-9 minutes. But i see that the logs you uploaded only take about 1 minute.
A common situation is that 2-3 GPUs have a utilization rate of 100, but the remaining GPUs have a utilization rate of 0. 
I think it's caused by GPU waiting for data, because when I set num-worker to 2(by default) it takes more time.

The second question:
What is the use of data augmentation using Musan since the training process uses PrecomputedFeatures?

Thank you and wish your reply!

**Comment by marcoyang1998** [comment]
Hi, are you having the same issue if you only use 1 GPU for training?

Regarding the usage of musan, please have a look at the implementation of `CutMix` in `lhotse`. The augmentation is done at the feature level.

**Comment by tianchaolangzi** [comment]
> Hi, are you having the same issue if you only use 1 GPU for training?

No. Training 50 batchs with only one GPU takes 1 minute

**Comment by marcoyang1998** [comment]
This is a bit strange. Are you training on one node? Also, could you please print the time in the dataloader? 24 is too big for --num-workers, is the default setting slow?

**Comment by tianchaolangzi** [comment]
> This is a bit strange. Are you training on one node? Also, could you please print the time in the dataloader? 24 is too big for --num-workers, is the default setting slow?

Yes, All operations run in the same environment on the same machine.

I set num-workers=2  and print the time cost of each batch load data. Some times are between 5-6 seconds, while others are within 0.02 seconds.

Then I set num-workers=24  and print the time cost of each batch load data. All the time are within 0.02 seconds.  

Maybe my disk reading speed is slow because the data is stored on a network mounted disk. 

> The first question: My machine has 128 CPUs and only I am using it myself. So I think this setting is not a problem. The current situation is that every 50 batches takes 8-9 minutes. But i see that the logs you uploaded only take about 1 minute. A common situation is that 2-3 GPUs have a utilization rate of 100, but the remaining GPUs have a utilization rate of 0. I think it's caused by GPU waiting for data, because when I set num-worker to 2(by default) it takes more time.

So why does this problem arise during multi GPU training.

**Comment by marcoyang1998** [comment]
> Maybe my disk reading speed is slow because the data is stored on a network mounted disk.

That could be the reason. Maybe there is a network bandwidth limit, which causes the slow training in multi GPU mode.

Could you please try using a local disk? You could try the `balanced` subset to verify this.

**Comment by pzelasko** [comment]
Another option is to use the lhotse shar format for faster IO, just keep in mind you might need to slightly adjust the dataloader initialization code. See the example here: https://github.com/lhotse-speech/lhotse/blob/master/examples/04-lhotse-shar.ipynb

**Comment by tianchaolangzi** [comment]
> Another option is to use the lhotse shar format for faster IO, just keep in mind you might need to slightly adjust the dataloader initialization code. See the example here: https://github.com/lhotse-speech/lhotse/blob/master/examples/04-lhotse-shar.ipynb
> 
> You can export your existing data using `lhotse shar export --help`

I thought training would only read those lca files that store features. My unbalanced dataset feature saved in 100 lca files. I don't think this is a big number. Will this be the reason that affects the speed of the dataloader? 

Will the dataloader read the original audio file during the training process? I think the number of original audio maybe large.  
According to the setting of max-duration=1200, each batch should have about 120 audio files.

**Comment by JinZr** [comment]
i dont think 100 lca files would be a huge problem on the io end

the dataloader will not read the original audio file if your are not using otf feature extraction.

i would rather suggest you to measure the bandwidth of your file system first, as we dont have much info on the hardware you have been working with.

**Comment by tianchaolangzi** [comment]
> i dont think 100 lca files would be a huge problem on the io end
> 
> the dataloader will not read the original audio file if your are not using otf feature extraction.
> 
> i would rather suggest you to measure the bandwidth of your file system first, as we dont have much info on the hardware you have been working with.

My machine's memory can hold the entire training set. Can I load all batches into memory at once and keep it in memory until the training is completed? This may avoid frequent disk IO

**Comment by JinZr** [comment]
i guess so, you can set a super large buffer size and see if it works

best regards
jin

**Comment by pzelasko** [comment]
LCA files require random access reading which is typically 5-100x slower than sequential IO from tar files (depending on your setup, SSD/HDD/NFS/etc). 

> i guess so, you can set a super large buffer size and see if it works

To make that work, you'd need to call `cuts = cuts.move_to_memory()` to pre-load the features into memory. Otherwise it will only pre-load the manifests.

**Comment by tianchaolangzi** [comment]
> LCA files require random access reading which is typically 5-100x slower than sequential IO from tar files (depending on your setup, SSD/HDD/NFS/etc).

Thank you for your suggestion.

I  have converted the data to shar format. Using command "lhotse shar export -f lilcom -j 40 xx.jsonl.gz shar_dir"
And loading shar with code 
`
cuts_musan = CutSet.from_shar(fields={
    "cuts": glob.glob(f"{self.args.shar_dir}/shar_musan/cuts.*.jsonl.gz"),
    "features": glob.glob(f"{self.args.shar_dir}/shar_musan/features.*.tar")
})
`
But this error was reported during the training process. 

"AssertionError: Mismatched IDs: cut ID is 'fsWmRuLVIaU' but found data with name 'REeHsSo_LbE.llc' fsor field feature"

File "/opt/conda/lib/python3.10/site-packages/lhotse/shar/readers/lazy.py", line 268, in __iter__ 
str(data_path.parent / data_path.stem) == cut.id

I'm not quite sure how to solve this problem. The feature I am currently using is computed from my custom feature extractor.

Is it related to the feature extractor？But I had no problem training with manifest before with the same feature.

**Comment by pzelasko** [comment]
Glob returns files in unsorted order. You can either sort the paths or use in_dir arg instead which will auto sort everything for you.

**Comment by tianchaolangzi** [comment]
> Glob returns files in unsorted order. You can either sort the paths or use in_dir arg instead which will auto sort everything for you.

Thank you, it's very fast now.

**Comment by duhtapioca** [comment]
> To make that work, you'd need to call `cuts = cuts.move_to_memory()` to pre-load the features into memory. Otherwise it will only pre-load the manifests.

I'm facing AttributeError: 'CutSet' object has no attribute 'move_to_memory', how do I move the cutset with calculated feats to memory?

**Comment by pzelasko** [comment]
apparently I didn't add this method to cutset, but you can do
```python
def to_mem(c):
    return c.move_to_memory()
cuts = cuts.map(to_mem)
```

**Comment by yushanyong** [comment]
> > LCA files require random access reading which is typically 5-100x slower than sequential IO from tar files (depending on your setup, SSD/HDD/NFS/etc).
> 
> Thank you for your suggestion.
> 
> I have converted the data to shar format. Using command "lhotse shar export -f lilcom -j 40 xx.jsonl.gz shar_dir" And loading shar with code `cuts_musan = CutSet.from_shar(fields={ "cuts": glob.glob(f"{self.args.shar_dir}/shar_musan/cuts.*.jsonl.gz"), "features": glob.glob(f"{self.args.shar_dir}/shar_musan/features.*.tar") })` But this error was reported during the training process.
> 
> "AssertionError: Mismatched IDs: cut ID is 'fsWmRuLVIaU' but found data with name 'REeHsSo_LbE.llc' fsor field feature"
> 
> File "/opt/conda/lib/python3.10/site-packages/lhotse/shar/readers/lazy.py", line 268, in **iter** str(data_path.parent / data_path.stem) == cut.id
> 
> I'm not quite sure how to solve this problem. The feature I am currently using is computed from my custom feature extractor.
> 
> Is it related to the feature extractor？But I had no problem training with manifest before with the same feature.

I am trying to run `egs/wenetspeech/KWS/zipformer/finetune.py`, and I exported shar in the same way and loaded it using `CutSet.from_shar`. The result was even slower than the original `load_manifest_lazy`. 

50 steps take time：3'40" vs 4'30"
GPU: V100 8*16G
lhotes：1.23.0

Is there something I missed? What could be the reason?

**Comment by yushanyong** [comment]
Thanks Reply.
I indeed did not set it up according to the tutorial, but after I set it up, the following problem occurred：
```
Traceback (most recent call last):
  File "/pathto/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/pathto/icefall/egs/wenetspeech/KWS/zipformer/finetune.py", line 756, in run
    train_dl.sampler.set_epoch(epoch - 1)
AttributeError: '_InfiniteConstantSampler' object has no attribute 'set_epoch'
```

cuts loading method：
```
    shar_cuts = CutSet.from_shar(
        fields={
            "cuts": self.load_shar_file('cuts_wenetspeech_L'),
            "features": self.load_shar_file('features_wenetspeech_L'),
        },
        shuffle_shards=True,
        stateful_shuffle=True,
        seed="randomized",
    ).repeat()
```

other codes, use `DynamicBucketingSampler`：
<img width="898" alt="image" src="https://github.com/user-attachments/assets/ea29baef-7872-4dd2-b178-3498bbe3c765">

Is it a version problem?

**Comment by pzelasko** [comment]
You can remove the set_epoch call. It’ll be automatically incremented inside the iterable dataset.

**Comment by yushanyong** [comment]
I tried it, and it does improve：
50 steps take time：3'40" -> 2'30"

But I think it is still too slow for a model with 3M parameters model and 8*V100. And often one or two GPUs have 0% utilization.

And I found that it is faster if I use 1 GPU，50 steps take time：40"+

**Comment by yushanyong** [comment]
<img width="1028" alt="image" src="https://github.com/user-attachments/assets/12dea7e4-32a1-4550-b79f-f46f82a5733f">

Is the `CutSet.mux` operation the cause of the slowness?

**Comment by pzelasko** [comment]
I don’t think so. It’s good you’re getting good perf on 1GPU, at least we know the issue is related to DDP setup. We’ll probably need a profiler to figure out what’s going wrong in your setup. You can try two approaches 

1) use pip install py-spy and run py-spy record attaching to your process PID. Ideally we want flamegraphs for the main (training loop) process and the data loading subprocess separately. You’ll need to figure out the pids using ps and pstree. 

2) you can obtain a comprehensive profile of your multi GPU training with NVIDIA Nsight systems. 

the workflow you generally want is the following:
- run some warmup (10-20 batches) 
- start the profiler
- run 3-5 batches, you don't really need more and it will keep the profile small
- stop the profiler and script
- explore in nsys

You can programmatically define the profiler scope by inserting:
torch.cuda.profiler.cudart().cudaProfilerStart()
# code to profile goes here
torch.cuda.profiler.cudart().cudaProfilerStop()

Then the command to start the profiling is the following:
nsys profile -w true -t nvtx,cuda,osrt -s cpu --capture-range=cudaProfilerApi --capture-range-end=stop-shutdown --cudabacktrace=true -x true -o /path/to/profile.nsys-rep --force-overwrite true -- python my-script.py <options>
(there's a bunch of options that make it auto-exit after profiling stops)

You can additionally add NVTX annotations which will add Python call stacks in the profile, super useful for interpreting the results, but it also adds a lot of overhead, so you need to verify all conclusions with a profile without NVTX (or manually insert NVTX only in very select places). You can add NVTX like this:
import nvtx
profile = nvtx.Profile()
profile.enable()  # before profiler start
profile.disable()  # after profiler ends

If you want to insert NVTX manually, use torch.cuda.nvtx.range_push and torch.cuda.nvtx.range_pop.

Typically it’s most useful to create a profile with and without NVTX and then compare the two.
