### ISSUE TITLE
Grad scale is too small

### ISSUE THREAD

**Issue by hoangtm-aimesoft** [k2-fsa/icefall#1661]
Hi all. I'm trying to train streaming zipformer on reazonspeech dataset (100h) with reazonspeech recipe and I got this error: 
![image](https://github.com/k2-fsa/icefall/assets/153600138/884950aa-ffe2-47e1-9453-0f736223b8c5)
Here is my training args
![image](https://github.com/k2-fsa/icefall/assets/153600138/9727780f-d0de-4166-8866-23ac3a2f0a92)
Can someone help me ? Thank you very much !

**Comment by csukuangfj** [comment]
@JinZr Could you have a look?

**Comment by JinZr** [comment]
Hi, please update your local cloned repo to the latest master branch and try again.

Thanks!

**Comment by chnk58hoang** [comment]
@JinZr Thank you for your reply. I have pulled the latest master branch but I cannot see any update on the reazonspeech recipe. Can you explain it ?

**Comment by JinZr** [comment]
hi, if so, please try reducing base_lr by 0.005 (i.e. from 0.045 to 0.04)
and see if it works.

could you also provide us with the computational resources you’ve been
working with?

Best Regards
Jin

**Comment by danpovey** [comment]
Next time try pasting more of the error.  That error appears if the model diverges but without seeing more output it can be hard to give more precise help other than "reduce the LR".

**Comment by chnk58hoang** [comment]
@JinZr I'm working with NVIDIA GeForce RTX 3090 with 24GB VRAM

**Comment by yuyun2000** [comment]
Yes, I am also training a streaming model on ReazonSpeech. I trained with 3k hours of data using a single Nvidia 3090 GPU, with a learning rate of 0.025. The training proceeds normally and the convergence is quite good, with each epoch taking approximately 4 hours.

**Comment by sangeet2020** [comment]
Hi @yuyun2000 ,
Is the streaming model trained on ReazonSpeech available publicly for use?
thank you

**Comment by yuyun2000** [comment]
> Hi @yuyun2000 , Is the streaming model trained on ReazonSpeech available publicly for use? thank you

Do you need it if you only have 3,000 hours of data? I don't think the performance is that strong.

**Comment by sangeet2020** [comment]
Yeah. Could be helpful. I am also planning to start a training and would be good to compare it with your model.
