### ISSUE TITLE
NPU Error

### ISSUE THREAD

**Issue by yushanyong** [k2-fsa/icefall#1685]
Conformer模型使用Paraformer的tokenizer，会导致grad_norm NaN，进而NPU会报Inner Error，但使用GPU训练一切正常
<img width="1360" alt="image" src="https://github.com/k2-fsa/icefall/assets/30676802/46a24624-af64-40e5-85f7-bbff4234ce25">

### 复现方式：
- 拉最新代码
- 修改wenet/examples/aishell/s0/run_npu.sh 下面 conf/train_conformer.yaml，将tokenizer改成paraformer
<img width="407" alt="image" src="https://github.com/k2-fsa/icefall/assets/30676802/01a60276-a1d7-4f1f-8335-6beb8e2928a8">

- 直接运行run_npu.sh

**Comment by csukuangfj** [comment]
这个是icefall。是不是弄错了？

**Comment by yushanyong** [comment]
尴尬，弄错了😂
