### ISSUE TITLE
get data manifest for SSL recipe

### ISSUE THREAD

**Issue by sanjuktasr** [k2-fsa/icefall#1697]
What are the different format of data inputs for zipformer/pretrain in SSL recipe? How can we obtain them?

**Comment by yfyeung** [comment]
I release all manifests on hugging face: https://huggingface.co/datasets/yfyeung/librispeech-hubert-base-ls960-iter1-l6-km500

**Comment by Mahmoud-ghareeb** [comment]
@yfyeung 
Everything is working perfectly for a single instance
Could you please help me with ideas on how to modify the training to support a multi-node cluster on Azure?

**Comment by yfyeung** [comment]
> [@yfyeung](https://github.com/yfyeung) Everything is working perfectly for a single instance Could you please help me with ideas on how to modify the training to support a multi-node cluster on Azure?

This commit supports for mult-node training: https://github.com/k2-fsa/icefall/pull/1745/commits/f26dd3ba17d5d87b4618c9c127d0fb892bbe92f7

You can submit a multi-node job (e.g. 4 nodes, 8 gpus per node), and perform:
- ssh node-0
- torchrun --nproc_per_node 8 --nnodes 4 --node_rank 0 --master_port $master_port  zipformer/pretrain.py --use-multi-node 1
- ssh node-1
- torchrun --nproc_per_node 8 --nnodes 4 --node_rank 1 --master_port $master_port  zipformer/pretrain.py --use-multi-node 1
- ssh node-2
- torchrun --nproc_per_node 8 --nnodes 4 --node_rank 2 --master_port $master_port  zipformer/pretrain.py --use-multi-node 1
- ssh node-3
- torchrun --nproc_per_node 8 --nnodes 4 --node_rank 3 --master_port $master_port  zipformer/pretrain.py --use-multi-node 1

**Comment by Mahmoud-ghareeb** [comment]
@yfyeung I will do the same experiment you did, but for a multilingual encoder.
My thought process is:
1. For K-means: Prepare 100 hours for each language and train it on the combined data.
2. For ASR: Prepare 100 hours for each language and train it on the combined data.

Then, after I have a multilingual encoder, I will use it to train full ASR per language when needed.

Note: all languages from the same family tree have a lot of similarities
Another note: One language makes up 80% of the data, while the remaining languages together account for only 20%.

What do you think about this?
Do you have any other recommendations?

Thanks a lot in advance
