### ISSUE TITLE
early context injection

### ISSUE THREAD

**Issue by EmreOzkose** [k2-fsa/icefall#1709]
Hi,

Are you planning to add early context injection approach ([Improving Neural Biasing for Contextual Speech Recognition by Early Context Injection and Text Perturbation](https://arxiv.org/pdf/2407.10303)) to Icefall?

**Comment by JinZr** [comment]
Hi,

Sorry we dont have such plans in sight so far. 

best
jin

**Comment by danpovey** [comment]
Ruizhe, how hard would it be to make a PR at least as a demo?

**Comment by huangruizhe** [comment]
I think it won't be that hard. I can start working on the librispeech recipe on the side.
