### ISSUE TITLE
Recommended recipe for noisy 5K hours noisy training data

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#1711]
Hello guys,

I am working with inhouse 5K hours noisy training data. What is the most recommended recipe for my case? Meantime I am using Zipformer from Tedlium recipe.

Thanks.

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/icefall/tree/master/egs/librispeech/ASR/zipformer

It is our best-performing recipe.
