### ISSUE TITLE
How to specify zipformer model training with different specifications

### ISSUE THREAD

**Issue by TszSimLaw** [k2-fsa/icefall#1718]

**Comment by JinZr** [comment]
which part of the model you would like to have further specifications applied to?

**Comment by TszSimLaw** [comment]
> which part of the model you would like to have further specifications applied to?

zipformer-S

**Comment by marcoyang1998** [comment]
Please have a look at this: https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/RESULTS.md#small-scaled-model-number-of-model-parameters-23285615-ie-233-m
