### ISSUE TITLE
execute prepare.sh  and encountered an error in gigaspeech

### ISSUE THREAD

**Issue by lmee** [k2-fsa/icefall#1728]
The file cuts_XL_raw.jsonl.gz did not exist during the ASR preparation.sh phase 5

<img width="473" alt="微信图片_20240822152254" src="https://github.com/user-attachments/assets/9d3fbe01-2b70-4920-9c64-1706c8700115">

Pls help to fix it ,Thanks
@pkufool

**Comment by marcoyang1998** [comment]
This could be an inconsistency in the naming convention. Could you please add a prefix to the file name, i.e cuts_XL_raw.jsonl.gz -> gigaspeech_cuts_XL_raw.jsonl.gz and try again?

**Comment by lmee** [comment]
yes,after the prefix is added, it works properly.
