### ISSUE TITLE
Assertion error,batch size mismatch in Training zipformer

### ISSUE THREAD

**Issue by bsshruthi22** [k2-fsa/icefall#1733]
Hello,
we are training a zipformer model for about 3400 hours of Tamil 
[batch_log.txt](https://github.com/user-attachments/files/16761055/batch_log.txt)
data. In training stage, I get the  below error,
 forward
    assert x.size(0) == x_lens.size(0) == y.dim0, (x.shape, x_lens.shape, y.dim0)
AssertionError: (torch.Size([192, 311, 80]), torch.Size([193]), 193)

I validated the manifests with script local/validate_manifest.py , it didnt throw any error,
I have attached the file after loading the batch.pt in exp folder,
Please let me know how to proceed with this.

**Comment by csukuangfj** [comment]
I suggest that you use `torch.load()` to load the saved `batch.pt` file and debug it by yourself.

**Comment by bsshruthi22** [comment]
I have done the same.I have attached the output of torch.load() in batch_log.txt. Please suggest some pointers where I can find the issue in the before attached file.

**Comment by csukuangfj** [comment]
Please post the info about
```
print(batch['inputs'].shape)

print(len(batch['supervisions']['text']))
```

assuming that you have run
```
batch = torch.load('batch.pt')
```

**Comment by csukuangfj** [comment]
Please check your data why there are 192 utterances having features while 193 utterances having transcripts.

One utterance does not have features. You need to find out which one.

**Comment by bsshruthi22** [comment]
just wondering why this error doesn't show up when validating cuts manifest?

**Comment by csukuangfj** [comment]
Please check
```
batch['supervisions']['cut']
```
by yourself.

it is a list and you need to check the duration of each cut.


---

> why this error doesn't show up when validating cuts manifest?

The validation script does not check the duration of a cut. Please re-check the validation script if you want to learn more.

**Comment by bsshruthi22** [comment]
The issue is there are duplicates in batch.pt .for eg:
{"id": "AST0084-1000000855-734821", "start": 0, "duration": 3.202, "channel": 0, "supervisions": [{"id": "AST0084-1000000855", "recording_id": "AST0084-1000000855", "start": 0.0, "duration": 3.202, "channel": 0, "text": "i am preclosing my loan", "speaker": "AST0084", "custom": {"origin": "giga"}}], "recording": {"id": "AST0084-1000000855", "sources": [{"type": "file", "channels": [0], "source": "/media/administrator/hdd2/database/In_Housedata/English-Hindi/All_data/eng_hindi_renamed/AST0084/AST0084-1000000855.wav"}], "sampling_rate": 8000, "num_samples": 25616, "duration": 3.202, "channel_ids": [0]}, "type": "MonoCut"}
{"id": "AST0084-1000000855-1769112", "start": 0, "duration": 3.202, "channel": 0, "supervisions": [{"id": "AST0084-1000000855", "recording_id": "AST0084-1000000855", "start": 0.0, "duration": 3.202, "channel": 0, "text": "i am preclosing my loan", "speaker": "AST0084", "custom": {"origin": "giga"}}], "recording": {"id": "AST0084-1000000855", "sources": [{"type": "file", "channels": [0], "source": "/media/administrator/hdd2/database/In_Housedata/English-Hindi/All_data/eng_hindi_renamed/AST0084/AST0084-1000000855.wav"}], "sampling_rate": 8000, "num_samples": 25616, "duration": 3.202, "channel_ids": [0]}, "type": "MonoCut"}

but when I check for duplicates in fbank/cuts_raw_train.jsonl.gz, I am not finding any duplicates.
Am I missing something?Please help.

**Comment by csukuangfj** [comment]
Please check the duration is larger than 0 for all the cuts in `batch.pt`.

**Comment by csukuangfj** [comment]
Not sure why you are checking for duplicates.

**Comment by csukuangfj** [comment]
> {"id": "AST0084-1000000855-734821", "start": 0, "duration": 3.202, "channel": 0, "supervisions": [{"id": "AST0084-1000000855", "recording_id": "AST0084-1000000855", "start": 0.0, "duration": 3.202, "channel": 0, "text": "i am preclosing my loan", "speaker": "AST0084", "custom": {"origin": "giga"}}], "recording": {"id": "AST0084-1000000855", "sources": [{"type": "file", "channels": [0], "source": "/media/administrator/hdd2/database/In_Housedata/English-Hindi/All_data/eng_hindi_renamed/AST0084/AST0084-1000000855.wav"}], "sampling_rate": 8000, "num_samples": 25616, "duration": 3.202, "channel_ids": [0]}, "type": "MonoCut"}

The two cuts you posted have different cut ids. Could you check they are present in your manifest file?

**Comment by bsshruthi22** [comment]
> Please check the duration is larger than 0 for all the cuts in `batch.pt`.
yes,greater than 0

**Comment by bsshruthi22** [comment]
> > {"id": "AST0084-1000000855-734821", "start": 0, "duration": 3.202, "channel": 0, "supervisions": [{"id": "AST0084-1000000855", "recording_id": "AST0084-1000000855", "start": 0.0, "duration": 3.202, "channel": 0, "text": "i am preclosing my loan", "speaker": "AST0084", "custom": {"origin": "giga"}}], "recording": {"id": "AST0084-1000000855", "sources": [{"type": "file", "channels": [0], "source": "/media/administrator/hdd2/database/In_Housedata/English-Hindi/All_data/eng_hindi_renamed/AST0084/AST0084-1000000855.wav"}], "sampling_rate": 8000, "num_samples": 25616, "duration": 3.202, "channel_ids": [0]}, "type": "MonoCut"}
> 
> The two cuts you posted have different cut ids. Could you check they are present in your manifest file?

Yes it is present twice in my manifest file.will removing those duplicate from my manifest file solve the issue?

**Comment by bsshruthi22** [comment]
i tried creating manifest from kaldi files(utt2spk,wav.scp,text). There its present only once.
