### ISSUE TITLE
devision by zero

### ISSUE THREAD

**Issue by Airgods** [k2-fsa/icefall#1737]

**Comment by Airgods** [comment]
不知道为什么在将ashell替换为我自己的数据集后，对wenet训练后的模型做微调时，会出现devision by zero的问题，以下是报错代码，请问有人遇到过吗？
![image](https://github.com/user-attachments/assets/824b7ca4-ab41-4788-9d19-64afa7fb228e)

**Comment by csukuangfj** [comment]
please recheck your data.
