### ISSUE TITLE
bug report : alimeeting prepare script: prepare_alimeeting_gss.sh some bug found. plz fix 

### ISSUE THREAD

**Issue by duhumail** [k2-fsa/icefall#1738]
run prepare script  on stage 3 ,some error:
![image](https://github.com/user-attachments/assets/f6e19cf9-b86e-4ba6-a340-32d71c3e1af7)

Error: Invalid value for 'CUTS_PER_SEGMENT': Path 'exp/alimeeting_gss/cuts_per_segment_train_split4/cuts_per_segment_train.JOB.jsonl.gz' does not exist.

path
egs/alimeeting/ASR_v2/local/prepare_alimeeting_gss.sh
The script uses a constant incorrectly, it should be a variable, and $ is missing

should be: 
$EXP_DIR/cuts_per_segment_train_split$nj/cuts_per_segment_train.$JOB.jsonl.gz $EXP_DIR/enhanced \

![image](https://github.com/user-attachments/assets/59b39a93-e94d-4f79-9eee-516451a74aa2)

**Comment by JinZr** [comment]
thanks! 

this pr should fix the issue: https://github.com/k2-fsa/icefall/pull/1749
