### ISSUE TITLE
bug report : alimeeting prepare script:  code comment not correct on stage 2  Prepare musan manifest

### ISSUE THREAD

**Issue by duhumail** [k2-fsa/icefall#1741]
![image](https://github.com/user-attachments/assets/17267404-ce02-4600-a38f-0501986f3817)

The musan corpus should be place in download/musan or $dl_dir/musan 
not data/musan 
Accroding to the script from the head of prepare.sh

![image](https://github.com/user-attachments/assets/8e65352e-cdca-4e9e-aa2b-b1d7b10dd8d2)

**Comment by JinZr** [comment]
thanks!

this PR should fix the issue: https://github.com/k2-fsa/icefall/pull/1747
