### ISSUE TITLE
data/manifests/musan_cuts.jsonl.gz can not found when running alimeeting train script ,plz check script issue 

### ISSUE THREAD

**Issue by duhumail** [k2-fsa/icefall#1742]
![image](https://github.com/user-attachments/assets/46425dd4-9c3d-43e4-b8f8-d347c9808e37)
FileNotFoundError: [Errno 2] No such file or directory: 'data/manifests/musan_cuts.jsonl.gz'

plz check the prepare script put the musan_cuts.jsonl.gz to data/fbank , not data/manifests.

i solved it by copy the musan_cuts.jsonl.gz file from data/fbank to data/manifests

plz check if the prepare script and trainning scipt mismatch

![image](https://github.com/user-attachments/assets/ec0adeeb-99d1-40eb-afb8-def1e3fe6702)

**Comment by JinZr** [comment]
thank you so much!

this pr should fix this issue: https://github.com/k2-fsa/icefall/pull/1750
