### ISSUE TITLE
Issue while running ./prepare.sh for yesno

### ISSUE THREAD

**Issue by chaksam** [k2-fsa/icefall#175]
Getting following issue while trying out the yesno recipe. Couldn't find any reference on internet to resolve this.

./prepare.sh 
2022-01-13 17:04:04 (prepare.sh:24:main) dl_dir: /home/stt/icefall/egs/yesno/ASR/download
2022-01-13 17:04:04 (prepare.sh:27:main) Stage 0: Download data
2022-01-13 17:04:04 (prepare.sh:36:main) Stage 1: Prepare yesno manifest
2022-01-13 17:04:05 (prepare.sh:42:main) Stage 2: Compute fbank for yesno
**Trying to register schema with name NCCLAllreduce from file /opt/conda/conda-bld/pytorch_1616554793803/work/caffe2/contrib/nccl/cuda_nccl_op_gpu.cc line 226, but it is already registered from file /pytorch/caffe2/contrib/nccl/hip/hip_nccl_op_gpu.cc line 227./prepare.sh: line 45: 21605 Aborted                 (core dumped) ./local/compute_fbank_yesno.py**

**Comment by chaksam** [comment]
The problem is occurring while importing get_executor from from icefall.utils

**>>> from icefall.utils import get_executor**
Trying to register schema with name NCCLAllreduce from file /opt/conda/conda-bld/pytorch_1616554793803/work/caffe2/contrib/nccl/cuda_nccl_op_gpu.cc line 226, but it is already registered from file /pytorch/caffe2/contrib/nccl/hip/hip_nccl_op_gpu.cc line 227Aborted (core dumped)

**Comment by danpovey** [comment]
I don't know that that part of the script even uses the GPU.
I suspect that different versions of Pytorch are being included somehowby different modules.
I'm surprised that that would even be possible though.

**Comment by chaksam** [comment]
I am working inside an environment named k2. Here is the list of packages in that environment. I am running ./prepare.sh inside this k2 conda environment. I can see just one PyTorch **(pytorch   1.8.1   py3.8_cuda11.1_cudnn8.0.5_0  pytorch)**. Shall I remove this environment and start from scratch?

**conda list -n k2**
--------------------------
# packages in environment at /home/chakrapani/anaconda3/envs/k2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
absl-py                   0.13.0                   pypi_0    pypi
argon2-cffi               20.1.0           py38h27cfd23_1  
async_generator           1.10               pyhd3eb1b0_0  
attrs                     21.2.0             pyhd3eb1b0_0  
audioread                 2.1.9                    pypi_0    pypi
backcall                  0.2.0              pyhd3eb1b0_0  
blas                      1.0                         mkl  
bleach                    4.0.0              pyhd3eb1b0_0  
ca-certificates           2021.10.26           h06a4308_2  
cachetools                4.2.2                    pypi_0    pypi
certifi                   2021.5.30                pypi_0    pypi
cffi                      1.14.6           py38h400218f_0  
charset-normalizer        2.0.4                    pypi_0    pypi
click                     8.0.1                    pypi_0    pypi
cudatoolkit               11.1.1               h6406543_8    conda-forge
cytoolz                   0.11.0                   pypi_0    pypi
dataclasses               0.6                      pypi_0    pypi
dbus                      1.13.18              hb2f20db_0  
debugpy                   1.4.1            py38h295c915_0  
decorator                 5.0.9              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
entrypoints               0.3                      py38_0  
expat                     2.4.1                h2531618_2  
fontconfig                2.13.1               h6c09931_0  
freetype                  2.10.4               h5ab3b9f_0  
glib                      2.69.1               h5202010_0  
google-auth               1.35.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.39.0                   pypi_0    pypi
gst-plugins-base          1.14.0               h8213a91_2  
gstreamer                 1.14.0               h28cd5cc_2  
h5py                      3.4.0                    pypi_0    pypi
icu                       58.2                 he6710b0_3  
idna                      3.2                      pypi_0    pypi
importlib-metadata        3.10.0           py38h06a4308_0  
importlib_metadata        3.10.0               hd3eb1b0_0  
intervaltree              3.1.0                    pypi_0    pypi
ipykernel                 6.2.0            py38h06a4308_1  
ipython                   7.26.0           py38hb070fc8_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.3              pyhd3eb1b0_1  
jedi                      0.18.0           py38h06a4308_1  
jinja2                    3.0.1              pyhd3eb1b0_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                3.2.0                      py_2  
jupyter                   1.0.0                    py38_7  
jupyter_client            6.1.12             pyhd3eb1b0_0  
jupyter_console           6.4.0              pyhd3eb1b0_0  
jupyter_core              4.7.1            py38h06a4308_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
k2                        1.6.dev20210824 cuda11.1_py3.8_torch1.8.1    k2-fsa
kaldialign                0.2                      pypi_0    pypi
kaldilm                   1.8                      pypi_0    pypi
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lhotse                    0.8.0                    pypi_0    pypi
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 11.1.0               hc902ee8_8    conda-forge
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.18               h7b6447c_0  
libstdcxx-ng              11.1.0               h56837e0_8    conda-forge
libuuid                   1.0.3                h1bed415_2  
libuv                     1.42.0               h7f98852_0    conda-forge
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.12               h03d6c58_0  
lilcom                    1.1.1                    pypi_0    pypi
llvm-openmp               12.0.1               h4bd325d_1    conda-forge
markdown                  3.3.4                    pypi_0    pypi
markupsafe                2.0.1            py38h27cfd23_0  
matplotlib-inline         0.1.2              pyhd3eb1b0_2  
mistune                   0.8.4           py38h7b6447c_1000  
mkl                       2021.3.0           h726a3e6_557    conda-forge
mkl-service               2.4.0            py38h497a2fe_0    conda-forge
mkl_fft                   1.3.0            py38h42c9631_2  
mkl_random                1.2.2            py38h1abd341_0    conda-forge
nbclient                  0.5.3              pyhd3eb1b0_0  
nbconvert                 6.1.0            py38h06a4308_0  
nbformat                  5.1.3              pyhd3eb1b0_0  
ncurses                   6.2                  h58526e2_4    conda-forge
nest-asyncio              1.5.1              pyhd3eb1b0_0  
ninja                     1.10.2               h4bd325d_0    conda-forge
notebook                  6.4.3            py38h06a4308_0  
numpy                     1.20.3           py38hf144106_0  
numpy-base                1.20.3           py38h74d4b33_0  
oauthlib                  3.1.1                    pypi_0    pypi
openssl                   1.1.1l               h7f8727e_0  
packaging                 21.0               pyhd3eb1b0_0  
pandocfilters             1.4.3            py38h06a4308_1  
parso                     0.8.2              pyhd3eb1b0_0  
pcre                      8.45                 h295c915_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pip                       21.2.4             pyhd8ed1ab_0    conda-forge
prometheus_client         0.11.0             pyhd3eb1b0_0  
prompt-toolkit            3.0.17             pyh06a4308_0  
prompt_toolkit            3.0.17               hd3eb1b0_0  
protobuf                  3.17.3                   pypi_0    pypi
ptyprocess                0.7.0              pyhd3eb1b0_2  
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.20                       py_2  
pygments                  2.10.0             pyhd3eb1b0_0  
pyparsing                 2.4.7              pyhd3eb1b0_0  
pyqt                      5.9.2            py38h05f1152_4  
pyrsistent                0.17.3           py38h7b6447c_0  
python                    3.8.10          h49503c6_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-graphviz           0.17                     pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
**pytorch                   1.8.1           py3.8_cuda11.1_cudnn8.0.5_0    pytorch**
pyyaml                    5.4.1                    pypi_0    pypi
pyzmq                     22.2.1           py38h295c915_1  
qt                        5.9.7                h5867ecd_1  
qtconsole                 5.1.0              pyhd3eb1b0_0  
qtpy                      1.10.0             pyhd3eb1b0_0  
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.26.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.7.2                    pypi_0    pypi
send2trash                1.5.0              pyhd3eb1b0_1  
sentencepiece             0.1.96                   pypi_0    pypi
setuptools                57.4.0           py38h578d9bd_0    conda-forge
sip                       4.19.13          py38he6710b0_0  
six                       1.16.0             pyh6c4a22f_0    conda-forge
sortedcontainers          2.4.0                    pypi_0    pypi
soundfile                 0.10.3.post1             pypi_0    pypi
sqlite                    3.36.0               h9cd32fc_0    conda-forge
tbb                       2021.3.0             h4bd325d_0    conda-forge
tensorboard               2.6.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
terminado                 0.9.4            py38h06a4308_0  
testpath                  0.5.0              pyhd3eb1b0_0  
tk                        8.6.11               h21135ba_0    conda-forge
toolz                     0.11.1                   pypi_0    pypi
torch                     1.8.1+rocm4.0.1          pypi_0    pypi
torchaudio                0.8.1                    pypi_0    pypi
tornado                   6.1              py38h27cfd23_0  
tqdm                      4.62.2                   pypi_0    pypi
traitlets                 5.0.5              pyhd3eb1b0_0  
typing_extensions         3.10.0.0           pyha770c72_0    conda-forge
urllib3                   1.26.6                   pypi_0    pypi
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py38_1  
werkzeug                  2.0.1                    pypi_0    pypi
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
widgetsnbextension        3.5.1                    py38_0  
xz                        5.2.5                h516909a_1    conda-forge
zeromq                    4.3.4                h2531618_0  
zipp                      3.5.0              pyhd3eb1b0_0  
zlib                      1.2.11            h516909a_1010    conda-forge

**Comment by chaksam** [comment]
After uninstalling, purging and reinstalling most of the dependencies, it worked fine.
