### ISSUE TITLE
Kmeans in SSL

### ISSUE THREAD

**Issue by SSwethaSel0609** [k2-fsa/icefall#1759]
I'm trying to train SSL with zipformer. I dont know how to prepare data for this. It is expecting kmeans. How can I prepare kmeans. Can you give me any idea?

I have already prepared manifest dir but without kmeans. 
{"id": "9904944b959642f8a1e9b21c4df14027-l_000064_393.660_395.550", "start": 393.66, "duration": 1.89, "channel": 0, "supervisions": [{"id": "9904944b959642f8a1e9b21c4df14027-l_000064_393.660_395.550", "recording_id": "9904944b959642f8a1e9b21c4df14027-l", "start": 0.0, "duration": 1.89, "channel": 0, "text": "five five zero seven seven", "speaker": "9904944b959642f8a1e9b21c4df14027-l"}], "features": {"type": "kaldi-fbank", "num_frames": 189, "num_features": 40, "frame_shift": 0.01, "sampling_rate": 8000, "start": 393.66, "duration": 1.89, "storage_type": "chunked_lilcom_hdf5", "storage_path": "/mnt/efs/swetha/English_data/sagemaker_data/icefall_sagemaker_en_40dim/manifests/train_en_40_dim_features_1/split-2.h5", "storage_key": "255c16ae-a6cf-4660-97ff-c2d6a06d867c", "channels": 0}, "recording": {"id": "9904944b959642f8a1e9b21c4df14027-l", "sources": [{"type": "command", "channels": [0], "source": "sox /mnt/efs/blessingh/asr_ensemble_automate/git_repo/ds-asr-datastrategy/configs/output_medicare_service_second_part/audio/medicare_service_second_part/medicare_service_second_part_channel_separated/9904944b959642f8a1e9b21c4df14027-l.wav -r 8000 -t wav -b 16 -e signed-integer - "}], "sampling_rate": 8000, "num_samples": 5894560, "duration": 736.82, "channel_ids": [0]}, "type": "MonoCut"}

**Comment by yfyeung** [comment]
You can refer https://github.com/k2-fsa/icefall/blob/25b6dd26ac72e55680dbb8a71f6cf83209379290/egs/librilight/SSL/local/extract_kmeans_from_hubert_base.py
