### ISSUE TITLE
Alignment with CTC phone model

### ISSUE THREAD

**Issue by RanoRaraku** [k2-fsa/icefall#176]
Hi, I am trying to run an alignment with a CTC phone model. I got a few questions.

1)  I can obtain "best_paths" FSa after running k2.shortest_path on a lattice. Then, I want to use icefall.utils.get_alignments(), but it fails with the following error :
     AttributeError: '_k2.ragged.RaggedTensor' object has no attribute 'contiguous'.
for the following constructor call :
    tokens = k2.RaggedTensor(
        token_shape, getattr(best_paths, kind).contiguous()
    )
When I checked  getattr(best_paths, kind) returns a _k2.ragged.RaggedTensor type for "labels" and "aux_labels".  What's the expected data type into that constructor; RaggedTensor or torch Tensor?  Any idea if this might be an issue of a version? I am using a k2 version: 1.11.

2) I can just print "labels" and "aux_labels" from the best_paths, but I can't use them to obtain the time stamps cause both words and phones are repeated only once in the output sequence. I wonder if this is an issue because the lexicon was processed using icefall/egs/librispeech/ASR/local/prepare_lang.py and sil_token is mapped to eps. If I read it correctly on line 299.

Thanks

**Comment by csukuangfj** [comment]
> I can obtain "best_paths" FSa after running k2.shortest_path on a lattice. 

How do you generate the lattice?

`lattice.labels` and `lattice.aux_labels` are expected to contain tensor attributes, not ragged tensor attributes.

https://github.com/k2-fsa/icefall/blob/273e5fb2f3ac2620bafdffe2689b8b3ee10173d3/egs/librispeech/ASR/conformer_ctc/ali.py#L211-L224

shows how to generate the lattice.

---

> When I checked getattr(best_paths, kind) returns a _k2.ragged.RaggedTensor type for "labels" and "aux_labels". 

The `type` of `labels` should never be a ragged tensor. If you get the lattice from a `HLG` graph, then the `aux_labels` may be a ragged tensor. But if you use an `H`, i.e., a ctc topo, then the `aux_labels` should also be a `torch.Tensor`.

---

> What's the expected data type into that constructor; RaggedTensor or torch Tensor?

It should be a `torch.Tensor`. Please refer to the documentation of the constructor. See
https://k2-fsa.github.io/k2/python_api/api.html#k2.ragged.RaggedTensor.__init__

**Comment by RanoRaraku** [comment]
> The `type` of `labels` should never be a ragged tensor. If you get the lattice from a `HLG` graph, then the `aux_labels` may be a ragged tensor. But if you use an `H`, i.e., a ctc topo, then the `aux_labels` should also be a `torch.Tensor`.

Thanks, that explains it. I have no problem for BPE-CTC model and BpeCtcTrainingGraphCompiler, only when I use phone CTC model and CtcTrainingGraphCompiler. I guess the best way to handle this is to do ragged to torch conversion after I finding the shortest path through the lattice, no way to control this during lattice creation for HLG?

**Comment by csukuangfj** [comment]
If you just want to get the alignment, HLG is not needed, I think. You only need H and the transcript of the corresponding utterance, like what we are doing in the training. 

For phone-based models, there are optional silences before and after each word. You can modify https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/local/prepare_lang.py to remove optional silences so that there are no epsilon transitions in the lexicon.

**Comment by pzelasko** [comment]
> For phone-based models, there are optional silences before and after each word. You can modify https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/local/prepare_lang.py to remove optional silences so that there are no epsilon transitions in the lexicon.

Interesting -- wouldn't removing optional silences make it impossible to distinguish silence from blank? E.g. the alignments wouldn't tell you about a silence between two words.

**Comment by csukuangfj** [comment]
> > For phone-based models, there are optional silences before and after each word. You can modify https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/local/prepare_lang.py to remove optional silences so that there are no epsilon transitions in the lexicon.
> 
> 
> 
> Interesting -- wouldn't removing optional silences make it impossible to distinguish silence from blank? E.g. the alignments wouldn't tell you about a silence between two words. 
> 
> 

For CTC models, can remove silence as we already have a blank symbol?

**Comment by danpovey** [comment]
Piotr-- yes, we wouldn't be able to distinguish silence from blank without
optional silences.
The *length* of blank symbol, though, may be somewhat useful as a crude
test for silence.

**Comment by pzelasko** [comment]
@csukuangfj Consider an utterance like this

0 0.5 !SIL
0.5 1.5 HI
1.5 3.0 !SIL
3.0 4.8 FANGJUN
4.8 6.0 !SIL

without a sil token and word, you will only be able to precisely find the initial !SIL, but not the second and third one.

**Comment by danpovey** [comment]
Might be possible with the help of some assumptions about phone duration;
but yes, difficult.

**Comment by RanoRaraku** [comment]
Thanks for all the comments. It gave us two ideas of how to solve the issue so I will close the thread and start a new one in case we will need your inputs. Best
