### ISSUE TITLE
Decoding through .pt model using Audio id

### ISSUE THREAD

**Issue by bhaswa** [k2-fsa/icefall#1765]
Hi,

I want to transcrible a batch of audios using zipformer .pt model (not using .onnx model). I checked there is a file named decode.py, but there I cannot provide the audio names explicitly, i have to prepare the features beforhand. Is there any file where I can give the audio names as input and it will give me the output in single go?

Or any idea how I can do it ?

**Comment by csukuangfj** [comment]
please use pretrained.py

**Comment by csukuangfj** [comment]
please see https://k2-fsa.github.io/icefall/model-export/export-model-state-dict.html#how-to-use-the-exported-model
