### ISSUE TITLE
Mismatch of pretrained weights size of SURT model downloaded from huggingface

### ISSUE THREAD

**Issue by nightwatcher-of-abyss** [k2-fsa/icefall#1784]
When I want to use pretrained SURT model to make inference, I encountered the following error like this:
size mismatch for encoder.encoders.4.upsample.bias: copying a param with shape torch.Size([2, 256]) from checkpoint, the shape in current model is torch.Size([2, 384]).
I ran the program icefall/egs/librispeech/ASR/pruned_transducer_stateless7_streaming_multi/pretrained.py, so how can I solve this without training the model?

**Comment by csukuangfj** [comment]
Please try to find the params used to train the SURT model and don't use default parameters.

**Comment by nightwatcher-of-abyss** [comment]
I found the params in the program "do not use it directly.py", but I have no idea how to effectively revise it. May I ask how to do this, buddy?

**Comment by nightwatcher-of-abyss** [comment]
https://huggingface.co/desh2608/icefall-surt-libricss-dprnn-zipformer
This is the provided weights of the url, but the recipe of the doc  https://icefall.readthedocs.io/en/latest/ do not provide the SURT's. So I just try by myself.

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/icefall/blob/master/egs/libricss/SURT/README.md#description-of-the-recipe

The above link should contain enough information to run the pre-trained model.

Also, the doc URL is https://k2-fsa.github.io/icefall/

**Comment by nightwatcher-of-abyss** [comment]
So the recipe focused on train the model and the pretrained recipe provided do not guide how to revise the model params without training the model and only for infering by pretrained weights

**Comment by nightwatcher-of-abyss** [comment]
So I can use decode.py to infer on my own wav file?

**Comment by csukuangfj** [comment]
of course

**Comment by nightwatcher-of-abyss** [comment]
Thank you！But is that normal when I use the weights to decode but finally got nothing to output?

**Comment by csukuangfj** [comment]
no, it is abnormal.

As said before，please post detailed steps for reproducing your issue.

**Comment by nightwatcher-of-abyss** [comment]
I used your command format provided in the code to transcribe my wav file and the pretrained.py can run normally and output logs, but the logs to show the transcription of my test.wav turn out to be none. The wav is English and resampled to 16000Hz and contained multi speakers

**Comment by csukuangfj** [comment]
As said before，please post detailed steps for reproducing your issue.

You can use public available test waves for testing.

**Comment by nightwatcher-of-abyss** [comment]
python ./pretrained.py \
  --checkpoint /icefall-surt-libricss-dprnn-zipformer/exp/surt_large/pretrained.pt \
  --tokens /icefall-surt-libricss-dprnn-zipformer/data/lang_bpe_500/tokens.txt \
  /test.wav
  other parameters is default value

**Comment by csukuangfj** [comment]
I have tested it with
- https://huggingface.co/csukuangfj/sherpa-onnx-moonshine-tiny-en-int8/resolve/main/test_wavs/0.wav
and
- https://huggingface.co/desh2608/icefall-surt-libricss-dprnn-zipformer/resolve/main/exp/surt_base/pretrained.pt

and it works perfectly.

Please try it and see if you can reproduce it.

Remember that this model is for English and your test wave must be in English.

---

Please post complete logs if you have further issues.
