### ISSUE TITLE
在从kaldi脚本生成cut的时候遇到json问题

### ISSUE THREAD

**Issue by 728826058** [k2-fsa/icefall#1811]
在运行/workspace/icefall/egs/wenetspeech/ASR/local/prepare_dataset_from_kaldi_dir.py脚本时，但
将代码改成
<img width="676" alt="5a8c81b5ca69dc21c2daf9f786493c7a" src="https://github.com/user-attachments/assets/4c82664d-445d-45d5-a1d4-a4959e25ec1c">
的时候，运行之后报了错误
<img width="676" alt="5a8c81b5ca69dc21c2daf9f786493c7a" src="https://github.com/user-attachments/assets/58672f5d-6ad1-4587-bcd5-123a1229ad7a">
我的text数据格式为
part01_05_0247223 paH bEk KiziK ikEn jumu
A210211576-aks20190822 xuniNdimu kONlini izdEp alattim Hazir saEt on on bir bolGiqE telefon
part01_01_0035793 mEn aldi bilEn OzEmni tonuxturdi
DR0242_000281 hElKimiz HeliHEm HEr KetimliK tamiKida nandin ayrilGan nansiz Eziz meHmanlirini uzatKan EmEs

**Comment by JinZr** [comment]
请问报错是什么？
