### ISSUE TITLE
请问目前有在k2框架训练ngram lm的脚本或者文档嘛

### ISSUE THREAD

**Issue by alanshaoTT** [k2-fsa/icefall#1824]

**Comment by JinZr** [comment]
你可以使用 kenlm 或者 srilm 训练 ngram 模型，得到 arpa 文件后 import 到 k2 中。

**Comment by alanshaoTT** [comment]
> 你可以使用 kenlm 或者 srilm 训练 ngram 模型，得到 arpa 文件后 import 到 k2 中。

好的谢谢。那比如transformer lm结合到zipformer解码有没有相关的实现呢

**Comment by JinZr** [comment]
NNLM 相关的内容可以参考这个文档里的解码方式：https://k2-fsa.github.io/icefall/decoding-with-langugage-models/index.html

best regards
jin
