### ISSUE TITLE
Zipformer missing bias parameter

### ISSUE THREAD

**Issue by fmac2000** [k2-fsa/icefall#1832]
Hi Authors,

[SimpleUpsample](https://github.com/k2-fsa/icefall/blob/a43480af47896329e82917d89ceee65f15afbf25/egs/librispeech/ASR/zipformer/zipformer.py#L1373) is missing the bias parameter.

Thanks for the model - it's been a treat to go through this incredible paper, thanks for the hard work and for open-sourcing 🥳!

**Comment by csukuangfj** [comment]
I think the comment should be updated.

It is there for zipformer v1.

Please see
https://github.com/k2-fsa/icefall/blob/a43480af47896329e82917d89ceee65f15afbf25/egs/librispeech/ASR/pruned_transducer_stateless7/zipformer.py#L817

**Comment by csukuangfj** [comment]
we recommend zipformer.v2, which is the one in the.paper.
