### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by lightandblue** [k2-fsa/icefall#1833]
**I encountered a RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR while training my RNN language model using nn.LSTM
I have already tried  change environments and run on other servers.**
> ./rnn_lm/train.py \
>     --world-size 1 \
>     --exp-dir $exp_dir \
>     --start-epoch 0 \
>     --num-epochs $num_epochs \
>     --vocab-size 500 \
>     --use-fp16 0 \
>     --tie-weights false \
>     --embedding-dim 800 \
>     --hidden-dim 200 \
>     --num-layers 2 \
>     --batch-size 50 \
>     --lm-data data/lang_bpe_500/sorted_lm_data.pt \
>     --lm-data-valid `data/lang_bpe_500/sorted_lm_data.pt

> Traceback (most recent call last):
>   File "./rnn_lm/train.py", line 689, in <module>
>     main()
>   File "./rnn_lm/train.py", line 682, in main
>     run(rank=0, world_size=1, args=args)
>   File "./rnn_lm/train.py", line 647, in run
>     train_one_epoch(
>   File "./rnn_lm/train.py", line 474, in train_one_epoch
>     loss, loss_info = compute_loss(
>   File "./rnn_lm/train.py", line 376, in compute_loss
>     nll = model(x, y, sentence_lengths)
>   File "/home/environment2/cywang/anaconda3/envs/k2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/node22_tmpdata/cywang/workspace/icefall/icefall/rnn_lm/model.py", line 151, in forward
>     rnn_out, _ = self.rnn(embedding)
>   File "/home/environment2/cywang/anaconda3/envs/k2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/environment2/cywang/anaconda3/envs/k2/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 812, in forward
>     result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
> RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

**Comment by marcoyang1998** [comment]
This is usually cause by a mismatch between the vocab size and the nn.Embedding in the LM. Could you please check it?

**Comment by lightandblue** [comment]
> This is usually cause by a mismatch between the vocab size and the nn.Embedding in the LM. Could you please check how many tokens you have in your data?

you mean' --vocab-size 500 --embedding-dim 800' must be equal ?

**Comment by marcoyang1998** [comment]
No, I mean the number of different tokens in your lm Training data. You had vocabulary size of 500, but your data seems to more than 500 tokens

**Comment by lightandblue** [comment]
> No, I mean the number of different tokens in your lm Training data. You had vocabulary size of 500, but your data seems to more than 500 tokens

Thank you !!!
