### ISSUE TITLE
 ImportError:cannot import name 'GradScaler' form 'toch.amp' 

### ISSUE THREAD

**Issue by Berskii** [k2-fsa/icefall#1839]
Hi, 

I've recently installed icefall, follow the installtion tutorial it all goes right util it runs yesno, It raise `ImportError:cannot import name 'GradScaler' form 'toch.amp' ` ,  I've tried torch2.1.0+cuda121 and torch1.13.0+cu116 and it doesn't help. How can I fix this?

**Comment by Berskii** [comment]
It solved by using torch.cuda.amp.

**Comment by csukuangfj** [comment]
Fixed in the latest master.
