### ISSUE TITLE
kws开源模型是否缺失文件

### ISSUE THREAD

**Issue by kaidachen** [k2-fsa/icefall#1847]
https://github.com/pkufool/keyword-spotting-models/releases/download/v0.11/icefall-kws-zipformer-wenetspeech-20240219.tar.gz
是否缺失预训练模型data/lang_partial_tone/L.pt？
我想基于开放的预训练模型，尝试用问问数据集微调训练，出现如下报错，看起来是缺少L.pt
执行run.sh第3步会出现如下报错
```
FileNotFoundError: [Errno 2] No such file or directory: 'icefall-kws-zipformer-wenetspeech-20240219/data/lang_partial_tone/L.pt'
```
期待回复

**Comment by csukuangfj** [comment]
@pkufool  Please have a look.

**Comment by Jerry-Kon** [comment]
你好，请问如何解决

**Comment by garymmi** [comment]
你好，我也遇到这个问题，请问有解吗，谢谢

**Comment by garymmi** [comment]
![Image](https://github.com/user-attachments/assets/109ad7c9-50c8-497e-b885-e1fe04d7ffea)

**Comment by csukuangfj** [comment]
你需要找到lexicon.txt，

L.pt是从lexicon.txt生成的

**Comment by Emma-Miao** [comment]
请问 lexicon.txt 文件在哪里呢？我在预训练模型文件夹中没有找到

**Comment by garymmi** [comment]
lexicon.txt 这必须从原始语料的文本生成

**Comment by pkufool** [comment]
> lexicon.txt 这必须从原始语料的文本生成

现在的脚本应该不需要这个文件了，很早就删除了。
