### ISSUE TITLE
k2 installation fail

### ISSUE THREAD

**Issue by gray4what** [k2-fsa/icefall#189]
failure after run `python3 -m k2.version` 
```
   from _k2 import DeterminizeWeightPushingType
ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/k2/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/ubuntu/anaconda3/envs/k2/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/ubuntu/gyang/k2-icefall/test-icefall/lib/python3.7/site-packages/k2/__init__.py", line 9, in <module>
    str(e) + "\nNote: If you're using anaconda and importing k2 on MacOS,"
ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
Note: If you're using anaconda and importing k2 on MacOS,
      you can probably fix this by setting the environment variable:
  export DYLD_LIBRARY_PATH=$CONDA_PREFIX/lib/python3.7/site-packages:$DYLD_LIBRARY_PATH
```
1. tried ubuntu 16.04 and 18.04, both fail.   tried `virtualenv ` and `conda `, same error. 
2. there is a`libpython3.7m.so.1.0` file in dir `ananconda3/lib/` , tried to copy this file to  `$CONDA_PREFIX/lib/python3.7/site-packages`, not works
3. btw, seems k2 requires GLIBC >2.27

**Comment by csukuangfj** [comment]
How did you install k2?

---

> btw, seems k2 requires GLIBC >2.27

If you install k2 from source, then it has no such a requirement, I think.
(See https://k2-fsa.github.io/k2/installation/from_source.html
and
https://k2-fsa.github.io/k2/installation/for_developers.html
for installing k2 from source)

**Comment by csukuangfj** [comment]
For the error:
> ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory

there are some suggestions in https://github.com/deepmind/acme/issues/47 that may be helpful.

**Comment by gray4what** [comment]
I created a conda env, and installed with pip. 

But I just successfully installed it by following `https://k2-fsa.github.io/k2/installation/conda.html`.
