### ISSUE TITLE
Recipes for release

### ISSUE THREAD

**Issue by pzelasko** [k2-fsa/icefall#2]
I'm thinking what are the recipes we can show at the tutorial, and whether we need to add more. AFAIK we have the following ready (and can use roughly any combination of them):

# Corpora
- LibriSpeech
- Aishell

# Architectures
- tdnn-lstm
- conformer
- contextnet

# Topologies
- CTC

# Criterions
- CTC
- MMI 2-gram dens

# AM targets
- phones + blank
- BPEs + blank

**Comment by pzelasko** [comment]
I am thinking about adding a recipe for something conversational, to illustrate the need for/benefits of multiple supervision segments with actual acoustic context. I could prepare a recipe for this, e.g. on Switchboard? Not sure if there's a similar corpus that is also open (maybe GigaSpeech, possibly a subset of it).

**Comment by danpovey** [comment]
Cool!
Yes, those features look good.  And also your thing about multiple
segments, although my focus right now is to simply have something --
anything-- ready by  the time we give the Interspeech tutorial.
Dan

**Comment by pzelasko** [comment]
Don't worry, we'll make it ;) 
Do you think we should copy the code from snowfall and adjust it somehow or just work on the snowfall repo for the time being? I think given that we're trying to limit the scope, maybe it makes sense to just stick to snowfall for now. Do you envision any serious changes to how the code is organized there by the tutorial deadline?

**Comment by danpovey** [comment]
I think we should take the opportunity to clean up interfaces a little and rework the directory structure a bit,
and get rid of any old versions of code that we don't want.  But we don't need to make very fundamental changes, I think.
