### ISSUE TITLE
Error while preparing BPE data

### ISSUE THREAD

**Issue by anderleich** [k2-fsa/icefall#225]
Hi,

Following the Librispeech recipe I'm trying to prepare my own custom data. When running the follwoing code I got an error (in the `local/prepare_lang_bpe.py` script):

```
for vocab_size in ${vocab_sizes[@]}; do
    lang_dir=$DATA/lang_bpe_${vocab_size}
    mkdir -p $lang_dir
    # We reuse words.txt from phone based lexicon
    # so that the two can share G.pt later.
    cp $DATA/lang_phone/words.txt $lang_dir

    if [ ! -f $lang_dir/transcript_words.txt ]; then
      log "Generate data for BPE training"
      cp /data/data.txt $lang_dir/transcript_words.txt
    fi

    ./local/train_bpe_model.py \
      --lang-dir $lang_dir \
      --vocab-size $vocab_size \
      --transcript $lang_dir/transcript_words.txt

    if [ ! -f $lang_dir/L_disambig.pt ]; then
      ./local/prepare_lang_bpe.py --lang-dir $lang_dir
    fi
  done
```

```
2022-02-24 16:47:12 (prepare.sh:77:main) Stage 6: Prepare BPE based lang
Traceback (most recent call last):
  File "./local/prepare_lang_bpe.py", line 254, in <module>
    main()
  File "./local/prepare_lang_bpe.py", line 225, in main
    L = lexicon_to_fst_no_sil(
  File "./local/prepare_lang_bpe.py", line 93, in lexicon_to_fst_no_sil
    pieces = [token2id[i] for i in pieces]
  File "./local/prepare_lang_bpe.py", line 93, in <listcomp>
    pieces = [token2id[i] for i in pieces]
KeyError: '0'
```
`words.txt` file has been automatically generated from the lexicon which in turn has been generated by processing all the words in the  `/data/data.txt` file. However while preparing BPEed lang directory `token2id[i]` is raising `KeyError` for entries in the lexicon file.
Any clues? Am I missing something?

**Comment by csukuangfj** [comment]
> However while preparing BPEed lang directory token2id[i] is raising KeyError for entries in the lexicon file.

The error indicates that `0` is a token, which does not seem to be right.
Can you print out the corresponding `word` and `pieces` that result in the error?

https://github.com/k2-fsa/icefall/blob/ac7c2d84bc44dd83a5653f68677ae1ef16551eea/egs/librispeech/ASR/local/prepare_lang_bpe.py#L88

**Comment by anderleich** [comment]
Indeed it is a token from the lexicon:
0 ['▁', '0']

I've tried increasing vocabulary size and then the error comes from another token:
Œ ['▁', 'Œ']

**Comment by anderleich** [comment]
I think it might come from here:
https://github.com/k2-fsa/icefall/blob/ac7c2d84bc44dd83a5653f68677ae1ef16551eea/egs/librispeech/ASR/local/prepare_lang_bpe.py#L158

If it is not in `token2id` it raises an exception. Should it be mapping the token to `<unk>`?

**Comment by danpovey** [comment]
If it's in local/, I think it's expected to be dataset-dependent.  You could make a decision for your own dataset about how you want to deal with unknown tokens, e.g. either delete them, map to something like `<unk>`, or discard the whole sentence.

**Comment by csukuangfj** [comment]
I think in the LibriSpeech dataset, there are only characters `A-Z` and the apostrophe `'` in a word, so BPE tokens also consist of `A-Z` and the `'` .

If a word contains characters other than `A-Z` and `'`, it should be mapped to the unknown word and should not be present in the lexicon, I think.

---

> words.txt file has been automatically generated from the lexicon which in turn has been generated by processing all the words in the /data/data.txt file.

Did you use `/data/data.txt` to train your BPE model?

**Comment by anderleich** [comment]
That makes sense. 
 
> Did you use /data/data.txt to train your BPE model?

Yes

Just to be sure with the logic during data preparation as I guess it is why I'm getting these errors.

1. Should the lexicon.txt file and therefore the words.txt file just contain words in the training supervisions or could it be built from the bigger data file used to train the LM? I mean, can I have words that are not part of the training data set?
2. Should the BPE model be trained just on the training supervisions or can I use the LM data file?
3. I guess vocab size is quite relevant here. In the case of Librispeech the maximum vocab size is 5000. In other tasks such as MT, I've seen 32k vocabs. What do you recommend? In addition, if I understood it correctly, there should not be unknown words using BPE

Overall, my question is: how should I generate language data? From the LM data or training supervisions?

Thanks

**Comment by danpovey** [comment]
> That makes sense.
> 
> > Did you use /data/data.txt to train your BPE model?
> 
> Yes
> 
> Just to be sure with the logic during data preparation as I guess it is why I'm getting these errors.
> 
> 1. Should the lexicon.txt file and therefore the words.txt file just contain words in the training supervisions or could it be built from the bigger data file used to train the LM? I mean, can I have words that are not part of the training data set?

You can use the data from the LM as well.  Sometimes it makes sense to use some kind of cutoff so that words with more than a certain count appear in the lexicon.txt/words.txt. 
BTW, the lexicon.txt/words.txt are more important in phone-based systems;  I don't know whether we actually make use of them in BPE-based systems, at least if we're not rescoring with a word-based language model.  However they may still be required for the data-dir validation.  If you are doing to decode in a way that's limited to words.txt for some reason, it's probably a good idea to have a fairly large vocabulary that includes more than just the training text.  

> 2. Should the BPE model be trained just on the training supervisions or can I use the LM data file?

My tendency would be to use the training supervisions, see below for reasons.

> 3. I guess vocab size is quite relevant here. In the case of Librispeech the maximum vocab size is 5000. In other tasks such as MT, I've seen 32k vocabs. What do you recommend? In addition, if I understood it correctly, there should not be unknown words using BPE

We have moved to using smaller BPE vocabularies, like 500, as we found that this was better (or at least not worse).  Also, for RNN-T it's a problem for memory if you use large vocab size; 5k is considered large in this context.  We can still train, without a problem, though, if we use the pruned RNN-T recipe (pruned_transducer_stateless, I think).

> Overall, my question is: how should I generate language data? From the LM data or training supervisions?

... it's probably not that critical as little data is required to generate the BPE, and anyway it will cover all words as long as all characters are seen.  Another issue is that if you train the BPE on LM training data and it gives you BPE pieces that have low or zero coverage in your training data, that would actually be a problem for model training, as you wouldn't have enough data to train those outputs.

**Comment by csukuangfj** [comment]
>  In addition, if I understood it correctly, there should not be unknown words using BPE

Well, that depends. If your words contain characters that all can be found in the known BPE tokens, then they are not considered OOV.

However, if your words contain characters that are not present in the BPE tokens, those words are considered OOVs.
For instance, in the librispeech datatset, if you pass a German word that contains umlaut, e.g., `nächste`, there is no way to represent `ä` by the known BPE tokens.

**Comment by csukuangfj** [comment]
>  I mean, can I have words that are not part of the training data set?

Yes, I think so as long as the characters in those words are known BPE tokens.

> Should the BPE model be trained just on the training supervisions or can I use the LM data file?

In ESPnet, it also uses only data from the training supervisions to train BPE. See 
https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/run.sh#L156
```bash
    cut -f 2- -d" " data/${train_set}/text > data/lang_char/input.txt
    spm_train --input=data/lang_char/input.txt --vocab_size=${nbpe} --model_type=${bpemode} --model_prefix=${bpemodel} --input_sentence_size=100000000
```

**Comment by danpovey** [comment]
Sounds reasonable.
Not all of those things are needed for all systems.  Generally the phone-based stuff is not needed if the recipe is BPE-based.
And the HLG might not be needed currently in a transducer-based system.

**Comment by anderleich** [comment]
Thanks @danpovey !

One more thing, a 11GB RAM GPU seems it is not enough to perform most of the decoding methods. Is this task so memory consuming? I mean the training step is taking around 3GB only. The decoding step, doesn't fit though.

**Comment by csukuangfj** [comment]
> Thanks @danpovey !
> 
> 
> 
> One more thing, a 11GB RAM GPU seems it is not enough to perform most of the decoding methods. Is this task so memory consuming? I mean the training step is taking around 3GB only. The decoding step, doesn't fit though.

Decoding methods without an G should require less memory. Also, transducer decoding requires even less memory.

**Comment by anderleich** [comment]
@csukuangfj are there any examples on how to perform decoding without a G or transducer decoding?

Thanks

**Comment by csukuangfj** [comment]
> @csukuangfj are there any examples on how to perform decoding without a G or transducer decoding?
> 
> Thanks

Yes, you can find them on
- https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/RESULTS.md (for transducer decoding)
- https://icefall.readthedocs.io/en/latest/recipes/librispeech/conformer_ctc.html#decoding (for conformer_ctc decoding without an G)

**Comment by anderleich** [comment]
Thanks! Both methods are meant to be used with the conformer models, aren't they?

**Comment by csukuangfj** [comment]
> Thanks! Both methods are meant to be used with the conformer models, aren't they?

Yes. The current transducer model (in the folder [transducer_stateless](https://github.com/k2-fsa/icefall/tree/master/egs/librispeech/ASR/transducer_stateless)) uses `Conformer` as its encoder network.
