### ISSUE TITLE
Slow code in joiner

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/icefall#232]
This line
https://github.com/k2-fsa/icefall/blob/05cb29785876b8594cc6be3d683a3da3f5c89c05/egs/librispeech/ASR/transducer_stateless/joiner.py#L53
could be a speed issue, because it does many independent GPU accesses in the loop.
(I am assuming that one of both of those lengths might be on the GPU; these args aren't documented, 
but pobably should be).
Probably the fix code-wise is to just copy them to CPU?

**Comment by csukuangfj** [comment]
I think I can figure out how to use torch.gather() to improve it.
