### ISSUE TITLE
Using raw audio samples as input features

### ISSUE THREAD

**Issue by mohsen-goodarzi** [k2-fsa/icefall#255]
Hi,
I am trying to do some experiment with wav2vec2 architectures. To do so I need to define the raw audio samples as features in CutSets, but I am not sure how to do that.
Can you please explain me what is the best practice to do that?

**Comment by csukuangfj** [comment]
You need to change
https://github.com/k2-fsa/icefall/blob/a7643301ecc7ca704b1fdc44b30b435fceda663f/egs/librispeech/ASR/tdnn_lstm_ctc/asr_datamodule.py#L244-L248

to

```python3
 train = K2SpeechRecognitionDataset( 
     cut_transforms=transforms, 
     input_transforms=input_transforms, 
     return_cuts=self.args.return_cuts, 
     input_strategy=AudioSamples()
 ) 
```

By default, it uses pre-computed features, see
https://github.com/lhotse-speech/lhotse/blob/master/lhotse/dataset/speech_recognition.py#L61
```python3
    def __init__(
        self,
        return_cuts: bool = False,
        cut_transforms: List[Callable[[CutSet], CutSet]] = None,
        input_transforms: List[Callable[[torch.Tensor], torch.Tensor]] = None,
        input_strategy: BatchIO = PrecomputedFeatures(),
    ):
```

If you change it to `AudioSamples()`, which is defined in 
https://github.com/lhotse-speech/lhotse/blob/master/lhotse/dataset/input_strategies.py#L176
```python3
class AudioSamples(BatchIO):
    """
    :class:`InputStrategy` that reads single-channel recordings, whose manifests
    are attached to cuts, from disk (or other audio source).
    It automatically zero-pads the recordings so that every example has the same number
    of audio samples as the longest cut in a mini-batch.
    This is needed to put all examples into a single tensor.
    .. automethod:: __call__
    """
```

the following line
https://github.com/k2-fsa/icefall/blob/a7643301ecc7ca704b1fdc44b30b435fceda663f/egs/librispeech/ASR/transducer_stateless/train.py#L399
returns a 2-D tensor of shape (B, T) that is defined by 
https://github.com/lhotse-speech/lhotse/blob/d91741113ebe9fd45c924c56e262d54a457f9d1b/lhotse/dataset/input_strategies.py#L211
```python3
    def __call__(
        self, cuts: CutSet
    ) -> Union[
        Tuple[torch.Tensor, torch.Tensor], Tuple[torch.Tensor, torch.Tensor, CutSet]
    ]:
        """
        Reads the audio samples from recordings on disk/other storage.
        The returned shape is ``(B, T) => (batch_size, num_samples)``.
        :return: a tensor with collated audio samples, and a tensor of ``num_samples`` of each cut before padding.
        """
```
