### ISSUE TITLE
Specifying Alignment in Supervision

### ISSUE THREAD

**Issue by teowenshen** [k2-fsa/icefall#257]
Hi, 

I noticed that Lhotse allows [specifying token alignment](https://lhotse.readthedocs.io/en/latest/_modules/lhotse/supervision.html) as part of the supervision , and that it is also handled in the [speech_recognition.py](https://github.com/lhotse-speech/lhotse/blob/f106fe4ccb07a7ecdbeb852192bd02eaa16acdaa/lhotse/dataset/speech_recognition.py#L152) of Lhotse. 

However, I cannot find how or where this labelled alignment is utilised in K2 before/after passed to the Conformer model. Can you point me towards the correct direction? 

Furthermore, if you have any literature on the topic to share, I will be grateful. 

Thanks.

**Comment by csukuangfj** [comment]
We are not using alignment information in training at present. The default alignment type in lhotse is word alignment; you may need framewise alignment information at the token level if you use BPE as modeling unit.

**Comment by teowenshen** [comment]
I see. Thank you for the clarification. 

If I manage to get framewise alignment information at the token level, (for example Aishell's Mandarin lang_char), can you point me in the correct direction towards where and how the alignment information can be utilised? 

My idea is to intercept the output of the Conformer and force the token at that labelled frame to be 1 and all other tokens to be 0, before passing to the intersection with the CTC graph. But, I am not sure about the pros and cons. 

I can't find any literature (scholarly or not) about this idea, but I am probably missing the technical term here.

**Comment by csukuangfj** [comment]
> can you point me in the correct direction towards where and how the alignment information can be utilised?

One possible way is to use framewise alignment information for cross-entropy training. Note that you have to disable time warping in SpecAugment.

**Comment by teowenshen** [comment]
Thanks for sharing your advice. 

Anyway, I will close this ticket now.
