### ISSUE TITLE
Is Search Graph HLG.pt in k2  similar to TLG.fst in eesen ?

### ISSUE THREAD

**Issue by Sundy1219** [k2-fsa/icefall#268]
Is Search Graph HLG.pt in k2  similar to TLG.fst in eesen ?

**Comment by csukuangfj** [comment]
Yes, you are right. However, there are differences in generating HLG.pt and TLG.fst, and you cannot simply replace HLG.pt with TLG.fst. For instance, there are no epsilon transitions in HLG.pt.

**Comment by Sundy1219** [comment]
what is the advantage of 'no epsilon transitions in HLG.pt' than that in eesen ?. Does you compare the differences between HLG.pt and TLG.fst such as recognition rate，search graph model size，decoder speed．

**Comment by csukuangfj** [comment]
No epsilon transitions simplifies the implementation. 

The recognition rate depends on your neural network model, I think.
As for the graph size, k2 removes epsilons from LG and there is no minimization, so the graph size is a little larger.

As for the decoding speed, k2 should be faster, as it runs on CUDA and also supports decoding in batches.

**Comment by Sundy1219** [comment]
ok, I see．your HLG.pt maybe similar to that in "https://github.com/thu-spmi/CAT" . it also removes epsilon transitions
