### ISSUE TITLE
Dependencies issue: lhotse cannot install torchaudio & possible API change

### ISSUE THREAD

**Issue by maxwellzh** [k2-fsa/icefall#276]
I follow the instruction [here](https://icefall.readthedocs.io/en/latest/installation/index.html) to install icefall.

When installing the dependency lhotse, for the two options:
> 1. pip install lhotse
> 2. pip install git+https://github.com/lhotse-speech/lhotse

With option1, lhotse can be installed, but torchaudio is not installed with it.
WIth option2, error is raised in installation
```
ValueError: We detected that you have already installed PyTorch, but haven't installed torchaudio. Unfortunately we can't detect the compatible torchaudio version for you; you will have to install it manually. For instructions, please refer either to https://pytorch.org/get-started/locally/ or https://github.com/pytorch/audio#dependencies
```

So possibly I think we should install `torchaudio` when installing `torch`.

And another issue, as I run `./prepare.sh` in `egs/yesno/ASR/`, there is an error:
```
2022-03-30 11:15:52 (prepare.sh:27:main) Stage 0: Download data
2022-03-30 11:15:52 (prepare.sh:36:main) Stage 1: Prepare yesno manifest
2022-03-30 11:15:57 (prepare.sh:42:main) Stage 2: Compute fbank for yesno
Traceback (most recent call last):
  File "./local/compute_fbank_yesno.py", line 83, in <module>
    compute_fbank_yesno()
  File "./local/compute_fbank_yesno.py", line 46, in compute_fbank_yesno
    FbankConfig(sampling_rate=8000, num_mel_bins=num_mel_bins)
TypeError: __init__() got an unexpected keyword argument 'sampling_rate'
```
Maybe it is due to the api change of lhotse.

**Comment by csukuangfj** [comment]
> WIth option2, error is raised in installation

Please use the second option. And install torch and torchaudio before you install lhotse.

**Comment by csukuangfj** [comment]
> And another issue, as I run ./prepare.sh in egs/yesno/ASR/, there is an error:

If you use the second option to install lhotse, then you won't have this error.

**Comment by maxwellzh** [comment]
> If you use the second option to install lhotse, then you won't have this error.

Yes, with torchaudio manually installed, data can be prepared successfully now.

And I think  the [installation guide](https://icefall.readthedocs.io/en/latest/installation/index.html#install-lhotse) needs a update  to tell users install lhotse from source instead of pypi and install torchaudio before lhotse.

**Comment by csukuangfj** [comment]
> > If you use the second option to install lhotse, then you won't have this error.
> 
> Yes, with torchaudio manually installed, data can be prepared successfully now.
> 
> And I think the [installation guide](https://icefall.readthedocs.io/en/latest/installation/index.html#install-lhotse) needs a update to tell users install lhotse from source instead of pypi and install torchaudio before lhotse.

Thanks for reporting. We just updated the installation page https://icefall.readthedocs.io/en/latest/installation/index.html
