### ISSUE TITLE
Mismatch initial condition of Transducer LSTM decoder of Librispeech egs

### ISSUE THREAD

**Issue by drawfish** [k2-fsa/icefall#324]
Hi guys! 
On training stage, the code use **sos_id** as the begining symbol of decoder inputs(see [here](https://github.com/k2-fsa/icefall/blob/3607c516d6512295ff50c7ba1ce9ca8c231f5782/egs/librispeech/ASR/transducer_lstm/model.py#L101)), but in decoding stage, the code use **blank_id** as the begining symbol of decoder inputs(see [here](https://github.com/k2-fsa/icefall/blob/3607c516d6512295ff50c7ba1ce9ca8c231f5782/egs/librispeech/ASR/transducer_lstm/beam_search.py#L41) and [here](https://github.com/k2-fsa/icefall/blob/3607c516d6512295ff50c7ba1ce9ca8c231f5782/egs/librispeech/ASR/transducer_lstm/beam_search.py#L119)).  This will lead to the problem that the training does not match the initial conditions of testing if sos_id != blank_id.
There is not pretrained model for Transducer LSTM(bpe model), but I evaluate these id with "icefall-asr-librispeech-transducer-stateless-bpe-500-2022-02-07" bpe model, it seems that sos_id and blank_id is really different (where sos_id = 1 and blank_id = 0).

This mismatch problem is found when I transfered Librispeech tarining and decoding code to our small internal dataset (about 1000 hours, just as Librispeech). And in our case, the mismatch would cause some deletion error at the begining of the decode result. After fix this bug, the recognition rate can be significantly improved.

So if you guys have a pretrained model, you can see if there is this mismatch problem in bpe_model and update the WER after fixing.

**Comment by danpovey** [comment]
Wow, that's great that you have found this!
I had a suspicion that we may have undiscovered bugs, as our WER results are not quite as good as I think they should be.

**Comment by csukuangfj** [comment]
Thanks!

Transducer LSTM is the first draft of RNN-T training and at that time I did not have a good understanding of RNN-T.

You can find in other transducer folders that there is no sos_id any longer.

**Comment by csukuangfj** [comment]
To be precise, there should be no sos/eos ID in the BPE modelling units for RNN-T training.

Since we are re-using the same BPE model from confromer_ctc, we keep the sos/eos ID in RNN-T, but it is never used
in RNN-T training except for `transducer_lstm`, which was a mistake, I think.

**Comment by drawfish** [comment]
Yes, in transducer_stateless setup, blank_id is used as initial symbol. Such mismatch problem only found in transducer_lstm.
