### ISSUE TITLE
Minor typos in librispeech transducer recipe.

### ISSUE THREAD

**Issue by whsqkaak** [k2-fsa/icefall#328]
Hello

I found some minor typos in Librispeech transducer recipe. 

https://github.com/k2-fsa/icefall/blob/5b6699a8354b70b23b252b371c612a35ed186ec2/egs/librispeech/ASR/transducer/decoder.py#L92-L94

https://github.com/k2-fsa/icefall/blob/1d44da845b264b3a24fadcc6af577055d399220d/egs/librispeech/ASR/transducer_lstm/decoder.py#L96-L98

https://github.com/k2-fsa/icefall/blob/95af0397336ac840a5bfed1ae8de79dbddcdad71/egs/yesno/ASR/transducer/decoder.py#L87-L89

I think `embeding_out` must be changed to `embedding_out`.

**Comment by csukuangfj** [comment]
Yes, you are right. Please make a PR if you have time.

**Comment by csukuangfj** [comment]
Closing via #329
