### ISSUE TITLE
logging not working for ddp training

### ISSUE THREAD

**Issue by pkufool** [k2-fsa/icefall#35]
Seems that logging module is not working when training with ddp for some particular pytorch version(I tried three versions, it works for torch 1.7.2, but not for 1.8.0, 1.8.1). 

I searched for a while and did not figure out how to fix it.

FYI.

**Comment by csukuangfj** [comment]
Please see 
https://github.com/k2-fsa/snowfall/pull/158#issuecomment-886193986

We have encountered such a problem before. I would recommend you to switch to torch 1.7.1

**Comment by pkufool** [comment]
Thanks, I did not notice the issue in snowfall.
I already switched to torch 1.7, just make others know.

**Comment by csukuangfj** [comment]
I think if you change `logging.info` to `logging.warn`, you will see the log.

This works for me when using `torch.distributed.launch` for multi-node multi-gpu training, with torch==1.9.0
