### ISSUE TITLE
failed to clone the icefall

### ISSUE THREAD

**Issue by cdxie** [k2-fsa/icefall#36]
hi, when I git clone the icefall（ git clone https://github.com/k2-fsa/icefall）, but falied:

fatal: unable to access 'https://github.com/k2-fsa/icefall/': gnutls_handshake() failed: The TLS connection was non-properly terminated.

**Comment by csukuangfj** [comment]
Are you using a proxy?

You can use Google to search the following error message

> gnutls_handshake() failed: The TLS connection was non-properly terminated.

and it will give you some suggestions.

**Comment by cdxie** [comment]
> Are you using a proxy?
> 
> You can use Google to search the following error message
> 
> > gnutls_handshake() failed: The TLS connection was non-properly terminated.
> 
> and it will give you some suggestions.

ok, I try another way,it is ok now,thanks
