### ISSUE TITLE
Empty or incomplete hypotheses when using non-trivial decoding graph (LG) in fast beam search (pruned_transducer_stateless2)

### ISSUE THREAD

**Issue by ahazned** [k2-fsa/icefall#403]
Hi,

I trained a model using egs/librispeech/ASR/pruned_transducer_stateless2 and decoding works fine with all the default search strategies in pruned_transducer_stateless2/decode.py: greedy_search, modified_beam_search and fast_beam_search (with trivial decoding graph)

But when I try to use LG.pt instead of the hardcoded trivial graph in fast_beam_search I often get empty or incomplete hypotheses (LG.pt is composed using local/compile_lg.py). Increasing beam helps to get better results as expected, but there are still to many empty/incomplete results. Maybe I need something like "allow partial results" in Kaldi's lattice generation. 

I wonder if anyone succeeded in using LG.pt with fast_beam_search and has a recommendation for getting better results. I know this sounds a little vague but I can also share some files if wanted. 

Thank you.

**Comment by pkufool** [comment]
Did you decode with `use-max=False`?  And if you are using librispeech dataset, the LG decoding results are expected to be worse than trivial graph because of the OOV words. see https://github.com/k2-fsa/icefall/pull/277.

**Comment by ahazned** [comment]
Thank you very much. I didn't look at the usage of fast_beam_search in `pruned_transducer_stateless/decode.py`. That solved my problem.
