### ISSUE TITLE
How to get exactly nbest?

### ISSUE THREAD

**Issue by yuekaizhang** [k2-fsa/icefall#432]
Hi,

When I am tryting to get nbest by k2.random_path(), after removing the paths with same word output, I always got valid paths smaller than num_path setting.

I was wondering if there is a way could make sure that I always get fixed number of hypos. If k2.shortest_path could give 1best, if it is possible to call functions like k2.top5shortest_path or something like that (https://www.openfst.org/twiki/bin/view/FST/ShortestPathDoc)? Maybe there is already a method I don't know, thanks.

**Comment by csukuangfj** [comment]
> When I am tryting to get nbest by k2.random_path(), after removing the paths with same word output, I always got valid paths smaller than num_path setting.

That is expected.

---

> I was wondering if there is a way could make sure that I always get fixed number of hypos.

You can use a larger number of num_paths for `k2.random_paths()`. You may also want to use `--nbest-scale=0.5` or some other value that we are using in icefall before calling `k2.random_paths()`.

---

>  If k2.shortest_path could give 1best, if it is possible to call functions like k2.top5shortest_path or something like that

Sorry, currently there is no such a method in k2.

**Comment by yuekaizhang** [comment]
> 

I see, thanks.
