### ISSUE TITLE
questions about composing LG

### ISSUE THREAD

**Issue by roysun2006** [k2-fsa/icefall#442]
compile_hlg.py in egs/aishell/ASR/local does a  compose(L, G) to get a LG.fst, but the scores in L_disambig.pt which are ln(p) (in the function lexicon_to_fst), the scores in G_3_gram.pt are -ln(p) (in the function arpa2fst), do I miss some operations in the k2 or icefall that deal with the scores in G_3_gram.pt?
I’d appreciate if anybody can help me! Thanks in advance!

**Comment by csukuangfj** [comment]
> the scores in G_3_gram.pt are -ln(p),

No, scores in `G_3_gram.pt` are `ln(p)`.

`G_3_gram.fst.txt` is using `-ln(p)`, but when it is converted to k2 format, we use `ln(p)`.

**Comment by csukuangfj** [comment]
Please pay attention to the suffixes of
- G_3_gram.fst.txt
- G_3_gram.pt

The first one is in openfst text format, while the second one is an FSA in k2 format serialized by PyTorch.

**Comment by roysun2006** [comment]
> 
thanks for your reply!
