### ISSUE TITLE
aishell prepare.sh failed when prepare G

### ISSUE THREAD

**Issue by Huren900** [k2-fsa/icefall#446]
when I run prepare.sh, I met error at stage 7
I had installed kaldilm
`2022-06-25 02:41:16 (prepare.sh:203:main) Stage 7: Prepare G
/usr/share/miniconda/envs/kaldilm/conda-bld/kaldilm_1654829205149/work/kaldilm/csrc/arpa_file_parser.cc:void kaldilm::ArpaFileParser::Read(std::istream&):112
[E] line 4 []: \data\ section missing or empty.
prepare.sh: 行 216: 25200 已放弃               (吐核)python -m kaldilm --read-symbol-table="$lang_phone_dir/words.txt" --disambig-symbol='#0' --max-order=3 $dl_dir/lm/3-gram.unpruned.arpa > data/lm/G_3_gram.fst.txt
`
can you help me ?

**Comment by csukuangfj** [comment]
What's the output of

head $dl_dir/lm/3-gram.unpruned.arpa

**Comment by Huren900** [comment]
> 
this is all
`version https://git-lfs.github.com/spec/v1
oid sha256:fd2b8d7d30f8dd0c1636b3f6cd3226254414561235613d2cd828d9276fe46e83
size 15245617
`

**Comment by Huren900** [comment]
> What's the output of
> 
> head $dl_dir/lm/3-gram.unpruned.arpa

I missed the git-lfs, after I install git-lfs, it work.
thanks!
