### ISSUE TITLE
one_sym_per_frame问题

### ISSUE THREAD

**Issue by piaohe111** [k2-fsa/icefall#457]
非常感谢开源！！！现在正在学习代码，目前有个问题，代码中训练transducer模型的时候用modified-transducer-prob动态调整one_sym_per_frame，但是用greedysearch解码的时候one_sym_per_frame设置的默认值3，问下这个是什么原因呢？我的理解是one_sym_per_frame对应不同的训练方式，解码时也会不一样吧。

**Comment by csukuangfj** [comment]
你看的是最新的代码吗？建议用pruned_transducer_starlessX

**Comment by piaohe111** [comment]
我看的是optimizer_transducer相关的代码，那我看看pruned_transducer_statelessX吧
