### ISSUE TITLE
Multi-GPU multi machine DDP training

### ISSUE THREAD

**Issue by ezerhouni** [k2-fsa/icefall#466]
According to https://icefall.readthedocs.io/en/latest/recipes/aishell/conformer_ctc.html , DDP multi gpu multi machines is not implemented yet. Is it still the case ? If so what would be the steps to add it ?
From what I saw, one needs to implement a ```torch.utils.data.distributed.DistributedSampler``` in lhotse similar to ```DynamicCutSampler```

**Comment by csukuangfj** [comment]
There is a PR supporting multi-node multi-GPU training with DDP, see https://github.com/k2-fsa/icefall/pull/63

One issue is that the communication overhead may dominate the training time when using multi-node multi-GPU training.

**Comment by csukuangfj** [comment]
> From what I saw, one needs to implement a torch.utils.data.distributed.DistributedSampler in lhotse similar to DynamicCutSampler

I don't think you need to implement a new sampler in lhotse. You can reuse `DynamicCutSampler` in the case
of multi-node multi-GPU training.

@pzelasko may have more to say on this.

**Comment by pzelasko** [comment]
Yeah, the existing samplers should support multi-node multi-GPU training. They auto-detect the world size and node rank, and you can also override them manually by providing `world_size` and `rank` arguments.

**Comment by ezerhouni** [comment]
Thanks @csukuangfj and @pzelasko I will have a look at the PR you mentioned
