### ISSUE TITLE
Duplicate fast-forwarding during restarting training from checkpoint

### ISSUE THREAD

**Issue by zzzacwork** [k2-fsa/icefall#473]
Hi all, 
I find when training is restarted, the fast-forwarding code is executed twice which causes some batches discarded unintentionally. 

First lhotse will fast-forward (skip) those many batches when loading sate dict from the checkpoint,
https://github.com/lhotse-speech/lhotse/blob/7cce647681cece04b40961fc378112d65aafbaa3/lhotse/dataset/sampling/dynamic_bucketing.py#L176-L191

Second inside `train.py`, the train_one_epoch` loop will also fast forward(skip) those many batches, 
https://github.com/k2-fsa/icefall/blob/f8d28f09987d44f017a8741f8dac84357c1da6d6/egs/librispeech/ASR/pruned_transducer_stateless2/train.py#L721-L723

I also noice that the `scan_pessimistic_batches_for_oom` function will also cause the `sampler` to skip batches, probably this function should only be called if we start the training from the beginning.

**Comment by luomingshuang** [comment]
Maybe we can change 
`if not params.print_diagnostics:` 
to 
`if params.print_diagnostics == False and params.start_epoch == 1 and params.start_batch == 0:` .

**Comment by danpovey** [comment]
@zzzacwork you might want to double check the code and see whether cur_batch_idx is actually nonzero in the code.
if it was skipping too much, it might be a bug in lhotse that was recently discussed on an issue there, some  interaction with multiple jobs.

**Comment by csukuangfj** [comment]
The `cur_batch_idx` was added when lhotse did not support resuming from a checkpoint.

I think everything related to `cur_batch_idx` can be safely removed when using the latest lhotse.

**Comment by zzzacwork** [comment]
> The `cur_batch_idx` was added when lhotse did not support resuming from a checkpoint.
> 
> I think everything related to `cur_batch_idx` can be safely removed when using the latest lhotse.

Yes, I fixed that locally and the only place I found `cur_batch_idx` still useful is at logging, 

https://github.com/k2-fsa/icefall/blob/c17233eca7d34c3f113abe6517c7e9ea1d74766a/egs/librispeech/ASR/pruned_transducer_stateless2/train.py#L778-L784

**Comment by zzzacwork** [comment]
> @zzzacwork you might want to double check the code and see whether cur_batch_idx is actually nonzero in the code. if it was skipping too much, it might be a bug in lhotse that was recently discussed on an issue there, some interaction with multiple jobs.

I did some tests to compare the checkpoints and found `cur_batch_idx` nonzero if we restart from the middle of an epoch. I already installed [the fix from lhotse](https://github.com/lhotse-speech/lhotse/pull/773)

**Comment by csukuangfj** [comment]
Closing via #421
