### ISSUE TITLE
HLG Exception

### ISSUE THREAD

**Issue by Andy-Lau-boy** [k2-fsa/icefall#474]
When I run ./local/compile_hlg.py --lang-dir $lang_phone_dir,it occur exception

Traceback (most recent call last):
  File "./local/compile_hlg.py", line 159, in <module>
    main()
  File "./local/compile_hlg.py", line 147, in main
    HLG = compile_HLG(lang_dir)
  File "./local/compile_hlg.py", line 108, in compile_HLG
    assert isinstance(LG.aux_labels, k2.RaggedTensor)
AssertionError

what should I fix it?

**Comment by luomingshuang** [comment]
This error means that your the type of `LG.aux_labels` is not `k2.RaggedTensor`.

**Comment by luomingshuang** [comment]
Maybe you can have a look at your `LG.aux_labels` by printing and be sure that `LG` is generated successfully.

**Comment by Andy-Lau-boy** [comment]
> Maybe you can have a look at your `LG.aux_labels` by printing and be sure that `LG` is generated successfully.

Ok,I will try.
Thank you

**Comment by csukuangfj** [comment]
Can you check that your G is not empty?

You can check its file size.

**Comment by Andy-Lau-boy** [comment]
> Can you check that your G is not empty?
> 
> You can check its file size.

Oh,I have checked it,it is empty.
My G is not generated successfully.
It run normally after I generated G successfully.
Thank you!
