### ISSUE TITLE
Failed to build k2

### ISSUE THREAD

**Issue by Andy-Lau-boy** [k2-fsa/icefall#476]
(kaldi2) root@interactive15077:/opt/data/private/Kaldi/k2# python3 setup.py install
cmake_path: /usr/bin/cmake
cmake version 3.10.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
running install
/root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing k2.egg-info/PKG-INFO
writing dependency_links to k2.egg-info/dependency_links.txt
writing requirements to k2.egg-info/requires.txt
writing top-level names to k2.egg-info/top_level.txt
reading manifest file 'k2.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'k2.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying k2/python/k2/torch_version.py -> build/lib.linux-x86_64-cpython-38/k2
copying k2/python/k2/__init__.py -> build/lib.linux-x86_64-cpython-38/k2
running build_ext
For fast compilation, run:
export K2_MAKE_ARGS="-j"; python setup.py install
Setting PYTHON_EXECUTABLE to /root/anaconda3/envs/kaldi2/bin/python3
build command is:

                cd build/temp.linux-x86_64-cpython-38

                cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=/root/anaconda3/envs/kaldi2/bin/python3 -DK2_ENABLE_BENCHMARK=OFF  -DK2_ENABLE_TESTS=OFF  -DCMAKE_INSTALL_PREFIX=/opt/data/private/Kaldi/k2/build/lib.linux-x86_64-cpython-38/k2  /opt/data/private/Kaldi/k2

                cat k2/csrc/version.h

                make  _k2 install
            
-- CMAKE_VERSION: 3.10.2
-- No NVCC detected. Disable CUDA support
-- Enabled languages: CXX
-- Set K2_ENABLE_NVTX to OFF since K2_WITH_CUDA is OFF
-- K2_OS: Ubuntu 18.04.5 LTS
-- C++ Standard version: 14
-- Could NOT find Valgrind (missing: Valgrind_INCLUDE_DIR Valgrind_EXECUTABLE) 
-- Downloading pybind11
-- pybind11 is downloaded to /opt/data/private/Kaldi/k2/build/temp.linux-x86_64-cpython-38/_deps/pybind11-src
-- pybind11 v2.6.0 
-- Found PythonInterp: /root/anaconda3/envs/kaldi2/bin/python3 (found version "3.8.13") 
-- Found PythonLibs: /root/anaconda3/envs/kaldi2/lib/libpython3.8.so
-- Python executable: /root/anaconda3/envs/kaldi2/bin/python3
-- The CUDA compiler identification is unknown
CMake Error at /root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:47 (enable_language):
  No CMAKE_CUDA_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.
Call Stack (most recent call first):
  /root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  cmake/torch.cmake:11 (find_package)
  CMakeLists.txt:279 (include)

-- Configuring incomplete, errors occurred!
See also "/opt/data/private/Kaldi/k2/build/temp.linux-x86_64-cpython-38/CMakeFiles/CMakeOutput.log".
See also "/opt/data/private/Kaldi/k2/build/temp.linux-x86_64-cpython-38/CMakeFiles/CMakeError.log".
/**
 * @brief
 * This file contains information for building k2, which is helpful
 * for describing the environment in which k2 is used when creating
 * an issue on GitHub.
 *
 * @copyright
 * Copyright (c)  2020  Mobvoi Inc.        (authors: Fangjun Kuang)
 *
 * @copyright
 * See LICENSE for clarification regarding multiple authors
 *
 * @caution
 * This file is auto-generated by CMake. Do NOT edit!
 * You can find it at build_dir/k2/csrc/version.h
 */

#ifndef K2_CSRC_VERSION_H_
#define K2_CSRC_VERSION_H_

namespace k2 {

// Version of k2 in "major.minor.patch" format
static constexpr const char *kVersion = "1.17";

// The commit used to build k2
static constexpr const char *kGitSha1 = "5954046db8b1305072c5f55914061b6ec87d4622";

// Date of the commit used to build k2
static constexpr const char *kGitDate = "Wed Jul 13 23:34:45 2022";

// Version of CUDA used to build k2.
// Its format is "major.minor", e.g., 10.1
static constexpr const char *kCudaVersion = "";

// cuDNN version, e.g., 8.0.2
static constexpr const char *kCudnnVersion = "";

// clang-format off
// Version of Python used to build k2 Python bindings.
static constexpr const char *kPythonVersion = "3.8";

// clang-format on

// CMake build type, e.g., Release or Debug.
static constexpr const char *kBuildType = "Release";

// The operating system that is used to build k2, e.g., Ubuntu 16.04 LTS
static constexpr const char *kOS = R"os(Ubuntu 18.04.5 LTS)os";

// e.g., 3.18.0
static constexpr const char *kCMakeVersion = "3.10.2";

// Version of the compiler, e.g., 5.4.0
static constexpr const char *kGCCVersion = "7.5.0";

// CUDA flags used to compile k2
static constexpr const char *kCMakeCudaFlags = R"cuda_flags()cuda_flags";

// CXX flags used to compile k2
static constexpr const char *kCMakeCxxFlags = R"cxx_flags( -D_GLIBCXX_USE_CXX11_ABI=1 -Wno-unused-variable  -Wno-strict-overflow )cxx_flags";

// Which PyTorch version k2 is using, e.g., 1.6.0+cu101
static constexpr const char *kTorchVersion = "1.7.1.post2";

// Which CUDA version PyTorch is using, e.g., 10.1
static constexpr const char *kTorchCudaVersion = "";

#ifndef K2_WITH_CUDA
/* #undef K2_WITH_CUDA */
#endif

#ifdef K2_WITH_CUDA
  static constexpr bool kWithCuda = true;
#else
  static constexpr bool kWithCuda = false;
#endif

// Indicate whether NVTX is enabled or not
#ifndef K2_ENABLE_NVTX
/* #undef K2_ENABLE_NVTX */
#endif

#ifdef K2_ENABLE_NVTX
static constexpr bool kEnableNvtx = true;
#else
static constexpr bool kEnableNvtx = false;
#endif
}  // namespace k2

#endif  //  K2_CSRC_VERSION_H_
-- CMAKE_VERSION: 3.10.2
-- No NVCC detected. Disable CUDA support
-- Enabled languages: CXX
-- Set K2_ENABLE_NVTX to OFF since K2_WITH_CUDA is OFF
-- K2_OS: Ubuntu 18.04.5 LTS
-- C++ Standard version: 14
-- Could NOT find Valgrind (missing: Valgrind_INCLUDE_DIR Valgrind_EXECUTABLE) 
-- Downloading pybind11
-- pybind11 is downloaded to /opt/data/private/Kaldi/k2/build/temp.linux-x86_64-cpython-38/_deps/pybind11-src
-- pybind11 v2.6.0 
-- Python executable: /root/anaconda3/envs/kaldi2/bin/python3
-- The CUDA compiler identification is unknown
CMake Error at /root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:47 (enable_language):
  No CMAKE_CUDA_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.
Call Stack (most recent call first):
  /root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  cmake/torch.cmake:11 (find_package)
  CMakeLists.txt:279 (include)

-- Configuring incomplete, errors occurred!
See also "/opt/data/private/Kaldi/k2/build/temp.linux-x86_64-cpython-38/CMakeFiles/CMakeOutput.log".
See also "/opt/data/private/Kaldi/k2/build/temp.linux-x86_64-cpython-38/CMakeFiles/CMakeError.log".
Makefile:252: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
Traceback (most recent call last):
  File "setup.py", line 198, in <module>
    setuptools.setup(
  File "/root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 177, in setup
    return run_commands(dist)
  File "/root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
    dist.run_commands()
  File "/root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
    self.distribution.run_command(command)
  File "/root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
    self.distribution.run_command(command)
  File "/root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "/root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
    self.distribution.run_command(command)
  File "/root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 459, in build_extensions
    self._build_extensions_serial()
  File "/root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 485, in _build_extensions_serial
    self.build_extension(ext)
  File "setup.py", line 171, in build_extension
    raise Exception('Failed to build k2')
Exception: Failed to build k2

**Comment by csukuangfj** [comment]
How did you install the cudatoolkit?

**Comment by Andy-Lau-boy** [comment]
> How did you install the cudatoolkit?

conda install pytorch  torchaudio cudatoolkit=10.2 -c pytorch

**Comment by csukuangfj** [comment]
What is the output of 
```
nvcc --version
```

**Comment by csukuangfj** [comment]
From your error logs:

> -- No NVCC detected. Disable CUDA support
>
> -- The CUDA compiler identification is unknown
CMake Error at /root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:47 (enable_language):
> No CMAKE_CUDA_COMPILER could be found.
>
> Tell CMake where to find the compiler by setting either the environment
variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
path to the compiler, or to the compiler name if it is in the PATH.

it shows cudatoolkit is not installed correctly.

**Comment by Andy-Lau-boy** [comment]
> From your error logs:
> 
> > -- No NVCC detected. Disable CUDA support
> > -- The CUDA compiler identification is unknown
> > CMake Error at /root/anaconda3/envs/kaldi2/lib/python3.8/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:47 (enable_language):
> > No CMAKE_CUDA_COMPILER could be found.
> > Tell CMake where to find the compiler by setting either the environment
> > variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
> > path to the compiler, or to the compiler name if it is in the PATH.
> 
> it shows cudatoolkit is not installed correctly.

I re-install cudatoolkit,I can insatll k2 succesfully.
Thanks a lot
