### ISSUE TITLE
No module named 'optimized_transducer'

### ISSUE THREAD

**Issue by wqn628** [k2-fsa/icefall#491]
hi~, after installing K2, lhotse and Icefall, I go to aishell/ASR， and run commandings as follows:

“export CUDA_VISIBLE_DEVICES="5,6,7"

./transducer_stateless_modified/train.py \
  --world-size 3 \
  --num-epochs 65 \
  --start-epoch 0 \
  --exp-dir transducer_stateless_modified/exp \
  --max-duration 250 \
  --lr-factor 2.0 \
  --context-size 2 \
  --modified-transducer-prob 0.25”
but error has occured as follows:
  File "/data/mnt/k2/icefall/egs/aishell/ASR/transducer_stateless_modified/model.py", line 120, in forward
    import optimized_transducer
ModuleNotFoundError: No module named 'optimized_transducer'
i have no idea where the optimized_transducer is..
Any help will be appreciated

**Comment by csukuangfj** [comment]
You can install it by
```
pip install optimized_transducer
```

I suggest trying pruned RNN-T loss, which is faster and consumes less memory. It does not require `optimized_transducer`.
https://github.com/k2-fsa/icefall/tree/master/egs/aishell/ASR/pruned_transducer_stateless3

**Comment by wqn628** [comment]
> You can install it by
> 
> ```
> pip install optimized_transducer
> ```
> 
> I suggest trying pruned RNN-T loss, which is faster and consumes less memory. It does not require `optimized_transducer`. https://github.com/k2-fsa/icefall/tree/master/egs/aishell/ASR/pruned_transducer_stateless3

thanks a lot.
i just have a try.
i will trying   pruned RNN-T  loss at once.
