### ISSUE TITLE
eval2000 decoding error with pretrained gigaspeech model

### ISSUE THREAD

**Issue by shaynemei** [k2-fsa/icefall#502]
When decoding eval2000 testset with the pretrained model [here](https://huggingface.co/wgb14/icefall-asr-gigaspeech-pruned-transducer-stateless2), I got this AssertionError. The recordings and supervisions are prepared from kaldi files (wav.scp, text, segments) using `lohtse.utils.load_kaldi_data_dir()`, and the features are computed with almost identical script to [this](https://github.com/k2-fsa/icefall/blob/master/egs/gigaspeech/ASR/local/compute_fbank_gigaspeech_dev_test.py)

![snap 2022-07-27 at 12 20 31 PM](https://user-images.githubusercontent.com/31003116/181362031-033b05af-b61e-40a2-94da-31b2c9cb4139.png)

OS: Ubuntu 20.04.3
k2: 1.17.dev20220725+cuda10.2.torch1.7.1
lhotse: 1.4.0
python: 3.8.10

**Comment by csukuangfj** [comment]
Is it the same issue as https://github.com/lhotse-speech/lhotse/issues/780#issuecomment-1197550153 ?

**Comment by shaynemei** [comment]
This error happened after I commented out that check in https://github.com/lhotse-speech/lhotse/blob/dc5aa88b53adb73c20e3bf7210742ec3a25c809c/lhotse/qa.py#L213-L216

But It could be related. I'll try out the `LHOTSE_AUDIO_DURATION_MISMATCH_TOLERANCE` as suggested and report back. 

Also, in another local audio file decoding, I ran into a very similar error:
![snap 2022-07-27 at 12 25 13 PM](https://user-images.githubusercontent.com/31003116/181408601-a7562c9e-0d86-466d-95c6-d39ea9f82aa0.png)
And i was able to solve it by slightly reducing the `end_time` by 0.01s for each segment in the kaldi `segments` file.

**Comment by pzelasko** [comment]
Can you try running `lhotse fix <recordings> <supervisions> <outdir>` on the manifests after Kaldi import, and then re-create the CutSet and start the training? It might just fix your issue. It's also available as a Python function:

https://github.com/lhotse-speech/lhotse/blob/dc5aa88b53adb73c20e3bf7210742ec3a25c809c/lhotse/qa.py#L42-L44

**Comment by shaynemei** [comment]
thank you, the `lohtse fix` worked like a charm.

However, when I tried adding the python function to the pipeline (inserted between `load_kaldi_data_dir()` and saving manifests to file) as follows:
```python
def generate_cutset_from_kaldi(kaldi_data_dir: str, output_dir: str, sample_rate: int = 16000, num_workers : int = 20, batch_dur : int = 600):
    # generate manifests dir (containing recordings.json and supervisions.json) from kaldi data dir
    dataset_name = Path(kaldi_data_dir).name
    manifests_dir = Path(__file__).parents[1] / f"data/manifests/{dataset_name}"
    manifests_dir.mkdir(exist_ok=True)
    # TODO: quick fix: use local modified version with num_samples calculated from sample rate and duration
    recordings, supervisions = load_kaldi_data_dir(kaldi_data_dir, sample_rate)
    recordings_fixed, recordings_fixed = fix_manifests(recordings=recordings, supervisions=supervisions)
    recordings_fixed.to_file(manifests_dir / f"recordings_{dataset_name}.jsonl.gz")
    recordings_fixed.to_file(manifests_dir / f"supervisions_{dataset_name}.jsonl.gz")

    # generate raw CutSets (containing <dataset_name>.jsonl.gz) from manifests dir
    cutset_dir = Path(output_dir) / dataset_name
    manifests_to_cutsets(manifests_dir, cutset_dir, dataset_name)

    ## compute fbank for CutSet
    compute_fbank(cutset_dir, num_workers, batch_dur)
```

I got an error:
![snap 2022-07-28 at 1 19 49 PM](https://user-images.githubusercontent.com/31003116/181630329-fa905e15-b0fc-41f3-a89b-2e765654e749.png)

Comparing the python function you posted and the CLI call here https://github.com/lhotse-speech/lhotse/blob/177ce3a6b963d4ac56a87843a0130ccfc74b3a57/lhotse/bin/modes/validate.py#L52 I can't really tell why this is happening.

**Comment by pzelasko** [comment]
Great! Closing the issue.

**Comment by pzelasko** [comment]
I'll leave the `lhotse fix` thing up to the recipe writers, but I definitely recommend using at least `lhotse validate` everywhere.
