### ISSUE TITLE
Is it a wrong file name?

### ISSUE THREAD

**Issue by JaheimLee** [k2-fsa/icefall#505]
S subset name seems has an extra name "test", but L and M subset doesn't.
https://github.com/k2-fsa/icefall/blob/f26b62ac006c6486a01c4af1542b7ef5eed61730/egs/wenetspeech/ASR/prepare.sh#L102

**Comment by csukuangfj** [comment]
@JaheimLee 
Yes, I think you are right.

The following code assumes that the name is `S_split_${num_splits}`. We should remove `_test`.
https://github.com/k2-fsa/icefall/blob/3c9e7f733b92c844d4dcac18f137f962ae8737be/egs/wenetspeech/ASR/local/compute_fbank_wenetspeech_splits.py#L96

Could you make a PR to do that?

cc @luomingshuang

**Comment by luomingshuang** [comment]
Oh，sorry. You're right. Thanks.
