### ISSUE TITLE
Explicit relative imports

### ISSUE THREAD

**Issue by shaynemei** [k2-fsa/icefall#508]
I would recommend that we use explicit relative imports as recommended by Guido: 
https://peps.python.org/pep-0328/#guido-s-decision

This will make the imports more readable and can avoid import issues especially in downstream applications when setting icefall up as a submodule in other repos.

For example:
https://github.com/k2-fsa/icefall/blob/2f75236c05d38fb52bceb14e77ac104952e856cc/egs/gigaspeech/ASR/pruned_transducer_stateless2/train.py#L59

This should be written as `from .asr_datamodule import GigaSpeechAsrDataModule`

**Comment by csukuangfj** [comment]
We are using relative import in `icefall/__init__.py`.

Yes, I agree that we should also use relative import in `xxx/train.py`.

**Comment by shaynemei** [comment]
it looks like all the scripts in the gigaspeech recipe are using not using explicit relative imports. I can make a PR to update the imports.

**Comment by csukuangfj** [comment]
> it looks like all the scripts in the gigaspeech recipe are using not using explicit relative imports. I can make a PR to update the imports.

Thanks. I think all the recipes are not using relative imports. 

If you are making a PR, would mind also updating other recipes?

**Comment by shaynemei** [comment]
@csukuangfj Sure! made a PR
