### ISSUE TITLE
using TPUs in Colab ??

### ISSUE THREAD

**Issue by jty016** [k2-fsa/icefall#53]
I'm working on and trying to train Zeroth Korean dataset with `tdnn_lstm_ctc` and `conformer_ctc`. But, unfortunately, I think  I will suffer from GPU memory shortage for a while before I updated GPUs in my data center.

Do you think I can try this icefall recipes (training) on Google Colab with multiple TPU env? It looks like needed slight code modification. 

By the way, I really appreciate about this Icefall open source work. It is now much better to use then Snowfall before. Thank you all!

**Comment by csukuangfj** [comment]
> Do you think I can try this icefall recipes (training) on Google Colab with multiple TPU env?

Conformer CTC training with full-librispeech may take several days on 3 NVIDIA v100 GPUs (with 32 GB RAM).
I don't think Colab allows you to train your model for that long without paying.
So I am not sure if it is worth the effort to modify the code to support running the training part on TPU using a Colab notebook.

---

The GPU in Colab has too little memory to run decoding with LM rescoring and we have to pay some money to upgrade to Colab Pro to do that.
If TPUs in Colab notebook has larger RAM supporting decoding with LM rescoring, I think it's useful to add TPU support to the decoding script.  Unfortunately, we don't have time to do that. Would be great if you could contribute.

**Comment by jty016** [comment]
@csukuangfj of course I'll use paid service for TPU if it is needed. Okay, I will try and get back to you with PR if it is works.
