### ISSUE TITLE
tedlium3 prepare.sh FileNotFoundError

### ISSUE THREAD

**Issue by shcxlee** [k2-fsa/icefall#566]
I am trying to download and train tedlium recipe, but I cannot successfully run prepare.sh

2022-09-06 21:38:54 (prepare.sh:51:main) Stage 0: Download data
2022-09-06 21:38:54 (prepare.sh:74:main) Stage 1: Prepare tedlium3 manifests
2022-09-06 21:38:54 (prepare.sh:85:main) Stage 2: Prepare musan manifests
2022-09-06 21:38:54 (prepare.sh:96:main) Stage 3: Compute fbank for tedlium3
2022-09-06 21:38:54 (prepare.sh:106:main) Stage 4: Compute fbank for musan
2022-09-06 21:38:54 (prepare.sh:115:main) Stage 5: Prepare phone based lang
2022-09-06 21:38:54,348 INFO [prepare_transcripts.py:84] Generating train.text
2022-09-06 21:38:54,348 INFO [prepare_transcripts.py:66] Loading data/manifests/supervisions_train.json!
Traceback (most recent call last):
  File "/icefall/egs/tedlium3/ASR/./local/prepare_transcripts.py", line 95, in <module>
    main()
  File "/icefall/egs/tedlium3/ASR/./local/prepare_transcripts.py", line 85, in main
    prepare_transcripts(manifests_dir, lang_dir)
  File "/icefall/egs/tedlium3/ASR/./local/prepare_transcripts.py", line 67, in prepare_transcripts
    with open(supervisions_train, "r") as load_f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/manifests/supervisions_train.json'

How can I fix this error?

**Comment by csukuangfj** [comment]
Please use
```
ls -lh data/manifests
```
to find the exact name for  `supervisions_train.json` and replace the one used in
`prepare_transcripts.py:66`.

**Comment by csukuangfj** [comment]
The code is outdated. After you fix it, would you mind creating a PR for it?

**Comment by shcxlee** [comment]
12K Aug 15 15:18 musan_recordings_music.jsonl.gz
15K Aug 15 15:18 musan_recordings_noise.jsonl.gz
6.0K Aug 15 15:18 musan_recordings_speech.jsonl.gz
9.5K Aug 15 15:18 musan_supervisions_music.jsonl.gz
488 Aug 15 15:17 tedlium_recordings_dev.jsonl.gz
570 Aug 15 15:17 tedlium_recordings_test.jsonl.gz
67K Aug 15 15:17 tedlium_recordings_train.jsonl.gz
44K Aug 15 15:17 tedlium_supervisions_dev.jsonl.gz
72K Aug 15 15:17 tedlium_supervisions_test.jsonl.gz
14M Aug 15 15:17 tedlium_supervisions_train.jsonl.gz

This is the list I got when I use `ls -lh data/manifests`. I guess "tedlium_supervisions_train.jsonl.gz" is the corresponding file.
Should I extract this before replacing it?

PS: Just to be clear, if PR stands for a pull request, yes I can make a pull request after fixing this issue.

**Comment by csukuangfj** [comment]
> Should I extract this before replacing it?

No, you don't need to extract it.

please change the following code to
https://github.com/k2-fsa/icefall/blob/e18fa78c3a010fac4e6d3e83bdcff28197df04dc/egs/tedlium3/ASR/local/prepare_transcripts.py#L63-L71

to
```python3
import lhotse # move this line to the beginning of the file


train_text = Path(lang_dir) / "train.text" 
sups = lhotse.load_manifest("data/manifests/tedlium_recordings_train.jsonl.gz")
for s in sups:
  texts.append(s.text)
```

**Comment by csukuangfj** [comment]
Also, I think you can remove the variable `texts` and write `s.text` to the file directly.

**Comment by csukuangfj** [comment]
> PS: Just to be clear, if PR stands for a pull request, yes I can make a pull request after fixing this issue.

Yes, please create a pull-request to fix it.

Thanks!

**Comment by shcxlee** [comment]
(prepare.sh:115:main) Stage 5: Prepare phone based lang
INFO [prepare_transcripts.py:88] Generating train.text
Traceback (most recent call last):
  File "/icefall/egs/tedlium3/ASR/./local/prepare_transcripts.py", line 99, in <module>
    main()
  File "/icefall/egs/tedlium3/ASR/./local/prepare_transcripts.py", line 89, in main
    prepare_transcripts(manifests_dir, lang_dir)
  File "/icefall/egs/tedlium3/ASR/./local/prepare_transcripts.py", line 68, in prepare_transcripts
    texts.append(s.text)
AttributeError: 'Recording' object has no attribute 'text'

Ok now I am getting this error...

**Comment by csukuangfj** [comment]
Sorry, I have updated the code, please use
```python3
sups = lhotse.load_manifest(f"{manifests_dir}/tedlium_supervisions_train.jsonl.gz")
```

**Comment by shcxlee** [comment]
What is the difference between that and the third line of this code? They look the same to me.

```python
import lhotse # move this line to the beginning of the file


train_text = Path(lang_dir) / "train.text" 
sups = lhotse.load_manifest(f"{manifests_dir}/tedlium_supervisions_train.jsonl.gz")
for s in sups:
  texts.append(s.text)
```

**Comment by csukuangfj** [comment]
I was using `tedlium_recordings_train`, not `tedlium_supervisions_train`.

**Comment by csukuangfj** [comment]
You can check the edit history.
<img width="580" alt="Screen Shot 2022-09-08 at 12 35 09 PM" src="https://user-images.githubusercontent.com/5284924/189035167-397d464c-8d35-4cc1-a278-acc3206f3c06.png">

**Comment by shcxlee** [comment]
I see. Now I am getting this error message:

(prepare.sh:115:main) Stage 5: Prepare phone based lang
INFO [prepare_transcripts.py:88] Generating train.text
INFO [prepare_transcripts.py:70] Loading data/manifests/supervisions_train.json!
Traceback (most recent call last):
  File "/icefall/egs/tedlium3/ASR/./local/prepare_transcripts.py", line 99, in <module>
    main()
  File "/icefall/egs/tedlium3/ASR/./local/prepare_transcripts.py", line 89, in main
    prepare_transcripts(manifests_dir, lang_dir)
  File "/icefall/egs/tedlium3/ASR/./local/prepare_transcripts.py", line 71, in prepare_transcripts
    with open(supervisions_train, "r") as load_f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/manifests/supervisions_train.json'

**Comment by csukuangfj** [comment]
Could you show your changes, i.e., the output of git diff?

**Comment by shcxlee** [comment]
```
diff --git a/egs/tedlium3/ASR/local/prepare_transcripts.py b/egs/tedlium3/ASR/local/prepare_transcripts.py
index 416264e..f867b4d 100755
--- a/egs/tedlium3/ASR/local/prepare_transcripts.py
+++ b/egs/tedlium3/ASR/local/prepare_transcripts.py
@@ -23,6 +23,7 @@ consisting of supervisions_train.json and does the following:
 1. Generate train.text.

 """
+import lhotse
 import argparse
 import json
 import logging
@@ -62,6 +63,9 @@ def prepare_transcripts(manifests_dir: str, lang_dir: str):

     supervisions_train = Path(manifests_dir) / "supervisions_train.json"
     train_text = Path(lang_dir) / "train.text"
+    sups = lhotse.load_manifest(f"{manifests_dir}/tedlium_supervisions_train.jsonl.gz")
+    for s in sups:
+       texts.append(s.text)

     logging.info(f"Loading {supervisions_train}!")
     with open(supervisions_train, "r") as load_f:
```

**Comment by csukuangfj** [comment]
> > Should I extract this before replacing it?
> 
> 
> 
> No, you don't need to extract it.
> 
> 
> 
> please change the following code to
> 
> https://github.com/k2-fsa/icefall/blob/e18fa78c3a010fac4e6d3e83bdcff28197df04dc/egs/tedlium3/ASR/local/prepare_transcripts.py#L63-L71
> 
> 
> 
> to
> 
> ```python3
> 
> import lhotse # move this line to the beginning of the file
> 
> 
> 
> 
> 
> train_text = Path(lang_dir) / "train.text" 
> 
> sups = lhotse.load_manifest(f"{manifests_dir}/tedlium_supervisions_train.jsonl.gz")
> 
> for s in sups:
> 
>   texts.append(s.text)
> 
> ```

Please see the above comments. You have not DELETED the original code yet.

**Comment by shcxlee** [comment]
I see. Thanks!
Now I am having an issue with prepare_lexicon.py...
````
INFO [prepare_lexicon.py:66] Loading data/manifests/supervisions_train.json!
Traceback (most recent call last):
  File "/icefall/egs/tedlium3/ASR/./local/prepare_lexicon.py", line 100, in <module>
    main()
  File "/icefall/egs/tedlium3/ASR/./local/prepare_lexicon.py", line 90, in main
    prepare_lexicon(manifests_dir, lang_dir)
  File "/icefall/egs/tedlium3/ASR/./local/prepare_lexicon.py", line 67, in prepare_lexicon
    with open(supervisions_train, "r") as load_f:
````

**Comment by shcxlee** [comment]
Do you think it will be helpful to create a PR before fixing prepare_lexicon.py?

**Comment by csukuangfj** [comment]
> Now I am having an issue with prepare_lexicon.py...

That is the same issue. Could you change its code by following https://github.com/k2-fsa/icefall/issues/566#issuecomment-1240197489 ?

----

>  Do you think it will be helpful to create a PR before fixing prepare_lexicon.py?

I suggest that you create a PR to fix both of them as they have the same issue.

**Comment by shcxlee** [comment]
I edited `prepare_lexion.py` regarding the changes that I made in `prepare_transcripts.py` and it seems like it works! I will create a PR soon. Thank you very much for your help!
