### ISSUE TITLE
lstm-transducer model for Chinese data

### ISSUE THREAD

**Issue by lucasjinreal** [k2-fsa/icefall#576]
<img width="283" alt="image" src="https://user-images.githubusercontent.com/21303438/191680295-3c33215f-eeda-4f83-aba1-1b95c6e59204.png">

Does there a lstm-transducer eg for Any Chinese dataset?

**Comment by csukuangfj** [comment]
Yes, please see

https://k2-fsa.github.io/sherpa/python/streaming_asr/lstm/index.html#chinese

**Comment by csukuangfj** [comment]
And here is the demo using the above Chinese model.

https://k2-fsa.github.io/sherpa/python/streaming_asr/endpointing.html#endpointing-demo-chinese

**Comment by csukuangfj** [comment]
> Does there a lstm-transducer eg for Any Chinese dataset?

We will upload the code soon.

**Comment by jinfagang** [comment]
OK. hoping for it. BTW, does wenet speech dataset is currently most accurate model for daily life voice recognition?

**Comment by csukuangfj** [comment]
I think Wenetspeech is the largest open-source Chinese dataset so far, to the best of my knowledge.
