### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by KajiMaCN** [k2-fsa/icefall#589]
D:\Anaconda3\envs\icefall\python.exe "D:\PyCharm Projects\icefall\egs\aishell\ASR\conformer_ctc\train.py" 
Traceback (most recent call last):
  File "D:\PyCharm Projects\icefall\egs\aishell\ASR\conformer_ctc\train.py", line 29, in <module>
    from asr_datamodule import AishellAsrDataModule
  File "D:\PyCharm Projects\icefall\egs\aishell\ASR\conformer_ctc\asr_datamodule.py", line 1
    ../tdnn_lstm_ctc/asr_datamodule.py
    ^
SyntaxError: invalid syntax

**Comment by csukuangfj** [comment]
I think the error is due to that windows does not support symlinks.

You can do

```bash
cd "D:\PyCharm Projects\icefall\egs\aishell\ASR"
cp tdnn_lstm_ctc/asr_datamodule.py conformer_ctc/
```

By the way, it is a good practice to not use `blanks` when naming your directories or files.

**Comment by KajiMaCN** [comment]
> 



> I think the error is due to that windows does not support symlinks.
> 
> You can do
> 
> ```shell
> cd "D:\PyCharm Projects\icefall\egs\aishell\ASR"
> cp tdnn_lstm_ctc/asr_datamodule.py conformer_ctc/
> ```
> 
> By the way, it is a good practice to not use `blanks` when naming your directories or files.

Yes, thanks for the advice, when I removed the `blanks` I feel much better, but I have another problem with [#587](https://github.com/k2-fsa/icefall/issues/587#issue-1387217292), can you help with that please?

**Comment by csukuangfj** [comment]
Please wait a moment, I am proposing a fix.

**Comment by KajiMaCN** [comment]
Here is another solution, using another piece of code as an example.

from label_smoothing import LabelSmoothingLoss

change to:

from egs.librispeech.ASR.conformer_ctc.label_smoothing import LabelSmoothingLoss
