### ISSUE TITLE
prepare error

### ISSUE THREAD

**Issue by KajiMaCN** [k2-fsa/icefall#590]
The program is difficult to use on Windows and the problem is as follows:

(icefall) PS D:\PyCharmProjects\icefall\egs\aishell\ASR> bash prepare.sh
prepare.sh: line 2: $'\r': command not found
: invalid option nameet: pipefail

**Comment by KajiMaCN** [comment]
When I saved prepare.sh to unix format using text software, the following message still appeared:
(icefall) PS D:\PyCharmProjects\icefall\egs\aishell\ASR> bash prepare.sh
parse_options.sh: line 5: $'\r': command not found
parse_options.sh: line 18: $'\r': command not found
parse_options.sh: line 19: $'\r': command not found
parse_options.sh: line 26: $'\r': command not found
parse_options.sh: line 27: $'\r': command not found
parse_options.sh: line 32: $'\r': command not found
parse_options.sh: line 34: syntax error near unexpected token `$'do\r''
'arse_options.sh: line 34: `for ((argpos=1; argpos<$#; argpos++)); do

**Comment by csukuangfj** [comment]
I think Windows handles line return differently from macos/Linux.

We have never tested ./prepare.sh on Windows.

Re-save it on Windows may fix your issue.

**Comment by KajiMaCN** [comment]
> 

You are right, I am ready to give up using icefall on Windows and Linux is probably the best option at the moment.
