### ISSUE TITLE
Loading Grammar FST fails - syntax error in input

### ISSUE THREAD

**Issue by ngoel17** [k2-fsa/icefall#599]
Here is the error message I get -- 
2022-10-04 01:24:25,182 INFO [compile_hlg.py:73] Loading G_3_gram.fst.txt
[F] /home/ngoel-00171/k2/k2/csrc/fsa_utils.cu:295:void k2::OpenFstStreamReader::ProcessLine(std::string&) Invalid line: 5	14548	154377	0, eof=true, fail=true, src
_state=5, dest_state=14548

[ Stack-Trace: ]
/home/ngoel-00171/k2/build_release/lib/libk2_log.so(k2::internal::GetStackTrace[abi:cxx11]()+0x5d) [0x7f1004ef58ed]
/home/ngoel-00171/k2/build_release/lib/libk2context.so(k2::internal::Logger::~Logger()+0x5a) [0x7f1005420cda]
/home/ngoel-00171/k2/build_release/lib/libk2context.so(k2::OpenFstStreamReader::ProcessLine(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >
&)+0x939) [0x7f1005536a49]

the line 
5 14548 154377 0 is the first line in G_3_gram.fst.txt that has only 4 columns. The 5th column in the FST if missing should be assumed to be zero, but I am getting a syntax error. 
It's not clear to me if the input needs to be corrected to ensure 5 columns for each row, or if the k2 FSA version that I am using is 
outdate.

**Comment by csukuangfj** [comment]
Could you use the latest k2? It should have been fixed in the latest master.

**Comment by ngoel17** [comment]
thanks
