### ISSUE TITLE
sacling convert skip ScaledLinear in self-attention?

### ISSUE THREAD

**Issue by kobenaxie** [k2-fsa/icefall#634]
Hi, why not convert ScaledLinear in self_attention ?
https://github.com/k2-fsa/icefall/blob/499ac24ecba64f687ff244c7d66baa5c222ecf0f/egs/librispeech/ASR/pruned_transducer_stateless3/scaling_converter.py#L287

**Comment by csukuangfj** [comment]
Because of the following lines:
https://github.com/k2-fsa/icefall/blob/499ac24ecba64f687ff244c7d66baa5c222ecf0f/egs/librispeech/ASR/pruned_transducer_stateless2/conformer.py#L990-L991

**Comment by kobenaxie** [comment]
oh, thanks~
