### ISSUE TITLE
How to test audio files with model trained on Gigaspeech

### ISSUE THREAD

**Issue by WangHelin1997** [k2-fsa/icefall#651]
Hi authors,

Do you have any suggestions about how to test audio files with model trained on Gigaspeech (you provided)? Thanks so much.

**Comment by csukuangfj** [comment]
There are multiple ways. You can choose either of them.

1. Go to https://huggingface.co/spaces/k2-fsa/automatic-speech-recognition
this approach is the simplest one. You only need a browser.

2. Use pretrained.py
Unfortunately, there is no `pretrained.py` in gigapseech folder. Normally, there will be a pretraniend.py
in each folder, e.g., librispeech, that you can use to decode waves with a pretrained model.

3. Use https://github.com/k2-fsa/sherpa/blob/master/sherpa/bin/pruned_transducer_statelessX/offline_asr.py
it also takes a pretrained model as input to decode wave files. You can find detailed usages inside the file.

4. There are also c++ binaries from https://github.com/k2-fsa/sherpa that you can use.
Please read the doc of sherpa for more details.
