### ISSUE TITLE
Recommended model for 15K hours data

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#658]
Hello,

I see that in LibriSpeech examples there are many different architectures. What architecture do you recommend to use for the case of 15,000 hours of data?

Thanks,
AlexG.

**Comment by csukuangfj** [comment]
Do you need a streaming model?

**Comment by userasrk2** [comment]
Can you please recommend models/recipes for both streaming and offline cases?

**Comment by csukuangfj** [comment]
> Can you please recommend models/recipes for both streaming and offline cases?

For the offline case, I suggest `pruned_transducer_stateless7`, which uses zipformer.

For the streaming case, I suggest that you can either use conv-emformer or streaming conformer.

**Comment by pkufool** [comment]
> Can you please recommend models/recipes for both streaming and offline cases?

For streaming models, you can try `pruned_transducer_stateless{4,5}` with `dynamic-chunk-training` and `causal-convolution` enabled.
