### ISSUE TITLE
streaming_decode.py or decode.py under stateless5?

### ISSUE THREAD

**Issue by Cescfangs** [k2-fsa/icefall#664]
Hey guys, I see both `streaming_decode.py` and `decode.py` under stateless5 support streaming decoding, what's the difference?

**Comment by pkufool** [comment]
In `decode.py`, it is simulate streaming decoding (i.e. using masking when calculating attention). 
In `streaming_decode.py` it is real streaming decoding (i.e decoding chunk by chunk).

So, you can decode a streaming model with either `simulate_streaming` in `decode.py` or `streaming_decode.py`, the decoding resutls should be almost the same.

**Comment by Cescfangs** [comment]
Got it, thanks !
