### ISSUE TITLE
Get n best results

### ISSUE THREAD

**Issue by ncakhoa** [k2-fsa/icefall#671]
Is there any way I can get n best decoding results for rescoring?

**Comment by csukuangfj** [comment]
Yes, please have a look at

https://github.com/k2-fsa/icefall/blob/2f43e4508b9eada64a9b89a4576935fb0b72694c/icefall/decode.py#L159

https://github.com/k2-fsa/icefall/blob/2f43e4508b9eada64a9b89a4576935fb0b72694c/icefall/decode.py#L621
