### ISSUE TITLE
conda installation of k2 dosn't work

### ISSUE THREAD

**Issue by fra1993** [k2-fsa/icefall#68]
Hi, I am trying to install k2 within a conda env with the command you provide:

`conda install -c k2-fsa -c pytorch -c conda-forge k2 python=3.8 cudatoolkit=11.1 pytorch=1.8.1
`
Unfortuntely conda compalins with: 

```
PackagesNotFoundError: The following packages are not available from current channels:

  - k2
```

I am running on a Windows 10 machine

**Comment by fra1993** [comment]
Ok, maybe you could just mention this in the installation guide! However, now I am trying to install on a linux machine following th steps cited [here](https://k2-fsa.github.io/k2/installation/pip.html). However, when I try to run the final test example the last line `fsa.draw('hello.svg', title='hello)` I get the error message `ModuleNotFoundError: no module named graphviz`

**Comment by csukuangfj** [comment]
Did you run `pip install graphviz`?
