### ISSUE TITLE
ONNX exported model count

### ISSUE THREAD

**Issue by abb128** [k2-fsa/icefall#682]
The ONNX exporting process currently exports five separate models:
  - ``encoder.onnx``
  - ``decoder.onnx``
  - ``joiner.onnx``
  - ``joiner_encoder_proj.onnx``
  - ``joiner_decoder_proj.onnx``

However, these models are just called sequentially, it doesn't look like there's much reason to keep them separate. It appears these models could be merged into just two .onnx models like so during the export:
* "encoder": `encoder`+`joiner_encoder_proj`
* "joiner": `decoder`+`joiner_decoder_proj`+`joiner`

Some sample code to illustrate what I mean:
```py
class OnnxEncoder(nn.Module):
    def __init__(self, encoder, joiner):
        super().__init__()
        self.encoder = encoder
        self.encoder_proj = joiner.encoder_proj

    def forward(self, x, h, c):
        x_lens = torch.tensor([9], dtype=torch.int64)
        x, _, new_states = self.encoder(x, x_lens, (h, c), 1.0)
        x = self.encoder_proj(x)

        return x, new_states[0], new_states[1]

class OnnxJoiner(nn.Module):
    def __init__(self, decoder, joiner):
        super().__init__()
        self.decoder = decoder
        self.joiner = joiner

    def forward(self, context, encoder_out):
        decoder_out = self.decoder(context, False)
        decoder_out = self.joiner.decoder_proj(decoder_out)

        joiner_out = self.joiner(encoder_out, decoder_out, False)

        return joiner_out
```

This could greatly reduce the amount of code and complexity required to perform inference, from loading and calling 5 models to just 2. Is there any reason they're separate and not merged like that?

**Comment by csukuangfj** [comment]
The reason is that `encoder_proj` and `decoder_proj` are inside the `joiner` network.
When exporting, we export each model independently.

We can change the export script by following your suggested code.

Would you mind making a PR?

**Comment by abb128** [comment]
I'll try and make a PR then

**Comment by csukuangfj** [comment]
Thanks!

**Comment by abb128** [comment]
I realized it might not be a good idea to merge the decoder and joiner like I did in my sample. After a blank token is emitted, the subsequent call to the merged decoder+joiner with the new encoder output would not re-use the previous decoder output, even though the context is the exact same. The stateless decoder seems small so I'm not sure it would matter too much for performance though.

**Comment by csukuangfj** [comment]
> I realized it might not be a good idea to merge the decoder and joiner like I did in my sample. After a blank token is emitted, the subsequent call to the merged decoder+joiner with the new encoder output would not re-use the previous decoder output, even though the context is the exact same. The stateless decoder seems small so I'm not sure it would matter too much for performance though.

I think you can leave the joiner as it is. Just move `decoder_proj` from the joiner to `decoder`, like what you are doing for the encoder.

**Comment by csukuangfj** [comment]
@abb128 
Please have a look at https://github.com/k2-fsa/icefall/pull/879
