### ISSUE TITLE
Train Completion Time

### ISSUE THREAD

**Issue by userasrk2** [k2-fsa/icefall#684]
Hi,

Is there a way to see when the model training will finish (something like a progress bar). I'm using `pruned_transducer_stateless5` recipe.

Thanks.

**Comment by csukuangfj** [comment]
> Hi,
> 
> Is there a way to see when the model training will finish (something like a progress bar). I'm using `pruned_transducer_stateless5` recipe.
> 
> Thanks.

How many hours of training data and how many GPUs are you using?

**Comment by userasrk2** [comment]
I have 1K training audio (original data before any augmentation) and using 4 Tesla V100 GPU cards. I was looking for some logs or API to query the ETA time.

**Comment by csukuangfj** [comment]
@userasrk2 
You can find links to the training logs of every recipe in the `RESULTS.md`, e.g. , for libirspeech, it is
https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/RESULTS.md

If you are using stateless5, please have a look at
https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/RESULTS.md

You can find tensorboard logs there.
