### ISSUE TITLE
Tensorboard data from remote computer

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#694]
Hello guys,

I've just completed TedLium3 training. But I did it on remote AWS machine.
How can I see tensorboard data?

Should I download this file events.out.tfevents.1668622331.bdcf5ab79459.10825.0 to my computer and to open it using the Crhome ?

Thanks,
AlexG.

**Comment by csukuangfj** [comment]
The first method will print a message, telling you to view it within your browser.

The second method will give you a public URL.
(You need to use your google account for authentication for your first run.)

**Comment by pkufool** [comment]
Since you did your exps on remote AWS machine, I think you have to use the second method, visit https://tensorboard.dev/ for more details.
