### ISSUE TITLE
max_duration

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#699]
Hello guys,

I am working with K2-Tedlium3 experiment.

In the following command what is the meaning of max-duration? I assumed that it is maximal number of frames in training utterances (i.e. 30 seconds). Is that correct?

./pruned_transducer_stateless/train.py \
  --world-size 4 \
  --num-epochs 30 \
  --start-epoch 0 \
  --exp-dir pruned_transducer_stateless/exp \
  --max-duration 300

In any case, I could not work with max-duration=300 because I got out of memory GPU error. So I reduced this value to max-duration=200. In this case the training work completed successfully. 

For my experiment I used 4 GPU's. And it seems that I got problematic results. For example for the greedy search on the test set in RESULTS.md file I see that the expected WER on the test set is 6.69%. But, in my experiment I got following:

2022-11-18 09:31:30,923 INFO [decode.py:378] batch 0/?, cuts processed until now is 8
2022-11-18 09:31:55,554 INFO [decode.py:378] batch 100/?, cuts processed until now is 1016
2022-11-18 09:31:58,018 INFO [decode.py:395] The transcripts are stored in pruned_transducer_stateless/exp/greedy_search/recogs-test-greedy_search-epoch-29-avg-13-context-2-max-sym-per-frame-1.txt
2022-11-18 09:31:58,072 INFO [utils.py:537] [test-greedy_search] %WER 8.23% [2339 / 28430, 622 ins, 755 del, 962 sub ]
2022-11-18 09:31:58,194 INFO [decode.py:408] Wrote detailed error stats to pruned_transducer_stateless/exp/greedy_search/errs-test-greedy_search-epoch-29-avg-13-context-2-max-sym-per-frame-1.txt
2022-11-18 09:31:58,198 INFO [decode.py:425] 
For test, WER of different settings are:
greedy_search	8.23	best for test

It seems that I got meaningful degradation in the system performance. Maybe you used single GPU for your training? Is it possible to check? Do you have another explanations of the degradation (do you think that my changing of max-duration from 300 to 200 can have so meaningful impact on the results?).

Your help is more than appreciated.

Thanks a lot,
AlexG.

**Comment by csukuangfj** [comment]
> In the following command what is the meaning of max-duration? I assumed that it is maximal number of frames in training utterances (i.e. 30 seconds)

It is the number of seconds in a batch before padding.

---

> pruned_transducer_stateless/exp/greedy_search/errs-test-greedy_search-epoch-29-avg-13-context-2-max-sym-per-frame-1.txt

Have you tried other values of `--epoch --avg`?

**Comment by AlexandderGorodetski** [comment]
Hello,

I am not sure I understand you question. Sorry for that. I used following command for the decoding

./pruned_transducer_stateless/decode.py \
  --epoch $epoch \
  --avg $avg \
  --exp-dir pruned_transducer_stateless/exp \
  --bpe-model ./data/lang_bpe_500/bpe.model \
  --max-duration 100

**Comment by csukuangfj** [comment]
> I am not sure I understand you question. Sorry for that. I used following command for the decoding

I am meaning that have you tried other combinations of `--epoch --avg` instead of `--epoch 29 --avg 13`?

**Comment by AlexandderGorodetski** [comment]
Oh, no. What values do you recommend to evaluate?

**Comment by csukuangfj** [comment]
> Oh, no. What values do you recommend to evaluate?

I suggest that you search for a combination that produces the best WER.

**Comment by AlexandderGorodetski** [comment]
Following are 9 different results (the best test WER is 9.23)

Epoch AVG WER_test
29 13 8.23
29 16 8.34
29 10 8.14
26 13 8.31
26 16 8.4
26 10 8.27
23 13 8.41
23 16 9.07
23 10 8.25

**Comment by AlexandderGorodetski** [comment]
Following are 9 different results (the best test WER is 8.14)

Epoch AVG WER_test
29 13 8.23
29 16 8.34
29 10 8.14
26 13 8.31
26 16 8.4
26 10 8.27
23 13 8.41
23 16 9.07
23 10 8.25

**Comment by AlexandderGorodetski** [comment]
How many GPU's were used to get the reference result?

**Comment by csukuangfj** [comment]
@AlexandderGorodetski 
Please have a look at https://github.com/k2-fsa/icefall/blob/master/egs/tedlium3/ASR/RESULTS.md#2022-03-21

It says the training command is
```bash
./pruned_transducer_stateless/train.py \
  --world-size 4 \
  --num-epochs 30 \
  --start-epoch 0 \
  --exp-dir pruned_transducer_stateless/exp \
  --max-duration 300
```
which means 4 GPUs are used.

**Comment by AlexandderGorodetski** [comment]
In my case I used 4 GPU's too. But I have meaningful degradation in WER. It seems that my change of max-duration from 300 to 200 caused this degradation? Do you agree?

**Comment by AlexandderGorodetski** [comment]
Maybe for max-duration=200 I should use smaller value of learning rate? Is it possible to change the learning rate. Maybe I should run more epochs? What do you think?

**Comment by csukuangfj** [comment]
> 

Yes, you can change
https://github.com/k2-fsa/icefall/blob/e5d942696a813ea2266579a1ba16ee99e0aba34d/egs/tedlium3/ASR/pruned_transducer_stateless/train.py#L125-L129
to adjust the learning rate.

Also, you can train it for more epochs.

**Comment by AlexandderGorodetski** [comment]
@csukuangfj 

I will take more expensive GPU's from AWS and I will rerun the experiment with max_duration=300. In this case my experiment will be exactly same to yours. And I believe that in this case I will get results similar to yours.
I will keep you updated.

Thanks so much.

**Comment by luomingshuang** [comment]
Maybe you can train the tedlium recipe with more epochs (>29 epochs) when max-duration is 200. And then test it.

**Comment by AlexandderGorodetski** [comment]
I will try to add 15 epochs.
However the graph of valid_pruned_loss is starting to rise even with only 30 epochs, so it seems that there is some overfitting. Do you think we should use a smaller learning rate?


![image](https://user-images.githubusercontent.com/20683945/204125288-74b2fc03-a7b0-4cd7-928f-dc380aad8a88.png)

**Comment by danpovey** [comment]
If anything a smaller learning rate will make overfitting worse, not better, by reducing gradient noise.
30 epochs is the number we normally train for.  It is really 90 epochs if you are using speed perturbation.

**Comment by iggygeek** [comment]
Are there any guidelines for running on 1 GPU ?  Because using the exact recipe with worldsize = 1, I get only on test WER = 8.4% instead of 6.3% ? And I don't have the compute power to run many experiments ...

**Comment by danpovey** [comment]
More recent experiments (I think, pruned_transducer_stateless5 or so and later) use a scheduler "Eden" that doesn't need much adjustment as you change the world size and the max-duration.
For old ones that use the standard Transformer scheduler "Noam", it may be helpful to reduce the base learning rate if you reduce the num jobs, e.g. by sqrt(change in num jobs), like halve it if you reduce the num jobs by a factor of 4.  That's what I would try first anyway. It may be learning too fast, so the gradient noise would be too much.  This would lead to worse loss function on the training set.
