### ISSUE TITLE
tedlium prepare.sh file should be updated

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#703]
Hello

There is following error during running prepare.sh of tedlium recipe

ValueError: It seems that 'sph2pipe' binary is not installed; did you run 'lhotse install-sph2pipe'?

The command 'lhotse install-sph2pipe' can be added at the beginning of prepare.sh file, I guess.

Thanks,
AlexG.

**Comment by csukuangfj** [comment]
Would you mind creating a PR to fix it?

**Comment by luomingshuang** [comment]
It seems lhotse assumes that you have installed sph2pipe (when you install kaldi.). By the way, maybe we can use one command to  check if the users install sph2pipe or not in prepare.sh .

**Comment by luomingshuang** [comment]
When I build the tedlium recipe, I install the kaldi firstly. So this error doesn't happen to me.
