### ISSUE TITLE
Tensodrboard values

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#707]
Hello guys,

I have a question regarding tedlium3 recipe tensorboard.

What are meanings of the following values:

current_loss
current_pruned_loss
current_simple_loss
tot_loss

Thanks very much,
AlexG.

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/icefall/blob/6693d907d3ddd5c5eade144b55a57c8831d6d9b2/egs/librispeech/ASR/pruned_transducer_stateless7/train.py#L695-L698

`current_loss` is the loss of the current batch, which is computed by
https://github.com/k2-fsa/icefall/blob/6693d907d3ddd5c5eade144b55a57c8831d6d9b2/egs/librispeech/ASR/pruned_transducer_stateless7/train.py#L685

`current_pruned_loss` is the pruned loss of the current batch.
`current_simple_loss` is the simple loss of the current batch.
The above two losses are computed by
https://github.com/k2-fsa/icefall/blob/6693d907d3ddd5c5eade144b55a57c8831d6d9b2/egs/librispeech/ASR/pruned_transducer_stateless7/train.py#L662

`tot_loss` is the total loss averaged over all batches that have seen so far (with some smoothing).
