### ISSUE TITLE
Training using narrow band data (8KHz)

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#709]
Hello guys,

Could you please let me know how to work with narrow band data (8KHz). What configuration files should be updated?

Thanks,
AlexG.

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/icefall/blob/6693d907d3ddd5c5eade144b55a57c8831d6d9b2/egs/yesno/ASR/local/compute_fbank_yesno.py#L57

The yesno recipe uses 8 kHz. Please have a look at that recipe.

Basically, the first thing you need to do is to use lhotse to prepare your data.

**Comment by AlexandderGorodetski** [comment]
Guys, from our experiments we can see that it is possible to work with telephony audio data that is upsampled to 16Khz and use a model that was originally trained with 16Khz data, e.g. librispeech+gigaspeech. The results are very good even for narrow band audio.
