### ISSUE TITLE
stm files

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#714]
Hello guys,

In your prepare.sh file I do not see where do you created STM files?

Could you clarify please.

Thanks a lot,
AlexG.

**Comment by csukuangfj** [comment]
What is STM?

**Comment by desh2608** [comment]
@csukuangfj STM is a NIST format for representing ASR reference (it stands for "segment time mark"). See Section 7.1 [here](https://www.nist.gov/system/files/documents/2021/08/03/OpenASR20_EvalPlan_v1_5.pdf).

@AlexandderGorodetski icefall recipes so far do not use sclite for scoring, so a STM file is not required. Currently most (all?) the recipes use [kaldialign](https://github.com/pzelasko/kaldialign) which is a wrapper around Kaldi's Levenshtein distance implementation. See [write_error_stats()](https://github.com/k2-fsa/icefall/blob/ece728d895c11545eb3232caa4f6a1c907192064/icefall/utils.py#L457) function.

**Comment by csukuangfj** [comment]
@desh2608 

Thanks for the explanation.

**Comment by AlexandderGorodetski** [comment]
Guys, I looked for a transcription information in data/ directory and I think I found it. It is located in manifest/*supervision* files. Could you approve it please.

**Comment by csukuangfj** [comment]
> Could you approve it please.

What can we do about that? And what is your issue?
