### ISSUE TITLE
Reasoning / Intuition behind Model Averaging

### ISSUE THREAD

**Issue by teowenshen** [k2-fsa/icefall#715]
Is there any reason or intuition for why the models are averaged in checkpoint.py by using this formula, instead of averaging over a weighted sum? 

![image](https://user-images.githubusercontent.com/36886809/204528906-5d4193b2-9c1a-4c87-a348-eb4e7af7b41f.png)
(I just copied the equation from https://github.com/k2-fsa/icefall/blob/1d5c03f85a55e24755189cd27aa0b74c0028f9a2/icefall/checkpoint.py#L400, where _b_ refers to `batch_idx `and _m_ refers to model params.)

It seemed quite counterintuitive to me that the earlier model is subtracted from a later model, even if indeed the weights for $m_{\text{end}}$ and $m_{\text{start}}$ do sum to 1. 

Is this actually an established model averaging method..? Or, was there any Github discussion regarding this model averaging method?

Thanks!

**Comment by csukuangfj** [comment]
Please have a look at
- https://github.com/k2-fsa/icefall/pull/344
- https://github.com/k2-fsa/icefall/issues/337

**Comment by yaozengwei** [comment]
In training, we maintain the `model_avg`, which is the average of all periodically sampled models (model_1, model_2,...,model_n) from the start:
<img width="283" alt="Screen Shot 2022-11-29 at 20 41 15" src="https://user-images.githubusercontent.com/19564185/204531860-aafb7a4b-7ba6-49cf-ab7e-e09a37256f63.png">
During decoding, we want to use the averaged model at the interval [p+1, p+2, ..., q]:
<img width="570" alt="Screen Shot 2022-11-29 at 20 48 52" src="https://user-images.githubusercontent.com/19564185/204533332-ee422da9-1169-4ae5-95d9-d55d7d7a0768.png">

**Comment by teowenshen** [comment]
I see. So in effect, Icefall is already averaging over every mini-batch (approximated by sampling every `params.average_period`) along the way during training, which is why the actual averaging itself for decoding is just a subtraction of the earlier models. 

Thank you so much for pointing me towards the correct direction and for connecting the dots for me.
