### ISSUE TITLE
onnx export 

### ISSUE THREAD

**Issue by userasrk2** [k2-fsa/icefall#716]
Hi,

Is there any plan to add onnx export support to `pruned_transducer_stateless7` and `pruned_transducer_stateless8` in `LibriSpeech` ?

Thanks,

**Comment by csukuangfj** [comment]
@userasrk2 

Would you mind creating a PR to support that?

**Comment by EmreOzkose** [comment]
@userasrk2  I can add in a few days.

**Comment by JinZr** [comment]
PR: https://github.com/k2-fsa/icefall/pull/1302
