### ISSUE TITLE
How to get token_ids for NBest lattice generated from nn_outs with H.

### ISSUE THREAD

**Issue by yuekaizhang** [k2-fsa/icefall#736]
Hi, I would like rescore a nbest list using attention decoder. However,  https://github.com/k2-fsa/icefall/blob/master/icefall/decode.py#L915 this line assumes the nbest lists are from HLG. 

I was wondering how to get nbest token_ids: List[List(int)] from H, since H has no attribute "tokens". I have tried to use H.aux_labels to replace the nbest.fsa.tokens but failed.

Thanks.

**Comment by csukuangfj** [comment]
> I have tried to use H.aux_labels to replace the nbest.fsa.tokens but failed.

Could you use `nbest.fsa.aux_labels` and remove `0`s from it?

**Comment by yuekaizhang** [comment]
> > I have tried to use H.aux_labels to replace the nbest.fsa.tokens but failed.
> 
> Could you use `nbest.fsa.aux_labels` and remove `0`s from it?

Thanks. It turns out I forgot to change `hyps = [[word_table[i] for i in ids] for ids in hyps]` to `hyps = bpe_model.decode(hyps)` when using H.
