### ISSUE TITLE
Disable noise augmentation

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#739]
Hello guys,

I have a question regarding tedlium3 recipe.
I see that during tedlium data preparation, fbank is extracted for tedlium and for musan. Therefore I assume that during the training noise augmentation is performed. Could you please point me in the code how can I disable this noise augmentation.

Thanks a lot,
AlexG.

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/icefall/blob/0e325c8782c8b9178cf0f2b030e49ae64f2b091d/egs/tedlium3/ASR/transducer_stateless/asr_datamodule.py#L165

Please pass
```
--enable-musan 0
```
to `./train.py` to disable musan.
