### ISSUE TITLE
training for own language

### ISSUE THREAD

**Issue by alidabaghi123** [k2-fsa/icefall#740]
hello. how are you??
can i train this model for mrxica

**Comment by csukuangfj** [comment]
Hi, the first thing you need to do is to prepare your data.

Please have a look at
- https://github.com/lhotse-speech/lhotse
- https://lhotse.readthedocs.io/en/latest/

You can find a list of corpus at
- https://github.com/lhotse-speech/lhotse/tree/master/lhotse/recipes

Specifically, I would recommend reading
- https://github.com/lhotse-speech/lhotse/blob/master/lhotse/recipes/yesno.py

You can find the yesno recipe in https://github.com/k2-fsa/icefall/tree/master/egs/yesno/ASR
