### ISSUE TITLE
num_mel_bins

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#748]
Hello guys,

I am going to work with num_mel_bins=60 instead of 80, because I am working with narrow band audio data (8KHz). Where should I change the architecture of the deep net so that it will expect working with 60 bins?

Thanks,
AlexG.

**Comment by desh2608** [comment]
You can change the num mel bins [here](https://github.com/k2-fsa/icefall/blob/d65fe17d2766e34adbb4080f9691ea829ac0ae05/egs/librispeech/ASR/local/compute_fbank_librispeech.py#L64) for feature extraction. For training, you can change the expected feature_dim [here](https://github.com/k2-fsa/icefall/blob/d65fe17d2766e34adbb4080f9691ea829ac0ae05/egs/librispeech/ASR/pruned_transducer_stateless2/train.py#L385).

**Comment by AlexandderGorodetski** [comment]
Thank you.

What about decoder?

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/icefall/blob/d65fe17d2766e34adbb4080f9691ea829ac0ae05/egs/librispeech/ASR/pruned_transducer_stateless7/decode.py#L119

The `decode.py` reuses the settings from `train.py`.

That is, once you update `train.py`, it automagically propagates the changes to `decode.py`.
