### ISSUE TITLE
Tedlium3 number of word pieces

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#756]
Hello,

I see that in Tedlium3 recipe you use 500 word pieces. Did you try another numbers? (1000, 2000). Is there some influence on the decoding results?

Thanks,
AlexG.

**Comment by csukuangfj** [comment]
We have tried 5000, 1000, and 500 on the librispeech dataset and found that 500 performs the best.

Tedlium3 uses the same config from librispeech. We have not tried other BPE vocab size on tedlium3 other than 500.
