### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by wwfcnu** [k2-fsa/icefall#759]
![image](https://user-images.githubusercontent.com/109075309/207278123-6404f5b4-822f-4e7f-95be-4a014c3f957b.png)

**Comment by wwfcnu** [comment]
![image](https://user-images.githubusercontent.com/109075309/207278211-8aba1595-cf15-4882-b1af-b50855fcf924.png)

**Comment by wwfcnu** [comment]
Is G too big?How big G can it support

**Comment by csukuangfj** [comment]
Can you using
https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/local/compile_hlg_using_openfst.py

Your G is too large and I am afraid it won't fit into your GPU memory even if you can build an HLG from it.

**Comment by wwfcnu** [comment]
> Can you using https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/local/compile_hlg_using_openfst.py
> 
> Your G is too large and I am afraid it won't fit into your GPU memory even if you can build an HLG from it.
Can I just replace the compile_hlg.py in the make_hlg.sh with compile_hlg_using_openfst.py

**Comment by wwfcnu** [comment]
> > Can you using https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/local/compile_hlg_using_openfst.py
> > Your G is too large and I am afraid it won't fit into your GPU memory even if you can build an HLG from it.
> > Can I just replace the compile_hlg.py in the make_hlg.sh with compile_hlg_using_openfst.py
I have installed kaldifst

**Comment by csukuangfj** [comment]
> Can I just replace the compile_hlg.py in the make_hlg.sh with compile_hlg_using_openfst.py

Yes, I think so.

Note that `compile_hlg_using_openfst.py` generates a file called `HLG_fst.pt`, while
it is `HLG.pt` for `compile_hlg.py`.
