### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by fightingtang** [k2-fsa/icefall#763]
Is there any way to get timestamp,not only the start time of word,but also duration

**Comment by csukuangfj** [comment]
For CTC, yes, it is possible to get the start time and end time of a token (You have to infer the start and end time for a word from the corresponding tokens).

For transducer-based models, we can only get the start time, not the end time (so it is not possible to get the duration).

**Comment by fightingtang** [comment]
thank you,I will try in CTC

**Comment by yaozengwei** [comment]
We have already some recipes that supports getting timestamps (only the start time of word currently). E.g.,
* For conformer-ctc model, please refer to https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/conformer_ctc3/decode.py. 
* For conformer-transducer model, please refer to https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless4/decode.py
