### ISSUE TITLE
Resuming training from saved batch-level checkpoint hangs up on "loading grad scaler state dict"

### ISSUE THREAD

**Issue by kfmn** [k2-fsa/icefall#764]
Hi,

I am training ASR model based on recipe "pruned_transducer_statless7_ctc" from egs/librispeech/ASR.
After stopping training at some stage I am trying to resume training and observe the following strange behavior:
- when I use --start-epoch parameter to resume training, all is resumed OK
- when I use --start-batch instead, the loading process freezes on the stage "Loading grad scaler state dict". I waited for about a half of an hour several times but no continuation was observed (when loading from epoch checkpoint this stage takes a minute or so)

Since epoch is rather long on my data I would like to have both options to resume training. Please advice how to fix this

Thanks,
Maxim

**Comment by csukuangfj** [comment]
You are not the first one who has encountered this issue.

Please have a look at https://github.com/lhotse-speech/lhotse/issues/750

**Comment by pzelasko** [comment]
Unfortunately with the current mechanisms I don't think we can speed up resumption. I am working on a new dataloading mechanism based on shards and I might be able to bake in a fast dataloading resumption mechanism sometime in Q1 2023.

**Comment by pzelasko** [comment]
... in the absence of this feature (at least for practical purposes), I find that changing the random seed (or otherwise shuffling cuts differently) each time you resume training instead tends to work pretty well.
