### ISSUE TITLE
Deletion of the first word during BPE training

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#766]
Hello guys,

I see following command before BPE training. Could you please explain why do you delete the first word of the line before the BPE training.

    cat data/lang_phone/train.text |
    cut -d " " -f 2- > $lang_dir/transcript_words.txt

Thanks,
AlexG.

**Comment by csukuangfj** [comment]
I think the first word is the utterance ID.

Could you check the file to confirm it?

**Comment by AlexandderGorodetski** [comment]
Hi @csukuangfj 

I have rechecked it. 

Following is example from train.txt file

"me was composed of stories of cravings of strivings of desires of the future"

Following is example from transcript_wrods file:

"was composed of stories of cravings of strivings of desires of the future"

It means that the first word was indeed deleted.

I recommend to change the code 

cat data/lang_phone/train.text |
cut -d " " -f 2- > $lang_dir/transcript_words.txt

to the following 

cat data/lang_phone/train.text |
cut -d " " -f 1- > $lang_dir/transcript_words.txt

Thanks,
AlexG.

**Comment by csukuangfj** [comment]
By the way, which recipe are you referring to?

**Comment by AlexandderGorodetski** [comment]
tedlium3

**Comment by csukuangfj** [comment]
Could you make a pull-request to fix that? I think the code is borrowed from the librispeech recipe, where the first field is the utterance ID.
