### ISSUE TITLE
confusion about masks used in zipformer

### ISSUE THREAD

**Issue by kobenaxie** [k2-fsa/icefall#767]
why pass `src_key_padding_mask` with attention mask `mask`, should be padding mask ?
https://github.com/k2-fsa/icefall/blob/6d659f423dbb67b20309e00d5885b76c5dfd15e8/egs/librispeech/ASR/pruned_transducer_stateless7/zipformer.py#L744

**Comment by yaozengwei** [comment]
It is an error here. It should be `src_key_padding_mask` here. 

I have test the corrected code with the trained model, which leads to 0.01 or 0.02 WER(%) difference on test-clean and test-other. I planned to make a PR to fix it.

**Comment by yaozengwei** [comment]
Fixed it in https://github.com/k2-fsa/icefall/pull/768.

**Comment by kobenaxie** [comment]
> It is an error here. It should be `src_key_padding_mask` here.
> 
> I have tested the corrected code with the trained model, which leads to 0.01 or 0.02 WER(%) difference on test-clean and test-other. I planned to make a PR to fix it.

Maybe differs for streaming mode.
