### ISSUE TITLE
Phone line simulation in lhotse

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#769]
Hello guys,

Could you let me know please if it is possible somehow to implement phone line augmentation in lhotse. My product should receive narrow band French telephony data. But for training I have only wideband data (TedX, CommonVoice, LibriSpeech). By the way, if someone is familiar with telephony French training data could you please let me know.

Thanks,
AlexG.

**Comment by desh2608** [comment]
I don't think there is a single effect for this, but it should be possible to leverage torchaudio (https://pytorch.org/tutorials/beginner/audio_preprocessing_tutorial.html#simulating-a-phone-recoding). The key steps are:
* apply a lowpass filter
* apply companding
* convert to 8kHz sample rate
* apply a GSM codec
