### ISSUE TITLE
pruned_transducer_sateless training with word pieces

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#771]
Hi All,

I am looking on the tedlium3 training command and I see that this command does not receive BPE directory as one of parameters. Therefore I assume that this training job is based on characters only? Do you have transducer training system example that is based on BPE word pieces? 

./pruned_transducer_stateless/train.py \
  --world-size 4 \
  --num-epochs 30 \
  --start-epoch 0 \
  --exp-dir pruned_transducer_stateless/exp \
  --max-duration 200 \
  --enable-musan 0 \
  --enable-spec-aug 0

Thanks a lot,
AlexG.

**Comment by marcoyang1998** [comment]
You may pass the path to your BPE model by modifying the arg `--bpe-model`. https://github.com/k2-fsa/icefall/blob/fbc1d3b194cfb2be4d01de85d9c3a3ea13c961fb/egs/tedlium3/ASR/pruned_transducer_stateless/train.py#L119

Note that we don't show all possible args in the training commands in `RESULTS.md`. You should have a look at `train.py` to see all the options.
