### ISSUE TITLE
tedlium3 length of input window

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#777]
Hello All,

Where in the code of tedlium3 recipe can I see length of input window into RNN-T. I mean number of frames related to the left context and number of frames related to the right context.

Thanks,
AlexG.

**Comment by AlexandderGorodetski** [comment]
Guys, how many frames are fed into RNN-T in a single decoding step. What is the size of decoding_window? What is the size of the slide for  every decoding step?

**Comment by AlexandderGorodetski** [comment]
Where can I see all these definitions in the code?

**Comment by csukuangfj** [comment]
tedlium3 contains only non-streaming models, so there is no left/right context. If any, they are infinity.
