### ISSUE TITLE
pruned_transducer_stateless8

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#781]
Hello guys,

I just wanted to verify that the best system in icefall today is pruned_transducer_stateless8. Is that correct?

I would like to try pruned_transducer_stateless8 in tedlium3 recipe. Can I simply copy pruned_transducer_stateless8 directory into tedlium recipe and to run it according to the guidelines in the results file. Should it work on your opinion?

Thanks,
AlexG.

**Comment by csukuangfj** [comment]
> Can I simply copy pruned_transducer_stateless8 directory into tedlium recipe and to run it according to the guidelines in the results file

Please change the dataset part (train.py and asr_datamodule.py). You can refer to `pruned_transducer_statelss` in tedlimu3.
Other part of the code can be reused and so I suggest that you create symlinks instead of copying files.

**Comment by marcoyang1998** [comment]
Please note that `pruned_transducer_statelss8` is a multi-dataset recipe which utilized extra data other than LibriSpeech. It might not yield better performance on tedlium3. But feel free to try it and we look forward to hearing good results from you.

**Comment by AlexandderGorodetski** [comment]
So, guys, we found that working with stateless7 scripts under TedLium indeed gives better performance than the conformer.
We got WER=5.17 using greedy decoding and we got WER=4.99% using beam search (beam=4).

**Comment by csukuangfj** [comment]
> So, guys, we found that working with stateless7 scripts under TedLium indeed gives better performance than the conformer.
> 
> We got WER=5.17 using greedy decoding and we got WER=4.99% using beam search (beam=4).

Would you mind creating a pull request about using stateless7 for Tedlium3?
