### ISSUE TITLE
train_conformer

### ISSUE THREAD

**Issue by alidabaghi123** [k2-fsa/icefall#786]
hello again.
i am trying to train for my own dataset. in stage 10 for code "prepare.sh" , I occurrence this error.
![Screenshot from 2022-12-25 15-44-11](https://user-images.githubusercontent.com/78419335/209467553-237e5a74-c368-4a45-abc1-4c89401441fa.png)

**Comment by e871** [comment]
? ?

**Comment by csukuangfj** [comment]
The error log says your G is empty. Please check its file size first.

**Comment by e871** [comment]
![Screenshot from 2022-12-25 16-47-20](https://user-images.githubusercontent.com/78419335/209469474-a0dc3730-cb42-4f26-9218-94fcc6417a9e.png)

**Comment by e871** [comment]
this is my G_file

**Comment by csukuangfj** [comment]
Then what's your L? Do your L and G share the same words.txt?
