### ISSUE TITLE
K2 Anaconda Environment for MAC

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#802]
Hello guys,

Can someone share please K2 Anaconda Environment for MAC.

I have troubles with K2 installation on MAC (I will send the relevant description in the next issue).

Thanks,
AlexG.

**Comment by csukuangfj** [comment]
Can you refer to the documentation for installation on Mac with conda?

**Comment by AlexandderGorodetski** [comment]
Ok guys. One problem I found. Could you please add a comment that before installation of lhotse, one should install cmake. Without cmake installed lhotse installation fails.

**Comment by AlexandderGorodetski** [comment]
Guys. Command "import k2" on my MAC produces following error. Any help is appreciated.

>>> import k2
Traceback (most recent call last):
  File "/opt/anaconda3/envs/K2/lib/python3.8/site-packages/k2/__init__.py", line 24, in <module>
    from _k2 import DeterminizeWeightPushingType
ImportError: dlopen(/opt/anaconda3/envs/K2/lib/python3.8/site-packages/_k2.cpython-38-darwin.so, 0x0002): Library not loaded: '@rpath/libmkl_intel_ilp64.2.dylib'
  Referenced from: '/opt/anaconda3/envs/K2/lib/python3.8/site-packages/_k2.cpython-38-darwin.so'
  Reason: tried: '/opt/anaconda3/envs/K2/lib/python3.8/site-packages/k2/lib/libmkl_intel_ilp64.2.dylib' (no such file), '/opt/anaconda3/envs/K2/lib/python3.8/site-packages/libmkl_intel_ilp64.2.dylib' (no such file), '/opt/anaconda3/envs/K2/lib/python3.8/site-packages/torch/lib/libmkl_intel_ilp64.2.dylib' (no such file), '/opt/anaconda3/envs/K2/lib/python3.8/site-packages/../../libmkl_intel_ilp64.2.dylib' (no such file), '/opt/anaconda3/envs/K2/lib/python3.8/site-packages/k2/lib/libmkl_intel_ilp64.2.dylib' (no such file), '/opt/anaconda3/envs/K2/lib/python3.8/site-packages/libmkl_intel_ilp64.2.dylib' (no such file), '/opt/anaconda3/envs/K2/lib/python3.8/site-packages/torch/lib/libmkl_intel_ilp64.2.dylib' (no such file), '/opt/anaconda3/envs/K2/lib/python3.8/site-packages/../../libmkl_intel_ilp64.2.dylib' (no such file), '/opt/anaconda3/envs/K2/bin/../lib/libmkl_intel_ilp64.2.dylib' (no such file), '/opt/anaconda3/envs/K2/bin/../lib/libmkl_intel_ilp64.2.dylib' (no such file), '/usr/local/lib/libmkl_intel_ilp64.2.dylib' (no such file), '/usr/lib/libmkl_intel_ilp64.2.dylib' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/K2/lib/python3.8/site-packages/k2/__init__.py", line 30, in <module>
    raise ImportError(
ImportError: dlopen(/opt/anaconda3/envs/K2/lib/python3.8/site-packages/_k2.cpython-38-darwin.so, 0x0002): Library not loaded: '@rpath/libmkl_intel_ilp64.2.dylib'
  Referenced from: '/opt/anaconda3/envs/K2/lib/python3.8/site-packages/_k2.cpython-38-darwin.so'
  Reason: tried: '/opt/anaconda3/envs/K2/lib/python3.8/site-packages/k2/lib/libmkl_intel_ilp64.2.dylib' (no such file), '/opt/anaconda3/envs/K2/lib/python3.8/site-packages/libmkl_intel_ilp64.2.dylib' (no such file), '/opt/anaconda3/envs/K2/lib/python3.8/site-packages/torch/lib/libmkl_intel_ilp64.2.dylib' (no such file), '/opt/anaconda3/envs/K2/lib/python3.8/site-packages/../../libmkl_intel_ilp64.2.dylib' (no such file), '/opt/anaconda3/envs/K2/lib/python3.8/site-packages/k2/lib/libmkl_intel_ilp64.2.dylib' (no such file), '/opt/anaconda3/envs/K2/lib/python3.8/site-packages/libmkl_intel_ilp64.2.dylib' (no such file), '/opt/anaconda3/envs/K2/lib/python3.8/site-packages/torch/lib/libmkl_intel_ilp64.2.dylib' (no such file), '/opt/anaconda3/envs/K2/lib/python3.8/site-packages/../../libmkl_intel_ilp64.2.dylib' (no such file), '/opt/anaconda3/envs/K2/bin/../lib/libmkl_intel_ilp64.2.dylib' (no such file), '/opt/anaconda3/envs/K2/bin/../lib/libmkl_intel_ilp64.2.dylib' (no such file), '/usr/local/lib/libmkl_intel_ilp64.2.dylib' (no such file), '/usr/lib/libmkl_intel_ilp64.2.dylib' (no such file)
Note: If you're using anaconda and importing k2 on MacOS,
      you can probably fix this by setting the environment variable:
  export DYLD_LIBRARY_PATH=$CONDA_PREFIX/lib/python3.8/site-packages:$DYLD_LIBRARY_PATH
>>>

**Comment by AlexandderGorodetski** [comment]
Of course I tried

export DYLD_LIBRARY_PATH=$CONDA_PREFIX/lib/python3.8/site-packages:$DYLD_LIBRARY_PATH

**Comment by AlexandderGorodetski** [comment]
Guys. To solve the upper error one should run following command:

pip install mkl

Could you please add it to the installation guide.

**Comment by csukuangfj** [comment]
Thanks for the suggestions. Will add that.

Have you managed to install k2?

**Comment by csukuangfj** [comment]
I just tested the `k2` installation on macOS with conda
```bash
conda create -n test-k2
conda activate test-k2

conda install -c k2 -c pytorch k2 pytorch==1.13.0
python3 -m k2.version
```

Everything works as expected and the above output is
<img width="1160" alt="Screenshot 2023-01-03 at 09 15 22" src="https://user-images.githubusercontent.com/5284924/210288999-38275108-aa28-4f5e-837f-99508f4f2fc1.png">

**Comment by csukuangfj** [comment]
> One problem I found. Could you please add a comment that before installation of lhotse, one should install cmake. Without cmake installed lhotse installation fails.

[kaldialign](https://github.com/pzelasko/kaldialign)
and
[lilcom](https://github.com/danpovey/lilcom)
are installed from source, both of which require `gcc` and `cmake` to be installed.

You can use `pip install cmake` to install cmake if you have not yet installed CMake.

**Comment by AlexandderGorodetski** [comment]
Guys. Currently everything is working properly on my side.
I would like to try all the process on another MAC and then I will close this issue. Thank you.

**Comment by AlexandderGorodetski** [comment]
Hello guys

I have created a script that performs all needed installations for MAC using Anaconda Env.

#!/bin/bash

# Checklist for K2 debugging environemt preparation.
# Anaconda --> Environments --> Create --> K2 --> Create --> K2 (triangle on the right side) --> Open terminal

stage=0

# If the below directory exists please delete it or move it to another location. Please do not use "rm -fr" command in
# this script.
working_dir=/Users/alexandergorodetski/Alex/projects/icefall

# Install cmake and mkl
if [ $stage -le 0 ]; then
  brew install cmake
  pip install mkl
fi

# Install PyTorch and torchaudio
if [ $stage -le 1 ]; then
  conda install pytorch torchvision torchaudio -c pytorch -y
fi

# Install lhotse
if [ $stage -le 2 ]; then
  pip install git+https://github.com/lhotse-speech/lhotse
fi

# K2 installation
if [ $stage -le 3 ]; then
  conda install -c k2-fsa -c pytorch cpuonly k2 python=3.8 pytorch=1.13.0 -y
fi

# Requirements install
if [ $stage -le 4 ]; then
  cd ${working_dir}/..
  git clone https://github.com/k2-fsa/icefall
  cd icefall
  pip install -r requirements.txt
  export PYTHONPATH=${working_dir}:$PYTHONPATH
fi

# Run yes/no example
if [ $stage -le 5 ]; then
  cd egs/yesno/ASR
  ./tdnn/train.py
  ./tdnn/decode.py
fi

**Comment by AlexandderGorodetski** [comment]
Hello guys,

I have prepared script that performs all needed installations for MAC.

**Comment by AlexandderGorodetski** [comment]
Hello guys, I have created script that can be used for installation of icefall on MAC. 

[INSTALL_ICEFALL_MAC.sh.gz](https://github.com/k2-fsa/icefall/files/10338855/INSTALL_ICEFALL_MAC.sh.gz)

**Comment by csukuangfj** [comment]
Thanks for sharing. I reposted your commands below for easier references:
```bash
#!/bin/bash

# Checklist for K2 debugging environemt preparation.
# Anaconda --> Environments --> Create --> K2 --> Create --> K2 (triangle on the right side) --> Open terminal

stage=0

# If the below directory exists please delete it or move it to another location. Please do not use "rm -fr" command in
# this script.
working_dir=/Users/alexandergorodetski/Alex/projects/icefall

# Install cmake and mkl
if [ $stage -le 0 ]; then
  brew install cmake
  pip install mkl
fi

# Install PyTorch and torchaudio
if [ $stage -le 1 ]; then
  conda install pytorch torchvision torchaudio -c pytorch -y
fi

# Install lhotse
if [ $stage -le 2 ]; then
  pip install git+https://github.com/lhotse-speech/lhotse
fi

# K2 installation
if [ $stage -le 3 ]; then
  conda install -c k2-fsa -c pytorch cpuonly k2 python=3.8 pytorch=1.13.0 -y
fi

# Requirements install
if [ $stage -le 4 ]; then
  cd ${working_dir}/..
  git clone https://github.com/k2-fsa/icefall
  cd icefall
  pip install -r requirements.txt
  export PYTHONPATH=${working_dir}:$PYTHONPATH
fi

# Run yes/no example
if [ $stage -le 5 ]; then
  cd egs/yesno/ASR
  ./tdnn/train.py
  ./tdnn/decode.py
fi
```

**Comment by csukuangfj** [comment]
By the way, I don't know why 
```
  pip install mkl
```
is needed. conda should install all the dependencies of k2, including `mkl`.
