### ISSUE TITLE
conv_emformer_transducer_stateless2 HLG decoding_graph error

### ISSUE THREAD

**Issue by is2022** [k2-fsa/icefall#809]
I'm trying to use the HLG as the decoding graph for conv_emformer_transducer_stateless2. In the streaming_decode.py I have:
hlg_filename = "data/lang_bpe_500/HLG.pt"
decoding_graph = k2.Fsa.from_dict(
        torch.load(hlg_filename, map_location=device)
    )
When I run it I get:
  File "/usr/local/lib/python3.6/dist-packages/sentencepiece/__init__.py", line 780, in Decode
    return self._DecodeIds(input)
  File "/usr/local/lib/python3.6/dist-packages/sentencepiece/__init__.py", line 337, in _DecodeIds
    return _sentencepiece.SentencePieceProcessor__DecodeIds(self, ids)
IndexError: Out of range: piece id is out of range.

**Comment by csukuangfj** [comment]
That script does not accept an HLG graph as input.

You can view the help information in that file for usage.

**Comment by is2022** [comment]
Since in decode_one_chunk it says "decoding_graph:
The decoding graph. Can be either a `k2.trivial_graph` or HLG, Used
        only when --decoding_method is fast_beam_search."
I thought it might work! 
Is there a way to use an LM with the transducer?

**Comment by csukuangfj** [comment]
> Since in decode_one_chunk it says "decoding_graph:
> 
> The decoding graph. Can be either a `k2.trivial_graph` or HLG, Used
> 
>         only when --decoding_method is fast_beam_search."
> 
> I thought it might work! 
> 
> Is there a way to use an LM with the transducer?

That is a typo. It should be LG.

Please see the help information from the file or read RESULTS.md for usage.

**Comment by is2022** [comment]
Thanks for your response. 
The usage for fast beam search seems to be:
"(3) fast beam search
./conv_emformer_transducer_stateless2/streaming_decode.py \
      --epoch 30 \
      --avg 10 \
      --exp-dir conv_emformer_transducer_stateless2/exp \
      --num-decode-streams 2000 \
      --num-encoder-layers 12 \
      --chunk-length 32 \
      --cnn-module-kernel 31 \
      --left-context-length 32 \
      --right-context-length 8 \
      --memory-size 32 \
      --decoding-method fast_beam_search \
      --use-averaged-model True \
      --beam 4 \
      --max-contexts 4 \
      --max-states 8"   
  which doesn't have the option for any LM.

**Comment by is2022** [comment]
Even with the lg_filename = "data/lang_bpe_500/LG.pt", I get the same error "IndexError: Out of range: piece id is out of range."

**Comment by csukuangfj** [comment]
Just found that
https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/conv_emformer_transducer_stateless2/streaming_decode.py
does not support fast_beam_search_LG.

I suggest that you follow
https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless3/decode.py#L531
to add it.

**Comment by is2022** [comment]
Thanks again @csukuangfj  

> I suggest that you follow https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless3/decode.py#L531 to add it.

This script is not a streaming one, is there any script which supports fast_beam_search_LG in a "streaming_decode.sh" set-up (i.e. with stream objects)?

**Comment by csukuangfj** [comment]
the decoding code also applies to the streaming case.

**Comment by csukuangfj** [comment]
You can also have a look at our sherpa repo .
