### ISSUE TITLE
Average model

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#810]
Guys. Do you have some script that takes several models (e.g. epoch-29.pt, epoch-30.pt, epoch-31.pt) and creates the average models (e.g. final.pt)

**Comment by AlexandderGorodetski** [comment]
Such script will be same for transducer_stateles and for conformer_ctc or different scripts should be prepared?

**Comment by yaozengwei** [comment]
We support model average for almost all recipes. E.g., in https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless4/decode.py, using function `average_checkpoints` and `average_checkpoints_with_averaged_model`.

**Comment by csukuangfj** [comment]
I think export.py in each recipe folder does that.
