### ISSUE TITLE
Attach some mtl training exp results 

### ISSUE THREAD

**Issue by yuekaizhang** [k2-fsa/icefall#816]
I conducted several experiments using ctc, rnn-t, and attention loss on zipformer. Attach WER results on librispeech test clean and test other here for reference. 

| Exp  | Attention loss scale, CTC loss scale| greedy search | fast beam search | modified beam search | ctc greedy search | transducer fast beam search nbest attention rescoring |
| ------------- | ------------- |------|-------|------|------|------|
| exp1  | 0, 0.2  | 2.23 & 5.17 |  2.21 & 5.06 | 2.21 & 5.06 | 2.49 & 5.77 | - | 
| exp2  | 0.5, 0.2 |2.26 & 5.16 | 2.24 & 5.07 | 2.25 & 5.03 | 2.54 & 5.8 | - | 
| exp3  | 1.0, 0.2  | 2.21 & 5.12| 2.2 & 5.10| 2.18 & 5.06 | 2.48 & 5.86 | 2.19 & 4.98 | 

Codes: https://github.com/yuekaizhang/icefall/blob/mtl/egs/librispeech/ASR/run.sh#L11 Seems like attention loss didn't help comparing with ctc loss + transducer loss training.

**Comment by yaozengwei** [comment]
Thanks. We will also build a system with the auxiliary attention decoder, following the network style in zipformer code, to see if there is any performance gain.
