### ISSUE TITLE
Tedlium3 decoding of single file (number of threads)

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#825]
Hello guys,

I am running decoding of a single wave under Tedlium recipe using MAC machine with 16 CPU's.

Does the decoding command execute the inference using multiple threads (i.e. the C++ code uses multi thread)? 

Or does everything run using a single thread?

Thanks,
AlexG.

**Comment by csukuangfj** [comment]
The neural network part can be run with multiple threads.

Please search for how to use multiple threads in PyTorch.

**Comment by AlexandderGorodetski** [comment]
I would like to understand the default number of threads during decoding of single wave. Is it 1 ?

**Comment by AlexandderGorodetski** [comment]
If it is not single thread, I would like to understand how can I change the decode.py to work in single thread mode?
