### ISSUE TITLE
train 

### ISSUE THREAD

**Issue by alidabaghi123** [k2-fsa/icefall#826]
hello, i am traning my dataset and occurrence this error
![Screenshot from 2023-01-10 10-34-36](https://user-images.githubusercontent.com/78419335/211483769-ea1c0ca1-e6f8-4b4a-b6fd-6d748d92ea42.png)

**Comment by csukuangfj** [comment]
The last line says
```
No space left on device
```

It means you need to increase the size of your hard disk, or you need to delete some files from your disk.

**Comment by e871** [comment]
![Screenshot from 2023-01-10 10-43-59](https://user-images.githubusercontent.com/78419335/211485574-5b2a8e39-835b-4aea-8544-cd32a7c279eb.png)

**Comment by e871** [comment]
is this volume low ?

**Comment by csukuangfj** [comment]
/dev/shm is running out of space. You may need to resize it.

**Comment by e871** [comment]
thank you. after prepare this error. i get this error?
![Screenshot from 2023-01-10 12-52-36](https://user-images.githubusercontent.com/78419335/211511968-13382cf6-a934-4414-9780-c60fbbb4af48.png)

**Comment by csukuangfj** [comment]
Which recipe are you using? Could you use `pdb` to find out the value of `tot_loss["frames"]`?

**Comment by e871** [comment]
librispeech

**Comment by csukuangfj** [comment]
Line 888 from the master is
https://github.com/k2-fsa/icefall/blob/fcffa593f011bd3213af5af044eb3ce2ede666c1/egs/librispeech/ASR/pruned_transducer_stateless4/train.py#L888

which is different from your logs.

Have you changed any code?

**Comment by e871** [comment]
i prepare my-test dataset in prepare.sh and training it. i have 10 audio test dataset. 
my goal is is train on low dataset and then train my all-dataset

**Comment by csukuangfj** [comment]
> i prepare my-test dataset in prepare.sh and training it. i have 10 audio test dataset. my goal is is train on low dataset and then train my all-dataset

Please follow this comment  to debug your code.

**Comment by e871** [comment]
Hello, I succeeded to train for my test dataset. for the export model I
![Screenshot from 2023-01-16 15-42-13](https://user-images.githubusercontent.com/78419335/212675567-1d0e811c-4364-4306-bdbb-88c7049ef8e1.png)
 occurrence this error.

**Comment by e871** [comment]
i used icefall documentation

**Comment by e871** [comment]
my model pruned_transducer_stateless4

**Comment by csukuangfj** [comment]
@e871 
It should be fixed by https://github.com/k2-fsa/icefall/pull/844

Please update your code to the latest master.

**Comment by e871** [comment]
very thanks
