### ISSUE TITLE
Suggestion to upload last trained epoch checkpoint to Huggingface

### ISSUE THREAD

**Issue by maltium** [k2-fsa/icefall#834]
Since during development you're training models, apart from just uploading the jit version of the model to Huggingface, it would be useful to also upload the last trained epoch checkpoint file.

The reason is two-fold:
- It allows others to continue training on the same dataset (this was the case for the librispeech stateless8 receipe)
- It allows others with less compute power to use the checkpoint to train a low resource language

I'm personally experimenting with low resource languages and noticed that when using checkpoints trained on Libri/Gigaspeech to train a lower resource language, I get better WER and also training is **much** faster.

I hoped to do the same for the recent Zipformer streaming model, but unfortunately there's no checkpoint I can use.

**Comment by csukuangfj** [comment]
Thanks for your suggestion. We will also upload `epoch-xxx.pt` in the future.

As for the streaming Zipformer, we are uploading the checkpoint containing `optimizer.state_dict()`.

**Comment by yaozengwei** [comment]
I have uploaded the last checkpoint epoch-30.pt on https://huggingface.co/Zengwei/icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/tree/main/exp.

**Comment by maltium** [comment]
Thank you, much appreciated.
