### ISSUE TITLE
Zipformer explanation

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#837]
Hello guys. Could you explain in several words what is zipformer. Thanks a lot.

**Comment by AlexandderGorodetski** [comment]
The explanation is here
https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless7/zipformer.py

**Comment by desh2608** [comment]
@danpovey @csukuangfj I was wondering if there is some documentation somewhere (similar to [this one](https://www.youtube.com/watch?v=BXYZI9FEOgU) about the reworked Conformer) that explains the key differences between conformer and zipformer?

**Comment by danpovey** [comment]
Sorry I have been waiting till I can commit the more recent version of the zipformer, that has a lot more changes.
I think the most significant difference is that there are multiple stacks of encoders, and they run at different rates,
with the middle ones more strongly downsampled, by up to a factor of 4, than the eventual output of the network.
This is more efficient as there are fewer frames to evaluate.

**Comment by desh2608** [comment]
Thanks @danpovey! Any tentative timeline on when we can expect the updated Zipformer in icefall?

**Comment by danpovey** [comment]
I'm hoping in a month or two.

**Comment by beyond-boy** [comment]
> I'm hoping in a month or two.

@danpovey  hi dan, is any progress in new updated zipformer?

**Comment by seastar105** [comment]
@danpovey is there any preprint or paper or report about zipformer?

**Comment by csukuangfj** [comment]
> @danpovey is there any preprint or paper or report about zipformer?

@seastar105 

Please see https://github.com/k2-fsa/icefall/issues/1230

**Comment by JinZr** [comment]
Full pre-print available here: https://github.com/k2-fsa/icefall/issues/1328

**Comment by MysticShadow427** [comment]
hello authors! I had one doubt regarding Zipformer.I am trying a simplistic implementation of Zipformer using PyTorch.
As per the paper the inputs to the model is a 3-D vector `[batch_size,num_time_steps,mel_features]` but the first layer of the model which is **ConvEmbed* has 2-D convolution layers with number of channels as given in the paper.The `nn.Conv2d` requires a 4-D array `[batch_size,num_channels,num_time_steps,mel_features]` , so how to tackle this,by unsqueezing a dimension and giving input a array of `[batch_size,1,num_time_steps,mel_features]` and if we pass this to the model which will work fine till **MultiHead Attention** layer,so how to implement our typical attention on a 4-D tensor?.
Please correct me if I missing something.Thank You!
