### ISSUE TITLE
Downloading of pretrained models

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#840]
Guys, could you please explain me how to download the pretrained model of pruned_transducer_stateless8 system. I was not able to do it according to links.

**Comment by csukuangfj** [comment]
Please have a look at 
https://k2-fsa.github.io/sherpa/cpp/pretrained_models/offline_transducer.html#icefall-asr-librispeech-pruned-transducer-stateless8-2022-12-02

**Comment by AlexandderGorodetski** [comment]
Great. Thank you @csukuangfj .
I see following decoding example.

for m in greedy_search modified_beam_search fast_beam_search; do
  sherpa-offline \
    --decoding-method=$m \
    --nn-model=./exp/cpu_jit.pt \
    --tokens=./data/lang_bpe_500/tokens.txt \
    ./test_wavs/1089-134686-0001.wav \
    ./test_wavs/1221-135766-0001.wav \
    ./test_wavs/1221-135766-0002.wav
done

I have 2 additional questions:
1. How can I compile sherpa-offline ?
2.  What is the fastest way to evaluate stateless8 model using tedlium3 benchmark?

**Comment by csukuangfj** [comment]
> 1. How can I compile sherpa-offline ?

Please follow
https://k2-fsa.github.io/sherpa/cpp/installation/index.html#installation-for-advanced-users-developers

> 2. What is the fastest way to evaluate stateless8 model using tedlium3 benchmark?

I suggest that you use `decode.py` from icefall to compute WER.

**Comment by AlexandderGorodetski** [comment]
During sherpa compilation I got following error. Any help is appreaciated

(base) root@ca3678a00d7e:/fsx_new/Alex/projects/sherpa/build# cmake ..
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No CMAKE_BUILD_TYPE given, default to Release
-- CMAKE_BUILD_TYPE: Release
-- SHERPA_ENABLE_TESTS: OFF
-- SHERPA_ENABLE_PORTAUDIO: ON
-- SHERPA_ENABLE_WEBSOCKET: ON
-- Looking for C++ include cxxabi.h
-- Looking for C++ include cxxabi.h - found
-- Looking for C++ include execinfo.h
-- Looking for C++ include execinfo.h - found
-- SHERPA_OS: 
-- CMake version: 3.25.0
-- Found Git: /usr/bin/git (found version "2.30.2") 
-- SHERPA_GIT_SHA1: 21a5b943dffb3f222010fcc5f2b52f25b889c905
-- SHERPA_GIT_DATE: Sun Jan 15 04:26:25 2023
-- SHERPA_GIT_BRANCH: master
CMake Warning (dev) at /opt/conda/lib/python3.8/site-packages/cmake/data/share/cmake-3.25/Modules/FetchContent.cmake:1279 (message):
  The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
  not set.  The policy's OLD behavior will be used.  When using a URL
  download, the timestamps of extracted files should preferably be that of
  the time of extraction, otherwise code that depends on the extracted
  contents might not be rebuilt if the URL changes.  The OLD behavior
  preserves the timestamps from the archive instead, but this is usually not
  what you want.  Update your project to the NEW behavior or specify the
  DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
  robustness issue.
Call Stack (most recent call first):
  cmake/pybind11.cmake:13 (FetchContent_Declare)
  cmake/pybind11.cmake:27 (download_pybind11)
  CMakeLists.txt:134 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Downloading pybind11
-- pybind11 is downloaded to /fsx_new/Alex/projects/sherpa/build/_deps/pybind11-src
-- pybind11 v2.10.2 
-- Found PythonInterp: /opt/conda/bin/python (found suitable version "3.8.15", minimum required is "3.6") 
-- Found PythonLibs: /opt/conda/lib/libpython3.8.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
CMake Warning (dev) at /opt/conda/lib/python3.8/site-packages/cmake/data/share/cmake-3.25/Modules/FetchContent.cmake:1279 (message):
  The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
  not set.  The policy's OLD behavior will be used.  When using a URL
  download, the timestamps of extracted files should preferably be that of
  the time of extraction, otherwise code that depends on the extracted
  contents might not be rebuilt if the URL changes.  The OLD behavior
  preserves the timestamps from the archive instead, but this is usually not
  what you want.  Update your project to the NEW behavior or specify the
  DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
  robustness issue.
Call Stack (most recent call first):
  cmake/json.cmake:16 (FetchContent_Declare)
  cmake/json.cmake:31 (download_json)
  CMakeLists.txt:135 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Downloading json https://github.com/nlohmann/json/archive/refs/tags/v3.11.2.tar.gz
-- json is downloaded to /fsx_new/Alex/projects/sherpa/build/_deps/json-src
-- Python executable: /opt/conda/bin/python
-- PYTHON_EXECUTABLE: /opt/conda/bin/python
-- TORCH_DIR: /opt/conda/lib/python3.8/site-packages/torch
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Warning at /opt/conda/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
  static library kineto_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  /opt/conda/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
  cmake/torch.cmake:14 (find_package)
  CMakeLists.txt:140 (include)


-- Found Torch: /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch.so  
-- TORCH_LIBRARIES: torch;torch_library;/opt/conda/lib/python3.8/site-packages/torch/lib/libc10.so
-- PyTorch version: 1.13.0
CMake Warning (dev) at cmake/k2.cmake:38:
  Syntax Warning in cmake code at column 52

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:141 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Python executable: /opt/conda/bin/python
-- K2_CMAKE_PREFIX_PATH: /opt/conda/lib/python3.8/site-packages/k2/share/cmake
-- Found k2: /opt/conda/lib/python3.8/site-packages/k2/lib/libk2_torch_api.so (Required is at least version "1.23.2") 
-- K2_FOUND: TRUE
-- K2_INCLUDE_DIRS: /opt/conda/lib/python3.8/site-packages/k2/include
-- K2_LIBRARIES: k2_torch_api;k2_torch;k2_log;k2context;k2fsa
-- K2_CXX_FLAGS:  -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-unused-variable  -Wno-strict-overflow 
-- K2_CUDA_FLAGS: 
-- K2_TORCH_VERSION_MAJOR: 1
-- K2_TORCH_VERSION_MINOR: 13
-- K2_WITH_CUDA: OFF
-- K2_CUDA_VERSION: 
-- K2_VERSION: 1.23.3
-- K2_GIT_SHA1: fd609c0ecd074a2414cbfe7cc827427e6b04c8fc
-- K2_GIT_DATE: Thu Jan 5 04:50:13 2023
-- CMAKE_CXX_FLAGS:    -Wall  -g  -D_GLIBCXX_USE_CXX11_ABI=0   -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-unused-variable  -Wno-strict-overflow 
CMake Warning (dev) at cmake/kaldifeat.cmake:32:
  Syntax Warning in cmake code at column 52

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:142 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Python executable: /opt/conda/bin/python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'kaldifeat'
-- KALDIFEAT_CMAKE_PREFIX_PATH: 
CMake Error at cmake/kaldifeat.cmake:18 (find_package):
  By not providing "Findkaldifeat.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "kaldifeat", but CMake did not find one.

  Could not find a package configuration file provided by "kaldifeat" with
  any of the following names:

    kaldifeatConfig.cmake
    kaldifeat-config.cmake

  Add the installation prefix of "kaldifeat" to CMAKE_PREFIX_PATH or set
  "kaldifeat_DIR" to a directory containing one of the above files.  If
  "kaldifeat" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:142 (include)


-- Configuring incomplete, errors occurred!
See also "/fsx_new/Alex/projects/sherpa/build/CMakeFiles/CMakeOutput.log".
See also "/fsx_new/Alex/projects/sherpa/build/CMakeFiles/CMakeError.log".

**Comment by csukuangfj** [comment]
Please first install kaldifeat
```bash
pip install kaldifeat
```
or use any methods listed in 
https://csukuangfj.github.io/kaldifeat/installation.html
