### ISSUE TITLE
Error during loading of pretrained model

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#841]
Guys. I am trying to load following pretrained model "icefall-asr-librispeech-pruned-transducer-stateless8-2022-12-02"

For some reason during loading of bpe.model I get following error. Could you help please:

(base) root@ca3678a00d7e:/fsx_new/Alex/tmp2/s8/icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13/data/lang_bpe_500# python
Python 3.8.15 (default, Nov 24 2022, 15:19:38) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sentencepiece as spm
>>> sp = spm.SentencePieceProcessor()
>>> sp.load("bpe.model")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/opt/conda/lib/python3.8/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())]

**Comment by csukuangfj** [comment]
```bash
cd icefall-asr-librispeech-pruned-transducer-stateless8-2022-12-02

git lfs pull --include "data/lang_bpe_500/bpe.model"

git lfs pull --include "exp/pretrained.pt"
```

We don't use `bpe.model` and `pretrained.pt` in sherpa, that is why the doc in sherpa does not mention the downloading of `bpe.model` and `pretrained.pt`.

Before using `git lfs pull`, please run
```bash
cd icefall-asr-librispeech-pruned-transducer-stateless8-2022-12-02

ls -lh data/lang_bpe_500
ls -lh exp
```

You will find that the file size of `bpe.model` and `pretrained.pt` is several hundred **bytes``, which
indicates you have not used `git lfs` to download them.

![Screen Shot 2023-01-16 at 07 01 34](https://user-images.githubusercontent.com/5284924/212572136-21af3d59-7b00-4473-ad6b-b8c709146949.png)

**Comment by desh2608** [comment]
You can also just "right click -> copy link address" on the "download" link on the model's HF page, e.g.,
![image](https://user-images.githubusercontent.com/5912325/212573835-d4d2df5c-835d-4159-99e7-6ca181d50130.png)
and then use `wget` to download it.
