### ISSUE TITLE
Librispeech decode.py for Tedlium3 test set

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#846]
Hello guys. I am using librispeech stateless7 decode.py for decoding Tedlium3 test set. I would like to evaluate perfromance of the pretrained stateless8 model on Tedlium3 test set.

I see that I get following errors. Could you please recommend me how can I change the code in order to ignore errors like these:

AimeeMullins_2009P-1:	(ignore_time_segment_in_scoring->she)
AimeeMullins_2009P-10:	(ignore_time_segment_in_scoring->a)

**Comment by csukuangfj** [comment]
Could you please show the complete command you are using and also the complete logs?

**Comment by AlexandderGorodetski** [comment]
We recommend to delete line with ignore_time_segment_in_scoring from the original STM files in tedlium Dev and Test data, this fixes the above mentioned problem.
