### ISSUE TITLE
Killed message during the decoding

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#847]
Hello guys. I am running on low resource CPU machine with 30GB RAM only. I get following error message during the decoding. I assume that the problem is with OOM. Is it possible to define MAX_RAM parameter or something alternative during the decoding.

./main.sh: line 32:  6482 Killed                  python ./pruned_transducer_stateless7/decode.py --epoch $epoch --avg $avg --use-averaged-model 0 --exp-dir ./pruned_transducer_stateless7/exp --feedforward-dims "1024,1024,2048,2048,1024" --max-duration 5 --decoding-method greedy_search

**Comment by csukuangfj** [comment]
How much actual RAM is available for your decoding process? 

30 GB RAM is more than enough for --max-duration=5.

**Comment by AlexandderGorodetski** [comment]
Guys. I have about 28GB of RAM available. But I sent this decoding process on machine with 240GB (on CPU machine only) and I saw that sometimes there is RAM consumption of 60GB.

**Comment by csukuangfj** [comment]
Which kind of data are you using?

What is the duration of the utterance length?

Are there very long utterances?
