### ISSUE TITLE
How to start a phone-based ctc training

### ISSUE THREAD

**Issue by oshindow** [k2-fsa/icefall#855]
Hi all,

I'm trying to train a phonetic alignment model in the aishell-1 dataset. The Conformer-CTC pre-train model is good enough at the char level, but at the phone level, there is only a Conformer-MMI model that can be used, which has a different TrainingGraphCompiler from the CTC model. 

What I noticed is the `tokens.txt` under `data/lang_phone` folder which does not include `sos/eos` and `<blk>` tokens but includes `<eps>`, `<SIL>`, `<SPN>` and disambig tokens. So does it possible to start a phone-based ctc training by simply changing  `tokens.txt`,  `L.pt` files and continuing to use CharCtcTrainingGraphCompiler?

Thanks a lot.

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/icefall/tree/master/egs/librispeech/ASR/tdnn_lstm_ctc

This recipe is also using a phone-based modeling unit. It is the very first recipe we have and its performance is no as good as our recent ones.

**Comment by oshindow** [comment]
> https://github.com/k2-fsa/icefall/tree/master/egs/librispeech/ASR/tdnn_lstm_ctc
> 
> This recipe is also using a phone-based modeling unit. It is the very first recipe we have and its performance is no as good as our recent ones.

Thanks for your recommendation. I have successfully trained a phone-based conformer-ctc with CER 9.5% at epoch 30 by creating a PhoneCtcTrainingGraphCompiler combined compile function of CharCtcTrainingGraphCompiler and lexicon of MmiTrainingGraphCompiler. 

As for the phonetic alignment results, the timestamp of the phone-based model is severely backward-biased compared to the char-based model. The start frame of the consonant is nearly the middle of the char.
