### ISSUE TITLE
zipformer onnx export failed.

### ISSUE THREAD

**Issue by kobenaxie** [k2-fsa/icefall#857]
onnx export can not deal `if statement` below.
https://github.com/k2-fsa/icefall/blob/74a2069f94f44a8e87f20fce4ea05d3cdbad9d73/egs/librispeech/ASR/pruned_transducer_stateless7/zipformer.py#L784-L790

https://github.com/k2-fsa/icefall/blob/74a2069f94f44a8e87f20fce4ea05d3cdbad9d73/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/zipformer.py#L1546-L1551

**Comment by csukuangfj** [comment]
Have you fixed it?

**Comment by kobenaxie** [comment]
I just change `if seq_len != d_seq_len * ds:` to `if seq_len != d_seq_len * ds or torch.jit.is_tracing():`, it is ok for onnx, but the model simplified by `onnxsim` will skip this `if statement`, which may raise error.

**Comment by csukuangfj** [comment]
@kobenaxie 
Please have a look at
- https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless7/export-onnx.py

- https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/export-onnx.py

**Comment by kobenaxie** [comment]
> 



> @kobenaxie Please have a look at
> 
> * https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless7/export-onnx.py
> * https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/export-onnx.py

Thanks
