### ISSUE TITLE
Install k2 from source Makefile:148: recipe for target 'all' failed

### ISSUE THREAD

**Issue by KajiMaCN** [k2-fsa/icefall#859]
I am getting the following error when installing k2 in a Docker image. I've searched the internet for [[some ways]](https://stackoverflow.com/questions/40322301/compile-opencv-3-on-ubuntu-16-04-linking-error-usr-lib-x86-64-linux-gnu-libsox) to do this, but still no solution.

(icefall) root@52153aa9053c:/k2# python3 setup.py install
running install
/root/anaconda3/envs/icefall/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/root/anaconda3/envs/icefall/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing k2.egg-info/PKG-INFO
writing dependency_links to k2.egg-info/dependency_links.txt
writing requirements to k2.egg-info/requires.txt
writing top-level names to k2.egg-info/top_level.txt
reading manifest file 'k2.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'k2.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-cpython-38
creating build/lib.linux-x86_64-cpython-38/k2
copying k2/python/k2/fsa_algo.py -> build/lib.linux-x86_64-cpython-38/k2
copying k2/python/k2/decode.py -> build/lib.linux-x86_64-cpython-38/k2
copying k2/python/k2/ops.py -> build/lib.linux-x86_64-cpython-38/k2
copying k2/python/k2/nbest.py -> build/lib.linux-x86_64-cpython-38/k2
copying k2/python/k2/mwer_loss.py -> build/lib.linux-x86_64-cpython-38/k2
copying k2/python/k2/utils.py -> build/lib.linux-x86_64-cpython-38/k2
copying k2/python/k2/rnnt_decode.py -> build/lib.linux-x86_64-cpython-38/k2
copying k2/python/k2/symbol_table.py -> build/lib.linux-x86_64-cpython-38/k2
copying k2/python/k2/rnnt_loss.py -> build/lib.linux-x86_64-cpython-38/k2
copying k2/python/k2/mutual_information.py -> build/lib.linux-x86_64-cpython-38/k2
copying k2/python/k2/dense_fsa_vec.py -> build/lib.linux-x86_64-cpython-38/k2
copying k2/python/k2/autograd_utils.py -> build/lib.linux-x86_64-cpython-38/k2
copying k2/python/k2/autograd.py -> build/lib.linux-x86_64-cpython-38/k2
copying k2/python/k2/__init__.py -> build/lib.linux-x86_64-cpython-38/k2
copying k2/python/k2/fsa.py -> build/lib.linux-x86_64-cpython-38/k2
copying k2/python/k2/torch_version.py -> build/lib.linux-x86_64-cpython-38/k2
copying k2/python/k2/ctc_loss.py -> build/lib.linux-x86_64-cpython-38/k2
copying k2/python/k2/fsa_properties.py -> build/lib.linux-x86_64-cpython-38/k2
copying k2/python/k2/online_dense_intersecter.py -> build/lib.linux-x86_64-cpython-38/k2
creating build/lib.linux-x86_64-cpython-38/k2/ragged
copying k2/python/k2/ragged/__init__.py -> build/lib.linux-x86_64-cpython-38/k2/ragged
creating build/lib.linux-x86_64-cpython-38/k2/sparse
copying k2/python/k2/sparse/autograd.py -> build/lib.linux-x86_64-cpython-38/k2/sparse
copying k2/python/k2/sparse/__init__.py -> build/lib.linux-x86_64-cpython-38/k2/sparse
creating build/lib.linux-x86_64-cpython-38/k2/version
copying k2/python/k2/version/__main__.py -> build/lib.linux-x86_64-cpython-38/k2/version
copying k2/python/k2/version/__init__.py -> build/lib.linux-x86_64-cpython-38/k2/version
copying k2/python/k2/version/version.py -> build/lib.linux-x86_64-cpython-38/k2/version
running build_ext
cmake_path: /root/anaconda3/envs/icefall/bin/cmake
Setting PYTHON_EXECUTABLE to /root/anaconda3/envs/icefall/bin/python3
build command is:

                cd build/temp.linux-x86_64-cpython-38

                cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=/root/anaconda3/envs/icefall/bin/python3 -DK2_ENABLE_BENCHMARK=OFF  -DK2_ENABLE_TESTS=OFF  -DCMAKE_INSTALL_PREFIX=/k2/build/lib.linux-x86_64-cpython-38/k2  /k2

                cat k2/csrc/version.h

                make -j6 install
            
-- CMAKE_VERSION: 3.18.0
-- Enabled languages: CXX;CUDA
-- The CXX compiler identification is GNU 7.5.0
-- The CUDA compiler identification is NVIDIA 11.1.105
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda-11.1/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- K2_OS: 
-- Found Git: /usr/bin/git (found version "2.17.1") 
-- Looking for C++ include cxxabi.h
-- Looking for C++ include cxxabi.h - found
-- Looking for C++ include execinfo.h
-- Looking for C++ include execinfo.h - found
-- Performing Test K2_COMPILER_SUPPORTS_CXX14
-- Performing Test K2_COMPILER_SUPPORTS_CXX14 - Success
-- C++ Standard version: 14
-- Autodetected CUDA architecture(s):  8.0
-- K2_COMPUTE_ARCH_FLAGS: -gencode;arch=compute_80,code=sm_80
-- K2_COMPUTE_ARCH_CANDIDATES 35;50;60;61;70;75;80;86
-- Skipping arch 35
-- Skipping arch 50
-- Skipping arch 60
-- Skipping arch 61
-- Skipping arch 70
-- Skipping arch 75
-- Adding arch 80
-- Skipping arch 86
-- K2_COMPUTE_ARCHS: 80
-- Could NOT find Valgrind (missing: Valgrind_INCLUDE_DIR Valgrind_EXECUTABLE) 
-- Downloading pybind11 from https://github.com/pybind/pybind11/archive/5bc0943ed96836f46489f53961f6c438d2935357.zip
-- pybind11 is downloaded to /k2/build/temp.linux-x86_64-cpython-38/_deps/pybind11-src
-- pybind11 v2.11.0 dev1
-- Found PythonInterp: /root/anaconda3/envs/icefall/bin/python3 (found suitable version "3.8.16", minimum required is "3.6") 
-- Found PythonLibs: /root/anaconda3/envs/icefall/lib/libpython3.8.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Python executable: /root/anaconda3/envs/icefall/bin/python3
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-11.1 (found version "11.1") 
-- Caffe2: CUDA detected: 11.1
-- Caffe2: CUDA nvcc is: /usr/local/cuda-11.1/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-11.1
-- Caffe2: Header version is: 11.1
-- Found CUDNN: /usr/lib/x86_64-linux-gnu/libcudnn.so  
-- Found cuDNN: v8.0.5  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- /usr/local/cuda-11.1/lib64/libnvrtc.so shorthash is 3a20f2b6
-- Autodetected CUDA architecture(s):  8.0
-- Added CUDA NVCC flags for: -gencode;arch=compute_80,code=sm_80
CMake Warning at /root/anaconda3/envs/icefall/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
  static library kineto_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  /root/anaconda3/envs/icefall/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
  cmake/torch.cmake:11 (find_package)
  CMakeLists.txt:292 (include)

-- Found Torch: /root/anaconda3/envs/icefall/lib/python3.8/site-packages/torch/lib/libtorch.so  
-- K2_TORCH_VERSION: 1.10
-- PyTorch version: 1.10.0+cu111
-- PyTorch cuda version: 11.1
-- Generated /k2/build/temp.linux-x86_64-cpython-38/torch_version.py
-- Downloading moderngpu from https://github.com/moderngpu/moderngpu/archive/8ec9ac0de8672de7217d014917eedec5317f75f3.zip
-- moderngpu is downloaded to /k2/build/temp.linux-x86_64-cpython-38/_deps/moderngpu-src
-- CMAKE_CUDA_FLAGS:  -Wno-deprecated-gpu-targets   -lineinfo --expt-extended-lambda -use_fast_math -Xptxas=-w  --expt-extended-lambda -gencode arch=compute_80,code=sm_80 -D_GLIBCXX_USE_CXX11_ABI=0 --compiler-options -Wall  --compiler-options -Wno-strict-overflow  --compiler-options -Wno-unknown-pragmas 
-- CMAKE_CXX_FLAGS:  -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-unused-variable  -Wno-strict-overflow 
-- CMAKE_CUDA_FLAGS:  -Wno-deprecated-gpu-targets   -lineinfo --expt-extended-lambda -use_fast_math -Xptxas=-w  --expt-extended-lambda -gencode arch=compute_80,code=sm_80 -D_GLIBCXX_USE_CXX11_ABI=0 --compiler-options -Wall  --compiler-options -Wno-strict-overflow  --compiler-options -Wno-unknown-pragmas 
-- Generated /k2/build/temp.linux-x86_64-cpython-38/k2/csrc/version.h
-- PYTHON_LIBRARY: /root/anaconda3/envs/icefall/lib/libpython3.8.so
-- Including k2/torch. K2_TORCH_VERSION is 1.10
-- Downloading kaldifeat from https://github.com/csukuangfj/kaldifeat/archive/refs/tags/v1.20.tar.gz
-- kaldifeat is downloaded to /k2/build/temp.linux-x86_64-cpython-38/_deps/kaldifeat-src
-- kaldifeat's binary dir is /k2/build/temp.linux-x86_64-cpython-38/_deps/kaldifeat-build
-- The C compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- C++ Standard version: 14
-- Python executable: /root/anaconda3/envs/icefall/bin/python3
CMake Warning at /root/anaconda3/envs/icefall/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
  static library kineto_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  /root/anaconda3/envs/icefall/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
  cmake/torch.cmake:11 (find_package)
  build/temp.linux-x86_64-cpython-38/_deps/kaldifeat-src/CMakeLists.txt:55 (include)

-- K2_TORCH_VERSION: 1.10
-- PyTorch version: 1.10.0+cu111
-- PyTorch cuda version: 11.1
-- CMAKE_CXX_FLAGS:  -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-unused-variable  -Wno-strict-overflow  -D_GLIBCXX_USE_CXX11_ABI=0
-- CMAKE_INSTALL_PREFIX: /k2/build/lib.linux-x86_64-cpython-38/k2
-- All headers: /k2/build/temp.linux-x86_64-cpython-38/_deps/kaldifeat-src/kaldifeat/csrc/feature-common-inl.h;/k2/build/temp.linux-x86_64-cpython-38/_deps/kaldifeat-src/kaldifeat/csrc/feature-common.h;/k2/build/temp.linux-x86_64-cpython-38/_deps/kaldifeat-src/kaldifeat/csrc/feature-fbank.h;/k2/build/temp.linux-x86_64-cpython-38/_deps/kaldifeat-src/kaldifeat/csrc/feature-functions.h;/k2/build/temp.linux-x86_64-cpython-38/_deps/kaldifeat-src/kaldifeat/csrc/feature-mfcc.h;/k2/build/temp.linux-x86_64-cpython-38/_deps/kaldifeat-src/kaldifeat/csrc/feature-plp.h;/k2/build/temp.linux-x86_64-cpython-38/_deps/kaldifeat-src/kaldifeat/csrc/feature-spectrogram.h;/k2/build/temp.linux-x86_64-cpython-38/_deps/kaldifeat-src/kaldifeat/csrc/feature-window.h;/k2/build/temp.linux-x86_64-cpython-38/_deps/kaldifeat-src/kaldifeat/csrc/log.h;/k2/build/temp.linux-x86_64-cpython-38/_deps/kaldifeat-src/kaldifeat/csrc/matrix-functions.h;/k2/build/temp.linux-x86_64-cpython-38/_deps/kaldifeat-src/kaldifeat/csrc/mel-computations.h;/k2/build/temp.linux-x86_64-cpython-38/_deps/kaldifeat-src/kaldifeat/csrc/online-feature-itf.h;/k2/build/temp.linux-x86_64-cpython-38/_deps/kaldifeat-src/kaldifeat/csrc/online-feature.h;/k2/build/temp.linux-x86_64-cpython-38/_deps/kaldifeat-src/kaldifeat/csrc/pitch-functions.h
-- Configuring done
-- Generating done
-- Build files have been written to: /k2/build/temp.linux-x86_64-cpython-38
/**
 * @brief
 * This file contains information for building k2, which is helpful
 * for describing the environment in which k2 is used when creating
 * an issue on GitHub.
 *
 * @copyright
 * Copyright (c)  2020  Mobvoi Inc.        (authors: Fangjun Kuang)
 *
 * @copyright
 * See LICENSE for clarification regarding multiple authors
 *
 * @caution
 * This file is auto-generated by CMake. Do NOT edit!
 * You can find it at build_dir/k2/csrc/version.h
 */

#ifndef K2_CSRC_VERSION_H_
#define K2_CSRC_VERSION_H_

namespace k2 {

// Version of k2 in "major.minor.patch" format
static constexpr const char *kVersion = "1.23.3";

// The commit used to build k2
static constexpr const char *kGitSha1 = "bd31a5bd9ac9deb5297570bb45b28980cfa46625";

// Date of the commit used to build k2
static constexpr const char *kGitDate = "Sun Jan 29 02:12:40 2023";

// Version of CUDA used to build k2.
// Its format is "major.minor", e.g., 10.1
static constexpr const char *kCudaVersion = "11.1";

// cuDNN version, e.g., 8.0.2
static constexpr const char *kCudnnVersion = "8.0.5";

// clang-format off
// Version of Python used to build k2 Python bindings.
static constexpr const char *kPythonVersion = "3.8";

// clang-format on

// CMake build type, e.g., Release or Debug.
static constexpr const char *kBuildType = "Release";

// The operating system that is used to build k2, e.g., Ubuntu 16.04 LTS
static constexpr const char *kOS = R"os()os";

// e.g., 3.18.0
static constexpr const char *kCMakeVersion = "3.18.0";

// Version of the compiler, e.g., 5.4.0
static constexpr const char *kGCCVersion = "7.5.0";

// CUDA flags used to compile k2
static constexpr const char *kCMakeCudaFlags = R"cuda_flags( -Wno-deprecated-gpu-targets   -lineinfo --expt-extended-lambda -use_fast_math -Xptxas=-w  --expt-extended-lambda -gencode arch=compute_80,code=sm_80 -D_GLIBCXX_USE_CXX11_ABI=0 --compiler-options -Wall  --compiler-options -Wno-strict-overflow  --compiler-options -Wno-unknown-pragmas )cuda_flags";

// CXX flags used to compile k2
static constexpr const char *kCMakeCxxFlags = R"cxx_flags( -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-unused-variable  -Wno-strict-overflow )cxx_flags";

// Which PyTorch version k2 is using, e.g., 1.6.0+cu101
static constexpr const char *kTorchVersion = "1.10.0+cu111";

// Which CUDA version PyTorch is using, e.g., 10.1
static constexpr const char *kTorchCudaVersion = "11.1";

#ifndef K2_WITH_CUDA
#define K2_WITH_CUDA
#endif

#ifdef K2_WITH_CUDA
  static constexpr bool kWithCuda = true;
#else
  static constexpr bool kWithCuda = false;
#endif

// Indicate whether NVTX is enabled or not
#ifndef K2_ENABLE_NVTX
#define K2_ENABLE_NVTX
#endif

#ifdef K2_ENABLE_NVTX
static constexpr bool kEnableNvtx = true;
#else
static constexpr bool kEnableNvtx = false;
#endif
}  // namespace k2

#endif  //  K2_CSRC_VERSION_H_

...
...
...

[ 56%] Building CUDA object k2/torch/csrc/CMakeFiles/k2_torch.dir/beam_search.cu.o
[ 57%] Building CUDA object k2/torch/csrc/CMakeFiles/k2_torch.dir/decode.cu.o
[ 58%] Building CUDA object k2/torch/csrc/CMakeFiles/k2_torch.dir/dense_fsa_vec.cu.o
[ 60%] Building CUDA object k2/torch/csrc/CMakeFiles/k2_torch.dir/deserialization.cu.o
[ 60%] Building CUDA object k2/torch/csrc/CMakeFiles/k2_torch.dir/fsa_algo.cu.o
[ 60%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/k2.cu.o
/k2/k2/torch/csrc/beam_search.cu: In function ‘std::vector<std::vector<int>, std::allocator<std::vector<int> > > k2::ModifiedBeamSearch(const torch::jit::Module&, const at::Tensor&, const at::Tensor&, int32_t)’:
/k2/k2/torch/csrc/beam_search.cu:272:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (cur_batch_size < cur.size()) {
     ~~~~~~~~~~~~~~~^~~~~~~~~~~~
/k2/k2/torch/csrc/beam_search.cu:298:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int32_t k = 0; k != prev.size(); ++k) {
                     ~~^~~~~~~~~~~~~~
/k2/k2/torch/csrc/deserialization.cu: In function ‘void k2::_GLOBAL__N__50_tmpxft_00003ffa_00000000_7_deserialization_cpp1_ii_4aae5ec1::restoreAccurateTypeTags(const c10::IValue&, const TypePtr&)’:
/k2/k2/torch/csrc/deserialization.cu:101:8: warning: enumeration value ‘StorageType’ not handled in switch [-Wswitch]
     switch (w.static_type->kind()) {
        ^
/k2/k2/torch/csrc/deserialization.cu:101:8: warning: enumeration value ‘ComplexType’ not handled in switch [-Wswitch]
/k2/k2/torch/csrc/deserialization.cu:101:8: warning: enumeration value ‘StreamObjType’ not handled in switch [-Wswitch]
/k2/k2/torch/csrc/deserialization.cu:101:8: warning: enumeration value ‘UnionType’ not handled in switch [-Wswitch]
[ 61%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/torch.cu.o
/root/anaconda3/envs/icefall/lib/python3.8/site-packages/torch/include/torch/csrc/jit/frontend/tree_views.h: In instantiation of ‘static torch::jit::Maybe<T> torch::jit::Maybe<T>::create(const torch::jit::SourceRange&, const T&) [with T = torch::jit::List<torch::jit::Property>]’:
/root/anaconda3/envs/icefall/lib/python3.8/site-packages/torch/include/torch/csrc/jit/frontend/tree_views.h:502:135:   required from here
/root/anaconda3/envs/icefall/lib/python3.8/site-packages/torch/include/torch/csrc/jit/frontend/tree_views.h:220:33: error: no matching function for call to ‘torch::jit::Compound::create(torch::jit::TokenKind, const torch::jit::SourceRange&, const torch::jit::List<torch::jit::Property>&)’
     return Maybe<T>(Compound::create(TK_OPTION, range, {value}));
                ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/root/anaconda3/envs/icefall/lib/python3.8/site-packages/torch/include/torch/csrc/jit/frontend/tree.h:142:16: note: candidate: static torch::jit::TreeRef torch::jit::Compound::create(int, const torch::jit::SourceRange&, torch::jit::TreeList&&)
   static TreeRef create(
                ^~~~~~
/root/anaconda3/envs/icefall/lib/python3.8/site-packages/torch/include/torch/csrc/jit/frontend/tree.h:142:16: note:   no known conversion for argument 3 from ‘const torch::jit::List<torch::jit::Property>’ to ‘torch::jit::TreeList&& {aka c10::SmallVector<c10::intrusive_ptr<torch::jit::Tree>, 4>&&}’
/root/anaconda3/envs/icefall/lib/python3.8/site-packages/torch/include/torch/csrc/jit/frontend/tree_views.h: In instantiation of ‘static torch::jit::Maybe<T> torch::jit::Maybe<T>::create(const torch::jit::SourceRange&, const T&) [with T = torch::jit::List<torch::jit::Assign>]’:
/root/anaconda3/envs/icefall/lib/python3.8/site-packages/torch/include/torch/csrc/jit/frontend/tree_views.h:502:186:   required from here
/root/anaconda3/envs/icefall/lib/python3.8/site-packages/torch/include/torch/csrc/jit/frontend/tree_views.h:220:33: error: no matching function for call to ‘torch::jit::Compound::create(torch::jit::TokenKind, const torch::jit::SourceRange&, const torch::jit::List<torch::jit::Assign>&)’
     return Maybe<T>(Compound::create(TK_OPTION, range, {value}));
                ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/root/anaconda3/envs/icefall/lib/python3.8/site-packages/torch/include/torch/csrc/jit/frontend/tree.h:142:16: note: candidate: static torch::jit::TreeRef torch::jit::Compound::create(int, const torch::jit::SourceRange&, torch::jit::TreeList&&)
   static TreeRef create(
                ^~~~~~
/root/anaconda3/envs/icefall/lib/python3.8/site-packages/torch/include/torch/csrc/jit/frontend/tree.h:142:16: note:   no known conversion for argument 3 from ‘const torch::jit::List<torch::jit::Assign>’ to ‘torch::jit::TreeList&& {aka c10::SmallVector<c10::intrusive_ptr<torch::jit::Tree>, 4>&&}’
[ 62%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/version.cu.o
[ 63%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/torch/arc.cu.o
[ 63%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/torch/fsa.cu.o
k2/torch/csrc/CMakeFiles/k2_torch.dir/build.make:120: recipe for target 'k2/torch/csrc/CMakeFiles/k2_torch.dir/deserialization.cu.o' failed
make[2]: *** [k2/torch/csrc/CMakeFiles/k2_torch.dir/deserialization.cu.o] Error 1
CMakeFiles/Makefile2:674: recipe for target 'k2/torch/csrc/CMakeFiles/k2_torch.dir/all' failed
make[1]: *** [k2/torch/csrc/CMakeFiles/k2_torch.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 64%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/torch/fsa_algo.cu.o
[ 65%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/torch/index_add.cu.o
[ 66%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/torch/index_select.cu.o
[ 66%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/torch/mutual_information.cu.o
[ 67%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/torch/mutual_information_cpu.cu.o
[ 68%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/torch/nbest.cu.o
[ 70%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/torch/ragged.cu.o
[ 71%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/torch/ragged_ops.cu.o
[ 71%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/torch/rnnt_decode.cu.o
[ 72%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/torch/v2/any.cu.o
[ 73%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/torch/v2/autograd/swoosh.cu.o
[ 74%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/torch/v2/doc/doc.cu.o
[ 74%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/torch/v2/k2.cu.o
[ 75%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/torch/v2/ragged_any.cu.o
[ 76%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/torch/v2/ragged_shape.cu.o
[ 77%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/torch/mutual_information_cuda.cu.o
[ 77%] Linking CUDA device code CMakeFiles/_k2.dir/cmake_device_link.o
[ 78%] Linking CUDA shared module ../../../lib/_k2.cpython-38-x86_64-linux-gnu.so
[ 78%] Built target _k2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 234, in <module>
    setuptools.setup(
  File "/root/anaconda3/envs/icefall/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/root/anaconda3/envs/icefall/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/root/anaconda3/envs/icefall/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/root/anaconda3/envs/icefall/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/root/anaconda3/envs/icefall/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/root/anaconda3/envs/icefall/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/root/anaconda3/envs/icefall/lib/python3.8/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/root/anaconda3/envs/icefall/lib/python3.8/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/root/anaconda3/envs/icefall/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/root/anaconda3/envs/icefall/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/root/anaconda3/envs/icefall/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/root/anaconda3/envs/icefall/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/root/anaconda3/envs/icefall/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/root/anaconda3/envs/icefall/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/root/anaconda3/envs/icefall/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/root/anaconda3/envs/icefall/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/root/anaconda3/envs/icefall/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/root/anaconda3/envs/icefall/lib/python3.8/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "/root/anaconda3/envs/icefall/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/root/anaconda3/envs/icefall/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/root/anaconda3/envs/icefall/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/root/anaconda3/envs/icefall/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/root/anaconda3/envs/icefall/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/root/anaconda3/envs/icefall/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions
    self._build_extensions_serial()
  File "/root/anaconda3/envs/icefall/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial
    self.build_extension(ext)
  File "setup.py", line 206, in build_extension
    raise Exception("Failed to build k2")
Exception: Failed to build k2

**Comment by csukuangfj** [comment]
There are several solutions for this:

1. Switch to cuda 10.2 if you use torch 1.10

2. Comment out or remove the code that results in the error. 
```
/root/anaconda3/envs/icefall/lib/python3.8/site-packages/torch/include/torch/csrc/jit/frontend/tree_views.h:220:33: error: no matching function for call to ‘torch::jit::Compound::create(torch::jit::TokenKind, const torch::jit::SourceRange&, const torch::jit::Listtorch::jit::Property&)’
return Maybe(Compound::create(TK_OPTION, range, {value}));
~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
```

---

You can choose any of them.

**Comment by KajiMaCN** [comment]
> There are several solutions for this:
> 
> 1. Switch to cuda 10.2 if you use torch 1.10
> 2. Comment out or remove the code that results in the error.
> 
> ```
> /root/anaconda3/envs/icefall/lib/python3.8/site-packages/torch/include/torch/csrc/jit/frontend/tree_views.h:220:33: error: no matching function for call to ‘torch::jit::Compound::create(torch::jit::TokenKind, const torch::jit::SourceRange&, const torch::jit::Listtorch::jit::Property&)’
> return Maybe(Compound::create(TK_OPTION, range, {value}));
> ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
> ```
> 
> You can choose any of them.

I commented out the relevant code and k2 installed successfully, thank you.
