### ISSUE TITLE
How to train a phone-based RNNT

### ISSUE THREAD

**Issue by didadida-r** [k2-fsa/icefall#860]
Hi, 
i want to know how to train a phone-based RNNT in icefall.

Thanks

**Comment by yaozengwei** [comment]
You can refer to https://github.com/k2-fsa/icefall/issues/855#issuecomment-1407567658

**Comment by didadida-r** [comment]
thanks, the `tdnn_lstm_ctc` use the ctc loss, but how to train a phone-based RNNT with RNNT loss, like `zipformer` or `enformer`.

**Comment by csukuangfj** [comment]
The data preparation part should be similar.  Please post your issues when you adapt it for the transducer.

**Comment by didadida-r** [comment]
i think the UniqLexicon is incompatiable for chinese, and i don't  know how to implement multiple prons lexicon

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/icefall/tree/master/egs/librispeech/ASR/tdnn_lstm_ctc

this recipe does not use UniqLexicon and it does support words with multiple pronunciations.
You can have a look and find how it is implemented.
