### ISSUE TITLE
Exporting the aishell conformer_ctc onnx model

### ISSUE THREAD

**Issue by CageLights** [k2-fsa/icefall#864]
Hello, I want to export the aishell conformer_ctc onnx model, but I don't know how to solve it, would you mind adding the aishell conformer_ctc onnx model export method? Thanks!

**Comment by csukuangfj** [comment]
Could you refer to
https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless3/export.py
to add onnx export support for aishell?
