### ISSUE TITLE
源码安装k2错误

### ISSUE THREAD

**Issue by Text2-m** [k2-fsa/icefall#872]
我用源码安装k2的时候出现k2/csrc/version.h 找不到的错误，请问怎么解决
<img width="401" alt="截屏2023-02-03 19 53 27" src="https://user-images.githubusercontent.com/37999223/216597480-c9e6f0bb-5ad1-4b4d-a6b4-fd96ac770b47.png">

**Comment by csukuangfj** [comment]
你好！请贴完整的 log.

上面的 log，包含的信息量太少了，无法判断是什么问题。

**Comment by Text2-m** [comment]
> 你好！请贴完整的 log.
> 
> 上面的 log，包含的信息量太少了，无法判断是什么问题。
这是完整的log
<img width="1426" alt="截屏2023-02-06 10 17 21" src="https://user-images.githubusercontent.com/37999223/216868876-67cf9568-c174-4f44-bdf0-d049d24a8f6e.png">

**Comment by Text2-m** [comment]
> 你好！请贴完整的 log.
> 
> 上面的 log，包含的信息量太少了，无法判断是什么问题。
你好，这是完整的log<img width="1426" alt="截屏2023-02-06 10 17 21" src="https://user-images.githubusercontent.com/37999223/216869481-4848aeda-644b-4dab-9316-5b50c5ae439d.png">

**Comment by csukuangfj** [comment]
```bash
cd /path/to/k2
rm -fv CMakeCache.txt # 如果有这个文件的话
rm -rf build
python3 setup.py build
```

可以再试一下上面的命令么？

----

**Comment by csukuangfj** [comment]
是不是一开始，你在 k2 的目录下执行过
```
cmake .
```

然后报错了. 但是你没有删掉 `cmake .` 生成的文件，然后你接着执行
```
python3 setup.py install
```
?

**Comment by Text2-m** [comment]
> 是不是一开始，你在 k2 的目录下执行过
> 
> ```
> cmake .
> ```
> 
> 然后报错了. 但是你没有删掉 `cmake .` 生成的文件，然后你接着执行
> 
> ```
> python3 setup.py install
> ```
> 
> ?
是cuda不支持吗？
<img width="1876" alt="截屏2023-02-06 11 34 54" src="https://user-images.githubusercontent.com/37999223/216878464-871629e6-1ed9-404e-89bf-7338d9ae98f2.png">

**Comment by Text2-m** [comment]
> 是不是一开始，你在 k2 的目录下执行过
> 
> ```
> cmake .
> ```
> 
> 然后报错了. 但是你没有删掉 `cmake .` 生成的文件，然后你接着执行
> 
> ```
> python3 setup.py install
> ```
> 
>

**Comment by Text2-m** [comment]
> 是不是一开始，你在 k2 的目录下执行过
> 
> ```
> cmake .
> ```
> 
> 然后报错了. 但是你没有删掉 `cmake .` 生成的文件，然后你接着执行
> 
> ```
> python3 setup.py install
> ```

我刚刚删除了以前编译的文件，重新编译的

**Comment by csukuangfj** [comment]
请参考我们的安装文档
https://k2-fsa.github.io/k2/installation/index.html

你现在没有安装 nvcc, 请先参考
https://k2-fsa.github.io/k2/installation/cuda-cudnn.html
去安装 cudatoolkit 和 cudnn, 然后再进行下一步.
