### ISSUE TITLE
Bidirectional LSTM

### ISSUE THREAD

**Issue by desh2608** [k2-fsa/icefall#873]
Is there any particular reason that the `ScaledLSTM` class does not allow bidirectional LSTMs? Ref: https://github.com/k2-fsa/icefall/blob/029c8566e424b44e64da70c6fb532caace9c7d54/egs/librispeech/ASR/pruned_transducer_stateless2/scaling.py#L461

**Comment by csukuangfj** [comment]
Because we want a streaming LSTM.

Bidirectional LSTM is not a streaming model.

**Comment by desh2608** [comment]
Sure, but I feel like that should be defined at the model level (e.g. while creating the encoder), instead of through an assertion within the LSTM module, don't you think? Anyway, it's just a minor nit.
