### ISSUE TITLE
源码编译k2出现错误

### ISSUE THREAD

**Issue by Text2-m** [k2-fsa/icefall#877]
源码编译，不知道是不是cuda不支持导致的编译失败？
<img width="1876" alt="截屏2023-02-06 11 34 54" src="https://user-images.githubusercontent.com/37999223/216879185-a72c18b3-2ca1-4d98-a36e-cdac8fba5a89.png">
<img width="1311" alt="截屏2023-02-06 11 43 54" src="https://user-images.githubusercontent.com/37999223/216879635-3c28d1c1-c8ae-47a3-a481-015ceac131f6.png">

**Comment by csukuangfj** [comment]
两张图片，代表两个问题
1. 第一张图片，请参考 https://k2-fsa.github.io/k2/installation/cuda-cudnn.html
如果你想要 cuda 版本的 k2, 请先安装 cudatoolkit 和 cudnn

2. 第二个问题。先把第一个解决了，第二个就没问题了。（这个问题应该是 mkl 的问题)

**Comment by Text2-m** [comment]
> 两张图片，代表两个问题
> 
> 1. 第一张图片，请参考 https://k2-fsa.github.io/k2/installation/cuda-cudnn.html
>    如果你想要 cuda 版本的 k2, 请先安装 cudatoolkit 和 cudnn
> 2. 第二个问题。先把第一个解决了，第二个就没问题了。（这个问题应该是 mkl 的问题)
安装了cuda 和cudnn后编译出现了一样的问题
<img width="1425" alt="截屏2023-02-06 12 58 43" src="https://user-images.githubusercontent.com/37999223/216887665-20aeb57b-77e9-4c81-af8b-a3361ebd2d2f.png">

**Comment by csukuangfj** [comment]
你的 pytorch 版本是哪一个？
安装好 cudatoolkit 后，先把之前 build 的目录，删掉，然后重试。

---

重复一遍，记得删掉 build 目录，然后重试。

**Comment by csukuangfj** [comment]
如果一开始，就是照文档安装的话，应该会很顺利。

**Comment by Text2-m** [comment]
> 如果一开始，就是照文档安装的话，应该会很顺利。

谢谢军神,添加了环境变量解决了。export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/run/anaconda/anaconda3/envs/k2/lib"

**Comment by Text2-m** [comment]
> 如果一开始，就是照文档安装的话，应该会很顺利。
这是什么问题呀
<img width="1427" alt="截屏2023-02-06 18 49 58" src="https://user-images.githubusercontent.com/37999223/216953145-367b7599-6412-4672-bbc9-00723da41033.png">

**Comment by csukuangfj** [comment]
> > 如果一开始，就是照文档安装的话，应该会很顺利。
> > 这是什么问题呀
> 
> <img alt="截屏2023-02-06 18 49 58" width="1427" src="https://user-images.githubusercontent.com/37999223/216953145-367b7599-6412-4672-bbc9-00723da41033.png">

这个代表，没有问题。输出是正常的

**Comment by Text2-m** [comment]
> > > 如果一开始，就是照文档安装的话，应该会很顺利。
> > > 这是什么问题呀
> > 
> > 
> > <img alt="截屏2023-02-06 18 49 58" width="1427" src="https://user-images.githubusercontent.com/37999223/216953145-367b7599-6412-4672-bbc9-00723da41033.png">
> 
> 这个代表，没有问题。输出是正常的

谢谢军神
