### ISSUE TITLE
Token hyp and token alignment in pruned_transducer_stateless7_ctc/decode.py

### ISSUE THREAD

**Issue by armusc** [k2-fsa/icefall#885]
Hi

if I use one of the decoding methods in decode.py, let's say fast_beam_search_nbest, I noticed I can have two sequences like this:

token_hyp = get_texts(best_path)
token_alignment = get_alignments(best_path, kind="labels")

where
token_hyp = [ .... 87, 2, 22, 22, 22, 22, 3, ..... ]
token_alignment = [...  22, 0, 0, 0, 22, 0, 0, 0, 0, 0, 22, 22, 0,.........]

so, the two consecutive non blank symbols in the alignment are retained in the best_path; in a CTC output we should remove duplicates like this, right?; is that normal with this kind of nnet output?

**Comment by csukuangfj** [comment]
> in a CTC output we should remove duplicates like this, right?

Yes, you are right. But that is for CTC, not for transducer.

`fast_beam_search_nbest` is for transducer, not CTC.
