### ISSUE TITLE
wenetspeech recognition error

### ISSUE THREAD

**Issue by CageLights** [k2-fsa/icefall#886]
Traceback (most recent call last):
  File "./pruned_transducer_stateless2/pretrained.py", line 334, in <module>
    main()
  File "/data/Anaconda3/envs/icefall/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "./pruned_transducer_stateless2/pretrained.py", line 224, in main
    model.load_state_dict(checkpoint["model"], strict=False)
  File "/data/Anaconda3/envs/icefall/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Transducer:
	size mismatch for decoder.embedding.weight: copying a param with shape torch.Size([6020, 512]) from checkpoint, the shape in current model is torch.Size([5537, 512]).
	size mismatch for joiner.output_linear.weight: copying a param with shape torch.Size([6020, 512]) from checkpoint, the shape in current model is torch.Size([5537, 512]).
	size mismatch for joiner.output_linear.bias: copying a param with shape torch.Size([6020]) from checkpoint, the shape in current model is torch.Size([5537]).
	size mismatch for simple_am_proj.weight: copying a param with shape torch.Size([6020, 512]) from checkpoint, the shape in current model is torch.Size([5537, 512]).
	size mismatch for simple_am_proj.bias: copying a param with shape torch.Size([6020]) from checkpoint, the shape in current model is torch.Size([5537]).
	size mismatch for simple_lm_proj.weight: copying a param with shape torch.Size([6020, 512]) from checkpoint, the shape in current model is torch.Size([5537, 512]).
	size mismatch for simple_lm_proj.bias: copying a param with shape torch.Size([6020]) from checkpoint, the shape in current model is torch.Size([5537]).

**Comment by CageLights** [comment]
./pruned_transducer_stateless2/pretrained.py \
        --checkpoint ./pruned_transducer_stateless2/exp/epoch-10.pt \
        --lang-dir ./data/lang_char \
        --decoding-method modified_beam_search \
        --beam-size 4 \
      /data/icefall/egs/aishell/ASR/conformer_ctc/test_waves/new/ljl/ljl_bws.wav

**Comment by danpovey** [comment]
Perhaps you changed the contents of data/lang_char since you trained the model?

**Comment by csukuangfj** [comment]
Could you describe where you get the pre-trained model and `data/lang_char`?
