### ISSUE TITLE
Explicit punctuation marks in GigaSpeech

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#896]
Hello,

We have studied the stateless-8 recipe for LibriSpeech, and we understand that it also combines training material from GigaSpeech. Both databases contain English text in upper case only, so the word pieces are also created in upper case.
However, GigaSpeech texts also contain explicit punctation marks, namely <PERIOD> <COMMA> <QUESTIONMARK> and <EXCLAMATIONPOINT> and we don't see anywhere in the code (including the Lhotse script that prepares the GigaSpeech manifests) where these marks are removed.
Is it possible that these marks remained during training, or are we missing something?

AlexG and RonW

**Comment by csukuangfj** [comment]
We do text normalization during data preparation to remove punctuation marks.

**Comment by AlexandderGorodetski** [comment]
Thank you @csukuangfj . Following your comment we found that normalization is done in the following file local/preprocess_gigaspeech.py
