### ISSUE TITLE
Only single word piece with apostrophe in the pretrained model

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#899]
Hello,

When running the word-piece generation script we have noticed the following peculiarity:
There is only a single word-piece than contain the apostrophe character, namely the singleton word piece " ' ".
This is strange, as we see that we have quite a lot of word pieces that match an entire word, for example "_ACROSS" - and we would have expected the generation of word pieces such as "_IT'S", "_I'LL" etc. as well.
The word IT'S for example occurs in the training texts about 10 times more than the word ACROSS.
We have noticed a similar phenomenon also in the stateless-8 pretrained model, so we suspect it is a feature of the SentencePiece module used by the script: i.e. it concatenates pieces that comprise only alphabetic characters... If so, is there a way to overcome this behavior?

Thanks,
Ron and Alex.

**Comment by csukuangfj** [comment]
The algorithm about how to split a word into pieces and what the pieces are is determined by the python package sentencepiece. 

I doubt it is customizable to choose the pieces by yourself.

**Comment by danpovey** [comment]
I don't see any option here
https://github.com/google/sentencepiece/blob/master/doc/options.md
that looks like it would treat apostrophe differently than letters.

**Comment by teowenshen** [comment]
If I remember correctly, I managed to achieve that behaviour by turning off `split_by_unicode_script`. 
Though, note that this applies to all unicode characters. For example, if "IT." appears often enough the trailing period will stick onto "IT" in the resulting token.
