### ISSUE TITLE
OOM not detected with scan_pessimistic_batches_for_oom

### ISSUE THREAD

**Issue by iggygeek** [k2-fsa/icefall#910]
Hi,
I tried the recipe of Librispeech "pruned_transducer_stateless7_streaming" on my own dataset which was working fine with Kaldi.

But with Icefall/K2 I got an OOM problem with --max-duration = 750 , 600  and was not detected with  "scan_pessimistic_batches_for_oom".
I filter out utterances longer than 50 seconds with "./pruned_transducer_stateless7_streaming/train.py" instead of 20 used in Librispeech because in my dataset statistics I see than 20 s is too small for me.
So my questions are : 
1) is it a good strategy to keep decreasing  --max-duration until there is no OOM or it will decrease accuracy in some way ?
2) it is OK to have utterances way longer to 20 seconds or it will always get difficult to handle and it better to find a way to split them ?
3) can you give some details on the error message because it did not understand the pytorch documentation on "max_split_size_mb"  and  "PYTORCH_CUDA_ALLOC_CONF" ? Do you  have suggestions on how to set these ?

Thanks for your help. Here is the log :

2023-02-13 16:43:08,625 INFO [train.py:1198] features shape: torch.Size([12, 4688, 80])
2023-02-13 16:43:08,627 INFO [train.py:1202] num tokens: 3635
Traceback (most recent call last):
  File "/home/usera/git/icefall/egs/ge/./pruned_transducer_stateless7_streaming/train.py", line 1265, in <module>
    main()
  File "/home/usera/git/icefall/egs/ge/./pruned_transducer_stateless7_streaming/train.py", line 1258, in main
    run(rank=0, world_size=1, args=args)
  File "/home/usera/git/icefall/egs/ge/./pruned_transducer_stateless7_streaming/train.py", line 1136, in run
    train_one_epoch(
  File "/home/usera/git/icefall/egs/ge/./pruned_transducer_stateless7_streaming/train.py", line 841, in train_one_epoch
    scaler.scale(loss).backward()
  File "/home/usera/miniconda3/envs/icefall/lib/python3.9/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/usera/miniconda3/envs/icefall/lib/python3.9/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 10.25 GiB (GPU 0; 47.53 GiB total capacity; 9.45 GiB already allocated; 9.67 GiB free; 23.12 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by yaozengwei** [comment]
I think you could try to filter the uneven-sized minibatch, as we did in https://github.com/k2-fsa/icefall/pull/843.

**Comment by pzelasko** [comment]
If you’re using DynamicBucketingSampler try setting quadratic_duration to sth between 30 and 50. You will need to tune max_duration later (typically I see it can be increased about +50%). You have extremely long utterances in training and that should help balance out the GPU memory usage across mini batches of different cut durations. 

https://github.com/lhotse-speech/lhotse/blob/527d96453b9ad119729ddef1a9613bcae536e6c7/lhotse/dataset/sampling/dynamic_bucketing.py#L75

**Comment by danpovey** [comment]
BTW,  this quadratic_duration thing is a very new feature in Lhotse.
The uneven-sized minibatch problem turned out to only be an issue in quite old versions of Lhotse (zengwei: we could actually remove this extra code, should be unnecessary in general.)
The batch length seems to be 12 * 4688 / 100, about 555 seconds.

HOWEVER, this:

 CUDA out of memory. Tried to allocate 10.25 GiB (GPU 0; 47.53 GiB total capacity; 9.45 GiB already allocated; 9.67 GiB free; 23.12 GiB  reserved in total by PyTorch

makes me think that the issue may be sharing the GPU with another process, maybe from a different training run, since 10.25 plus the 9.45 GiB already allocated is much less than the 47.53GiB total.
Unlikely to be a fragmentation issue since even the "23.12 GiB reserved in total by PyTorch" plus the 10.25GiB request is much less than the 475.53GiB total capacity.

Use nvidia-smi to see what's using the GPU

**Comment by iggygeek** [comment]
OK, sorry for late reply.
Yes I trained with DynamicBucketingSampler.
Indeed an other process (not mine) was sharing the GPU.
Do you suggest that the GPU memory used by k2 during training will be always less that the one used for the first batch and that the problem comes from the other process which grew in memory ?

**Comment by danpovey** [comment]
Oom search is not a guarantee.
