### ISSUE TITLE
BUG Report on pytorch

### ISSUE THREAD

**Issue by HsunGong** [k2-fsa/icefall#911]
See https://github.com/pytorch/pytorch/issues/30651

icefall/icefall/utils.py:41 from torch.utils.tensorboard import SummaryWriter

SummaryWriter may cause errors
SummaryWriter should be add at `the very first`!!!

Also for?

icefall/transformer_lm/train.py
icefall/rnn_lm/train.py

**Comment by csukuangfj** [comment]
Could you have a look at #674 for a fix?

Thanks for sharing the link.

**Comment by HsunGong** [comment]
Good, THX.
Anyway, I suggest the title of #674 should be changed such as "torch tensorboard SummaryWriter caught Segmentation fault".

Close this issue.
