### ISSUE TITLE
question about shallow fusion.

### ISSUE THREAD

**Issue by kobenaxie** [k2-fsa/icefall#922]
Generally, in LM shallow fusion, we can get new tokens and scores by topk like 
> `topk_logprobs, topk_tokens = torch.topk(logprob_am + lm_scale * logprob_lm`

but in [modified_beam_search_lm_shallow_fusion](https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py#L2125), firstly get new tokens over `logprob_am` [here](https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py#L2321), like
>  `topk_logprobs, topk_tokens = torch .topk(logprob_am)` 

and then add `lm_score` [lm fusion](https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py#L2345) for each token.
> hyp_log_prob += lm_score[new_token] * lm_scale  # add the lm score

Why modify shallow fusion here ?

**Comment by marcoyang1998** [comment]
We did this because the probability of blank is not well-defined in neural network LM. So we don't want to add the lm_score to blank symbols when doing shallow fusion.

Please see #754 for more discussions.

**Comment by csukuangfj** [comment]
> topk_logprobs, topk_tokens = torch .topk(logprob_am)


Why do you use `logprob_am` here, especially the `am`? Do you mean we are not using LM scores when taking `topk`?

**Comment by kobenaxie** [comment]
> > topk_logprobs, topk_tokens = torch .topk(logprob_am)
> 
> Why do you use `logprob_am` here, especially the `am`? Do you mean we are not using LM scores when taking `topk`?

code [here](https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py#L2321) is not using LM scores in topk.

**Comment by csukuangfj** [comment]
> > > topk_logprobs, topk_tokens = torch .topk(logprob_am)
> > 
> > 
> > Why do you use `logprob_am` here, especially the `am`? Do you mean we are not using LM scores when taking `topk`?
> 
> code [here](https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py#L2321) is not using LM scores in topk.

Please re-read the code. We are indeed using LM scores.

**Comment by kobenaxie** [comment]
> > > > topk_logprobs, topk_tokens = torch .topk(logprob_am)
> > > 
> > > 
> > > Why do you use `logprob_am` here, especially the `am`? Do you mean we are not using LM scores when taking `topk`?
> > 
> > 
> > code [here](https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py#L2321) is not using LM scores in topk.
> 
> Please re-read the code. We are indeed using LM scores.
> 
> Maybe it is not clear at the first glance or our code is not that clear.

Sorry, Actually the lm_score has beed added at previous decoding step.

**Comment by kobenaxie** [comment]
> We did this because the probability of blank is not well-defined in neural network LM. So we don't want to add the lm_score to blank symbols when doing shallow fusion.
> 
> Please see #754 for more discussions.

Thanks.
