### ISSUE TITLE
can't reproduce pruned_transducer_stateless7_streaming WER result

### ISSUE THREAD

**Issue by roanlane** [k2-fsa/icefall#928]
Hi, i attempt reproduce streaming result from https://github.com/k2-fsa/icefall/pull/787 for librispeech test other
I use scpript from https://huggingface.co/Zengwei/icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/blob/main/exp/decode.sh **with changing --avg 1 and --use-averaged-model False** - i found only last checkpoint into repository.
With greedy_search-epoch-30-avg-1-streaming-chunk-size-64-context-2-max-sym-per-frame-1 i get **8.76** WER, which worse then release result.
I can't understand differents in result caused missing model averaging or i should get same result use only one checkpoint?

**SOLUTION - i find solution during writing time  - yoy should using pretrained.pt for reproduce result - may be it help somebody else)

**Comment by marcoyang1998** [comment]
Yes, you are expected to use `pretrained.pt` for decoding, this one is the averaged model.
We prepare this [script](https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/pretrained.py) for you to decode with `pretrained.pt`.

**Comment by roanlane** [comment]
I can't process dataset, librispeech test other for example with this script. It will be great add dataset processing like from [decode.py](https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/decode.py) to this script

**Comment by marcoyang1998** [comment]
> I can't process dataset, librispeech test other for example with this script. It will be great add dataset processing like from [decode.py](https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/decode.py) to this script

A work-around for that is renaming `pretrained.pt` to `epoch-99.pt`. Then you use [decode.py](https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/decode.py) by setting `--epoch99 --avg 1 --use-averaged-model False`.

**Comment by csukuangfj** [comment]
@roanlane 

We have documentation about how to use pre-trained model for decoding. Please see
https://k2-fsa.github.io/icefall/model-export/index.html

![Screenshot 2023-03-02 at 10 36 27](https://user-images.githubusercontent.com/5284924/222316647-ed60fb77-0a21-42b7-b2a3-46be57b5c7c9.png)
