### ISSUE TITLE
wenetspeech compute fbank error

### ISSUE THREAD

**Issue by Text2-m** [k2-fsa/icefall#929]
我用自己的测试集提取fbank的出现以下问题
<img width="1431" alt="截屏2023-03-03 17 36 29" src="https://user-images.githubusercontent.com/37999223/222685559-788c0028-0c40-46a9-8c5f-297457cb868f.png">

**Comment by csukuangfj** [comment]
lilcom_interface.py, 36 行，你可以把  input 和 meta 的 type 输出来么?

**Comment by Text2-m** [comment]
> lilcom_interface.py, 36 行，你可以把 input 和 meta 的 type 输出来么?

input_type: <class 'numpy.ndarray'> meta_type: <class 'list'>

**Comment by Text2-m** [comment]
> > lilcom_interface.py, 36 行，你可以把 input 和 meta 的 type 输出来么?
> 
> input_type: <class 'numpy.ndarray'> meta_type: <class 'list'>

测试集的json是根据L sub_dataset的json的格式准备的，start_time end_time duration 这些字段的value都是编造的。跟这个有关系吗

**Comment by csukuangfj** [comment]
你用 pdb 调试 看看，为什么你传进去的参数类型和期望的不对？

**Comment by Text2-m** [comment]
> 你用 pdb 调试 看看，为什么你传进去的参数类型和期望的不对？

我有什么办法能跳过prepare.sh 这些步骤，用decode.py解码音频文件

**Comment by csukuangfj** [comment]
> 用decode.py解码音频文件

1. 用 pretrained.py
请参考文档
https://k2-fsa.github.io/icefall/model-export/export-with-torch-jit-script.html#how-to-use-the-exported-model

2. 使用 sherpa
请参考文档 https://k2-fsa.github.io/sherpa/

---

icefall 是用来训练模型的。如果你只是想做推理，不想训练模型，请使用 sherpa

- https://k2-fsa.github.io/sherpa/
- https://k2-fsa.github.io/sherpa/ncnn/index.html
- https://k2-fsa.github.io/sherpa/onnx/index.html

**Comment by Text2-m** [comment]
没看到 支持decoding-method fast_beam_search_nbest_LG

**Comment by csukuangfj** [comment]
> 没看到 支持decoding-method fast_beam_search_nbest_LG

sherpa 里有支持的
https://github.com/k2-fsa/sherpa/blob/master/sherpa/python/sherpa/decode.py#L33

**Comment by Text2-m** [comment]
声学模型（pretrain_model）的tokens.txt 和语言模型(自己的数据集训得)的tokens.txt 要怎么修改 解码才能正确

**Comment by csukuangfj** [comment]
> 声学模型（pretrain_model）的tokens.txt 和语言模型(自己的数据集训得)的tokens.txt 要怎么修改 解码才能正确

不能修改，也不用修改。

你必须要用 pre-trained model 配套的  tokens.txt.
