### ISSUE TITLE
Zipformer CTC-attention

### ISSUE THREAD

**Issue by desh2608** [k2-fsa/icefall#931]
I am training a CTC+attention model (similar to conformer_ctc but using zipformer encoder) on LibriSpeech. Note that it is not exactly the original LibriSpeech, the train/test split is somewhat different. The tensorboard is here: https://tensorboard.dev/experiment/RFPUNe3BSvOQKGMXmDLIWQ/#scalars

I would appreciate if someone can check and let me know if the loss looks okay so far, since I am not sure what value of losses to expect.

**Comment by desh2608** [comment]
For a comparison, here is the tensorboard for the original conformer_ctc training: https://tensorboard.dev/experiment/hZDWrZfaSqOMqtW0NEfXKg/#scalars. But it was trained with a batch size 200, whereas my batch size is 800, so the steps are not directly comparable.

**Comment by csukuangfj** [comment]
> 

Sorry for the late replay.

The loss curve looks normal to me.

**Comment by desh2608** [comment]
> > 
> 
> 
> 
> Sorry for the late replay.
> 
> 
> 
> The loss curve looks normal to me.

Thanks. Yeah I was just trying to get early opinion so I could make the InterSpeech deadline :)
