### ISSUE TITLE
how to export jit

### ISSUE THREAD

**Issue by Yymax-max** [k2-fsa/icefall#938]
can you tell me or get me some advices to export jit of wenetspeech-lstm-transducer-stateless

**Comment by csukuangfj** [comment]
Please refer to our documentation
https://k2-fsa.github.io/icefall/model-export/index.html

**Comment by Yymax-max** [comment]
> Please refer to our documentation https://k2-fsa.github.io/icefall/model-export/index.html

i find lstm-transducer-stateless can exported using torch.jit.trace.but in librispeech/ASR/lstm_transducer_stateless2/export.py should input bpe-model but  wenetspeech-lstm-transducer-stateless is lang_dir.how can i do ? thank

**Comment by Yymax-max** [comment]
i use https://github.com/k2-fsa/icefall/pull/595/files#diff-d4a0c4d8b574ae5b1707e825e5f08e1e1cce9e7733f5d60ba2dc185b18da8aa9 export.py,but meet the error
<img width="874" alt="image" src="https://user-images.githubusercontent.com/39081569/223977010-df622ab9-a2a5-4d53-9fb4-1ce88f0be271.png">

and i use the modle of https://huggingface.co/csukuangfj/icefall-asr-wenetspeech-lstm-transducer-stateless-2022-10-14/tree/main

**Comment by uni-sagar-raikar** [comment]
@csukuangfj I was trying to export jit model from pruned_transducer_stateless7, Facing issue with scaling.py and scaling_converter.py. 

In sherpa/triton, https://github.com/k2-fsa/sherpa/blob/32da4486f1b23b04d0be72d1890f5dd7368aef46/triton/scripts/conformer_triton.py#L30 has ScaledConv2d being imported from [scaling.py](https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless7/scaling.py) but its missing. Could you please help on this? I might be missing something.

Thanks
Sagar

**Comment by csukuangfj** [comment]
Are you using the latest master?

Which script are you using and could you post the complete commands you are using?

**Comment by uni-sagar-raikar** [comment]
Yes, I am using latest master in sherpa_server:latest docker. I am using https://github.com/k2-fsa/sherpa/blob/master/triton/scripts/export_jit.py and https://github.com/k2-fsa/sherpa/blob/master/triton/scripts/conformer_triton.py

**Comment by csukuangfj** [comment]
Please post the detailed arguments you are using for the above scripts.

**Comment by uni-sagar-raikar** [comment]
python3 pruned_transducer_stateless7/export_jit.py \
        --pretrained-model $ICEFALL_DIR/egs/librispeech/ASR/pruned_stateless_transducer7/en_in_model \
        --output-dir $ICEFALL_DIR/egs/librispeech/ASR/pruned_stateless_transducer7/en_in_model --bpe-model $ICEFALL_DIR/egs/librispeech/ASR/pruned_stateless_transducer7/en_in_model/bpe.model
