### ISSUE TITLE
分词结果含有自定义词典之外的词

### ISSUE THREAD

**Issue by wwfcnu** [k2-fsa/icefall#939]
jieba.load_userdict("user.txt")
jieba.cut(text,HMM=False)
user.txt中有200000，切出的词却超过了200000，包含了一些词典中不存在的词，比如词典中没有“胡如雷”，却分出了这个词，按理说，不应该分成胡 如 雷三个单字吗？

**Comment by csukuangfj** [comment]
我们对jieba 不太熟，你可以去jieba 的GitHub repo 寻求帮助吗？
