### ISSUE TITLE
error in aishell prepare.sh fbank

### ISSUE THREAD

**Issue by konolcda** [k2-fsa/icefall#948]
while I run compute_fbank_aishell.py, it goes wrong.
![IMG_20230315_182729](https://user-images.githubusercontent.com/120434308/225281824-9098031c-ee5c-48a5-8d03-f1bde91ab326.jpg)
the len(manifests) is 0 which comes from read_manifests_if_cached() in util.py.
![wx_camera_1678870699676](https://user-images.githubusercontent.com/120434308/225283049-5a85f969-a8ea-4379-9e71-f312abaeb2ed.jpg)
same error appears in musan fbank compute.
what should I do?
thanks

**Comment by csukuangfj** [comment]
Could you show the output of
```bash
ls -lh data/manifests
```

The file sizes of the files inside `data/manifests` are helpful to debug this issue.

**Comment by konolcda** [comment]
> 你能展示一下的输出吗
> 
> ```shell
> ls -lh data/manifests
> ```
> 
> 里面文件的文件大小`data/manifests`有助于调试这个问题。

ok， it's the result
![Uploading IMG_20230315_185150.jpg…]()

**Comment by csukuangfj** [comment]
Has it been fixed via the QQ group of Next-gen Kaldi?

The reason is that it is not run inside egs/aishell/ASR.
