### ISSUE TITLE
dev and test performance

### ISSUE THREAD

**Issue by huangruizhe** [k2-fsa/icefall#951]
I was wondering when we interprete the WER results of the pretrained models, e.g., [here](https://huggingface.co/WayneWiser/icefall-asr-librispeech-conformer-ctc2-jit-bpe-500-2022-07-21/blob/main/log/log-rnn-lm/log-decode-2022-07-21-17-00-55), it seems we are using/reporting the WER results with the best hyper parameters for TEST data (e.g., 2.37% and 4.98% in [here](https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/RESULTS.md#librispeech-bpe-training-results-conformer-ctc-2)), instead of finding the best hyper parameters for DEV data and applying them on TEST data (so that the hyper params are optimal for DEV but may not be so for TEST).

It seems in our current set up, TEST data is actually "seen" during training (for tuning the hyper params).

Will that be an issue? Thanks!

**Comment by danpovey** [comment]
It would probably be more correct to choose the hyper-parameters on dev not test, but in practice I don't think it's a very important issue.
