### ISSUE TITLE
MP3 support

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#952]
Hello guys,

I am using tedlium recipe to train K2 model using my inhouse data. 

I wanted just to check with you if compute_fbank_tedlium.py script will extract features from MP3 files?

(I checked working with SPH files and with WAV files, in both cases feature extraction is working properly).

Thanks a lot,
AlexG.

**Comment by huangruizhe** [comment]
I think it should be supported, or only with minimal modification. Icefall is using [lhotse](https://lhotse.readthedocs.io/en/latest/_modules/lhotse/cut/set.html?highlight=mp3#) to load/compute features. Lhotse supports mp3.
