### ISSUE TITLE
ami and alimeeting recipe question

### ISSUE THREAD

**Issue by Yymax-max** [k2-fsa/icefall#957]
individual headset microphone (IHM)
Single distant microphone (SDM)
我想请问这个两个方法是指在原音频数据抽取对应的通道是么，因为我记得ami和alimeeting是多通道？

**Comment by pkufool** [comment]
应该是的，关于icefall的recipe，数据准备可以参考 https://github.com/lhotse-speech/lhotse/blob/master/lhotse/recipes/ali_meeting.py，只抽取了第一个通道。

**Comment by Yymax-max** [comment]
> 应该是的，关于icefall的recipe，数据准备可以参考 https://github.com/lhotse-speech/lhotse/blob/master/lhotse/recipes/ali_meeting.py ，只抽取了第一个通道。

好的，感谢
