### ISSUE TITLE
G (external LM) sometimes empties path at nbest.intersect(G)

### ISSUE THREAD

**Issue by MicKot** [k2-fsa/icefall#959]
So I have:
- HLG with G built using transcriptions
- external G made with srilm

Weird things happen:
- if with that external G I rescore lattice using `rescore_with_n_best_list` for some lattices it empties best_path (meaning I have a nice recognition and after `nbest.intersect(G)` there is no more nice recognition)
- this thing may be the most important: let's say I have emissions in shape [1, 350, 500], if I take first 330 frames and `rescore_with_n_best_list`, the recognition is exactly as it should, but if I take 331 frames and rescore it the same way, then it clears the recognition. This is pretty random, not necessarily for long recordings, sometimes short. Of course doing `one_best_decoding` either way gives proper recognition
- I tried training another LMs on other data using `kenlm` and `make_kn_lm.py` and while I could incorporate them into HLG, the second I do `nbest.intersect(G)` the same thing happens (but maybe not for the same emissions)

Both Gs (from HLG and rescoring) use the same lexicon for conversion to fst
k2 version: 1.23.4

**Comment by csukuangfj** [comment]
Can you check that the id of #0 is larger than the id of all other words and the id of "<s>" and "</s>" are also larger than that of #0 in words.txt?

**Comment by MicKot** [comment]
Yes, words.txt is typical:
```
<eps> 0
!SIL 1
<SPOKEN_NOISE> 2
<UNK> 3
...
#0 779048
<s> 779049
</s> 779050
```
I would guess that intersecting anything with LM should give back this anything, maybe with very small weights, especially if they share words.txt.
I will check what the difference is in lattice in the second point.

**Comment by MicKot** [comment]
Ok, I found the issue: if rescoring G encounters a word it doesn't have in it's unigrams it says 'that sequence is impossible' and that's it. I would expect that sharing words.txt means, there is some probability given to all words, but no.

To anyone with similar issue: If retraining your rescoring G is problematic, you can train lm on just your wordlist and mix it with G using srilm.
