### ISSUE TITLE
Enable log probs input for rnnt loss ?

### ISSUE THREAD

**Issue by kobenaxie** [k2-fsa/icefall#963]
In [torchaudio pr](https://github.com/pytorch/audio/pull/2798), adding fused_log_softmax argument (default/current behavior = True) to rnnt loss. Will fast_rnnt  or k2 support this ?

**Comment by pkufool** [comment]
> In [torchaudio pr](https://github.com/pytorch/audio/pull/2798), adding fused_log_softmax argument (default/current behavior = True) to rnnt loss. Will fast_rnnt or k2 support this ?

I don't think so,  for `rnnt_loss` and `rnnt_loss_pruned`, it may be doable, but for `rnnt_loss_simple` and `rnnt_loss_smooth`, they accept `encoder output` and `predictor output` as inputs, we normerize them internally in an efficient way (don't have to construct a 4-dims tensor).

**Comment by kobenaxie** [comment]
Ok, thanks
