### ISSUE TITLE
Domain transition

### ISSUE THREAD

**Issue by Zeiny96** [k2-fsa/icefall#991]
Is there a way to resume training on different domain without forgetting the main domain?
Like after training the model on Librispeech, I can resume the training using Giga speech while maintaining Librispeech results.

**Comment by marcoyang1998** [comment]
I think this is in general difficult. We have examples of fine-tuning, it shows good performance on the fine-tuning set. But we didn't evaluate it on the original training set. Maybe you can test it out.

Also, there are a few papers addressing catastrophic forgetting which might be helpful: https://arxiv.org/abs/2210.15282, https://arxiv.org/pdf/2104.01616.pdf
